### ISSUE TITLE
Request for adding Pack/Unpack to onnx (that are the ops tf.stack/tf.unstack)

### ISSUE THREAD

**Issue by jiangsuliji** [onnx/tensorflow-onnx#10]
@guschmue  
While I was converting a frozen tensorflow model, it errors out with "StridedSlice not implemented". 
I checked the node and this operation just raises an error. 
I was wondering when it could be implemented. Thanks a lot.

Details:
  File "C:\Program Files\Python35\lib\site-packages\tf2onnx\tfonnx.py", line 668, in stridedslice_op
    raise ValueError("StridedSlice not implemented")
ValueError: StridedSlice not implemented

**Comment by jiangsuliji** [comment]
Moved to main folder

**Comment by guschmue** [comment]
We can add support for StridedSlice for the special case strides=1, but your model also needs Pack/Unpack operators which would need to be added to onnx.

**Comment by guschmue** [comment]
StridedSlice for  strides=1 added with https://github.com/onnx/tensorflow-onnx/pull/37

**Comment by guschmue** [comment]
I have added a hack to support f.stack / tf.unstack to the converter until pack/unpack is supported in onnx here:
https://github.com/onnx/tensorflow-onnx/pull/56
