### ISSUE TITLE
Slice_op starts:[0,0,1] size:[-1,-1,-1] --> ends:[-1, -1,0] if shape =[1, 1917, 91] run caffe2 error 

### ISSUE THREAD

**Issue by laobadao** [onnx/tensorflow-onnx#100]
[enforce fail at slice_op.h:58] end >= start. 0 vs 1 Error from operator: 
input: "Postprocessor/raw_box_scores:0" input: "OC2_DUMMY_106"
 input: "OC2_DUMMY_109" output: "Postprocessor/Slice:0" name: "Postprocessor/Slice" 
type: "Slice" device_option { device_type: 0 cuda_gpu_id: 0 }

 ends = np.add(starts, size)   

Whether we should get the shape first and then calculate ends ,  if  size  contains -1 

```
def slice_op(ctx, node, name, args):
    print("----------------------------------slice_op-----------------------------------------")
    # T output = Slice(T input, Index begin, Index size, @type Index)
    # T output = Slice(T data, @INTS axes, @INTS ends, @INTS starts)
    starts = node.inputs[1].get_tensor_value()
    size = node.inputs[2].get_tensor_value()
    ends = np.add(starts, size)
    ctx.remove_input(node, node.input[2])
    ctx.remove_input(node, node.input[1])
    node.set_attr("starts", starts)
    node.set_attr("ends", ends)
    #shape = ctx.get_shape(node.input[0])
    ......
    return node
```

**Comment by laobadao** [comment]
`begin` is zero-based; `size` is one-based. If `size[i]` is -1,
  all remaining elements in dimension i are included in the
  slice. In other words, this is equivalent to setting:

  `size[i] = input.dim_size(i) - begin[i]`

  This operation requires that:

  `0 <= begin[i] <= begin[i] + size[i] <= Di  for i in [0, n]`

**Comment by zhijxu-MS** [comment]
the follwing PR fixed this issue.

https://github.com/onnx/tensorflow-onnx/pull/429

**Comment by zhijxu-MS** [comment]
@laobadao is the issue fixed? if so, i am going to close it, thanks.

**Comment by laobadao** [comment]
yes, thanks a lot.
