### ISSUE TITLE
AssertionError: pred_sbbox/concat_2 is not in graph

### ISSUE THREAD

**Issue by duanqipeng** [onnx/tensorflow-onnx#1001]
when i use the way(checkpoint way)to convert to onnx file,i occur the problem
![image](https://user-images.githubusercontent.com/17905397/86684621-4dd7a800-c035-11ea-93b3-a91a376c240e.png)
the script i use is
 `python -m tf2onnx.convert --checkpoint /home/lcy/DQP/yolov3_fire_detection-master/checkpoint/yolov3_test_loss=3.2609.ckpt-43.meta --output /home/lcy/DQP/yolov3_fire_detection-master/checkpoint/model1.onnx --inputs input/input_data:0[1,416,416,3] --outputs pred_sbbox/concat_2:0,pred_mbbox/concat_2:0,pred_lbbox/concat_2:0 --verbose --fold_const`
can somody solve the problem? thanks

**Comment by guschmue** [comment]
The error message says ```pred_sbbox/concat_2:0 ``` you passed in the command line is not in the graph. Can you re-check if that is really the correct output ?

**Comment by duanqipeng** [comment]
> The error message says `pred_sbbox/concat_2:0 ` you passed in the command line is not in the graph. Can you re-check if that is really the correct output ?

Hi，thanks for reply!The code i use is yolov3  and train on my dataset to detect fire and smoke,so i think the output should be the same with other yolov3 outputs.I am not familiar with tesorflow ,can you teach me how to know the correct outputs in the model?

**Comment by duanqipeng** [comment]
> The error message says `pred_sbbox/concat_2:0 ` you passed in the command line is not in the graph. Can you re-check if that is really the correct output ?

Acturally,i used to be success in useing your tools convert from .pb to onnx but when i use the .onnx file to get a tensorrt engine,it's only 2kb! when i print the num_layer,it only have one layer,i don't know why

**Comment by guschmue** [comment]
So the onnx file is only 2k? 
tf2onnx will find the subgraph you'd need to produce the output - one possibility is that if you'd pick an output close to the inputs that the onnx file might be very small.
At the end of running to tf2onnx it prints some stats where you can see how many conv, etc ... it might give you some hint.

**Comment by duanqipeng** [comment]
> So the onnx file is only 2k?
> tf2onnx will find the subgraph you'd need to produce the output - one possibility is that if you'd pick an output close to the inputs that the onnx file might be very small.
> At the end of running to tf2onnx it prints some stats where you can see how many conv, etc ... it might give you some hint.

the onnx's size is
![image](https://user-images.githubusercontent.com/17905397/86701534-b11d0680-c044-11ea-9b89-91686c7d7a88.png)
but when i use the tensorrt to load the onnx file ,the output engine is only 2kb,only have one layer

![image](https://user-images.githubusercontent.com/17905397/86701825-f2adb180-c044-11ea-9a8d-9a590b09d7c9.png)

**Comment by guschmue** [comment]
seems to be more a trt issue.

**Comment by MuhammadAsadJaved** [comment]
@duanqipeng  Have you resolved this issue? I am having the same problem. 

I am able to convert .pb to .onnx but got the same error while converting from .ckpt.meta to .onnx.

**Comment by guschmue** [comment]
closing - seems a trt issue
