### ISSUE TITLE
How to specify --inputs-as-nchw? 

### ISSUE THREAD

**Issue by p98-ai** [onnx/tensorflow-onnx#1007]
**Describe the bug**
How to specify --inputs-as-nchw? Can you give one example. 
I want the order to be HWC [Height, Width, Channel] instead of CHW [Channel, Height, Width] 
While converting from keras to onnx,
How should I specify this?

**Comment by guschmue** [comment]
currently we support only NHWC since it is pretty rare to not have a batch dimension.

**Comment by bekor** [comment]
Hey,

I think I have the same issue. I have to specify input as NCHW because the converter is Transposing the input: https://github.com/opencv/opencv/issues/17917

Is there a workaround to eliminate the transposition when I converting a .pb to onnx?

**Comment by guschmue** [comment]
my comment above it a little misleading, let me explain a little better:
```--inputs-as-nchw some_input_name:0``` will insert the transpose but only for NHWC aka rank 4. The original issue wanted HWC (without N) I believe. But in your case ```--inputs-as-nchw some_input_name:0``` should work I believe.

**Comment by p98-ai** [comment]
yes i was referring to (with N). 
thanks @guschmue ,

**Comment by guschmue** [comment]
Oh good, if you have N you should be able to use ```--inputs-as-nchw some_input_name:0```
