### ISSUE TITLE
How to set outputs as nchw?

### ISSUE THREAD

**Issue by zccyman** [onnx/tensorflow-onnx#1008]
````
python -m tf2onnx.convert --graphdef output/frozen_models/simple_frozen_graph.pb --output colorE.onnx --inputs x:0 --outputs Identity:0 --opset 11 --inputs-as-nchw x:0
````
I want to specify the outputs as nchw, not a nhwc format. Have any plan to support it?

**Comment by guschmue** [comment]
we don't support this because we have not seen much models where this applies. We'll consider adding an option.

**Comment by zccyman** [comment]
@guschmue Thanks. I hope this onnx model can be loaded by tensorRT or OpenCV DNN, and tensorRT or OpenCV DNN support input and output dimension as NCHW formate.

**Comment by feiyuhuahuo** [comment]
@zccyman  You can transpose the output format to NCHW  manually in your code. Then convert the model to ONNX format. Besides, I'd like to ask if you have tried to load onnx model by tensorRT? Have you encountered any problems?

**Comment by zccyman** [comment]
> @zccyman You can transpose the output format to NCHW manually in your code. Then convert the model to ONNX format. Besides, I'd like to ask if you have tried to load onnx model by tensorRT? Have you encountered any problems?

No other questions. only found the output dimension is NHWC formate, and need to transpose manually in my code.

**Comment by nithinme3** [comment]
@feiyuhuahuo Thanks man.. it was simple..but really helped.
