### ISSUE TITLE
AttributeError: 'Driver' object has no attribute 'disable_pyfun'

### ISSUE THREAD

**Issue by Thinker-or-Dreamer** [onnx/tensorflow-onnx#1013]
when I run the efficientdet.ipynb in tutorials,it gives an erro
<ipython-input-15-65245b866a80> in build(self, params_override)
     19             class_outputs, box_outputs = build_model(self.model_name, images, **params)
     20             params.update(
---> 21                 dict(batch_size=self.batch_size, disable_pyfun=self.disable_pyfun))
     22             detections = det_post_process(params, class_outputs, box_outputs, scales,
     23                                           self.min_score_thresh,

AttributeError: 'Driver' object has no attribute 'disable_pyfun'
How can I solve it

**Comment by guschmue** [comment]
Yes, it keeps changing. Let me update the tutorial to the latest efficientdet

**Comment by hududed** [comment]
Hello

is there a solution to this?

**Comment by guschmue** [comment]
Sorry, forgot about this one. Let me see if I get it to work on their master.

**Comment by cvhuang** [comment]
Hi,
@guschmue
After comment params.update and modified det_post_process, I was able to convert the model to onnx and run in onnxruntime. It's works. But, when I used the onnx model in tensorrt, it did not support uint8 datatype. So I changed the raw_imges's datatype to tf.float32. This time datatype worked, but another error incurred. 

----------------------------------------------------------------
Input filename:   ./d0.onnx
ONNX IR version:  0.0.7
Opset version:    12
Producer name:    tf2onnx
Producer version: 1.7.1
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
[11/03/2020-14:53:26] [W] [TRT] onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
ERROR: builtin_op_importers.cpp:2248 In function importPad:
[8] Assertion failed: inputs.at(1).is_weights()
-----------------------------------------------------------------

Unfortunately, this time I could not find a way to get out.

Could you please write an a  tutorial how to use efficientdet ONNX model in tensorrt.
Many thanks!

**Comment by anhlt18vn** [comment]
I have the same issue. Any update?

**Comment by guschmue** [comment]
working on it. Exporting to onnx works now again but we have some issue with how the latest efficientdet uses nms. Once I fix that we should be good.
I'm not sure about the tensorrt issue above - we'd cast down to int32 only when needed (ie nms in onnx outputs int64 indexes but in tensorflow it is int32 so we need to cast).

**Comment by guschmue** [comment]
this should be ok now.
