### ISSUE TITLE
Wrong conversion of simple model. Few Transposes and excess input layers

### ISSUE THREAD

**Issue by bronstein87** [onnx/tensorflow-onnx#1024]
**Describe the bug**
After conversion from tensorflow graph i get onnx model with few sequential transposes and excess input layers. Here what i'm talking about:
![Снимок](https://user-images.githubusercontent.com/17082585/88699628-3fe6e580-d110-11ea-8f1c-54114763824c.PNG)
![Снимок2](https://user-images.githubusercontent.com/17082585/88699640-41b0a900-d110-11ea-8ce2-8e2107e57ccc.PNG)

**System information**
- Windows 10
- Tensorflow Version: 1.15.0
- Python version: 3.7.0
- tf2onnx, onnx version: 1.7.0

**To Reproduce**

https://drive.google.com/drive/folders/1hzck3gW54LFknuySV2QNb60Myb83CRbR?usp=sharing
here is code to generate model which i try to convert and onnx file which i get after conversion

**Comment by guschmue** [comment]
did you use command line or python api?

**Comment by bronstein87** [comment]
> did you use command line or python api?

Hi. That is code i used to convert:
```
    output_graph_def = tf2onnx.tf_loader.freeze_session(session, input_names=["images:0"], output_names=["features:0"])
    output_graph = "model_tf_test.pb"
    with tf.gfile.GFile(output_graph, "wb") as f:
        f.write(output_graph_def.SerializeToString())

    with tf.Graph().as_default() as tf_graph:
        tf.import_graph_def(output_graph_def, name='')

    onnx_graph = tf2onnx.tfonnx.process_tf_graph(tf_graph, input_names=["images:0"],
                                  output_names=["features:0"], opset=10)
    model_proto = onnx_graph.make_model("test")
    with open("D:/projects/deep_sort-master/RUNNINGDATA/tensor_networks/model_tf_float2.onnx", "wb") as f:
        f.write(model_proto.SerializeToString())
```

**Comment by guschmue** [comment]
after tf2onnx.tfonnx.process_tf_graph, add the line (from https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/convert.py#L157):
```
 onnx_graph = optimizer.optimize_graph(onnx_graph)
```
