### ISSUE TITLE
The outputs shape of onnx model converted from SavedModel is not identical with original shape

### ISSUE THREAD

**Issue by meatybobby** [onnx/tensorflow-onnx#1029]
**Describe the bug**
The outputs shape of onnx model is changed after converting from SavedModel.
The original outputs of SavedModel show by `saved_model_cli`:
```
  The given SavedModel SignatureDef contains the following output(s):
    outputs['end_logits'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 384)
        name: unstack:1
    outputs['start_logits'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 384)
        name: unstack:0
    outputs['unique_ids'] tensor_info:
        dtype: DT_INT32
        shape: (-1)
        name: unique_ids_1:0
```
The outputs shape of ONNX model converted from SavedModel:
```
>>> model = onnx.load('model.onnx')
>>> model.graph.output
[name: "unique_ids_1:0"
type {
  tensor_type {
    elem_type: 6
    shape {
      dim {
        dim_param: "unk__1109"
      }
    }
  }
}
, name: "unstack:1"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_param: "unk__1110"
      }
      dim {
        dim_value: 384
      }
    }
  }
}
, name: "unstack:0"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: 1
      }
      dim {
        dim_param: "unk__1111"
      }
      dim {
        dim_value: 384
      }
    }
  }
}
]
```
The shape of outputs "unstack:0" is changed from (-1, 384) to (1, -1, 384). The shape of other outputs are identical. Only this one is changed.

**System information**
- OS Platform and Distribution : Linux Ubuntu 18.04
- Tensorflow Version: 1.15.2
- Python version: 3.6.9

**To Reproduce**
The SavedModel file: https://drive.google.com/file/d/1gMA5I-m_11syafvbeJSDl8I5ky1Cw9Q1/view?usp=sharing
Follow the instructions(https://github.com/onnx/tensorflow-onnx#getting-started) to convert the SavedModel:
```
pip install git+https://github.com/onnx/tensorflow-onnx
python -m tf2onnx.convert --saved-model model.savedmodel --output model.onnx --opset 12
```

**Expected behavior**
The outputs shape should be identical.

**Comment by guschmue** [comment]
yes, that doesn't look right. We'll look at it.

**Comment by jashshah** [comment]
Do we have any updates on this?

**Comment by TomWildenhain-Microsoft** [comment]
Looking at it now
