### ISSUE TITLE
tensorflow Pad operator

### ISSUE THREAD

**Issue by dmoham1476** [onnx/tensorflow-onnx#103]
Is there an option in tf2onnx to fuse the Pad operator into the Conv? The caffe2->onnx model has no operators and instead has a conv layer with padding, in tensorflow and the tf2onnx model, there is a separate pad operator followed by conv and the conv operator does not have a paddings input (unlike caffe)

**Comment by guschmue** [comment]
we follow the tensorflow graph: if the conv op has padding we map it to onnx and pass it to the conv op.
If there is a seperate pad op after the conv we'll add the same to onnx.
I assume you are asking if we can fuse the pad op into the previous conv op?
Hm, yes - might be doable. Need to look into details.

**Comment by guschmue** [comment]
On second thought: a tf.pad() after tf.conv2d() would pad the output while onnx conv() pads=[...] would pad the input. So maybe if you have something like conv1->pad->conv2->pad->conv3 you could fuse the pad into the following conv but I'd expect model models will do this already in the source code ... have not seen many models that call tf.pad()

**Comment by dmoham1476** [comment]
Hi, I see that the pad operator is before the convolution. (pad->conv), I see this pattern in resnet50 tensorflow graph in three places.

**Comment by guschmue** [comment]
I can take a look, maybe there is a way of fusing this into the pads for conv()

**Comment by tlepley-cadence** [comment]
We've also got a  different TF models with this Pad node before Conv2D. We had to handle it after tf2onnx. But if tf2onnx does the merge of Pad with Conv2D, I think this makes the generated ONNX model nicer.

**Comment by pengwa** [comment]
this should be fixed in https://github.com/onnx/tensorflow-onnx/pull/334 by @lucienwang1009 . please let us know if you still have issue on this.
