### ISSUE TITLE
Conversion Artifacts in MobileNetv3 on h-Swish, h-Sigmoid

### ISSUE THREAD

**Issue by phager90** [onnx/tensorflow-onnx#1039]
**Describe the bug**
When converting MBv3 the additive terms (+3) in the h-Swish and h-Sigmoid activation (https://arxiv.org/pdf/1905.02244.pdf) are not initializers within the 'Add'-node but broadcasted from one common reshape node.

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.1 LTS
- Tensorflow Version: 2.3.0
- Python version: 3.6.10
- tf2onnx: 1.7.0

**To Reproduce**
python ./tests/run_pretrained_models.py --tests mobilenet_v3_large_float --onnx-file out

**Expected behavior**
I would expect the +3 to be an initializer within the add node

**Screenshots**
![image](https://user-images.githubusercontent.com/9904169/89391878-0f530d00-d709-11ea-9d23-05e74199a1f0.png)

![image](https://user-images.githubusercontent.com/9904169/89391937-21cd4680-d709-11ea-9f9b-5c3bdd0e0d13.png)

**Comment by guschmue** [comment]
Oh, you mean the reshape(const, const) can be constant folder?
Yes, good observation and something we can fix.

**Comment by phager90** [comment]
Yes, I meant the constant folding, i.e., to have the constant 3 inside the Add node. 
(same as with "B"-operand for the mult node in the screenshot above)

**Comment by phager90** [comment]
@guschmue:
I had some time and I patched this locally on my installation:

in `tf2onnx/optimizer/const_fold_optimizer.py` I added:
```
    @staticmethod
    @_register_func("Reshape")
    def _fold_reshape(node, graph):
        const_val_data = node.inputs[0].get_tensor_value(as_list=False) 
        const_val_shape = node.inputs[1].get_tensor_value(as_list=False)
        const_val_after_trans = const_val_data.reshape(const_val_shape)
        return [const_val_after_trans]
```

If you want the patch via pull request let me know.
[but I cannot write a unit test for it at this point for it...]

**Comment by guschmue** [comment]
contributions are very welcome and since you already have the fix - yes please. We can take care of the unit test.
