### ISSUE TITLE
get_tf_tensor_data in utils.py does not consider tf.float16

### ISSUE THREAD

**Issue by ziyuang** [onnx/tensorflow-onnx#104]
In TensorFlow 1.10 `tf.float16` has a value of 19.
Adding 

    elif tensor.dtype == tf.float16:
            data = [0]  # not [0.]

bypasses the `'tensor data not supported'` error but I wonder it is safe for the conversion.

**Comment by guschmue** [comment]
Sure, we should fix this. Want to send a  PR or want me to fix it ?

**Comment by ziyuang** [comment]
Looks like the PR #105 breaks some checks.

**Comment by guschmue** [comment]
yes, but not your fault. Some conflict with the travis env and tf-1.10. 
I changed the travis env to use tf-1.9 for now.

**Comment by guschmue** [comment]
fix merged: https://github.com/onnx/tensorflow-onnx/pull/105
