### ISSUE TITLE
Sparse2Dense layer not supported

### ISSUE THREAD

**Issue by Narasimha1997** [onnx/tensorflow-onnx#1048]
I am trying to convert [Universal Sentence encoder](https://tfhub.dev/google/universal-sentence-encoder-lite/2) lite given by Tensorflow Hub. When I try to convert it with opset 12, I get the error saying that the operation `Sparse2Dense` is not supported. 

Here is the error I am getting : 
```
Tensorflow op [Encoder_en/KonaTransformer/Encode/SparseToDense: SparseToDense] is not supported
Unsupported ops: Counter({'SparseToDense': 1})
```
However this op is available in Tensorflow and I have read we can add custom ops by mapping them, but there is no well-defined documentation for this, so I decided to post this here, How can I mitigate this issue? The end goal is to successfully convert this model to ONNX and run inference on the ONNX model.

**Comment by guschmue** [comment]
SparseToDense comes from tf.sparse.to_dense(). As far I know there is no onnx op we could map this too but we can take a look if there is a way of composing this with some other ops.
