### ISSUE TITLE
change name of input in the .onnx file

### ISSUE THREAD

**Issue by dmoham1476** [onnx/tensorflow-onnx#107]
How can I change the name of the input in the generated .onnx file? As in I see in tf2onnx, the input node name is input:0 and for the caffe2onnx it is data_0. I want to keep these names consistent.

**Comment by guschmue** [comment]
We take the names as found in the tensorflow model since they are defined by the model developer this way. No plans to change this.

**Comment by vsoorya** [comment]
when the input node is "input:0" , and I try to load the model with tensorflow backend, I get an error saying it is not a valid scope name.

onnx_tf.backend.prepare(model)
ValueError: 'input:0' is not a valid scope name

I guess the ":" in the name is causing this error. How to fix this.

**Comment by mrgloom** [comment]
Where these names can be changed in the code?
