### ISSUE TITLE
Inconsitent <Conv - BN> Fusing Behaviour

### ISSUE THREAD

**Issue by phager90** [onnx/tensorflow-onnx#1079]
**Describe the bug**
On some networks the BN layer is not fused into the Conv operation. 
Sometimes there are dedicated Mul and Add operations placed as independent operations (see SDD-MBv1 example).
In other cases, some BN layers remain (EfficientNet Lite example).

**To Reproduce**
If I follow this tutorial for SSD-MBv1:
https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/ConvertingSSDMobilenetToONNX.ipynb

I noticed a problem with the BN fusing:
![image](https://user-images.githubusercontent.com/9904169/91449788-d4fa0d00-e87b-11ea-9066-43793de9ba08.png)

However, if I check the onnx file form here:
https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/ssd-mobilenetv1
... which was supposedly created with the same script then the fusing is ok:

![image](https://user-images.githubusercontent.com/9904169/91450128-3d48ee80-e87c-11ea-827a-5850995631bf.png)

I am wondering, why I am getting different results here.

---

I see similar issues in other networks: Here Efficientnet Lite0:
![image](https://user-images.githubusercontent.com/9904169/91450368-80a35d00-e87c-11ea-91e9-31ad32b10143.png)
For some reasons *some* BN layers are not fused. (but many others are fused correctly)

**Urgency**
None

**System information**
- Tensorflow Version: 2.3.0
- Python version: 3.6.10

**Expected behavior**
Consitent fusing of BN layers into CONV layers

**Comment by guschmue** [comment]
In theory we should be fusing both of the above but there are some constrains when we don't touch it. We can take a look.

**Comment by phager90** [comment]
@guschmue thanks!

BTW: can you tell me where the fusing of the first case is taking place?
I figured the second (BN fusing) is done in the back_to_back_optimizer.py, but I could not find the 'Mul Add' fusing.

**Comment by guschmue** [comment]
the Mul/Add sequence is part of the transpose optimizer (ok it should not be there).
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/optimizer/transpose_optimizer.py#L378
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/optimizer/transpose_optimizer.py#L469

Tested this is a little with ssd-mobilenet - in all cases we got rid of them.

**Comment by phager90** [comment]
@guschmue Thanks for checking! And thanks for letting me know where this is in the optimizer!

However, I am not sure I fully understood your answer: 
You basically are saying that you cannot reproduce the "behaviour", in the sense that in your tests, they were always properly merged?

I will check then why this is not the case on my side. 
In case, I would figure out something, I would post this here.

**Comment by guschmue** [comment]
Yes, always looks good for me. I'm using tf-1.15 and tf-2.3.
We don't fuse bn if any of the parameters are consumed by others.
