### ISSUE TITLE
tf.string support

### ISSUE THREAD

**Issue by bedapisl** [onnx/tensorflow-onnx#1080]
Hello, does onnx support models with tf.string tensor type?

**Comment by guschmue** [comment]
In general yet but not as complete as tensorflow and in tf2onnx we don't do a lot with it because there was not much ask for it.
Got a specific model in mind?

**Comment by bedapisl** [comment]
Thanks for the answer.

> Got a specific model in mind?

 We have a model based on universal sentence encoder (https://www.tensorflow.org/hub/tutorials/semantic_similarity_with_tf_hub_universal_encoder).
