### ISSUE TITLE
OSError: SavedModel file does not exist (tf 2.3.0)

### ISSUE THREAD

**Issue by shiragit** [onnx/tensorflow-onnx#1082]
I'm trying to convert a tf2 pretrained model, downloaded from the tf2 model zoo - ssd_resnet50_v1_fpn_1024x1024_coco17_tpu-8 (a saved_model is already included).
While running the conversion command on tf==2.3.0, I'm getting this following error:
`OSError: SavedModel file does not exist at: /tf2_onnx_trt/ssd_resnet50_v1_fpn_1024x1024_coco17_tpu-8/saved_model/{saved_model.pbtxt|saved_model.pb}`

**Comment by guschmue** [comment]
what's the link to the model? And what command line did you use ?

**Comment by shiragit** [comment]
here's the link to the model: http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_resnet50_v1_fpn_1024x1024_coco17_tpu-8.tar.gz

I used: 
`python -m tf2onnx.convert --opset 11 --saved-model /ssd_resnet50_v1_fpn_1024x1024_coco17_tpu-8/saved_model --output /ssd_resnet50_v1_fpn_1024x1024_coco17_tpu-8/saved_model/model.onnx`

**Comment by shiragit** [comment]
solved!

**Comment by yfq512** [comment]
@shiragit ,Hi, how do you solved? I have the same bug, when I update TensorFlow, bug comes

**Comment by nezbyy** [comment]
Dne út 29. 9. 2020 8:31 uživatel yfq512 <notifications@github.com> napsal:

**Comment by yfq512** [comment]
I solved it，卸载h5py，重新安装h5py

**Comment by Marwen-Bhj** [comment]
at least share the solution for others who faced the same issue.
