### ISSUE TITLE
replace_all_inputs() method it doesn't work

### ISSUE THREAD

**Issue by laobadao** [onnx/tensorflow-onnx#109]
```
    @staticmethod
    def replace_all_inputs(ops, old_input, new_input):
        """Replace all inputs pointing to old_input with new_input."""
        for node in ops:
            for i, input_name in enumerate(node.input):
                if input_name == old_input:
                    node.input[i] = new_input
```

```
    @property
    def input(self):
        return self._input
```

don't have a setter method

**Comment by pengwa** [comment]
what's wrong with this? what do you think to fix it?

**Comment by guschmue** [comment]
input doesn't have a setter because we never update the list reference itself, only the content of the list. Basically we do things like ```input[1] =x or input.append(x)``` but we don't do ``input = [] or input = x```. The later would require a setter.
