### ISSUE TITLE
NonMaxSuppressionV3,Round and Atan2 operators do not support on AVOD model convert

### ISSUE THREAD

**Issue by zengdiqing1994** [onnx/tensorflow-onnx#1092]
**Describe the bug**
I have trained AVOD(Aggregate View Object Detection) model by TensorFlow, and want to convert the frozen pb model to ONNX model, but when I used tf2onnx tool to convert, it will appear:

**ERROR - Tensorflow op [proposals/nms/non_max_suppression/NonMaxSuppresionV3: NonMaxSuppresionV3] is not supported.
ERROR - Tensorflow op [avod_nms/non_max_suppression/NonMaxSuppresionV3: NonMaxSuppresionV3] is not supported.**

**ERROR - Tensorflow op [avod_regression/Atan2_1: Atan2] is not supported.
ERROR - Tensorflow op [avod_regression/Atan2: Atan2] is not supported.
ERROR - Tensorflow op [avod_orientation/Atan2: Atan2] is not supported.**

**ERROR - Tensorflow op [avod_regression/Round: Round] is not supported.
ERROR - Tensorflow op [avod_encode_mb_anchors/Round_3: Round] is not supported.
ERROR - Tensorflow op [avod_encode_mb_anchors/Round_2: Round] is not supported.**

It seems that tf2onnx tool does not support these ops: NonMaxSuppresionV3, Atan2, and Round. But I found on [tf2onnx Support Status](https://github.com/onnx/tensorflow-onnx/blob/19d3f9726e573994427c96659dd1e901637e04ff/support_status.md), it really supports NonMaxSuppressionV3 and Round, and on [math.py](https://github.com/onnx/tensorflow-onnx/blob/19d3f9726e573994427c96659dd1e901637e04ff/tf2onnx/onnx_opset/math.py) and [test_backend.py](https://github.com/onnx/tensorflow-onnx/blob/d7fe8bb0147a3ea79f64eee00a9e4cf78be91950/tests/test_backend.py), it includes the Atan2 ops, but how can I use in the tf2onnx tool to implement those?

**System information**
- Linux Ubuntu 16.04.1):
- Tensorflow Version: 1. 15
- Python version: 3.6.10

**Additional**
 As more and more adas models to be used now, especially 3D detection, so maybe we should trace the process to pay attention to that.

Thanks a lot!

**Comment by guschmue** [comment]
NonMaxSuppresionV3, Atan2 and Round are supported. Try adding ```--opset 11``` to the command line.

**Comment by zengdiqing1994** [comment]
> NonMaxSuppresionV3, Atan2 and Round are supported. Try adding `--opset 11` to the command line.

Oh, excellent! it converts correctly! What is the command '--opset 11' meaning? Does the modifies merged in opset 11 version or some other explains? Thanks for your reply!

**Comment by guschmue** [comment]
opset is the 'version' of onnx. If new ops are added or enhanced the opset is released. 
We default to opset 8 which is pretty old but  supported by most runtimes.
opset 11 has much better support for things like NonMaxSuppresion but as far I know onnxruntime is the only one fully supporting it,

**Comment by zengdiqing1994** [comment]
> opset is the 'version' of onnx. If new ops are added or enhanced a new opset is released.
> We default to opset 8 which is pretty old but supported by most runtimes.
> opset 11 has much better support for things like NonMaxSuppresion but as far I know onnxruntime is the only one fully supporting it,

Yes and the onnxruntime of Microsoft supports crop_and_resize, it seems that it covers a lot! Thanks again!
