### ISSUE TITLE
multiple input node

### ISSUE THREAD

**Issue by hopflink** [onnx/tensorflow-onnx#110]
How can transform models with multiple input nodes?

**Comment by pengwa** [comment]
python -m tf2onnx.convert\
    --input tests/models/fc-layers/frozen.pb\
    --inputs X:0\
    --outputs output:0\
    --output tests/models/fc-layers/model.onnx\
    --verbose


You can specify multiple input nodes in "inputs" parameter, and make them separated with comma. 

be noted, there should be no spaces.
