### ISSUE TITLE
Incorrect graph conversion of fp16 model

### ISSUE THREAD

**Issue by pawel-ziecina** [onnx/tensorflow-onnx#1104]
**Describe the bug**
Tried to convert TF 1.15 16bit floating-point ResNet50 model using the tf2onnx tool.
The resulting model has wrong graph structure, which causes errors during inference.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Tensorflow Version: 1.15.2
- Python version: 3.6.9

It is run under `nvcr.io/nvidia/tensorflow:20.06-tf1-py3` container.

**To Reproduce**
Describe steps/code to reproduce the behavior:

1. download tf saved models (fp32 and fp6): 

https://drive.google.com/drive/folders/1RDkDGS4LxjXGpieiYAsch8qguk4WKvtH?usp=sharing

2. install python packages:
``` shell
pip install onnx==1.7.0
pip install onnxruntime==1.4.0
pip install tf2onnx==1.6.3
```
- convert models with 
``` shell
python -m tf2onnx.convert \
    --saved-model tf-fp32.savedmodel \
    --opset 12 \
    --output model-fp32.onnx
python -m tf2onnx.convert \
    --saved-model tf-fp16.savedmodel \
    --opset 12 \
    --output model-fp16.onnx
```
- run onnx inference with code:
``` python3
#!/usr/bin/env python3
from numpy.random import default_rng
import numpy as np
import onnxruntime

providers = [
    'CUDAExecutionProvider',
    'CPUExecutionProvider',
]

def dataloader(n=16):
    rng = default_rng()
    for i in range(n):
        x = rng.integers(0, 255, (1, 224, 224, 3)).astype(np.float32)
        y_true = rng.integers(0, 1000, (1, )).astype(np.int32)
        yield {'input_tensor:0': x}, {'classes': y_true}

def main():
    import argparse

    parser = argparse.ArgumentParser(description='short_description')
    parser.add_argument('--onnx-model', help='Path to ONNX model', required=True)
    args = parser.parse_args()

    output_names = ['resnet50/output/softmax:0', 'ArgMax:0']
    sess = onnxruntime.InferenceSession(args.onnx_model, providers=providers)
    for x, y_true in dataloader(n=16):
        y_pred = sess.run(output_names, x)
        y_pred = dict(zip(output_names, y_pred))
        print(x, y_true, y_pred)


if __name__ == '__main__':
    main()
```
- for model-fp16.onnx got errors
```
Traceback (most recent call last):
  File "./infer_onnx.py", line 34, in <module>
    main()
  File "./infer_onnx.py", line 26, in main
    sess = onnxruntime.InferenceSession(args.onnx_model, providers=providers)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers or [])
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Type Error: Type parameter (T) bound to different types (tensor(float16) and tensor(float) in node (resnet50/conv2d/conv2d/Conv2D).
```

**Expected behavior**
FP16 model provides results for a given set of inputs as in the FP32 case.

**Additional context**
As the error is pointing, the first Conv2d has 2 not compatible inputs: fp16 input data and fp32 kernel data. This part of graph changed after running `remove_back_to_back` optimizer in `optimizer.optimize_graph(g)`. But even after disabling `optimize_graph` function there is same kind of errors in another place of a graph.

**Comment by guschmue** [comment]
let me take a look.

**Comment by guschmue** [comment]
yes, the kernel is fp16 in the tf model and for some reason we end up with fp32. Going to fix it.

**Comment by guschmue** [comment]
saw your app working after the fix.

**Comment by pawel-ziecina** [comment]
Yes, it works as intended. Thanks!
