### ISSUE TITLE
Object Detection Models

### ISSUE THREAD

**Issue by ram1897** [onnx/tensorflow-onnx#111]
When can we expect support for Object detection models (for example Faster RCNN) will be added?

**Comment by pengwa** [comment]
as I tried previously, on a few faster rcnn models, they are all stuck at tf.resource type conversion failure, https://github.com/onnx/tensorflow-onnx/issues/61. 

This is related to control flow ops, while onnx till now, only has limited supported on control flow, and it's still in experimental stage. So it might change before being part of formal op set. we may not support that now.

**Comment by guschmue** [comment]
most of the object detection model zoo should be working since some time.
