### ISSUE TITLE
Output of all zeros for inference using converted tf to onnx model

### ISSUE THREAD

**Issue by hemelroy** [onnx/tensorflow-onnx#1115]
**Describe the bug**
After converting tensorflow graphdef to .onnx file, the output of the onnx model consists of rows of zeros. It does not resemble the output of the pb file. 

**Urgency**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Tensorflow Version: 1.14.0
- Python version: 3.5.6

**To Reproduce**
Folder containing all necessary scripts and models to reproduce: https://drive.google.com/file/d/181zkK1jQ3B4XGPt9pCTp2QzxXAs0B8im/view

`simple_onnxruntime_test.py` is used to run .onnx model, `simple_pb_tf_test.py` is used to run .pb model.

Command used to generate .onnx file from .pb file: `python -m tf2onnx.convert --graphdef model.pb --output mymodel.onnx --inputs Placeholder_1:0 --outputs decoded/Sigmoid:0 --fold_const --opset 11`

**Expected behavior**
It is expected that the output of the final node of the onnx model resembles that of the pb file. 

**Screenshots**
Visual of the two model files:
![Screenshot from 2020-09-25 15-47-55](https://user-images.githubusercontent.com/41270801/94312318-a474c400-ff4a-11ea-96c9-ca87560a0039.png)

Comparison of pb file output (left) and onnx file output (right)
![image](https://user-images.githubusercontent.com/41270801/94312548-1b11c180-ff4b-11ea-8da0-a8f22c2a0dfd.png)

**Additional context**

- The pb file can be used to correctly generate an output when using tensorflow

- I've checked the output at several nodes for both .pb and .onnx files and have found the output of the input node is identical for both. However, the outputs for the nodes that follow start to differ greatly. The first conv_1 layer is not similar between the two

**Comment by TomWildenhain-Microsoft** [comment]
I'll take a look.  Thanks for providing the script

**Comment by TomWildenhain-Microsoft** [comment]
The problem is caused by the FusedBatchNorm op which has is_training set to true.  tf2onnx only supports graphs used for inference, not training.  When is_training is true, FusedBatchNorm has mean and variance empty which we change to 0, affecting the result.

**Comment by TomWildenhain-Microsoft** [comment]
Were you able to get the model to convert after setting is_training to false?

**Comment by hemelroy** [comment]
Sorry for the delay. There is an issue with the implementation of the tensorflow model itself, not actually setting the is_training to false. I'll close the issue, thanks for pointing that out.
