### ISSUE TITLE
ValueError: tensorflow op BatchMatMul is not supported

### ISSUE THREAD

**Issue by hopflink** [onnx/tensorflow-onnx#112]
I want to transform my own tf model to onnx, but I've got this message.
Is BatchMatMul not supported yet?

**Comment by guschmue** [comment]
Is this an older graph? I vaguely remember that tf.batch_matmul() was replaced by tf.matmul().
BatchMatMul is still registered in tf-1.10 but no python code would reference it ... I guess it is there for pre 1.0 graphs.
It should be possible to add support for it ... looking.

**Comment by guschmue** [comment]
made some change to master - hope it will do the job as long adj_x and adj_y attributes are not used. I can't really test it because newer versions of tensorflow  don't call this op.

**Comment by hopflink** [comment]
Thanks. My graph is built on tf1.2. I tested it and it seems work.
