### ISSUE TITLE
How to make face recognition using pb to onnx converted model?

### ISSUE THREAD

**Issue by KowsalyaR97** [onnx/tensorflow-onnx#1129]
Hi, I am converted facenet **VGGFACE** model 20180402-114759.pb to 20180402-114759.onnx model. I need to know is there any way to load this onnx model to make prediction on face dataset.
Example,
In facenet after making frozen graph we were creating classifier pickle file from the .PB file by loading and getting embeddings from the model file and make predictions on faces.
Likewise is there any way to load this converted onnx model to make prediction on face dataset.

**Comment by TomWildenhain-Microsoft** [comment]
Yes, you can run the model using the onnx runtime:
https://github.com/microsoft/onnxruntime

`pip install onnxruntime`

Let me know if you need more help with this

**Comment by KowsalyaR97** [comment]
@TomWildenhain-Microsoft... Thanks
