### ISSUE TITLE
Convert tensorflow 2 object detection model with StatefulPartitionedCall

### ISSUE THREAD

**Issue by scuaaa** [onnx/tensorflow-onnx#1153]
**Describe the bug**
Convert tensorflow 2 object detection model with StatefulPartitionedCall to onnx.
"ValueError: Input 1 of node StatefulPartitionedCall was passed float from conv1_conv/kernel:0 incompatible with expected resource."

**System information**
- OS Platform and Distribution:  windows 10
- Tensorflow Version: 2.1.0
- Python version: 3.7.9

**To Reproduce**
 1.Download the model: [SSD ResNet50 V1 FPN 640x640 (RetinaNet50)](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8.tar.gz)
 2 . Run python -m tf2onnx.convert --saved-model saved_model --output model.onnx --fold_const --tag serve --verbose

**Expected behavior**
Model is converted.

**Screenshots**

`D:\tf_train\workspaces\fangzhijiproject\trained_frozen_models\10.19\ssd_resnet50_v1_fpn_640_float_image_tensor>python -m tf2onnx.convert --saved-model saved_model --output model.onnx --fold_const --tag serve --verbose
WARNING:tensorflow:From d:\tf_train\addons\tensorflow-onnx-master\tf2onnx\verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2020-10-29 21:13:12,917 - WARNING - tensorflow: From d:\tf_train\addons\tensorflow-onnx-master\tf2onnx\verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2020-10-29 21:13:12.956540: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:From d:\tf_train\addons\tensorflow-onnx-master\tf2onnx\tf_loader.py:234: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
2020-10-29 21:13:13,003 - WARNING - tensorflow: From d:\tf_train\addons\tensorflow-onnx-master\tf2onnx\tf_loader.py:234: load (from tensorflow.python.saved_model.loader_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.loader.load or tf.compat.v1.saved_model.load. There will be a new function for importing SavedModels in Tensorflow 2.0.
INFO:tensorflow:Restoring parameters from saved_model\variables\variables
2020-10-29 21:13:31,708 - INFO - tensorflow: Restoring parameters from saved_model\variables\variables
WARNING:tensorflow:From d:\tf_train\addons\tensorflow-onnx-master\tf2onnx\tf_loader.py:149: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
2020-10-29 21:13:41,204 - WARNING - tensorflow: From d:\tf_train\addons\tensorflow-onnx-master\tf2onnx\tf_loader.py:149: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From C:\Users\yangw\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\framework\graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2020-10-29 21:13:41,239 - WARNING - tensorflow: From C:\Users\yangw\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\framework\graph_util_impl.py:277: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
INFO:tensorflow:Froze 463 variables.
2020-10-29 21:13:46,896 - INFO - tensorflow: Froze 463 variables.
INFO:tensorflow:Converted 463 variables to const ops.
2020-10-29 21:13:51,060 - INFO - tensorflow: Converted 463 variables to const ops.
2020-10-29 21:13:51,711 - INFO - tf2onnx: inputs: ['serving_default_input_tensor:0']
2020-10-29 21:13:51,711 - INFO - tf2onnx: outputs: ['StatefulPartitionedCall:0', 'StatefulPartitionedCall:1', 'StatefulPartitionedCall:2', 'StatefulPartitionedCall:3', 'StatefulPartitionedCall:4', 'StatefulPartitionedCall:5', 'StatefulPartitionedCall:6', 'StatefulPartitionedCall:7']
Traceback (most recent call last):
  File "C:\Users\yangw\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\framework\importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 1 of node StatefulPartitionedCall was passed float from conv1_conv/kernel:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\anaconda\envs\newone1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\software\anaconda\envs\newone1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\tf_train\addons\tensorflow-onnx-master\tf2onnx\convert.py", line 188, in <module>
    main()
  File "d:\tf_train\addons\tensorflow-onnx-master\tf2onnx\convert.py", line 154, in main
    tf.import_graph_def(graph_def, name='')
  File "C:\Users\yangw\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\yangw\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\framework\importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "C:\Users\yangw\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\framework\importer.py", line 505, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 1 of node StatefulPartitionedCall was passed float from conv1_conv/kernel:0 incompatible with expected resource.`

**Additional context**
I find two issues may related to my problem.
1. the data type of the node is not right. [#77](https://github.com/onnx/tensorflow-onnx/issues/77)
2. the node "StatefulPartitionedCall" may not supported in the conversion. [#1093](https://github.com/onnx/tensorflow-onnx/issues/1093)

Could any one give me some help?

**Comment by TomWildenhain-Microsoft** [comment]
The model converts fine for me using the latest opset (opset 12).  We have made some recent changes to fix issues like the one you describe.  Can you try using the latest tf2onnx from github?  Also what opset are you using?

`pip uninstall tf2onnx`
`pip install git+https://github.com/onnx/tensorflow-onnx`

**Comment by scuaaa** [comment]
> The model converts fine for me using the latest opset (opset 12). We have made some recent changes to fix issues like the one you describe. Can you try using the latest tf2onnx from github? Also what opset are you using?
> 
> `pip uninstall tf2onnx`
> `pip install git+https://github.com/onnx/tensorflow-onnx`

Thank you very much for your relpy!!

But I still can not fix the problem.
First I use `pip uninstall tf2onnx` , It's work.
But for `pip install git+https://github.com/onnx/tensorflow-onnx`.
![image](https://user-images.githubusercontent.com/64390450/97917133-02eb4a00-1d22-11eb-89ad-de909fc1f0ce.png)
It should be some problem about the git.

So, instead, I download the file from Git hub directly.
![image](https://user-images.githubusercontent.com/64390450/97917328-52317a80-1d22-11eb-8273-d5d44cdc19a2.png)
and use the code,

`pip uninstall tf2onnx
python setup.py install
python setup.py develop
python setup.py bdist_wheel`

All the code is working.

then use the code 
`python -m tf2onnx.convert --saved-model saved_model --output model.onnx --fold_const --tag serve --verbose --opset 12`

Then I get same results, did I do something wrong??? The version of code I download is not right??

**Comment by TomWildenhain-Microsoft** [comment]
Interesting... Can you run `pip list` and post the result?

**Comment by scuaaa** [comment]
sorry for my problem, I am just a newbie. Here is my result,
`(newone1) D:\tf_train\addons\tensorflow-onnx-master>pip list
Package                Version             Location
---------------------- ------------------- -----------------------------------------
absl-py                0.10.0
aiohttp                3.6.3
argon2-cffi            20.1.0
astor                  0.8.1
async-generator        1.10
async-timeout          3.0.1
attrs                  20.2.0
backcall               0.2.0
bleach                 3.2.1
blinker                1.4
brotlipy               0.7.0
cachetools             4.1.1
certifi                2020.6.20
cffi                   1.14.3
chardet                3.0.4
click                  7.1.2
colorama               0.4.4
cryptography           3.1.1
decorator              4.4.2
defusedxml             0.6.0
entrypoints            0.3
gast                   0.2.2
google-auth            1.22.1
google-auth-oauthlib   0.4.1
google-pasta           0.2.0
graphviz               0.8.4
grpcio                 1.31.0
h5py                   2.10.0
idna                   2.6
importlib-metadata     2.0.0
ipykernel              5.3.4
ipython                7.18.1
ipython-genutils       0.2.0
ipywidgets             7.5.1
jedi                   0.17.2
Jinja2                 2.11.2
jsonschema             3.2.0
jupyter                1.0.0
jupyter-client         6.1.7
jupyter-console        6.2.0
jupyter-core           4.6.3
jupyterlab-pygments    0.1.2
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.0
Markdown               3.3.2
MarkupSafe             1.1.1
mistune                0.8.4
mkl-fft                1.2.0
mkl-random             1.1.1
mkl-service            2.3.0
multidict              4.7.6
mxnet                  1.5.0
nbclient               0.5.1
nbconvert              6.0.7
nbformat               5.0.8
nest-asyncio           1.4.1
networkx               2.4
notebook               6.1.4
numpy                  1.19.1
oauthlib               3.1.0
onnx                   1.7.0
opt-einsum             3.1.0
packaging              20.4
pandocfilters          1.4.2
parso                  0.7.0
pickleshare            0.7.5
pip                    20.2.4
prometheus-client      0.8.0
prompt-toolkit         3.0.8
protobuf               3.13.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycparser              2.20
Pygments               2.7.1
PyJWT                  1.7.1
pyOpenSSL              19.1.0
pyparsing              2.4.7
pyreadline             2.1
pyrsistent             0.17.3
PySocks                1.7.1
python-dateutil        2.8.1
pywin32                227
pywinpty               0.5.7
PyYAML                 5.3.1
pyzmq                  19.0.2
qtconsole              4.7.7
QtPy                   1.9.0
requests               2.18.4
requests-oauthlib      1.3.0
rsa                    4.6
scipy                  1.5.2
Send2Trash             1.5.0
setuptools             50.3.0.post20201006
six                    1.15.0
tensorboard            1.15.0
tensorboard-plugin-wit 1.6.0
tensorflow             1.15.4
tensorflow-estimator   1.15.1
termcolor              1.1.0
terminado              0.9.1
test-generator         0.1.1
testpath               0.4.4
tf2onnx                1.8.0               d:\tf_train\addons\tensorflow-onnx-master
tornado                6.0.4
traitlets              5.0.5
typing-extensions      3.7.4.3
urllib3                1.22
wcwidth                0.2.5
webencodings           0.5.1
Werkzeug               0.16.1
wheel                  0.35.1
widgetsnbextension     3.5.1
win-inet-pton          1.1.0
wincertstore           0.2
wrapt                  1.12.1
yarl                   1.6.2
zipp                   3.3.1`

**Comment by TomWildenhain-Microsoft** [comment]
Hmm... I don't have much experience with Conda.  Can you try making a fresh virtual environment with pip?
`python -m venv tf2onnxvenv`
Then pip install tensorflow, onnx, onnxruntime, and git+https://github.com/onnx/tensorflow-onnx
I'm not sure why you are getting the git issue.  If you get it again in the new venv, try running `git clone https://github.com/onnx/tensorflow-onnx.git` directly and see if you get the same error.

**Comment by TomWildenhain-Microsoft** [comment]
It looks like you are using Tensorflow 1.15.4 not Tensorflow 2.1.0.  I think that is the problem.  If you make a new venv with the latest version of TF (2.3.0) you should be fine.  TF1 doesn't know how to deal with StatefulPartitionedCalls properly.

**Comment by scuaaa** [comment]
> It looks like you are using Tensorflow 1.15.4 not Tensorflow 2.1.0. I think that is the problem. If you make a new venv with the latest version of TF (2.3.0) you should be fine. TF1 doesn't know how to deal with StatefulPartitionedCalls properly.

Thank you very much for your help. This is indeed the problem I have. I use the conda enviroment, so the pip enviroment is not supported with the code.

I test tensorlfow=2.3 in my windows 10, it works!
`2020-11-02 16:36:58,920 - INFO - tf2onnx.optimizer: After optimization: BatchNormalization -94 (97->3), Cast -29 (75->46), Const -717 (977->260), Identity -58 (58->0), Mul -2 (18->16), Reshape -1 (24->23), Shape -1 (16->15), Slice -1 (25->24), Squeeze -2 (31->29), Sub -1 (21->20), Transpose -401 (426->25), Unsqueeze -12 (49->37)
2020-11-02 16:36:59,020 - INFO - tf2onnx:
2020-11-02 16:36:59,021 - INFO - tf2onnx: Successfully converted TensorFlow model saved_model to ONNX
2020-11-02 16:37:00,109 - INFO - tf2onnx: ONNX model is saved at model.onnx`

Then I test tensorflow=2.2 in my ubuntu 20.04, it's works too. Thank you!
`2020-11-02 16:38:03,915 - INFO - tf2onnx.optimizer: After optimization: BatchNormalization -94 (97->3), Cast -29 (75->46), Const -717 (977->260), Identity -58 (58->0), Mul -2 (18->16), Reshape -1 (24->23), Shape -1 (16->15), Slice -1 (25->24), Squeeze -2 (31->29), Sub -1 (21->20), Transpose -401 (426->25), Unsqueeze -12 (49->37)
2020-11-02 16:38:03,974 - INFO - tf2onnx: 
2020-11-02 16:38:03,974 - INFO - tf2onnx: Successfully converted TensorFlow model saved_model to ONNX
2020-11-02 16:38:04,212 - INFO - tf2onnx: ONNX model is saved at model.onnx
`

Thanks a lot, bro !!!

**Comment by TomWildenhain-Microsoft** [comment]
Awesome!  Glad it works!
