### ISSUE TITLE
Issue with TransformGraph in tf_loader for lower version model

### ISSUE THREAD

**Issue by FerdinandZhong** [onnx/tensorflow-onnx#1166]
**Describe the bug**
When I tried to transform my tensorflow frozen graph (tf version 1.13.1) through tf_loader, I find an issue with the transforms list. 
As `fold_constant` is a parameter passed in and it can be false (by default is true). If false, `fold_constants` would not be added to transforms, but adding `fold_batch_norms` is a default operation. 
However, from the documentation of tensorflow, `fold_constants` is the Prerequisites of `fold_batch_norms` 
[reference from tensorflow/graph_transform](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md#fold_batch_norms)
And I think perhaps transforms can be a parameter to let user define his/her own transform list.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.
None. I can add my own transform function first.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Tensorflow Version: 1.13.1
- Python version: 3.7.9

**To Reproduce**
Describe steps/code to reproduce the behavior:
Please check `tf_optimze` in `tf_loader.py`

**Expected behavior**
Modify the func to avoid the issue and allow user defined transforms

**Screenshots**
![image](https://user-images.githubusercontent.com/13790266/98318046-b9984480-2018-11eb-9501-b99fc87e4b81.png)

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by guschmue** [comment]
We had an option to disable fold_constants because long time back we sometimes hit problems (if I remember correctly graph_transforms has issues in really old tensorflow versions).
But by now this is under control and we decided to just remove this option all together and have not had issues since.
Maybe best to remove the fold_constants altogether since we don't set it anywhere to false.

**Comment by FerdinandZhong** [comment]
Thanks for your reply.
I agree, it's good to just remove fold_constants to avoid it to be set as false
