### ISSUE TITLE
Too many transpose operations in inception graph

### ISSUE THREAD

**Issue by lburzawa** [onnx/tensorflow-onnx#117]
I looked at the inception v3 onnx graph after using the converter and it does not make sense to me that the model still tries to preserve Tensorflow's NHWC order which causes every other layer to be a transpose. Are there any plans to have it just use ONNX's NCHW order and remove all tranposes? If not, is there any easy way to edit the source code to have it work with NCHW?

**Comment by prasanthpul** [comment]
@pengwa has some optimizations coming that address this issue

**Comment by guschmue** [comment]
add ```--optimize_transpose```

**Comment by lburzawa** [comment]
Looks perfect now, thanks! Quick questions, are the batchnorms fused into convolutions?

**Comment by guschmue** [comment]
not yet. We are going to look at it.

**Comment by lburzawa** [comment]
I think the nodes obtained with "optimize_transpose" are not topologically sorted. Onnx checker gives this error on tf-slim inception v3:

onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'Conv__220:0' of node: 
input: "Conv__220:0" output: "InceptionV3/InceptionV3/Conv2d_1a_3x3/Relu:0" name: "InceptionV3/InceptionV3/Conv2d_1a_3x3/Relu" op_type: "Relu"
 is not output of any previous nodes.

**Comment by guschmue** [comment]
@pengwa ... want to take a look?

**Comment by pengwa** [comment]
@guschmue yeah, will check it.
