### ISSUE TITLE
There is no support for some TF operations

### ISSUE THREAD

**Issue by achernigin1987** [onnx/tensorflow-onnx#12]
There are no support for Tile, leakyRelu and ResizeNearestNeighbor operations, that are used in our convolutional NN. Please, add support

**Comment by guschmue** [comment]
I think we can add support for Tile and leakyRelu. 
ResizeNearestNeighbor is currently not in onnx.

**Comment by guschmue** [comment]
ResizeNearestNeighbor  should be supported with https://github.com/onnx/tensorflow-onnx/pull/20
