### ISSUE TITLE
Output ONNX file is incorrect because shape is passed as an input to RandomUniform

### ISSUE THREAD

**Issue by qeexowill** [onnx/tensorflow-onnx#1214]
**Describe the bug**

I am testing using the publicly available model: [cifar10_cnn.pb](https://github.com/uTensor/simple_cnn_tutorial/blob/master/cifar10_cnn.pb):

```
python -m tf2onnx.convert --input cifar10_cnn.pb --output cifar10_cnn.onnx --outputs fully_connect_2/logits:0 --inputs Placeholder:0
```

Model conversion finishes without error, but the output onnx file is unusable. Loading with onnxruntime, I get:

```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from cifar10_cnn.onnx failed:This is an invalid model. Error in Node:dropout/random_uniform/RandomUniform : Node (dropout/random_uniform/RandomUniform) has input size 1 not in range [min=0, max=0].
```

The problem seems to be that the shape is passed as input to `RandomUniform`, while ONNX expects it to be an attribute (or else RandomUniformLike needs to be used).

It seems like you already have some code for handling this case:
https://github.com/onnx/tensorflow-onnx/blob/19d3f9726e573994427c96659dd1e901637e04ff/tf2onnx/rewriter/random_uniform.py#L89
but for some reason it's not being triggered in this case.

I can look into this further, but was wondering if you had any thoughts about this.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac Catalina
- Tensorflow Version: 2.3.1 (for conversion environment, not sure what was used for produce the trained model file)
- Python version: 3.7.6
- tf2onnx version 1.7.2

**Comment by TomWildenhain-Microsoft** [comment]
Hi, thanks for the issue report and the thorough investigation.  Try again with the `--opset 9` flag.  The default opset is 8, which doesn't support RandomUniform with non-constant shape.  I've opened a PR to improve this messaging.  #1215

**Comment by qeexowill** [comment]
Thanks! That seems to fix it.
