### ISSUE TITLE
Convert tensorflow 2 custom model to onxx create issue. (wrong prediction)

### ISSUE THREAD

**Issue by RD191295** [onnx/tensorflow-onnx#1252]
**Describe the bug**
I convert tensorflow model to onxx using tf2onnx .but after converting model it giving wrong prediction . i used ssd mobile net model. it's custom train model and while testing it giving wrong output every time.

**Urgency**
It is in Development. if i get support quickly,it appreciate lot

**System information**

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubantu
ONNX  installed from (source or binary): binary
Python version: 3.7
Visual Studio version (if applicable): no
GCC/Compiler version (if compiling from source): no
GPU model and memory: NVIDIA Jetson board

**To Reproduce**

while transfering custom train ssd mobile net model to onnx it give such error. I tried with ssd resnet-50 also
Please check model at this location : [model link](https://drive.google.com/drive/folders/13sc6FAF941KTKHT5A__YgBB6ZDEex0he?usp=sharing.
)

**Expected behavior**
Giving wrong result on test image . every time it give number of detection same as 100 on any image

**Comment by TomWildenhain-Microsoft** [comment]
I have a few issues to get to but I'll try to do this one soon.  I see that the Google Drive you linked to has a saved_model.pb but no variables folder.  Are you sure this is the entire model?

**Comment by TomWildenhain-Microsoft** [comment]
Your Colab suggests you have a frozen inference graph.  Would you be able to share it?

**Comment by RD191295** [comment]
No i did not make frozen inference graph for this model.  about variables forlder i wil upload that again seems like some issue for access.

**Comment by RD191295** [comment]
I just upload 3 model . Two model is Tensorflow 2 model and one is from tensorflow 1 model.  One which is tensorflow 1 is working fine and no issue. but tensorflow 2 model give wrong prediction. 

Folder name is : 
1.  Tensorflow_1 model --- Pre train model ---- working fine
2.  Tensorflow2_SSD_MobileNet --- custom model --- issue
3. Tensorflow2_SSD_Resnet ----   issue 

i tried tensorflow 2 model with pre trained model. it has same issue.

**Comment by TomWildenhain-Microsoft** [comment]
Hi @RD191295 , I tried running Tensorflow2_SSD_MobileNet locally and I'm getting matching results for the .pb and .onnx files you uploaded.  What version of ORT are you using?  Also can you upload a test image?  Is possible you are using the output names in the wrong order?

**Comment by RD191295** [comment]
I am getting output name with some identify_o and so one...  Where tensorflow model has name like detection_box and so on... So I take order from same way and use this... Will you tell me you also get same one...

**Comment by RD191295** [comment]
Can you check Tensorflow2_SSD_Resnet also... Will this also give same results?

**Comment by TomWildenhain-Microsoft** [comment]
Yes I also get nodes named Identity_1, etc.  I used the same order as the TF model and got the same results.  I can try Tensorflow2_SSD_Resnet on Monday.

**Comment by RD191295** [comment]
I checked my python script and done some change with that and now i am able to get same result. Thank you so much helping for me to sort it out this issue. Happy New year!! Have a nice year ahed!!

**Comment by TomWildenhain-Microsoft** [comment]
Excellent!  Happy New year!

**Comment by satpalsr** [comment]
Hey @RD191295 , I am facing a similar issue. The onnx model that I created using tf2onnx gives wrong predictions. My TensorFlow model is built on top of resnet-50 and works well. Can you tell me how you resolved the issue?

CC: @TomWildenhain-Microsoft

**Comment by RD191295** [comment]
@satpalsr can you provide access to your notebook if possible so i can help you better.

**Comment by satpalsr** [comment]
Hey @RD191295. Thanks for getting back, there was some mistake with my inference script and not the onnx model. It's working great.
