### ISSUE TITLE
Support for ragged range operator

### ISSUE THREAD

**Issue by buddhapuneeth** [onnx/tensorflow-onnx#1254]
**Describe the bug**
I am not able to convert TF model with ragged.range operator.

**Urgency**
We are experimenting few approaches for our usecase. One of the way is using ragged range operator. This approach is working fine in TF. We would like to see can it be support with minimal changes on tf2onnx

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS Catalina 10.15.7
- Tensorflow Version: 2.0
- Python version: 3.6

**To Reproduce**
sample code used:
```
import tensorflow as tf
import numpy as np
ip = np.array([3,5,2])
x = tf.placeholder(tf.float32, ip.shape, name="input")
d = tf.ragged.range(x, name="output",row_splits_dtype=tf.dtypes.int32)
sess = tf.Session()
feed_dict = {"input:0": ip}
output = sess.run(sess.graph.get_tensor_by_name("output:0"), feed_dict=feed_dict);
print(output)
sess.close()
```

[rr_test2.txt](https://github.com/onnx/tensorflow-onnx/files/5757932/rr_test2.txt)

**You can convert the type to .pb from .txt** (I modified to upload here)

**Command**
`python -m tf2onnx.convert --input rr_test2.pb --inputs input:0 --output rr_test2.onnx --outputs output:0  --opset 11 --fold_const`

**Error**
```
Value "<dtype: 'int32'>" is not valid attribute data type.
2020-12-31 09:23:49,363 - ERROR - pass1 convert failed for name: "output"
op: "RaggedRange"
input: "output/Cast"
input: "input"
input: "output/Cast_1"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "Tsplits"
  value {
    type: DT_INT32
  }
}
, ex=Not a cmessage
```

**Expected behavior**
Able to convert to ONNX

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by TomWildenhain-Microsoft** [comment]
Sure, I can look into adding this.  Does the model have other ragged ops, or is this the only one?  Also, is the ragged range you are using "mostly dense" (do most of the ranges have the same number of elements?)  This might inform how I implement the conversion.

**Comment by TomWildenhain-Microsoft** [comment]
Also is opset 12 support sufficient, or do you need support for a lower opset?

**Comment by buddhapuneeth** [comment]
@TomWildenhain-Microsoft Thanks for quick response!
- we have only one ragged op in our model
- we can't assume it as dense, it will be variable. But variable with in a small range. For example between 2 to 4 like 2,4,3,2,4.
- Opset 12 is fine
- the output of ragged op (i.e. ragged tensor) is used as input to gather_nd operator (pass as indicies). In our case, I believe this might be fine during conversion. Please correct me if I am wrong.

**Comment by TomWildenhain-Microsoft** [comment]
Great, that all sounds good.  If the length of the ranges is upper-bounded by 4, then an implementation that is inefficient in that dimension should be fine.  I'll give it a shot.

**Comment by TomWildenhain-Microsoft** [comment]
I made a PR for this.  You will need to install from GitHub to use it before we make a release.

`pip uninstall tf2onnx`
`pip install git+https://github.com/onnx/tensorflow-onnx`

Or before the branch merges into master:
`pip install git+https://github.com/onnx/tensorflow-onnx/pull/1256`

**Comment by buddhapuneeth** [comment]
@TomWildenhain-Microsoft Awesome! I verified with your changes and my sanity checks are passed. Thanks a lot!
