### ISSUE TITLE
Input Output Tensor names needed after tf to onnx conversion

### ISSUE THREAD

**Issue by matinehshaker** [onnx/tensorflow-onnx#1257]
I am writing a piece of software that receives an ONNX model from a model provider. The final goal is that this model is converted to Tensorflow and that's how it will be used in run-time. There’s existing TF infra and the rest of the deep learning models are in TF.

In the backend, the imported ONNX model is transformed and exported as TF graph pb file, using onnx_tf tool. Then we use import_graph_def() to load the model to GraphDef. This way we will be able to get the default graph while model is loaded into it. 

However, my current issue is that from the tensorflow GraphDef object, it is not clear what are the input and output nodes of the graph. I see solutions like this:

input_tensor = graph.get_tensor_by_name(INPUT_TENSOR_NAME)
output_tensor = graph.get_tensor_by_name(OUTPUT_TENSOR_NAME)

However, all I have at the time of loading tf pf file to GraphDef is the pb file, and not the tensor names. I wonder how could this problem be solved. Do I HAVE TO ask model providers to tag their input and output nodes at the time of converting their TF or PyTorch models to ONNX? Or there's a way that we could retrieve the information from ONNX graph? Ideally we don't want to limit users in how they write their original deep learning model (before onnx conversion), in terms of saved format, version, etc.

**System information**
- Tensorflow Version: 1.15
- Python version: 3.6
- onnx==1.7.0

**Comment by TomWildenhain-Microsoft** [comment]
This is the tf2onnx repo for converting from tensorflow to onnx.  It seems like this issue should go to the onnx-tensorflow repo: https://github.com/onnx/onnx-tensorflow
