### ISSUE TITLE
Not able to run the tutorials converting efficientdet from TF to ONNX 

### ISSUE THREAD

**Issue by anhlt18vn** [onnx/tensorflow-onnx#1258]
**Describe the bug**
I got this error at the final step of the example:
[https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/efficientdet.ipynb](https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/efficientdet.ipynb)

Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Concat node. Name:'detections_Concat__1830' Status Message: Not satisfied: dim_value == inputs_0_dims[axis_index]
concat.cc:79 PrepareForComputeNon concat axis dimensions must match: Axis 1 has mismatched dimensions of 11 and 100

**System information**
- Linux Ubuntu 16.04
- TF : 2.3.1 
- python: 3.6

**Comment by guschmue** [comment]
I think I made a fix for this but we have not done a release since. We'll do so this week.
In the meantime you could do
```
pip install git+https://github.com/onnx/tensorflow-onnx
```
