### ISSUE TITLE
ValueError: Node 'output:0': Node name contains invalid characters

### ISSUE THREAD

**Issue by matinehshaker** [onnx/tensorflow-onnx#1274]
I use the code in `examples/call_converter_via_python.py` to create a simple onnx file from tf:

`import tensorflow as tf
import tf2onnx

with tf.Session() as sess:
    x = tf.placeholder(tf.float32, [2, 3], name="input")
    x_ = tf.add(x, x)
    _ = tf.identity(x_, name="output")
    onnx_graph = tf2onnx.tfonnx.process_tf_graph(sess.graph, input_names=["input:0"], output_names=["output:0"])
    model_proto = onnx_graph.make_model("test")
    with open("/tmp/model.onnx", "wb") as f:
        f.write(model_proto.SerializeToString())`

I convert model.onnx back to to tensorflow PB and load it to tensorflow GraphDef using this code:

with tf.gfile.FastGFile(TF_PB_PATH, 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())

with tf.Graph().as_default() as graph:
	tf.import_graph_def(graph_def, name="name")

However I see this error:

  File "/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 505, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Node 'output:0': Node name contains invalid characters

**System information**
- Tensorflow Version: 1.15.2
- Python version: 3.6.9
- tf2onnx: 1.7.1

**Comment by TomWildenhain-Microsoft** [comment]
Have you tried running the onnx graph in ONNXRuntime?  It is possible the tf->onnx conversion is fine but the onnx->tf conversion introduces an error.

**Comment by guschmue** [comment]
assume this is resolved.
