### ISSUE TITLE
tensorflow2.0 saved model convert onnx

### ISSUE THREAD

**Issue by jianqianzhou** [onnx/tensorflow-onnx#1278]
**System information**
CPU Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz centos
- Tensorflow Version: 2.2.0
- Python version: 3.6
- transformers：3.0.2
- onnx     1.7.0
- tf2onnx                    1.6.3

```
from transformers import BertTokenizer, TFBertForSequenceClassification
import tensorflow as tf

tokenizer = BertTokenizer.from_pretrained('./bert-base-cased')
model = TFBertForSequenceClassification.from_pretrained('./bert-base-cased')

inputs = tokenizer("Hello, my dog is cute", return_tensors="tf")

inputs["labels"] = tf.reshape(tf.constant(1), (-1, 1)) # Batch size 1
logits = model(inputs)
logit = tf.identity(logits[0], name="output")
model.save('path_to_saved_model', save_format='tf')
```

then I used
 python -m tf2onnx.convert         --saved-model ./path_to_saved_model --output ./output/bert.onnx         --opset 11  
I want to saved model to onnx,but report an error：
attr {
  key: "_read_only_resource_inputs"
  value {
    list {
      i: 1
      i: 2
      i: 3
      i: 4
      i: 5
      i: 6
      i: 7
      i: 8
      i: 9
      i: 10
      i: 11
      i: 12
      i: 13
      i: 14
      i: 15
      i: 16
      i: 17
      i: 18
      i: 19
      i: 20
      i: 21
      i: 22
      i: 23
      i: 24
      i: 25
      i: 26
      i: 27
      i: 28
      i: 29
      i: 30
      i: 31
      i: 32
      i: 33
      i: 34
      i: 35
      i: 36
      i: 37
      i: 38
      i: 39
      i: 40
      i: 41
      i: 42
      i: 43
      i: 44
      i: 45
      i: 46
      i: 47
      i: 48
      i: 49
      i: 50
      i: 51
      i: 52
      i: 53
      i: 54
      i: 55
      i: 56
      i: 57
      i: 58
      i: 59
      i: 60
      i: 61
      i: 62
      i: 63
      i: 64
      i: 65
      i: 66
      i: 67
      i: 68
      i: 69
      i: 70
      i: 71
      i: 72
      i: 73
      i: 74
      i: 75
      i: 76
      i: 77
      i: 78
      i: 79
      i: 80
      i: 81
      i: 82
      i: 83
      i: 84
      i: 85
      i: 86
      i: 87
      i: 88
      i: 89
      i: 90
      i: 91
      i: 92
      i: 93
      i: 94
      i: 95
      i: 96
      i: 97
      i: 98
      i: 99
      i: 100
      i: 101
      i: 102
      i: 103
      i: 104
      i: 105
      i: 106
      i: 107
      i: 108
      i: 109
      i: 110
      i: 111
      i: 112
      i: 113
      i: 114
      i: 115
      i: 116
      i: 117
      i: 118
      i: 119
      i: 120
      i: 121
      i: 122
      i: 123
      i: 124
      i: 125
      i: 126
      i: 127
      i: 128
      i: 129
      i: 130
      i: 131
      i: 132
      i: 133
      i: 134
      i: 135
      i: 136
      i: 137
      i: 138
      i: 139
      i: 140
      i: 141
      i: 142
      i: 143
      i: 144
      i: 145
      i: 146
      i: 147
      i: 148
      i: 149
      i: 150
      i: 151
      i: 152
      i: 153
      i: 154
      i: 155
      i: 156
      i: 157
      i: 158
      i: 159
      i: 160
      i: 161
      i: 162
      i: 163
      i: 164
      i: 165
      i: 166
      i: 167
      i: 168
      i: 169
      i: 170
      i: 171
      i: 172
      i: 173
      i: 174
      i: 175
      i: 176
      i: 177
      i: 178
      i: 179
      i: 180
      i: 181
      i: 182
      i: 183
      i: 184
      i: 185
      i: 186
      i: 187
      i: 188
      i: 189
      i: 190
      i: 191
      i: 192
      i: 193
      i: 194
      i: 195
      i: 196
      i: 197
      i: 198
      i: 199
      i: 200
      i: 201
    }
  }
}
attr {
  key: "config"
  value {
    s: ""
  }
}
attr {
  key: "config_proto"
  value {
    s: "\n\007\n\003GPU\020\000\n\007\n\003CPU\020\0012\002J\0008\001"
  }
}
attr {
  key: "executor_type"
  value {
    s: ""
  }
}
attr {
  key: "f"
  value {
    func {
      name: "__inference__wrapped_model_21380"
    }
  }
}
, ex=value "name: "__inference__wrapped_model_21380"
" is not valid attribute data type.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/work/tensor1.12/tf2.0/lib/python3.6/site-packages/tf2onnx/convert.py", line 171, in <module>
    main()
  File "/work/tensor1.12/tf2.0/lib/python3.6/site-packages/tf2onnx/convert.py", line 155, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/work/tensor1.12/tf2.0/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 379, in process_tf_graph
    onnx_nodes, op_cnt, attr_cnt, output_shapes, dtypes, _ = tensorflow_to_onnx(tf_graph, shape_override)
  File "/work/tensor1.12/tf2.0/lib/python3.6/site-packages/tf2onnx/tf_utils.py", line 229, in tensorflow_to_onnx
    return tflist_to_onnx(graph, shape_override)
  File "/work/tensor1.12/tf2.0/lib/python3.6/site-packages/tf2onnx/tf_utils.py", line 216, in tflist_to_onnx
    onnx_node = helper.make_node(node.type, input_names, output_names, name=node.name, **attr)
  File "/work/tensor1.12/tf2.0/lib/python3.6/site-packages/onnx/helper.py", line 56, in make_node
    for key, value in sorted(kwargs.items()))
  File "/work/tensor1.12/tf2.0/lib/python3.6/site-packages/onnx/helper.py", line 56, in <genexpr>
    for key, value in sorted(kwargs.items()))
  File "/work/tensor1.12/tf2.0/lib/python3.6/site-packages/onnx/helper.py", line 272, in make_attribute
    'value "{}" is not valid attribute data type.'.format(value))
TypeError: value "name: "__inference__wrapped_model_21380"
" is not valid attribute data type.

**Comment by guschmue** [comment]
We fixed this - do a ```pip install tf2onnx -U``` to get the latest version.

**Comment by guschmue** [comment]
I just tested this:
```
python -m tf2onnx.convert --saved-model /tmp/bert --output /tmp/bert.onnx --opset 13
```
works fine with tf2onnx-1.8.1
