### ISSUE TITLE
Convert ssd_resnet50_v1 to onnx

### ISSUE THREAD

**Issue by romeolandry** [onnx/tensorflow-onnx#1290]
**Describe the bug**
I get a multiple error  when I try to convert  [ssd_resnet50_v1_fpn_640x640_coco17_tpu8`](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_resnet50_v1_fpn_640x640_coco17_tpu-8.tar.gz)  to onnx

**Urgency**
The project is for my master degree an I really need it to for Inference with DeepStream SDK.
 

**System information**
- OS Platform and Distribution: Linux Ubuntu 20.04
- Tensorflow Version: 2.5
- Python version: 3.8
- tf2onnx:1.8.0
- onnx:1.6.0
- onnxruntine: 1.6.0

**To Reproduce**
I run the following command to convert ssd_mobilnet_V2 to onnx:
`(tfTrainOdIs) kamgo@stream:~/Dokumente/Projects/Train_tensorflow_OD_API/workspace/TF_Train_OD_IS/scripts/Evaluation$ python -m tf2onnx.convert --opset 10 --fold_const --saved-model /home/kamgo/Dokumente/Projects/Trainings_model/ssd_resnet50V1_coco17_640x640/train_2/my_ssd_resnet50_v1_fpn_640x640_coco17_tpu-8_saved/saved_model  --output /home/kamgo/Dokumente/Projects/Trainings_model/ssd_resnet50V1_coco17_640x640/train_2/my_ssd_resnet50_v1_fpn_640x640_coco17_tpu-8_saved/saved_model/ssd.onnx `

**Expected behavior**
I won an converted onnx file from the model.

**Screenshots**
![warning](https://user-images.githubusercontent.com/26627344/105473363-54f69880-5c9d-11eb-95f8-027a4893b583.png)
![error1](https://user-images.githubusercontent.com/26627344/105473127-08ab5880-5c9d-11eb-8f71-5c12c1bdb9c9.png)
![Error2](https://user-images.githubusercontent.com/26627344/105473291-3e504180-5c9d-11eb-9e45-eda99ed2a516.png)

**Comment by TomWildenhain-Microsoft** [comment]
Are you able to use opset 11?  The problem here is that opset 10 of ONNX does not support non-constant paddings.  If not, I might be able to work around this using ConstantOfShape and Concat ops.

**Comment by romeolandry** [comment]
Thanks for your Answer!
Which opset will be good for that model? I just begin to work whit onnx and don't have a lot of knowledge about.

**Comment by TomWildenhain-Microsoft** [comment]
The only reason to use a lower opset would be if you are shipping to a device that doesn't support the latest opset.  The newest opset is 13, so use that if possible.

**Comment by TomWildenhain-Microsoft** [comment]
Actually I'm not sure which opsets deepstream supports so you might have to experiment

**Comment by romeolandry** [comment]
a lot of thank for your answer!
I have tried to convert with a lower opset it didn't work. But its work from opset 11. 
The the convertor work and save onnx output, but i have a lot of  warning and Error. I won to know if this error will be  a problem during the inference with the both model (SSD and Mask-rcnn). are there any solution ?
the link to [ssd](https://drive.google.com/file/d/16e1SbdTrO4ZBRQ8HMCgApsO1BuIyACu1/view?usp=sharing) and [mask](https://drive.google.com/file/d/1UFhwCVnKXY4n2qjUyd3B1Z8cr8Du1kL5/view?usp=sharing).

Thank your for your time.

**Comment by TomWildenhain-Microsoft** [comment]
Yes, opset 11 is required for dynamic padding.  Try running the model in onnx runtime and see if it produces the same results.  If so, it should be fine.

`pip install onnxruntime`

`import onnxruntime as ort`
`sess = ort.InferenceSession('path to model')`
`results = sess.run(None, {'input_1': np.array(value1), 'input_2': np.array(value2)})`

**Comment by romeolandry** [comment]
Hey! 
Thanks for the script.
![cmg_inputsize](https://user-images.githubusercontent.com/26627344/106002937-f91f7b80-60b1-11eb-81b3-9f2ebc3820b4.png)
![notebook_ort](https://user-images.githubusercontent.com/26627344/106002955-ff155c80-60b1-11eb-8eca-88e63506b915.png)

As you can see I give the right input name but its seem to invalid.

How can know which name my input have?

**Comment by romeolandry** [comment]
Thanks so much I found the correct input name using `netron` to  visualize the model.
its work find!
