### ISSUE TITLE
Quantization Support

### ISSUE THREAD

**Issue by msquigle** [onnx/tensorflow-onnx#1295]
**Describe the bug**
When attempting to convert quantized SavedModels, the following error occurs
site-packages\tensorflow\python\saved_model\function_deserialization.py", line 261, in recreate_function
    concrete_function_objects.append(concrete_functions[concrete_function_name])
KeyError: '__inference_expanded_conv_depthwise_layer_call_fn_33826'
This is using just a common quantized MobileNet.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Tensorflow Version: 2.3.2
- Python version: 3.8.1

**To Reproduce**
graph_def, inputs, outputs = tf2onnx.tf_loader.from_saved_model(module, input_names, output_names)
with tf.Graph().as_default() as tf_graph:
        tf.import_graph_def(graph_def, name='')
    with tf2onnx.tf_loader.tf_session(graph=tf_graph):
        g = tf2onnx.tfonnx.process_tf_graph(tf_graph, input_names=inputs, output_names=outputs)
    onnx_graph = tf2onnx.optimizer.optimize_graph(g)
    model_proto = onnx_graph.make_model("Converted from %s" % infile)
    with open(outfile, "wb") as f:
        f.write(model_proto.SerializeToString())

**Expected behavior**
Conversion of quantized TF Models to ONNX.

**Additional context**
The main goal is to be able to convert quantized models to ONNX, there are a few things that appear to be unsupported with either Keras H5 and TFLite Models and then also there hasn't been any mention of quantization support for SavedModels.

**Comment by guschmue** [comment]
this looks like tf is throwing an error when we ask for a concrete function for the model.
Can you share a link to the model ?

**Comment by msquigle** [comment]
[imagenet_mobilenet_v1_100_128_quantops_classification_3.zip](https://github.com/onnx/tensorflow-onnx/files/5882450/imagenet_mobilenet_v1_100_128_quantops_classification_3.zip)

**Comment by TomWildenhain-Microsoft** [comment]
Were you able to convert the model with the new PR?
