### ISSUE TITLE
Unable to convert TensorFlow Model Zoo MobileNet

### ISSUE THREAD

**Issue by msquigle** [onnx/tensorflow-onnx#1298]
**Describe the bug**
When attempting to convert the Mobilenet V2 1.0 224 from the [TensorFlow Slim Model Zoo](https://github.com/tensorflow/models/tree/master/research/slim), using the following command

python -m tf2onnx.convert --graphdef mobilenet_v2_1.0_224_frozen.pb --output test_mobilenet.onnx --inputs input:0 --outputs MobilenetV2/Predictions/Reshape_1:0

the following error is received.

ValueError: Shape must be rank 4 but is rank 0 for '{{node MobilenetV2/Conv/Conv2D}} = Conv2D[T=DT_FLOAT, _output_shapes=[[?,?,?,32]], data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true](input, Const_90)' with input shapes: [], [3,3,3,32].

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Tensorflow Version: 2.3.2
- Python version: 3.8

**To Reproduce**
Describe steps/code to reproduce the behavior:
Download the tar file for Mobilenet V2 1.0 224
Untar the file and run the following command on the .pb file
python -m tf2onnx.convert --graphdef mobilenet_v2_1.0_224_frozen.pb --output test_mobilenet.onnx --inputs input:0 --outputs MobilenetV2/Predictions/Reshape_1:0

**Expected behavior**
The model should be converted without issue as is stated by support for all TF 1.x Models.

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by TomWildenhain-Microsoft** [comment]
Hi @msquigle, the problem here is that the placeholder doesn't have a shape specified, so we incorrectly assume the input is a scalar.  To correct this, append the input shape in the --input flag, like `--inputs input:0[1,2,3,4]`  I'm adding a PR to improve the messaging and allow for unknown dimensions in the flag.  Once it merges, you can convert with `--inputs input:0[-1,-1,-1,-1]`, since in this case since only the rank is needed here. #1300

**Comment by msquigle** [comment]
Ok great! Yea having some documentation to let that be more obvious then would help, even an example in the -h when running convert.
