### ISSUE TITLE
Install Modifies TFLite

### ISSUE THREAD

**Issue by msquigle** [onnx/tensorflow-onnx#1303]
**Describe the bug**
When tf2onnx is installed using pip, if tflite is installed, every schema file for tflite is modified and sometimes there are even files added.

**Urgency**
Affects other packages that should be unrelated to tf2onnx as tflite 2 onnx is not supported.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Tensorflow Version: None
- Python version: 3.8

**To Reproduce**
Create a new virtual environment
$ virtualenv -p 3.8 test_tf2onnx
$ pip install --no-dependencies tflite
$ pip install --no-dependencies tf2onnx

If you create a git repo or have another way of tracking file changes before the tf2onnx install and after the install you will see something similar to the following:
        modified:   site-packages/tflite/AbsOptions.py
        modified:   site-packages/tflite/AddNOptions.py
        modified:   site-packages/tflite/AddOptions.py
        modified:   site-packages/tflite/ArgMaxOptions.py
        modified:   site-packages/tflite/ArgMinOptions.py
        modified:   site-packages/tflite/BatchMatMulOptions.py
        modified:   site-packages/tflite/BatchToSpaceNDOptions.py
        modified:   site-packages/tflite/BidirectionalSequenceLSTMOptions.py
        modified:   site-packages/tflite/BidirectionalSequenceRNNOptions.py
        new file:   site-packages/tflite/BroadcastToOptions.py
        modified:   site-packages/tflite/Buffer.py
        modified:   site-packages/tflite/BuiltinOperator.py
        modified:   site-packages/tflite/BuiltinOptions.py
        new file:   site-packages/tflite/CallOnceOptions.py
        modified:   site-packages/tflite/CallOptions.py
        modified:   site-packages/tflite/CastOptions.py
        modified:   site-packages/tflite/ConcatEmbeddingsOptions.py
        modified:   site-packages/tflite/ConcatenationOptions.py
        modified:   site-packages/tflite/Conv2DOptions.py
        modified:   site-packages/tflite/CosOptions.py
        new file:   site-packages/tflite/CumsumOptions.py
        modified:   site-packages/tflite/CustomQuantization.py
        modified:   site-packages/tflite/DensifyOptions.py
        modified:   site-packages/tflite/DepthToSpaceOptions.py
        modified:   site-packages/tflite/DepthwiseConv2DOptions.py
        modified:   site-packages/tflite/DequantizeOptions.py
        modified:   site-packages/tflite/DimensionMetadata.py
        modified:   site-packages/tflite/DivOptions.py
        modified:   site-packages/tflite/EmbeddingLookupSparseOptions.py
        modified:   site-packages/tflite/EqualOptions.py
        modified:   site-packages/tflite/ExpOptions.py
        modified:   site-packages/tflite/ExpandDimsOptions.py
        modified:   site-packages/tflite/FakeQuantOptions.py
        modified:   site-packages/tflite/FillOptions.py
        modified:   site-packages/tflite/FloorDivOptions.py
        modified:   site-packages/tflite/FloorModOptions.py
        modified:   site-packages/tflite/FullyConnectedOptions.py
        modified:   site-packages/tflite/GatherNdOptions.py
        modified:   site-packages/tflite/GatherOptions.py
        modified:   site-packages/tflite/GreaterEqualOptions.py
        modified:   site-packages/tflite/GreaterOptions.py
        modified:   site-packages/tflite/HardSwishOptions.py
        modified:   site-packages/tflite/IfOptions.py
        modified:   site-packages/tflite/Int32Vector.py
        modified:   site-packages/tflite/L2NormOptions.py
        modified:   site-packages/tflite/LSHProjectionOptions.py
        modified:   site-packages/tflite/LSTMOptions.py
        modified:   site-packages/tflite/LeakyReluOptions.py
        modified:   site-packages/tflite/LessEqualOptions.py
        modified:   site-packages/tflite/LessOptions.py
        modified:   site-packages/tflite/LocalResponseNormalizationOptions.py
        modified:   site-packages/tflite/LogSoftmaxOptions.py
        modified:   site-packages/tflite/LogicalAndOptions.py
        modified:   site-packages/tflite/LogicalNotOptions.py
        modified:   site-packages/tflite/LogicalOrOptions.py
        modified:   site-packages/tflite/MatrixDiagOptions.py
        modified:   site-packages/tflite/MatrixSetDiagOptions.py
        modified:   site-packages/tflite/MaximumMinimumOptions.py
        modified:   site-packages/tflite/Metadata.py
        modified:   site-packages/tflite/MirrorPadOptions.py
        modified:   site-packages/tflite/Model.py
        modified:   site-packages/tflite/MulOptions.py
        modified:   site-packages/tflite/NegOptions.py
        modified:   site-packages/tflite/NonMaxSuppressionV4Options.py
        modified:   site-packages/tflite/NonMaxSuppressionV5Options.py
        modified:   site-packages/tflite/NotEqualOptions.py
        modified:   site-packages/tflite/OneHotOptions.py
        modified:   site-packages/tflite/Operator.py
        modified:   site-packages/tflite/OperatorCode.py
        modified:   site-packages/tflite/PackOptions.py
        modified:   site-packages/tflite/PadOptions.py
        modified:   site-packages/tflite/PadV2Options.py
        modified:   site-packages/tflite/Pool2DOptions.py
        modified:   site-packages/tflite/PowOptions.py
        modified:   site-packages/tflite/QuantizationParameters.py
        modified:   site-packages/tflite/QuantizeOptions.py
        modified:   site-packages/tflite/RNNOptions.py
        modified:   site-packages/tflite/RangeOptions.py
        modified:   site-packages/tflite/RankOptions.py
        modified:   site-packages/tflite/ReducerOptions.py
        modified:   site-packages/tflite/ReshapeOptions.py
        modified:   site-packages/tflite/ResizeBilinearOptions.py
        modified:   site-packages/tflite/ResizeNearestNeighborOptions.py
        modified:   site-packages/tflite/ReverseSequenceOptions.py
        modified:   site-packages/tflite/ReverseV2Options.py
        new file:   site-packages/tflite/Rfft2dOptions.py
        modified:   site-packages/tflite/SVDFOptions.py
        modified:   site-packages/tflite/ScatterNdOptions.py
        modified:   site-packages/tflite/SegmentSumOptions.py
        modified:   site-packages/tflite/SelectOptions.py
        modified:   site-packages/tflite/SelectV2Options.py
        modified:   site-packages/tflite/SequenceRNNOptions.py
        modified:   site-packages/tflite/ShapeOptions.py
        new file:   site-packages/tflite/SignatureDef.py
        modified:   site-packages/tflite/SkipGramOptions.py
        modified:   site-packages/tflite/SliceOptions.py
        modified:   site-packages/tflite/SoftmaxOptions.py
        modified:   site-packages/tflite/SpaceToBatchNDOptions.py
        modified:   site-packages/tflite/SpaceToDepthOptions.py
        modified:   site-packages/tflite/SparseToDenseOptions.py
        modified:   site-packages/tflite/SparsityParameters.py
        modified:   site-packages/tflite/SplitOptions.py
        modified:   site-packages/tflite/SplitVOptions.py
        modified:   site-packages/tflite/SquareOptions.py
        modified:   site-packages/tflite/SquaredDifferenceOptions.py
        modified:   site-packages/tflite/SqueezeOptions.py
        modified:   site-packages/tflite/StridedSliceOptions.py
        modified:   site-packages/tflite/SubGraph.py
        modified:   site-packages/tflite/SubOptions.py
        modified:   site-packages/tflite/Tensor.py
        new file:   site-packages/tflite/TensorMap.py
        modified:   site-packages/tflite/TensorType.py
        modified:   site-packages/tflite/TileOptions.py
        modified:   site-packages/tflite/TopKV2Options.py
        modified:   site-packages/tflite/TransposeConvOptions.py
        modified:   site-packages/tflite/TransposeOptions.py
        modified:   site-packages/tflite/Uint16Vector.py
        modified:   site-packages/tflite/Uint8Vector.py
        modified:   site-packages/tflite/UnidirectionalSequenceLSTMOptions.py
        modified:   site-packages/tflite/UniqueOptions.py
        modified:   site-packages/tflite/UnpackOptions.py
        modified:   site-packages/tflite/WhereOptions.py
        modified:   site-packages/tflite/WhileOptions.py
        modified:   site-packages/tflite/ZerosLikeOptions.py
        modified:   site-packages/tflite/__init__.py

**Expected behavior**
The install should not be modifying other site-packages as it leads to issues where TFLite models are no longer able to be read properly.

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by guschmue** [comment]
Yes, can confirm - this is bad. There was a short time where we had this and moved it in master but we have not released master yet. Going to release it today.

**Comment by msquigle** [comment]
Ok great! I will retry this then tomorrow! Thanks

**Comment by guschmue** [comment]
thanks for catching this !!!

**Comment by guschmue** [comment]
We released [1.8.2](https://github.com/onnx/tensorflow-onnx/releases/tag/v1.8.2) that has the fix.
```pip install -U tf2onnx``` should install it and the PR for the fix is here: https://github.com/onnx/tensorflow-onnx/pull/1273

**Comment by TomWildenhain-Microsoft** [comment]
Yeah this was my mistake.  @msquigle let us know if the fix works for you.

**Comment by msquigle** [comment]
Can confirm fixed in 1.8.2!
