### ISSUE TITLE
Duplicated output name in onnx model

### ISSUE THREAD

**Issue by jeakon** [onnx/tensorflow-onnx#1324]
- Problem: 
The output op in converted onnx model has two same names (the two at the bottom in the following image): 
<img width="646" alt="onnx_issue" src="https://user-images.githubusercontent.com/3182816/107245310-f8032c80-6a69-11eb-9fba-de80446ca060.png">

- Model: 
I'm using BERT with linear layer. I want to get the output vector in onnx.
- Convert method:
I'm using tf2onnx CLI to convert savedModel to onnx model:
`python -m tf2onnx.convert --opset 11 --saved-model onnx_convert/0207.2 --tag serve --signature_def serving_default --inputs query_id:0,query_mask:0 --outputs dummy_score:0,query_vec:0 --output query_vec.onnx`
- Enviroment:
OS: Ubuntu 18.04.3 LTS
tensorflow=1.14.0
onnx=1.7.0
tf2onnx=1.8.2/05babf 

The savedModel looks fine for visualization:
<img width="520" alt="onnx_issue2" src="https://user-images.githubusercontent.com/3182816/107245892-a27b4f80-6a6a-11eb-9a13-a24bc81d0274.png">

So what's the reason for the duplicated output names? how to deal with the problem? 

Thanks.

**Comment by TomWildenhain-Microsoft** [comment]
Hi @jeakon, yes it looks like something isn't converting correctly here.  The two outputs you have listed are called `dummy_score:0` and `query_vec:0`.  We keep output names the same during conversion, so I'm not sure why the onnx output has two `BiasAdd:0` outputs.  In the saved model, what is the name of the output of the last node (`dnn_ctr/query_emb_output_layer/BiasAdd`)?  Is it `query_vec:0`?  Also what does the other ouptut look like in the saved model?

It would help if you could upload the saved model (and ideally the onnx model you got from conversion).

Thanks,
Tom

**Comment by jeakon** [comment]
Hi @TomWildenhain-Microsoft , in the saved model I try to signature the last node  (dnn_ctr/query_emb_output_layer/BiasAdd) by "query_vec"  but it seems not working. The other output of saved model is "dummy_score:0" for I named it in tensorflow. The correspoending output of onnx is still duplicated. 
I also tried to convert withou specifying --inputs and --outputs, but the resuts remain the same.

**Comment by TomWildenhain-Microsoft** [comment]
Hmm... I think I'll need to see the model to help.  Please upload the model to cloud storage and post a share link here.

**Comment by jeakon** [comment]
@TomWildenhain-Microsoft  I've put the SavedModel and onnx model [here](https://1drv.ms/u/s!AmpocKGEF8oRa-ZTLBiCVnJD4Kk?e=tmfyid). 
Thanks!

**Comment by TomWildenhain-Microsoft** [comment]
Interesting.  The conversion is working fine for me.  Can you try again using the latest tf2onnx from git?

`pip uninstall tf2onnx`
`pip install git+https://github.com/onnx/tensorflow-onnx`

Also if the model is otherwise correct you can manually edit it to remove the extra outputs.  The tool onnx2py may be useful:
https://github.com/microsoft/onnxconverter-common/blob/master/onnxconverter_common/onnx2py.py

**Comment by jeakon** [comment]
Thanks @TomWildenhain-Microsoft  for sharing the tool. I'll take a try later.
It seems if I remove the `--signature_def` option, it will work well. But I still wonder why it matters.
