### ISSUE TITLE
tf.image.non_max_suppression_with_scores results are not consistent

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [onnx/tensorflow-onnx#1341]
**Describe the bug**
I have trained custom yolov3 OD model and using tf.image.non_max_suppression_with_scores in inference. I have tested inference with a couple of images using tensorflow model, accuracy is good.
But when i converted from tensorflow savedmodel format to onnx format, bounding box accuracy is fine, but getting wrong classes.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Tensorflow Version: 2.4
- Python version: 3.8

**To Reproduce**
Describe steps/code to reproduce the behavior: converting custom yolov3 object detection tensorflow savedmodel to onnx model.

**Expected behavior**
A clear and concise description of what you expected to happen. Same results as tensorflow inference.

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by TomWildenhain-Microsoft** [comment]
Hi @VeeranjaneyuluToka, can you upload a copy of the savedmodel you are converting along with your test data/script?

**Comment by VeeranjaneyuluToka** [comment]
Hi, thanks for coming back on this issue!. However i found that there is some issue in my preprocessing step because of which results differs. i have tested with a few samples and results are identical. Am closing this issue as of now and reopen in case if i find any issue wrt this. Thanks Again!
