### ISSUE TITLE
OSError: SavedModel file does not exist

### ISSUE THREAD

**Issue by dalavayi** [onnx/tensorflow-onnx#1348]
Hello, 
I am getting the OSError, when trying to access the saved model. 

commands used: 

tf.saved_model.save(model,'./content') - to save the model 

files inside content folder:
02/17/2021  01:32 PM    <DIR>          assets
02/17/2021  01:32 PM                         saved_model.pb
02/17/2021  01:32 PM    <DIR>          variables

!python -m tf2onnx.convert --saved-model './content' --opset 10 --output model.onnx
error: OSError: SavedModel file does not exist at: './content'/{saved_model.pbtxt|saved_model.pb}.

I have tried by passing the absolute path, still the error persists, please help me resolve this issue.

Thanks.

checked this issue, no proper explanation found : https://github.com/onnx/tensorflow-onnx/issues/1082#issue-688722350

**Comment by TomWildenhain-Microsoft** [comment]
Try without the single quotes.  I'm suspicious that the error has single quotes around the path.

**Comment by dalavayi** [comment]
thank you that resolved the error @TomWildenhain-Microsoft
