### ISSUE TITLE
PRelu is not supported by tf2onnx

### ISSUE THREAD

**Issue by JoeProgram** [onnx/tensorflow-onnx#1364]
Hello!

I'm a NN newbie, so I'll do my best to explain what I'm running into.

I'm trying to convert [MediaPipe's Palm Detection tflite model](https://github.com/google/mediapipe/tree/master/mediapipe/modules/palm_detection) into ONNX so that it may work with  [Unity Barracuda](https://docs.unity3d.com/Packages/com.unity.barracuda@1.0/manual/Exporting.html).

On my mac, when I run the command in terminal:
`python3.8 -m tf2onnx.convert --tflite palm_detection.tflite --output palm_detection.onnx`

I get the error:
`ERROR - Tensorflow op [p_re_lu_1: TFL_PRELU] is not supported`

I see that [ONNX supports PRelu](https://github.com/onnx/onnx/blob/master/docs/Operators.md), but that the [tf2onnx ticket from April 2019 for OPSET 9](https://github.com/onnx/tensorflow-onnx/issues/270) support listed PRelu under the **We don't care?** heading.

Would it be possible to add PRelu support to tf2onnx?  If not, do you have a workaround you could suggest?

Thanks for your time!

Joe

**Comment by TomWildenhain-Microsoft** [comment]
For sure.  Should be easy to add.

**Comment by JoeProgram** [comment]
Awesome!  Thanks so much.

**Comment by TomWildenhain-Microsoft** [comment]
#1372
