### ISSUE TITLE
tf_loader fails to load .pb file

### ISSUE THREAD

**Issue by Laubeee** [onnx/tensorflow-onnx#1367]
**Describe the bug**
Can't convert .pb file

**System information**
- Win10
- Tensorflow Version: 1.15.3
- Python version: 3.7.1

**To Reproduce**
get [EfficientPose model II](https://github.com/daniegr/EfficientPose/blob/master/models/tensorflow/EfficientPoseII.pb) and try to convert it to onnx

**Additional context**
```
Traceback (most recent call last):
  File "[...]\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "[...]\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "[...]\site-packages\tf2onnx\convert.py", line 233, in <module>
    main()
  File "[...]\site-packages\tf2onnx\convert.py", line 159, in main
    graph_def, inputs, outputs = tf_loader.from_graphdef(args.graphdef, args.inputs, args.outputs)
  File "[...]\site-packages\tf2onnx\tf_loader.py", line 202, in from_graphdef
    frozen_graph = freeze_session(sess, input_names=input_names, output_names=output_names)
  File "[...]\site-packages\tf2onnx\tf_loader.py", line 156, in freeze_session
    output_node_names = [i.split(':')[:-1][0] for i in output_names]
TypeError: 'NoneType' object is not iterable
```

Tried with newer opsets as well

Edit: the corresponding tflite model fails as well

**Comment by guschmue** [comment]
Seems to work for me. Try 
```
python -m tf2onnx.convert --input ~/download/EfficientPoseII.pb --inputs input_res1:0 --outputs upscaled_confs/BiasAdd:0 --output /tmp/t.onnx --opset 13
```

**Comment by Laubeee** [comment]
Ah I see, I did not specify inputs and outputs.. what is the behaviour on that, I mean, what is the tool trying to do if these are missing? Shouldn't it error out in that case?

Moreover: is it possible to have an automatic fallback extracting all inputs and outputs from the .pb file? (which would be a feature request)

**Comment by guschmue** [comment]
the .pb is a graph_def and that format does specify inputs and outputs ... that is why we need them passed in the command line.
If the model would be a saved-model or a tflite format ... those specify inputs and outputs so we don't need them in the command line.

Its the same when you try to run inference in tensorflow on that model ... you need to know the input and output names.

**Comment by TomWildenhain-Microsoft** [comment]
You can use Netron to visualize the model and more easily get the inputs/outputs. https://github.com/lutzroeder/Netron

**Comment by Laubeee** [comment]
> You can use Netron to visualize the model and more easily get the inputs/outputs. https://github.com/lutzroeder/Netron

Kind of my point: if Netron can do it, can't anyone do it?

Otherwise: "detecting" that the input is a graphdef without specified in- and outputs, raising a user error, would be cool. (I take it from your explanation the converter just assumed the file is a saved model and processed it as far as it could? Is it possible that this behaviour successfully finishes, but produces an incomplete model and hence unexpected results?)

That being said, my original issue is solved, it's up to you to decide if you want to pursue either of above suggestions before you close it or not. Thanks @guschmue for helping out so quickly :)

**Comment by guschmue** [comment]
If you look at a graphdef in netron - it doesn't tell the inputs or outputs BUT a human can see it in many cases just by looking at the graph. Its possible to reliable identify inputs, but any node in the graph could be an output that the app wants to pull so that we can't do reliable do.
The fix is to use a saved-model and since keras is recently the common way to write tf models the model will come most likely as  saved-model.

**Comment by TomWildenhain-Microsoft** [comment]
Yeah the issue is the graph_def is underspecified as a format and does not indicate the outputs.  We could of course find all nodes with outputs that are unused and treat them as graph outputs.  That would be correct most of the time.
