### ISSUE TITLE
need to optimize resize->transpose->ArgMax sequence

### ISSUE THREAD

**Issue by guschmue** [onnx/tensorflow-onnx#1379]
Resize->Transpose->Argmax to Resize->Argmax

Resize followed by a NCHW->NHWC transpose, then an ArgMax on axis 3.
instead remove the Transpose and use ArgMax on axis 1

**Comment by TomWildenhain-Microsoft** [comment]
If the transpose was pushed there by the transpose optimizer, we might just be able to add an optimizer before it for Resize->Argmax

**Comment by guschmue** [comment]
or maybe build it into the transpose optimizer
