### ISSUE TITLE
cannot import name 'from_graph_def' from 'tf2onnx.convert'

### ISSUE THREAD

**Issue by Phincle** [onnx/tensorflow-onnx#1393]
in README.md -> Python API reference -> from_graph_def
no such api "from_graph_def"

**Comment by guschmue** [comment]
Oh, sorry - this is fairly new and we have not pushed this to pypi. Will do so in the next few days. In the meantime you could use
```
pip install git+https://github.com/onnx/tensorflow-onnx
```
to install from master.

**Comment by Phincle** [comment]
> o

thank you
