### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by creidieki** [onnx/tensorflow-onnx#1396]
In the "Python API Reference" section of README.md, there's a link 
`See tutorials/keras-resnet50.ipynb for an end to end example.`
which leads to https://github.com/onnx/tensorflow-onnx/blob/master/keras-resnet50  . But that page is a 404 error.

Thanks!

**Comment by guschmue** [comment]
sorry, typo - I'll fix it. The correct link is:
https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/keras-resnet50.ipynb

**Comment by guschmue** [comment]
fixed.
