### ISSUE TITLE
assert d in name_to_node, "%s is not in graph" % d, AssertionError: <node name> is not in graph

### ISSUE THREAD

**Issue by hoaquocphan** [onnx/tensorflow-onnx#1399]
Dear All,

Currently, I have a issue and the following steps will explain how to reproduce, 
download tensorflow model from tensorflow hub: **efficientnet_b0_classification_1**

I can convert the tensorflow model to onnx model as below command:
```
python3 -m tf2onnx.convert --saved-model efficientnet_b0_classification_1 --output efficientnet_b0_classification_1.onnx --concrete_function 2 --opset 12 --inputs inputs:0[1,224,224,3] --inputs-as-nchw inputs:0
```

but, when  I try to remove the softmax op by command:
```
python3 -m tf2onnx.convert --saved-model efficientnet_b0_classification_1 --output efficientnet_b0_classification_1.onnx --concrete_function 2 --opset 12 --inputs inputs:0[1,224,224,3] --inputs-as-nchw inputs:0 --outputs StatefulPartitionedCall/StatefulPartitionedCall/logits/StatefulPartitionedCall/MatMul_Gemm__23:0
```

I have checked the node name of model on https://netron.app/ and get the output name, but This have the error as below:

> Instructions for updating:
> Use `tf.compat.v1.graph_util.extract_sub_graph`
> 2021-03-16 15:30:30,828 - WARNING - From /usr/local/lib/python3.6/dist-packages/tf2onnx-1.9.0-py3.6.egg/tf2onnx/tf_loader.py:557: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `tf.compat.v1.graph_util.extract_sub_graph`
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.9.0-py3.6.egg/tf2onnx/convert.py", line 461, in <module>
>     main()
>   File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.9.0-py3.6.egg/tf2onnx/convert.py", line 213, in main
>     args.large_model, return_initialized_tables=True, return_tensors_to_rename=True)
>   File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.9.0-py3.6.egg/tf2onnx/tf_loader.py", line 466, in from_saved_model
>     tag, signatures, concrete_function, large_model)
>   File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.9.0-py3.6.egg/tf2onnx/tf_loader.py", line 423, in _from_saved_model_v2
>     frozen_graph = from_function(concrete_func, inputs, outputs, large_model)
>   File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.9.0-py3.6.egg/tf2onnx/tf_loader.py", line 152, in from_function
>     graph_def = tf_optimize(input_names, output_names, graph_def)
>   File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.9.0-py3.6.egg/tf2onnx/tf_loader.py", line 557, in tf_optimize
>     graph_def = extract_sub_graph(graph_def, needed_names)
>   File "/home/rvc/.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
>     return func(*args, **kwargs)
>   File "/home/rvc/.local/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py", line 208, in extract_sub_graph
>     _assert_nodes_are_present(name_to_node, dest_nodes)
>   File "/home/rvc/.local/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py", line 163, in _assert_nodes_are_present
>     assert d in name_to_node, "%s is not in graph" % d
> AssertionError: StatefulPartitionedCall/StatefulPartitionedCall/logits/StatefulPartitionedCall/MatMul_Gemm__23 is not in graph

So Please anyone have faced this issue, please help me?

**Comment by TomWildenhain-Microsoft** [comment]
Run the first conversion again, and use the `--output_frozen_graph frozen.pb` flag to save a copy of the frozen tf graph.  Then open it in Netron and get the name from there.  Sometimes the graph freezing process changes the names of the nodes.

**Comment by hoaquocphan** [comment]
Dear @TomWildenhain-Microsoft 
I have tried your solution, but the network of  frozen.pb have some difference with network of onnx model. so when I use the node name on frozen.pb, it have the same error log.

**Comment by TomWildenhain-Microsoft** [comment]
Sorry, the model I downloaded from tfhub doesn't have that node.  Can you link directly to the model and make sure it is the same version that you have on disk?  Or you can upload the model you have.  

Also the `MatMul_Gemm__23` node is created by tf2onnx during conversion.  The name `StatefulPartitionedCall/StatefulPartitionedCall/logits/StatefulPartitionedCall/MatMul:0` is more likely to work.  If it doesn't, please provide a link to the model and I can look.

**Comment by hoaquocphan** [comment]
Hi @TomWildenhain-Microsoft 

Thank for your support!
I changed the op name from **MatMul_Gemm__23** to **MatMul** and it works, the command as below:

`python3 -m tf2onnx.convert --saved-model efficientnet_b0_classification_1 --output efficientnet_b0_classification_1.onnx --concrete_function 2 --opset 12 --inputs inputs:0[1,224,224,3] --inputs-as-nchw inputs:0 --outputs StatefulPartitionedCall/StatefulPartitionedCall/logits/StatefulPartitionedCall/MatMul:0`

As your comment, the **MatMul_Gemm__23** node is created by tf2onnx but it actually is **MatMul** node.
I don't know why the tf2onnx tool doesn't use **MatMul** node as the original? 
Why should it change from **MatMul** to **MatMul_Gemm__23**?
the **MatMul_Gemm__23** is actually Matmul node or Gemm node?
What is related between Matmul  and Gemm?

Please explain for me above question, and help me to get the basic knowledge about this.

Thank you very much!

**Comment by TomWildenhain-Microsoft** [comment]
Glad to hear it worked.  In general, **the names of graph input/output nodes are preserved, but all other names could change during conversion**.  Honestly, I'm not sure why the node is named `MatMul_Gemm__23` in this case.  The `__23` indicates that it was created by tf2onnx, but it is possible that a node `MatMul_Gemm` exists in the original graph.

It is possible we inserted a Gemm node and then an optimizer subsequently replaced it was a MatMul.
