### ISSUE TITLE
conda package doesn't support Python 3.8

### ISSUE THREAD

**Issue by markusweimer** [onnx/tensorflow-onnx#1412]
The `tf2onnx` package on conda-forge doesn't (claim to) work with Python 3.8. Are there plans to update it?

**Comment by guschmue** [comment]
3.8 or 3.9 is fine and works ok with pypi.
We don't publish to conda-forge ourselfs - let me find out how it gets there and where the version assumption gets it.

**Comment by markusweimer** [comment]
Thanks for checking! Yes, I saw that it works on pypi. That is why I was surprised it wasn't on `conda-forge`.

Some background: We are preparing the next default environment for Azure Synapse. We have chosen `conda` as the environment manager. For stability and ease of use, we'd like to keep as many of the packages we install by default on the `conda` side of the `conda`/`pip` divide. For example, `tf2onnx` requires `numpy` and `onnx`, which we already install via `conda`.

**Comment by guschmue** [comment]
the package on conda-forge is behind as well what is really not good. We are debating if we should publish a conda package ourselves so we have some control over it. Should decide today on this.

**Comment by markusweimer** [comment]
I'm +1 on conda packages. It makes it much easier for places like Synapse which want to create a complete, yet clean, base environment for our customers.

**Comment by xhochy** [comment]
@guschmue Feel free to add yourself as a maintainer at https://github.com/conda-forge/tf2onnx-feedstock

Nevertheless, I'm going to have a look at this now.

**Comment by xhochy** [comment]
One of the issues is that you are not releases `sdist` tarballs to PyPI. Uploading them alongside the wheels would make maintenance of the conda package simpler.

**Comment by xhochy** [comment]
This issue will be fixed by https://github.com/conda-forge/tf2onnx-feedstock/pull/9

**Comment by guschmue** [comment]
Sorry, did not get to this yet. I guess we can upload a sdist to pypi. Was planning to upload a release next few days anyway.

**Comment by xhochy** [comment]
This is now fixed and we also have Python 3.9 packages additionally on conda-forge.

**Comment by guschmue** [comment]
Awesome, thanks!!!!
