### ISSUE TITLE
No opset import for domain 'ai.onnx.ml' when importing back from ONNX to TensorFlow

### ISSUE THREAD

**Issue by franespiga** [onnx/tensorflow-onnx#1415]
**Describe the bug**
I can successfully export a saved model from TFHUB to ONNX using additional operators and opset13. 
The only warning I get has to do with shape:
`WARNING - Cannot infer shape for StatefulPartitionedCall/model/keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/text_preprocessor/hash_table_Lookup/hash_table_Lookup/LookupTableFindV2: StatefulPartitionedCall/model/keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/text_preprocessor/hash_table_Lookup/hash_table_Lookup/LookupTableFindV2:0`

If I try to import it back to TensorFlow, then it throws an error

```
onnx.onnx_cpp2py_export.checker.ValidationError: No opset import for domain 'ai.onnx.ml'
--
 
==> Context: Bad node spec: input: "StatefulPartitionedCall/model/keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/text_preprocessor/GatherNd:0" output: "StatefulPartitionedCall/model/keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/text_preprocessor/hash_table_Lookup/hash_table_Lookup/LookupTableFindV2:0" name: "StatefulPartitionedCall/model/keras_layer/StatefulPartitionedCall/StatefulPartitionedCall/text_preprocessor/hash_table_Lookup/hash_table_Lookup/LookupTableFindV2" op_type: "CategoryMapper" attribute { name: "cats_int64s" ints: 221359 ints: 336467 ints: 386359 ints: 364955 ints:
```

**Urgency**
None

**System information**
- Linux Ubuntu 20.04
- Tensorflow Version: 2.4.1
- Python version: 3.8.5

**To Reproduce**
**1 ) Save the model from TFHUB locally**
```
import tensorflow_hub as hub
import tensorflow as tf

url = "https://tfhub.dev/google/universal-sentence-encoder/4"
encoder = hub.KerasLayer(url)
input_ = tf.keras.layers.Input(shape=(), dtype='string')
output_ = encoder(input_)
model = tf.keras.Model(input_, output_)
model.save("./use_tf2")
```

**2 ) Convert to ONNX**
`python -m tf2onnx.convert --saved-model use_tf2/ --opset 13 --output use_model.onnx --extra_opset ai.onnx.contrib:1`

**3 ) Convert back to TF**
```
import onnx
from onnx_tf.backend import prepare

onnx_model = onnx.load("./use_model.onnx") 
model  = prepare(onnx_model)
```

**Additional context**
I want to do this to see if converting back from ONNX allows me to extract portions of the model. 

Thanks, 
F.

**Comment by guschmue** [comment]
Sounds https://github.com/onnx/onnx-tensorflow team should look at this. I'd open an issue there.

**Comment by guschmue** [comment]
Please open against https://github.com/onnx/onnx-tensorflow
