### ISSUE TITLE
How to avoid converting to int64?

### ISSUE THREAD

**Issue by hoangmt** [onnx/tensorflow-onnx#1430]
Hi, when converting tf models to onnx, some operators including Squeeze, Unsqueeze and some others require dtype=int64, which is not supported by tensorRT. Questions:
1. Is there anyway (e.g., my own new pluggin for Squeeze, Unsqueeze?) to have int32 instead as I need to ultimately convert onnx model to tensorrt which does not support int64? Can I modify current Squeeze and Unsqueeze instead of starting from scratch?
2. If using new pluggin for these operators, how to make trtexec recognize them?

**Comment by guschmue** [comment]
I'd file an issue against tensorrt, for example here https://github.com/onnx/onnx-tensorrt. 
tensorrt has to support this somehow since the onnx spec defines it this way.
