### ISSUE TITLE
some error about process_tf_graph() when use convert.py convert pb to onnx

### ISSUE THREAD

**Issue by 250zhanghu** [onnx/tensorflow-onnx#1432]
**Describe the bug :**when use convert.py convert pb to onnx,some errors happened.
Traceback (most recent call last):
  File "convert.py", line 467, in <module>
    main()
  File "convert.py", line 256, in main
    output_path=args.output)
  File "convert.py", line 153, in _convert_common
    g = process_tf_graph(tf_graph, const_node_values=const_node_values,tensors_to_rename = None, **kwargs)
TypeError: process_tf_graph() got multiple values for keyword argument 'tensors_to_rename'
**Urgency :**very important.
**System information**
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):jetson xavier, ubuntu 18.04
Tensorflow Version:1.15.3
Python version:3.6.9
other:tf2onxx =1.9.0, onxx=1.8.0.
**To Reproduce:**

**Comment by TomWildenhain-Microsoft** [comment]
The line referenced `g = process_tf_graph(tf_graph, const_node_values=const_node_values,tensors_to_rename = None, **kwargs)` does not match the file on git.  Can you please make sure you have the latest version of tf2onnx?

`pip uninstall tf2onnx`
`pip install git+https://github.com/onnx/tensorflow-onnx`

**Comment by 250zhanghu** [comment]
> The line referenced `g = process_tf_graph(tf_graph, const_node_values=const_node_values,tensors_to_rename = None, **kwargs)` does not match the file on git. Can you please make sure you have the latest version of tf2onnx?
> 
> `pip uninstall tf2onnx`
> `pip install git+https://github.com/onnx/tensorflow-onnx`

thanks very much for your advice, I have try it but failed. 
I run the convert.py by writing arguments to this file, not use command-line, maybe this is the reason.
I will try the instruction. thanks for your help again.

**Comment by TomWildenhain-Microsoft** [comment]
Did you modify the contents of convert.py at all?  What is the origin of the line `g = process_tf_graph(tf_graph, const_node_values=const_node_values,tensors_to_rename = None, **kwargs)`?

Python is complaining because it is getting two values for `tensors_to_rename`.  One is from `kwargs`, the other is added with the 
 `tensors_to_rename = None` expression.

**Comment by guschmue** [comment]
assume this is resolved.
