### ISSUE TITLE
convert group conv2d op to onnx failed.

### ISSUE THREAD

**Issue by BBuf** [onnx/tensorflow-onnx#1434]
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/nn.py#L340

tensorflow's convolution OP also has a groups parameter, why not consider it here? 

code is here.

```
class Net(tf.keras.Model):
        def __init__(self):
            super(Net, self).__init__()
            self.conv = tf.keras.layers.Conv2D(6, 3, strides=(1, 1), padding="valid", groups=2, dilation_rate=2)

        def call(self, x):
            x = self.conv(x)
            return x
```

**Comment by guschmue** [comment]
Hm, interesting. Seems to work only on gpu.
The op itself doesn't have a group attribute:
https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/conv2-d
I guess one can find out via shapes.
Let us see if we can add this.

**Comment by BBuf** [comment]
Hello, I calculate the group parameter according to the shape of input and output tensor, and then set it as the attribute of onnx node. PR is here
https://github.com/onnx/tensorflow-onnx/pull/1435

**Comment by TomWildenhain-Microsoft** [comment]
Looks like one of the tests is failing: resnet_v2_fp32_savedmodel_NCHW

`Status Message: Input channels C is not equal to kernel channels * group. C: 3 kernel channels: 3 group: 3`

**Comment by BBuf** [comment]
I have solved it。

**Comment by TomWildenhain-Microsoft** [comment]
Awesome.  When committing you have to use the `-s` flag or the DCO bot gets mad.  You can fix your existing commits by following the instructions here:
https://github.com/onnx/tensorflow-onnx/pull/1435/checks?check_run_id=2251056099

**Comment by BBuf** [comment]
I have solved it，Can this pr be merged?

**Comment by farzanehnakhaee70** [comment]
Do you find any solution for this one?
I had exactly similar issue where I want to pass the groups parameter based on the shape of the input size. But currently, it is not being performed correctly.

**Comment by AlexM4** [comment]
Doesn't seem to be fixed.

Toy example
model=Sequential()
model.add(Conv3D(16,(3,3,3),groups=2,input_shape=(6,6,6,4)))

after exporting to onnx, the convolution layer still has groups=1

**Comment by reach-satori** [comment]
Thank you alex, that was the exact issue I happened to be having. That was lucky, if you hadn't replied to this I'd never have found it. I just needed to get something working quickly so this is the hack I edited in, in case anybody else is in a similar position:

```python
        add_padding(                                                                                
            ctx, node, kernel_shape, strides, dilations=dilations, spatial=spatial                  
        )                                                                                           
        groups = int(1)                                                                             
        data_format = str(node.attr["data_format"].s, encoding="utf8")                              
        shape_dim = -1                                                                                  
        if data_format == "NHWC":                                                                   
            shape_dim = ctx.get_shape(node.input[0])[3]                                             
        elif data_format == "NCHW":                                                                 
            shape_dim = ctx.get_shape(node.input[0])[1]                                             
        elif data_format == "NDHWC":                                                                
            shape_dim = ctx.get_shape(node.input[0])[4]                                             
        if shape_dim != -1:                                                                         
            if len(data_format) == 5:                                                               
                groups = int(shape_dim / ctx.get_shape(node.input[1])[3])                           
            else:                                                                                   
                groups = int(shape_dim / ctx.get_shape(node.input[1])[2])                           
                                                                                                    
        node.set_attr("group", groups)```
