### ISSUE TITLE
Move from Upscale to Resize?

### ISSUE THREAD

**Issue by dspmihai** [onnx/tensorflow-onnx#1437]
**Describe the bug**
I see that ResizeNearestNeighbor is converted to ONNX Upsample here: https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/nn.py#L1158
But I see that Upsample is deprecated: https://github.com/onnx/onnx/blob/master/docs/Operators.md#Upsample
And I think the Resize should be the best option, right? Is there a plan to move from Upsample to Resize?

**Urgency**
None

**Comment by guschmue** [comment]
This specific code is for opset-7 which did not have resize.
opset-9 and later will use resize:
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/nn.py#L1237
