### ISSUE TITLE
TF2onnx exported custom trained Object Detection model from model zoo fails check_model

### ISSUE THREAD

**Issue by bdnkth** [onnx/tensorflow-onnx#1443]
**Describe the bug**
Exporting a pretrained object detection model from https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md to onnx passes the check_model test.
However, if the same pretrained model is trained on custom data with the object detection api from TensorFlow and afterwards saved and then exported to onnx with tf2onx, the onnx model fails the check_model test with a ValidationError. There is no difference in the layout between both models. The only difference, which I've found so far, is, if the model is viewed in Netron, the pretrained model has graph def version v456 and the custom trained model has the graph def version according to the TensorFlow version, so either v440 for TF 2.3.1 or v651 for TF 2.4.1. I do not know where the v456 comes from, it is not from an officially released TensorFlow version. However, that model is officially from TensorFlow.
This happens with several models, it is not exclusively to the EfficientDet.

**System information**
- OS Platform and Distribution: Windows 10
- Tensorflow Version: 2.4.1 and 2.3.1
- Python version: 3.8.8
- Onnx version: 1.8.1
- tf2onnx version: 1.8.4

**To Reproduce**
Download a model from https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md. Export it to onnx with tf2onnx, load it into onnx and perform the check_model test. Test passes.
Use the same model, train it on custom data, save it, export it to onnx with tf2onnx. Check_model test fails.

**Comment by TomWildenhain-Microsoft** [comment]
@bdnkth to save me the effort of making the model with a custom dataset, could you upload you tf and onnx files?  Ideally the 2 onnx files you comapred in Netron and the 2 TF files.  Also you can try comparing the models using onnx2py:
https://github.com/microsoft/onnxconverter-common/blob/master/onnxconverter_common/onnx2py.py

Some differences are not visible in Netron.

**Comment by bdnkth** [comment]
Thank you for the fast reply. You can find the requested files at [weTransfer](https://we.tl/t-piY55Rb3AH) since the files are larger than the 10MB size limit of github.

I have checked the python model from the onnxconverter, they are indeed not the same. I was not expecting this since I do not change anything about the layout of the model during custom training with the object detection API. Or at least that is what I'm expecting.
Since I have installed the onnxconverter the error message from check_model has changed to:
ValidationError: No Op registered for TensorListStack with domain_version of 11 ==> Context: Bad node spec: input: "StatefulPartitionedCall/map/while_loop:1" input: "StatefulPartitionedCall/map/TensorArrayV2Stack_1/TensorListStack/element_shape:0" output: "StatefulPartitionedCall/map/TensorArrayV2Stack_1/TensorListStack:0" name: "StatefulPartitionedCall/map/TensorArrayV2Stack_1/TensorListStack" op_type: "TensorListStack" attribute { name: "num_elements" i: 1 type: INT }

Since this error is related to opset 11 (which I need anyway due to TensorRT) I have tested also opset 13 to see if that fixes the ValidationError but it does not. Only difference is that the error message is changed to domain_version of 13.

This leads me to the question, if this problem is really related to tf2onnx or if TensorFlow is mixing something up during the custom training for the object detection.

**Comment by TomWildenhain-Microsoft** [comment]
Thanks for the model.  The custom trained model contains a loop which adds the TensorListStack.  Normally we can convert it if the TensorListStack is the direct output of a While node, but in this case an Identity node was blocking that pattern.  I've made a fix to skip over the Identity node and the model now converts on my machine.  #1448

**Comment by VeeranjaneyuluToka** [comment]
Hi, i am also facing the same issue and attached are two models netron outputs
Pretrained model - ![Screenshot from 2021-04-26 10-38-32](https://user-images.githubusercontent.com/61545398/116054056-98d1b300-a67b-11eb-81e1-75b6dec0f075.png)

Custom model - 
![Screenshot from 2021-04-26 10-39-46](https://user-images.githubusercontent.com/61545398/116054212-bd2d8f80-a67b-11eb-9119-ce14b60da909.png)
After i consider the #1448 changes, TensorListStack is not being showed in grop and checker.checkmodel is not complaining and graph looks as below
![Screenshot from 2021-04-26 10-41-41](https://user-images.githubusercontent.com/61545398/116054512-08e03900-a67c-11eb-9c10-e9cbefd57abb.png)
Still shows loop and graph differs compare to original pretrained-model graph. could you please have a look and let me know if there are any changes that i need to consider to make both pretrained and custom model graphs are equal?

**Comment by bdnkth** [comment]
It is not neccessarily a problem, that the custom trained graph looks different than the original pretrained graph. My custom trained graph looks different than the original pretrained graph but produces the results I expect. Both in TF runtime and in onnx runtimeI assume that Tensorflow changes something during the export of the custom trained model but that does not seem to have any influence on the results, at least for my model.

**Comment by VeeranjaneyuluToka** [comment]
OK, thanks for quick reply. I am able to run the inference using onnx runtime and results also looks fine. But i am trying to convert from onnx to Tensorrt egnine, and it is reporting at the loop node which is present in my custom model. Did you also try convert from onnx to trt and got succeeded?

**Comment by bdnkth** [comment]
I tried to convert to TensorRT but failed due to the missing support of NonMaxSuppression by TensorRT

**Comment by TomWildenhain-Microsoft** [comment]
Yes, the model looks different because we don't have support for TensorList ops in onnx and resort to using Scan outputs instead.  Check if the results match in ORT and if they do you should be fine.
