### ISSUE TITLE
Shape inference mismatch error when I return intermediate Convolution layer output from ONNX graph

### ISSUE THREAD

**Issue by PreethaVeera** [onnx/tensorflow-onnx#145]
@guschmue @pengwa 
I want to return the output of first convolution layer's output from VGG-16's ONNX graph with caffe-2 backend. I am using tests/run_pretrained_models.py script with vgg conversion enabled in the yaml and the output set as the first convolution node name.

I am able to get the onnx graph but "run_onnx" fails with the following error:

RuntimeError: Inferred shape and existing shape differ in dimension 1: (64) vs (224)

But I don't face any issue if I set the output node as ReLu Layer that follows the Convolution. Its evident that the issue is because of the NHWC and NCHW difference and the transpose layer succeeding the convolution fixes the shape issue with Relu. But I am in need of the output values of first Convolution layer. Is there any workaround so that I get the output of the Convolution layer as it is?

Another issue is that with the --optimize_transpose flag in the same setup, I am getting the same error while returning the output for ReLu node too. Is there is any hidden bug in the code?

PS: I see the same behaviour for other models also.

**Comment by guschmue** [comment]
If I understand this correctly you want vgg16 and use output of the 1st conv layer. 
Don't see a problem with this in general. You'd need to make sure the shape of the input in the yaml file is the same as what is defined by the model (the shape in the yaml file is only used to generate the test data and we could have just asked tensorflow for that shape but we configure it in case there are unknown dimensions in the shape (say for example the batch size)).
If you can send a link to the specific model and the output name you want we can take a look.

**Comment by PreethaVeera** [comment]
@guschmue  We have used the VGG-16 from the tensorflow-slim models (http://download.tensorflow.org/models/vgg_16_2016_08_28.tar.gz). The shape of the input in the yaml is [1,224,224,3] same as the shape specified for training. We are trying to return the output  of node vgg_16/conv1/conv1_1/Conv2D:0 (the first convolution layer's output without the transpose operation)

**Comment by guschmue** [comment]
Looked at it: this kind of works as expected, only that vgg_16/conv1/conv1_1/Conv2D:0 needs a transpose. We can't reference the transpose output name in the outputs, because the outputs are also used to find the    inference subgraph and that happens early on in the processing when the generated transpose is not known.
2 ways of dealing with it:
1. get vgg_16/conv1/conv1_1/Conv2D:0 and add the transpose in your app
2. take the output from the node after the Conv  vgg_16/conv1/conv1_1/BiasAdd 
Does any of this work for you ?

**Comment by PreethaVeera** [comment]
The fix suggested by @guschmue worked fine on that use case. Now when I try to dump an ONNX model and try to compare the layerwise results from TF inference and Caffe2 inference, I am facing various shape inference issues. 

Currently the original TF node names are not retained for the generated ONNX nodes. When I try to get the output of single layer based on TF graph node name I fail because the new nodes in ONNX are created with names having  "__"  scopes.  Is there any possibility in retaining the actual TF node names for the created ONNX pattern output nodes. 

As quoted above the Transpose node should have the node name vgg_16/conv1/conv1_1/Conv2D:0 rather than some made up name.

I have also added a brief explanation of this naming issue [here ](https://github.com/onnx/tensorflow-onnx/issues/188).

**Comment by guschmue** [comment]
If we can use the tensorflow nodes as found we'll not change their name. Names with ```__``` indicate nodes that we have inserted, say for example there is a NotEqual op in tensorflow and we need to compose it has Equal and Not (since onnx does not have NotEqual) we'd insert the Not op using the name of the tf  NotEqual + __ + some number.
Don't think there is a way of avoiding this.

**Comment by PreethaVeera** [comment]
I get the reason behind the insertion of "__" + some number as the naming pattern. But this arises a potential Issue if Layer-wise comparison of graphs is to be performed. 

Previously the nodes that are newly created were returned in the form of List to its calling function. 
[Previous implementation of Op functions](https://github.com/onnx/tensorflow-onnx/blob/c6d9f0ae8238036ee05e5ccbf748d97a93e603ed/tf2onnx/tfonnx.py#L2298 )

In the Current tip the functions are not returning the nodes. If the info of the nodes that are created/ modified at each op functions is available as it was previously, then the last node can be renamed with the TF original name. 
For eg : In NotEqual op decomposed into Equal + Not in ONNX then we can rename Not with the original TF graph NotEqual node name. 

Are there any specific reasons behind removing the return statements at the function level? Can we have the return statements back to rename the Last node with original TF node name?
Thanks.

**Comment by guschmue** [comment]
Maybe that would work for simple mappings but for things like control flow we can not guarantee names are the same as in tensorflow and it would make graph optimizations harder (like if we fuse a pad into conv a node name will disappear).

**Comment by PreethaVeera** [comment]
Yeah True. It is tricky when it comes to optimizations. But if it is atleast possible to verify the intermediate results by turning of the optimizations I think it would be really great for us to ensure the conversion to ONNX is happening right. I would like to know if we can bring back the return statement as in the [previous implementation of Op functions with return Statement](https://github.com/onnx/tensorflow-onnx/blob/c6d9f0ae8238036ee05e5ccbf748d97a93e603ed/tf2onnx/tfonnx.py#L2298) that returns the onnx nodes that are created for TF node at the handlers. The node list thus returned from the handler can be subjected to a module that renames the last onnx node in the list to Tensorflow actual node name.

(like in the handler for Less op a Cast op is introduced while mapping to ONNX {Less = Cast + Less} can we bring back the return statement as in  [Previous implementation of Op functions](https://github.com/onnx/tensorflow-onnx/blob/c6d9f0ae8238036ee05e5ccbf748d97a93e603ed/tf2onnx/tfonnx.py#L463). )

**Comment by PreethaVeera** [comment]
@guschmue  Any updates with regards to handling node names?

**Comment by guschmue** [comment]
Kind of hard for us to do and not very high on our list.

**Comment by guschmue** [comment]
closing, no plan to do this.
