### ISSUE TITLE
Error : No module named tf2onnx 

### ISSUE THREAD

**Issue by debtanu97** [onnx/tensorflow-onnx#1471]
Mam/Sir,
I installed the latest version of tf2onnx using the command : pip install git+https://github.com/onnx/tensorflow-onnx 
On runnning the function tf2pnnx.convert : 
Specifically the command : "python -m tf2onnx.convert --saved-model saved_model.pb --opset 13 --output saved_model.onnx", I get the following error : 
"/usr/bin/python: No module named tf2onnx"

My onnx version is : 1.8.1
      tf2onnx version is : 1.9.0
      tensorflow version is : 2.4.1

I want to convert a ".pb" file to ".onnx" for running a program on my model. Is there any fix to resolve this issue?

Thank You

**Comment by guschmue** [comment]
sounds like something in your environment. Maybe use python3 or pip3.
You can check with 
```
which python
which pip
```
you are using.

**Comment by TomWildenhain-Microsoft** [comment]
This sounds like it might be a virtual environment error.  You might have installed the package into a python that is different from the one you are running.  Also make sure you are using python3.  usr/bin/python is often python 2.

- Is tensorflow-onnx listed when you run `pip list`?
- Did you create a virtual environment with `python3 -m venv virtual_env_name`?
- Did you activate it with `source virutal_env_name/bin/activate`?

**Comment by debtanu97** [comment]
Thank You Sir, using the virtual environment in Python3 worked 👍 :)
