### ISSUE TITLE
OSError: SavedModel file does not exist at

### ISSUE THREAD

**Issue by debtanu97** [onnx/tensorflow-onnx#1474]
Sir,
This is with respect to a previous issue #1471.
Indeed tf2onnx library was installed for python 2 while I was using a python 3 virtual environment. On running with python3, the tf2onnx not found error was resolved but there was another issue as follows : 

But, on running the following command : 
"python3 -m tf2onnx.convert --saved-model ~/project/ERAN/saved_model_1.pb --output saved_model.onnx". 
Where I have a model saved_model_1.pb saved in the current directory and I want to convert it into an onnx file, the following error is shown : 
OSError: SavedModel file does not exist at: /home/deeppoly/project/ERAN/saved_model_1.pb/{saved_model.pbtxt|saved_model.pb}

Any takes on how this issue can be resolved? 
Thank You again for resolving the issue #1471 . It would be very helpful if you could suggest a fix :)

Thank You

**Comment by weihualiuhupituzi** [comment]
how to slove it?
