### ISSUE TITLE
Rank mismatch error from a model involving TF combined NMS

### ISSUE THREAD

**Issue by masahi** [onnx/tensorflow-onnx#1487]
The attached ONNX file fails to load on ORT with the following error:

```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8_combined_nms.onnx failed:Node (Concat__835) Op (Concat) [ShapeInferenceError] All inputs to Concat must have same rank
```
Specifically, it seems to be complaining about the Concat at https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/tensor.py#L1924.

The ONNX file is generated via `tf2onnx` v1.9.0, the original model comes from TF2 detection zoo, reexported using the overridden config `use_combined_nms: true`. The reexported `saved_model` is also attached below.

cc @TomWildenhain-Microsoft 

```
import onnxruntime


model_path = "ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8_combined_nms.onnx"
ort_sess = onnxruntime.InferenceSession(model_path)
```

[ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8_combined_nms.zip](https://github.com/onnx/tensorflow-onnx/files/6397144/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8_combined_nms.zip)

[saved_model_export.zip](https://github.com/onnx/tensorflow-onnx/files/6398008/saved_model_export.zip)

**Comment by TomWildenhain-Microsoft** [comment]
Hi @masahi, thanks for the detailed error report.  The problem was caused by the combined NMS handler using the batch_dims property of GatherND, which is only available in opset >= 12.  Try again with `--opset 12` and see if that fixes the issue.  #1488 will correct the min opset of the handler.

**Comment by masahi** [comment]
@TomWildenhain-Microsoft Great! I confirmed that reexporting with `opset 12` fixed the issue. Thank you very much!!
