### ISSUE TITLE
Error while parsing modified onnx file

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [onnx/tensorflow-onnx#1491]
![Screenshot from 2021-04-30 21-21-18](https://user-images.githubusercontent.com/61545398/116744044-125dfe00-a9fa-11eb-8517-37327870f51a.png)
**Describe the bug**
I have converted from tensorflow 2 savedmodel to onnx using the below command

python -m tf2onnx.convert --saved-model /tf_git_hubs/tensorflow/workspace/training_demo/exported-models/my_ssd_mobnetv2_fpnlite_model/saved_model --output /tf_git_hubs/tensorflow/workspace/training_demo/exported-models/my_ssd_mobnetv2_fpnlite_model/290421_convert/ssd-mobnetv2_fpnlite_model.onnx --opset 12 --inputs "input_tensor:0" --outputs "Identity_6:0","Identity_7:0"

and then modified using the below command to get rid of loop

polygraphy surgeon extract /tf_git_hubs/tensorflow/workspace/training_demo/exported-models/my_ssd_mobnetv2_fpnlite_model/290421_convert/ssd-mobnetv2_fpnlite_model.onnx --inputs StatefulPartitionedCall/map/while_loop:2,1x640x640x3,float32 -o /tf_git_hubs/tensorflow/workspace/training_demo/exported-models/my_ssd_mobnetv2_fpnlite_model/290421_convert/ssd-mobnetv2-fpnlite-model-inploop-removed.onnx

And then using the below command to verify the above modified onnx file

polygraphy run /tf_git_hubs/tensorflow/workspace/training_demo/exported-models/my_ssd_mobnetv2_fpnlite_model/280421_convert/ssd-mobnetv2-fpnlite-model-inploop-removed.onnx --trt --trt-outputs mark all --onnxrt --onnx-outputs mark all

It should pass all but i am getting the below error log

[I] Runner: trt-runner-N0-04/30/21-16:28:04          | Activating and starting inference
[TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[I] Building engine with configuration: max_workspace_size=16777216 bytes (16.00 MB) | tf32=False, fp16=False, int8=False, strict_types=False | 1 profiles
[TensorRT] WARNING: TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.4
[TensorRT] WARNING: TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.4
[TensorRT] WARNING: TensorRT was linked against cuDNN 8.1.0 but loaded cuDNN 8.0.4
[I] Runner: trt-runner-N0-04/30/21-16:28:04          | Completed 1 iterations.
[I] Runner: onnxrt-runner-N0-04/30/21-16:28:04       | Activating and starting inference
[W] ONNX Checker exited with an error:
    Field 'type' of value_info is required but missing.
2021-04-30 15:28:41.401327113 [W:onnxruntime:, graph.cc:84 MergeShapeInfo] Error merging shape info for output. 'StatefulPartitionedCall/ssd_mobile_net_v2fpn_keras_feature_extractor/model/bn_Conv1/FusedBatchNormV3:0' source:{1,32,320,320} target:{0,32,320,320}. Falling back to lenient merge.
Traceback (most recent call last):
  File "/home/veeru/anaconda3/envs/tf_fish_2.2.0_dev/bin/polygraphy", line 47, in <module>
    main()
  File "/home/veeru/anaconda3/envs/tf_fish_2.2.0_dev/bin/polygraphy", line 43, in main
    sys.exit(args.subcommand(args))
  File "/home/veeru/anaconda3/envs/tf_fish_2.2.0_dev/lib/python3.6/site-packages/polygraphy/tools/run/run.py", line 264, in __call__
    exec(script)
  File "<string>", line 32, in <module>
  File "/home/veeru/anaconda3/envs/tf_fish_2.2.0_dev/lib/python3.6/site-packages/polygraphy/comparator/comparator.py", line 170, in run
    run_results[runner.name] = execute_runner(runner, loader_cache)
  File "/home/veeru/anaconda3/envs/tf_fish_2.2.0_dev/lib/python3.6/site-packages/polygraphy/comparator/comparator.py", line 79, in execute_runner
    with runner as active_runner:
  File "/home/veeru/anaconda3/envs/tf_fish_2.2.0_dev/lib/python3.6/site-packages/polygraphy/backend/base/runner.py", line 67, in __enter__
    self.activate()
  File "/home/veeru/anaconda3/envs/tf_fish_2.2.0_dev/lib/python3.6/site-packages/polygraphy/backend/base/runner.py", line 93, in activate
    self.activate_impl()
  File "/home/veeru/anaconda3/envs/tf_fish_2.2.0_dev/lib/python3.6/site-packages/polygraphy/backend/onnxrt/runner.py", line 40, in activate_impl
    self.sess, _ = misc.try_call(self._sess)
  File "/home/veeru/anaconda3/envs/tf_fish_2.2.0_dev/lib/python3.6/site-packages/polygraphy/util/misc.py", line 274, in try_call
    ret = func(*args, **kwargs)
  File "/home/veeru/anaconda3/envs/tf_fish_2.2.0_dev/lib/python3.6/site-packages/polygraphy/backend/onnxrt/loader.py", line 41, in __call__
    return onnxruntime.InferenceSession(model_bytes)
  File "/home/veeru/anaconda3/envs/tf_fish_2.2.0_dev/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 280, in __init__
    self._create_inference_session(providers, provider_options)
  File "/home/veeru/anaconda3/envs/tf_fish_2.2.0_dev/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 309, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (StatefulPartitionedCall/Postprocessor/Decode/mul_1) Op (Mul) [ShapeInferenceError] Incompatible dimensions

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Tensorflow Version:2.4
- Python version: 3.6

**To Reproduce**
Described the commands used above.

**Screenshots**

**Additional context**
Would be great help if there is any tool or way to check whether my modified model is valid.

**Comment by TomWildenhain-Microsoft** [comment]
It looks like ORT thinks the shapes of the multiplication don't match.  To get a model with shapes, do:
```
import onnx
model = onnx.load("path/to/model.onnx")
model_shapes = onnx.shape_inference.infer_shapes(model)
onnx.save(model, "dst/path/model_shapes.onnx")
```
Then open it in Netron and look at the shapes.  You will hopefully see a shape mismatch and be able to find where it came from.

**Comment by VeeranjaneyuluToka** [comment]
@TomWildenhain-Microsoft , thanks for quick reply, have run the shape inference as you suggested about and getting error as below

  File "modify_onnx.py", line 110, in main
    save_model_shapes(onnx_model_path, shapes_model_path)
  File "modify_onnx.py", line 100, in save_model_shapes
    model_shapes = onnx.shape_inference.infer_shapes(model)
  File "/home/veeru/anaconda3/envs/tf_fish_2.4/lib/python3.8/site-packages/onnx/shape_inference.py", line 37, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type, strict_mode)
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Conv, node name: StatefulPartitionedCall/ssd_mobile_net_v2fpn_keras_feature_extractor/model/Conv1/Conv2D): [ShapeInferenceError] Inferred shape and existing shape differ in dimension 0: (1) vs (0)

Tried to have a look into cpp2py_export.cc as reported above but could not get much, Any suggestions to analyze further on this issue?

**Comment by TomWildenhain-Microsoft** [comment]
Looking at your original image, the first conv has a dimension of 0.  I doubt that's what you want.  I don't know how that got there, since tf2onnx doesn't put any shapes in the graph at all.  If polygraphy adds shapes, maybe it has a bug.  In any case, onnx infer_shapes is complaining that the shape it inferred conflicts with an existing shape (the dimension is 1 not 0).  If the shapes in the graph you have are wrong, you will need to get rid of them.  You can use the onnx2py tool to edit an onnx model (and remove incorrect shape info).  

`pip install onnxconverter-common`
`python -m onnxconverter_common.onnx2py "my_model.onnx" "my_model.py"`

Then edit "my_model.py" and run `python my_model.py my_new_model.onnx`.  Specifically you will need to delete all the value info from the model.

**Comment by VeeranjaneyuluToka** [comment]
I deleted all the value info from the model, then run the shape inference, this time it gave me the below error

   app.run(main)
  File "/home/veeru/anaconda3/envs/tf_fish_2.4/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/veeru/anaconda3/envs/tf_fish_2.4/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "modify_onnx.py", line 111, in main
    save_model_shapes(onnx_model_path, shapes_model_path)
  File "modify_onnx.py", line 101, in save_model_shapes
    model_shapes = onnx.shape_inference.infer_shapes(model)
  File "/home/veeru/anaconda3/envs/tf_fish_2.4/lib/python3.8/site-packages/onnx/shape_inference.py", line 37, in infer_shapes
    inferred_model_str = C.infer_shapes(model_str, check_type, strict_mode)
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Unsqueeze, node name: StatefulPartitionedCall/Postprocessor/ExpandDims_1): [ShapeInferenceError] Inferred shape and existing shape differ in rank: (4) vs (3)

i have removed the squeeze node present in original graph to get the 4D tensor, you can see the difference between the graph which has squeeze and which does not have squeeze. However i was still get 3D tensor only and able to convert to trt but results are very bad.
![Screenshot from 2021-05-05 13-10-19](https://user-images.githubusercontent.com/61545398/117132686-78080c80-ada3-11eb-841c-364e785d0cdf.png)
![Screenshot from 2021-05-05 13-10-16](https://user-images.githubusercontent.com/61545398/117132700-7c342a00-ada3-11eb-87f3-ea1e7cb25ac0.png)

I think there is something wrong while removing squeeze node, would you please check these two graphs and let me know what is the mistake? and .py files difference as below

After removing "Squeeze node" and adding NMS plugin
            ),
            make_node(
                'Transpose',
                inputs=['StatefulPartitionedCall/Postprocessor/Decode/stack_Concat__750:0'],
                outputs=['StatefulPartitionedCall/Postprocessor/Decode/transpose_1:0'],
                name='StatefulPartitionedCall/Postprocessor/Decode/transpose_1',
                perm=[1, 0],
            ),
            make_node(
                'Reshape',
                inputs=['StatefulPartitionedCall/Postprocessor/Decode/transpose_1:0', 'const_fold_opt__860'],
                outputs=['StatefulPartitionedCall/Postprocessor/Reshape_2:0'],
                name='StatefulPartitionedCall/Postprocessor/Reshape_2',
            ),
            **make_node('Unsqueeze', inputs=['StatefulPartitionedCall/Postprocessor/Reshape_2:0'], outputs=['Identity_6:0'], name='StatefulPartitionedCall/Postprocessor/ExpandDims_1', axes=[2]),**
            make_node(
                'BatchedNMS_TRT',
                inputs=['Identity_6:0', 'Identity_7:0'],
                outputs=['num_detections:0', 'detection_boxes:0', 'detection_scores:0', 'detection_classes:0'],
                name='onnx_graphsurgeon_node_0',
                shareLocation=1,
                numClasses=5,
                backgroundLabelId=-1,
                topK=4096,
                keepTopK=100,
                scoreThreshold=0.30000001192092896,
                iouThreshold=0.6000000238418579,
                isNormalized=1,
                clipBoxes=1,
            ),
        ],
    ),
)

Before removing "squeeze node"
            make_node(
                'Transpose',
                inputs=['StatefulPartitionedCall/Postprocessor/Decode/stack_Concat__750:0'],
                outputs=['StatefulPartitionedCall/Postprocessor/Decode/transpose_1:0'],
                name='StatefulPartitionedCall/Postprocessor/Decode/transpose_1',
                perm=[1, 0],
            ),
            make_node(
                'Reshape',
                inputs=['StatefulPartitionedCall/Postprocessor/Decode/transpose_1:0', 'const_fold_opt__860'],
                outputs=['StatefulPartitionedCall/Postprocessor/Reshape_2:0'],
                name='StatefulPartitionedCall/Postprocessor/Reshape_2',
            ),
            **make_node(
                'Unsqueeze',
                inputs=['StatefulPartitionedCall/Postprocessor/Reshape_2:0'],
                outputs=['StatefulPartitionedCall/Postprocessor/ExpandDims_1:0'],
                name='StatefulPartitionedCall/Postprocessor/ExpandDims_1',
                axes=[2],
            ),
            make_node('Squeeze', inputs=['StatefulPartitionedCall/Postprocessor/ExpandDims_1:0'], outputs=['Identity_6:0'], name='StatefulPartitionedCall/Postprocessor/Squeeze', axes=[2]),**
        ],
    ),
)

**Comment by VeeranjaneyuluToka** [comment]
Hi @TomWildenhain-Microsoft again, i could fix the above issue by modifying the output shape from 1x51150x4 to 1x51150x1x4. I am able to generate onnx with shapes info with that change and it is as below.
![Screenshot from 2021-05-05 14-39-00](https://user-images.githubusercontent.com/61545398/117144198-f23f8d80-adb1-11eb-8cae-a39dc5142696.png)

but if you check the graph, there is 1x51150x6 which is classes tensor shape but 1x51150x1x4 boxes tensor shape. I think right shape is 1x51150x6x6 for multiple classes. Any suggestion on how to get the right shaped tensor?

**Comment by TomWildenhain-Microsoft** [comment]
Have you verified that the original output of tf2onnx (without polygraphy modifications) is correct?  Even if you can't run it in TensorRT, you should be able to use onnxrunime at least to verify correctness.

**Comment by VeeranjaneyuluToka** [comment]
I converted from the savedmodel to onnx using the below command, ran the inference using onnxruntime and the results of tf saved model and onnx are same.

**python -m tf2onnx.convert --saved-model /tf_git_hubs/tensorflow/workspace/training_demo/exported-models/my_ssd_mobnetv2_fpnlite_model/saved_model --output /tf_git_hubs/tensorflow/workspace/training_demo/exported-models/my_ssd_mobnetv2_fpnlite_model/030521_convert/ssd-mobnetv2_fpnlite_model.onnx --opset 12**

And the above model has preprocessing, network, postprocessing, which means that it applies filters and NMS and gives the following outputs
['detection_anchor_indices', 'detection_boxes', 'detection_classes', 'detection_multiclass_scores', 'detection_scores', 'num_detections', 'raw_detection_boxes', 'raw_detection_scores']
Out of which we need only detection_boxes, detection_classes and detection_scores which are final outputs (after NMS).

But as i can not convert the above onnx to trt as there are some limitations wrt to preprocessing postprocessing. I have used the below command to get only raw_detection_boxes/scores (basically avoiding the postprocessing i.e NMS part)

**python -m tf2onnx.convert --saved-model /tf_git_hubs/tensorflow/workspace/training_demo/exported-models/my_ssd_mobnetv2_fpnlite_model/saved_model --output /tf_git_hubs/tensorflow/workspace/training_demo/exported-models/my_ssd_mobnetv2_fpnlite_model/030521_convert/ssd-mobnetv2_fpnlite_model_no_NMS.onnx --opset 12 --inputs "input_tensor:0" --outputs "Identity_6:0","Identity_7:0"**

Then applied the following modifications on top of onnx graph that i got from the above command to make onnx to trt engine conversion works

The above onnx graph has the following which does not support by TensorRT
-> **input tensor type Uint8**, have used the below piece of code to change input type
def modify_input_type(graph):
    for inp in graph.inputs:
        inp.dtype == np.float32
    return graph

->  **loop node (which i have removed using polygraphy)**, used the following command to remove loop node
polygraphy surgeon extract /tf_git_hubs/tensorflow/workspace/training_demo/exported-models/my_ssd_mobnetv2_fpnlite_model/290421_convert/ssd-mobnetv2_fpnlite_model.onnx --inputs StatefulPartitionedCall/map/while_loop:2,1x3x640x640,float32 -o /tf_git_hubs/tensorflow/workspace/training_demo/exported-models/my_ssd_mobnetv2_fpnlite_model/290421_convert/ssd-mobnetv2-fpnlite-model-inploop-removed.onnx

-> **Removed Squeeze node to get the 4D rather than 3D**, have used the following piece of code to remove squeeze node
def remove_node(graph, node_name):
    fake_node = [node for node in graph.nodes if node.op == node_name][-1]
    inp_node = fake_node.i()
    inp_node.outputs = fake_node.outputs
    fake_node.outputs.clear()

-> **and then added NMS plugin**

Am able to convert from onnx to TensorRT with the above modification but results are quite different (trt engine results are completely wrong). Not sure where it went wrong and how to track differences. Would be great help if you can share any tools using which if i can track the differences?

**Comment by TomWildenhain-Microsoft** [comment]
Ok, I'm glad to hear that onnxruntime produces the correct results.  That at least tells us that the initial onnx model is correct, and gives us a reference model to compare to.  To debug, try setting the outputs to the middle of the model and compare it to the original ORT model.  You can modify the outputs in the model for ORT either using polygraphy or a quick and dirty:
```
import onnx
model = onnx.load("path/to/model.onnx")
model.graph.output[0].name = "desired output name"
import onnxruntime as ort
sess = ort.InferenceSession(model.SerializeToString())
res = sess.run(["desired output name"], {feed dict})
```
The types will be wrong technically but I think ORT will overwrite them.

Try to find the first output in the model that is incorrect.  That should tell you where the error is.

**Comment by mibrahimy** [comment]
Why are you working with output `Identity_6:0` and `Identity_7:0` which I think corresponds to `detection_anchor_indices` and `detection_multiclass_scores`?

**Comment by guschmue** [comment]
I assume this is no longer an issue.
