### ISSUE TITLE
error converting from onnx

### ISSUE THREAD

**Issue by CharlesWang528** [onnx/tensorflow-onnx#1493]
Hi,

I am trying to convert from a model from onnx as:

`from onnx2keras import onnx_to_keras
import onnx

onnx_model = onnx.load('interhand.onnx')

k_model = onnx_to_keras(onnx_model, ['img'])`

Following error is generated. 
<img width="736" alt="onehot" src="https://user-images.githubusercontent.com/68451307/116814455-13d91480-ab27-11eb-8a01-632b3857fd43.PNG">

Does that mean OneHot is currently not supported, if so, do you guys plan on supporting it? 

Can you please help me, many thanks!

**Comment by guschmue** [comment]
This repo is about tensorflow-onnx, not onnx_to_keras.
