### ISSUE TITLE
tf-onnx introducing many transpose operations

### ISSUE THREAD

**Issue by dmoham1476** [onnx/tensorflow-onnx#15]
Hi, I got to convert an tf graph to onnx and I see that there are several transpose operations in the graph because of tf and onnx layout differences. Is there a way I can tweak the tfonnx/other files to avoid these transposes and still get the correct output shape? I am running on a CPU

I see a related post here for onnx-> tensorflow. https://github.com/onnx/onnx-tensorflow/issues/31

**Comment by guschmue** [comment]
If the model is nhwc we wrap the ops with transpose. There are only 2 optimizations: if the input is a const ant we apply the transpose to the constant and if we find back to back transpose we remove it. Pretty conservative and I'm sure we can do better.
Let me find some time to look at it.

**Comment by guschmue** [comment]
This will help:
https://github.com/onnx/tensorflow-onnx/pull/108
