### ISSUE TITLE
How to convert pb with a dynamic-link library?

### ISSUE THREAD

**Issue by fsy2000** [onnx/tensorflow-onnx#1506]
I'm trying to convert a TensorFlow model with a customized **kernel filtering operation** to ONNX.  The library is compiled from the codes [here](https://github.com/xmeng525/MultiResolutionKernelPredictionCNN/tree/master/0_kernel_functions). I import the SO file by `tf.load_op_library('0_kernel_functions/kernel_filter.so')` before I convert trained model to pb.

However, when I'm trying to convert pb to onnx via command line, I get an error:

```bash
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'KernelFilter' in binary running on Server. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
```

Should I use tf2onnx Python API and import this library again before converting pb to onnx? And how?

**Comment by fsy2000** [comment]
I tried to use `tf.load_op_library('0_kernel_functions/kernel_filter.so')` but got `Unsupported ops`. So I set `outputs` the nodes just above the kernel filtering operation to avoid it (I use kernel filtering to calibrate the output images). Therefore, the model only contains TensorFlow operations, but I still encounter errors:
```bash
Tensorflow op [TFRecordDataset: TFRecordDataset] is not supported
Unsupported ops: Counter({'TFRecordDataset': 1})
Tensorflow op [ParseSingleExample/ParseSingleExample: ParseSingleExample] is not supported
Tensorflow op [DecodeRaw_1: DecodeRaw] is not supported
Tensorflow op [DecodeRaw: DecodeRaw] is not supported
Unsupported ops: Counter({'DecodeRaw': 2, 'ParseSingleExample': 1})
```

**Comment by guschmue** [comment]
I think we might be able to do something on DecodeRaw.
ParseSingleExample and TFRecordDataset deal with  tf.example proto and there is no such thing in onnx.
I assume all tf.example  is related to the input processing.
One way of dealing with this would use a node behind the tf.example related preprocessing as input, aka feed the raw images into the model. You could use ```--inputs``` in the tf2onnx command line, just need to find the proper node in the graph.

**Comment by guschmue** [comment]
Closing this one - onnx does not support the ops needed for TFRecordDataset.
