### ISSUE TITLE
Unsupported ops:Counter

### ISSUE THREAD

**Issue by alanMachineLeraning** [onnx/tensorflow-onnx#1507]
Unsupported ops:Counter

**Comment by TomWildenhain-Microsoft** [comment]
Hi @alanMachineLeraning, this op appears to be an experimental op.  https://www.tensorflow.org/api_docs/python/tf/data/experimental/Counter

Can you replace it with tf.range?

**Comment by guschmue** [comment]
assume this is resolved.
