### ISSUE TITLE
Model inputs with uppercase characters triggers at least two bugs

### ISSUE THREAD

**Issue by csantosbh** [onnx/tensorflow-onnx#1525]
**Description**
When a character of the input model is in uppercase, at least two strange behaviors happen:
1. The input name is converted to lowercase. This is not desirable; the input name should remain intact (unless, of course, `--rename-inputs` is provided)
2. If a `tf.constant` exists in the model graph, `tf2onnx` creates unwanted inputs named `unknown:<n>`.

**Urgency**
Medium priority, as a workaround is to use lowercase names when creating the model, then providing tf2onnx with the flag `--rename-inputs` with the actually desired names.

**System information**
- Ubuntu 20.04.2 LTS under WSL 2
- Tensorflow Version: 2.4.1
- Python version: 3.7.10
- tf2onnx version: 1.8.5

**Reproducing**
Use the following source code:
```py
import numpy as np
import tensorflow as tf
import tensorflow.keras as keras


# Here: If input name is `myinput`, it works as expected.
# If it is `myInput`, the bugs are reproducible
x = keras.layers.Input(shape=(1,), name='myInput')
# If we use tf.constant, an additional `unknown` input appears if the input name has an upper case char
y = x + tf.constant(1.0)
model = keras.Model(x, y)
model.summary()

model.save('my_model')
```
Then:
```bash
python sample.py && python -m tf2onnx.convert --saved-model my_model --output model.onnx
```
**Screenshots**
Here is what the model looks like when the two bugs occur (i.e. when the input is named `myInput` and the addition is made with `tf.constant`).
![image](https://user-images.githubusercontent.com/1847919/118828829-e7125480-b8bd-11eb-882b-052fc3f3516c.png)

**Comment by TomWildenhain-Microsoft** [comment]
Interesting.  I can't reproduce this, but maybe it only happens on tf linux.  I get:

![image](https://user-images.githubusercontent.com/67606533/118875977-b4b32800-b8ba-11eb-85cb-af6079eeabdb.png)

Can you try with the latest tf2onnx from github?
`pip uninstall tf2onnx`
`pip install git+https://github.com/onnx/tensorflow-onnx`

If it still happens, can you upload a zip of the saved model?  If it is tf dependent that might make it easier to reproduce.

**Comment by guschmue** [comment]
I can reproduce it on linux. The unknown:0 we get from tf as input and because its an input we don't throw it out. Need to debug a little to see why tf gives this to us.

**Comment by guschmue** [comment]
We are getting myinput:0 and unknown:0 from concrete_func.inputs that comes from the default signature. No idea why tensorflow has it in lower case. @TomWildenhain-Microsoft, we could pickup concrete_func.structured_input_signature and stick it into tensors_to_rename ... what do you think?

unknown:0 comes from tensorflow (it is not in concrete_func.structured_input_signature but in concrete_func.inputs). I guess we could remove such inputs if they are not connected.

**Comment by TomWildenhain-Microsoft** [comment]
The lowercasing I think is normal.  My model converted properly but was converted to lower case.  That unknown:0 is strange.  I think I'd need to trace through the debugger and see where it comes from.  Does the in-memory saved model have anything it could be referencing?  I'm surprised TF doesn't crash on it if it actually doesn't exist in the graph at all.  Actually I'm surprised tf2onnx doesn't output its normal "inputs/outputs not found" error.  Maybe TF generates a noop with that name?

**Comment by guschmue** [comment]
The tf graph looks like this:
![image](https://user-images.githubusercontent.com/22941064/119571774-a192d300-bd66-11eb-8056-7a14b0a23c96.png)
unknown is a const in tf that tf also passes as input. I assume we see that the const isn't used so we throw it out but we are not cleaning up the input list.
Happens to be with tf-2.5.

**Comment by TomWildenhain-Microsoft** [comment]
Ah, I think I know what is going on.  That's a captured input that should be filtered out.  As far as the names go, currently our CLI uses concrete output names but not concrete input names to avoid breaking existing conversions (mainly our own run_pretrained_models tests).  I can add a legacy flag "--use-graph-names" and make inputs also concrete by default.  That will fix the capitalization issue.

**Comment by guschmue** [comment]
sounds like a plan

**Comment by TomWildenhain-Microsoft** [comment]
This first PR just removes the captured inputs ("unknown:0).  #1533 Can you check that it fixes that problem?  The other change will be a bit larger and require updating the unit tests a bit.

**Comment by guschmue** [comment]
yeap, I can test it

**Comment by guschmue** [comment]
ack - unknown:0 is gone with your branch.

**Comment by TomWildenhain-Microsoft** [comment]
@csantosbh Can you test again with the latest tf2onnx from GitHub?  Both the name and extraneous input problems should be resolved.

**Comment by TomWildenhain-Microsoft** [comment]
Ah shoot, sorry to hear that.  Thanks for the detailed error reports.

Also I'm doing an informal survey of our users: What is your motivation for using ONNX? Do you plan on running on CPU or GPU?

**Comment by csantosbh** [comment]
Sorry for the long delay, as I've been on vacation this week. I'm amazed to see that the other issue also seems to be solved now!
As for your question, our current use case is to export ONNX models for inferencing with tensorRT on nVidia GPUs. If you have other questions, I'll be happy to answer :)

Cheers!
