### ISSUE TITLE
Could tf2onnx fold_const optimizer preserve the node(weight) name?

### ISSUE THREAD

**Issue by wm2012011492** [onnx/tensorflow-onnx#1531]
**Describe the bug**
  For tf2onnx fold_const optimizer, the new const node is named by utils.make_name("const_fold_opt") which lose the useful node/weight name. For example, one model contains two conv nodes which share the same kernel weights. tf2onnx will insert two tranpose nodes between the const node (kernel read) and two conv nodes. Then one transpose node is removed and the other one is fold-const with name "const_fold_opt_11".

  Is that possible to preserve the original name with tf2onnx fold_const optimizer?

**System information**
- Ubuntu 18.04:
- TF 1.15
- Python 3.6

**To Reproduce**
python3 -m tf2onnx.convert --input test_op.pb --inputs input:0 --outputs output:0 --output test_op.onnx --verbose --opset 12

**Additional context**
[test_op.zip](https://github.com/onnx/tensorflow-onnx/files/6538003/test_op.zip)

**Comment by TomWildenhain-Microsoft** [comment]
We could make the name be based on the node name.  Do you want this for debugging, or do you want the names exactly the same for some kind of script?  In general, tf2onnx doesn't guarantee that any names are maintained except inputs/outputs.  Making the names exactly the same can be challenging in cases where we are trying to avoid a name conflict.  Also of course const folding can combine two consts with different names so the resulting name must be different from at least one of them (and most likely both if we make the folded const named after the node being folded, not the input consts).

If you want to be able to programmatically edit the weights, you could add them as inputs.  tf2onnx lets you convert any node in the graph to an input.

**Comment by wm2012011492** [comment]
How about we changing the base name from "const_fold_opt" to the initializer/weight name? Below is my modification to fix the issue that kernel name is lost during const fold optimizer when two convs share the same kernel.
```
diff --git a/tf2onnx/optimizer/const_fold_optimizer.py b/tf2onnx/optimizer/const_fold_optimizer.py
index 6b265b9..fb95fe9 100644
--- a/tf2onnx/optimizer/const_fold_optimizer.py
+++ b/tf2onnx/optimizer/const_fold_optimizer.py
@@ -87,12 +87,18 @@ class ConstFoldOptimizer(GraphOptimizerBase):
     def _replace_node_with_const(node, graph, vals):
         utils.make_sure(len(node.output) == len(vals), "length of node outputs and const vals should be same")
         for old_input, val in zip(node.output, vals):
-            const_node = graph.make_const(utils.make_name("const_fold_opt"), val)
+            basename = "const_fold_opt"
+            if node.type == "Transpose":
+                basename = node.input[0]
+            const_node = graph.make_const(utils.make_name(basename), val)
             graph.set_dtype(const_node.output[0], utils.map_numpy_to_onnx_dtype(val.dtype))
             graph.set_shape(const_node.output[0], val.shape)
             graph.replace_all_inputs(old_input, const_node.output[0])  # ops=graph.get_nodes()
         graph.remove_node(node.name)
```

**Comment by TomWildenhain-Microsoft** [comment]
What behavior would you expect when two consts are combined into one?  Also what do you want this for?

**Comment by guschmue** [comment]
I assume this is resolved.
