### ISSUE TITLE
TensorFlow2 model to ONNX conversion (from_function) fails for models with tensors bigger than 2GB

### ISSUE THREAD

**Issue by kacper-kleczewski** [onnx/tensorflow-onnx#1540]
**Description**
Function tf2onnx.convert.from_function fails when model has tensors bigger than 2GB.

**Urgency**
High. Conversion of models with big tensors from TF2 to ONNX is impossible.
For example DLRM with big embedding tables: 
https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow2/Recommendation/DLRM

**System information**
Build docker with TF2 from  NVIDIA NGC
```
FROM nvcr.io/nvidia/tensorflow:21.04-tf2-py3
RUN pip install -U tf2onnx 
```

**Expected results**
Model converted to onnx format.

**Current results**
Failure with error: 
```
Traceback (most recent call last):
  File "testonnx.py", line 86, in <module>
    graph_def = from_function(
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tf_loader.py", line 170, in from_function
    raise e
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tf_loader.py", line 163, in from_function
    frozen_func = convert_variables_to_constants_v2(func, lower_control_flow=False, aggressive_inlining=True)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 1073, in convert_variables_to_constants_v2
    output_graph_def, converted_input_indices = _replace_variables_by_constants(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 1028, in _replace_variables_by_constants
    input_graph.nodes[tensor_name].convert_variable_to_constant(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 379, in convert_variable_to_constant
    tensor_proto = tensor_util.make_tensor_proto(tensor_data.numpy,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/tensor_util.py", line 527, in make_tensor_proto
    raise ValueError(
ValueError: Cannot create a tensor proto whose content is larger than 2GB.
```

**To Reproduce**
You can use this code sample to test it:

```python
import tensorflow as tf

from tf2onnx.tf_loader import from_function
# Types
from typing import Dict, NamedTuple, Tuple
class TensorSpec(NamedTuple):
    name: str
    dtype: str
    shape: Tuple

# Example
FeatureSize=11316796 # this is too big to be converted
#FeatureSize=1572176 # this works
OutputSize=128

class EmbeddingTable(tf.keras.layers.Layer):

    def __init__(self, input_dim, output_dim):
       super(EmbeddingTable, self).__init__(dtype=tf.float32)
       self.input_dim = input_dim
       self.output_dim = output_dim
       self.embedding_table = None

    def build(self, input_shape):
        self.embedding_table = self.add_weight("embedding_table", 
	                    shape=[self.input_dim, self.output_dim],
			    dtype=tf.float32,
			    initializer=tf.keras.initializers.Identity(),
			    trainable=False
			    )

    def call(self, indices):
        return tf.gather(params=self.embedding_table, indices=indices)

class SimpleModel(tf.keras.Model):

    def __init__(self, input_dim, output_dim):
        super(SimpleModel, self).__init__()
        self.embedding_layer = EmbeddingTable(input_dim, output_dim)

    def call(self, input_idxs):
        return self.embedding_layer(input_idxs)

def get_wrapper_model(model, feature_size):
    """
    Wrapper model that will have model.input_names and model.inputs fields.
    """

    input_categorical_feature = tf.keras.layers.Input(
            shape=(1,),
            name=f"categorical_feature_0",
            dtype="int64"
        )
    output = model(input_categorical_feature)
    wrapper_model = tf.keras.Model(inputs=[input_categorical_feature], outputs=output)
    return wrapper_model

if __name__ == "__main__":
    # original big model
    model = SimpleModel(FeatureSize, OutputSize)

    # define wrapper model
    wrapper_model = get_wrapper_model(model, FeatureSize)

    @tf.function
    def call_fn(*arg):
        return wrapper_model(arg, training=False)

    """
    Do the ONNX conversion
    """
    inputs_dict: Dict[str, TensorSpec] = {
        input_name: TensorSpec(t.name, t.dtype.name, tuple(t.shape.as_list()))
        for input_name, t in zip(wrapper_model.input_names, wrapper_model.inputs)
    }

    concrete_func = call_fn.get_concrete_function(
        *[tf.TensorSpec(shape=spec.shape, dtype=spec.dtype, name=name) for name, spec in inputs_dict.items()]
    )

    input_tensors_names = [tensor.name for tensor in concrete_func.inputs if tensor.dtype != tf.dtypes.resource]
    output_tensors_names = [tensor.name for tensor in concrete_func.outputs]
    
    # If the embedding table is too big, this function call fails
    # Regardless of "large_model" flag.
    graph_def = from_function(
        concrete_func, input_tensors_names, output_tensors_names, large_model=False
    )
````

It fails also with CLI tools:
`python -m tf2onnx.convert --saved-model <path_to_model> --large_model`

With error:
`ValueError: Cannot create a tensor proto whose content is larger than 2GB.`

**Comment by TomWildenhain-Microsoft** [comment]
Last year we added the ability to convert models larger than 2GB but I believe you are the first person to try to convert a _tensor_ larger than 2GB. 🥇 

Making this work might be a bit tricky since TF and onnx don't really like having tensors that big, but we can probably hack together a solution.

As a workaround, can you split the weight into smaller tensors and add a few matmuls together?  That might actually run faster.

**Comment by kacper-kleczewski** [comment]
I discussed this workaround proposal with our team and unfortunately it is not suitable for us.

**Comment by guschmue** [comment]
Hard one. I guess the real fix would be in onnx which might take some time.
If Tom's suggestion is not working - this is because of the memory footprint increase ?
Is it visible to make the 2GB tensor fp16?

**Comment by kacper-kleczewski** [comment]
Our embedding tables are bigger than 10 GB so even FP16 won't be enough.

**Comment by guschmue** [comment]
uff, that is large. Going to be a challenge to address this in onnx. Let me ask around.

**Comment by guschmue** [comment]
ok, finally realized its coming from tensorflow and not onnx.

**Comment by kacper-kleczewski** [comment]
So this caused by tensorflow? Is it possible that you can workaround this tensorflow issue in tf2onnx?

**Comment by guschmue** [comment]
Yes, the biggest issue is tensorflow. We ask tensorflow to convert variables to constants and during that conversion some function in tensorflow creates a protobuf that bails.
Not impossible to workaround this - we'd need to take that entire variable to constant conversion into tf2onnx I think. Still looking at the details how to go about this.
There is secondary issue in onnx: onnx can can express such tensors correctly but because of some implementation choice you'd not be able to load such a graph today. That one can fixed for sure.

**Comment by TomWildenhain-Microsoft** [comment]
Try it again once #1558 merges

**Comment by guschmue** [comment]
One suggestion for your example app - instead of using tf2onnx.tf_loader.from_function use the following code:

```
    signature = [tf.TensorSpec(shape=spec.shape, dtype=spec.dtype, name=name) for name, spec in inputs_dict.items()]
    model_proto, external_tensor_storage = \
        tf2onnx.convert.from_function(call_fn, input_signature=signature, opset=13, large_model=True, output_path="/tmp/large.zip")
```

**Comment by guschmue** [comment]
Just ran the script and seems it works.

**Comment by TomWildenhain-Microsoft** [comment]
@kacper-kleczewski is it working for you?

**Comment by kacper-kleczewski** [comment]
@TomWildenhain-Microsoft  I didn't have time to check it yet. I will test it next week.

**Comment by kacper-kleczewski** [comment]
@TomWildenhain-Microsoft
Unfortunately results are the same, it looks like from_function from convert.py still uses tf_loader.py internally.

`File "/usr/local/lib/python3.8/dist-packages/tf2onnx/convert.py", line 407, in from_function
    frozen_graph = tf_loader.from_function(concrete_func, input_names, output_names, large_model=large_model)
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tf_loader.py", line 157, in from_function
    return convert_variables_to_constants_large_model(func)
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tf_loader.py", line 137, in convert_variables_to_constants_large_model
    frozen_graph_def, _ = _replace_variables_by_constants(converter_data=converter_data)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 1028, in _replace_variables_by_constants
    input_graph.nodes[tensor_name].convert_variable_to_constant(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py", line 379, in convert_variable_to_constant
    tensor_proto = tensor_util.make_tensor_proto(tensor_data.numpy,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/tensor_util.py", line 527, in make_tensor_proto
    raise ValueError(
ValueError: Cannot create a tensor proto whose content is larger than 2GB.`

**Comment by TomWildenhain-Microsoft** [comment]
Did you install the latest version from GitHub?
`pip uninstall tf2onnx`
`pip install git+https://github.com/onnx/tensorflow-onnx`

**Comment by kacper-kleczewski** [comment]
I was using 1.8.5 release.
