### ISSUE TITLE
ValueError: Dimension -1 must be >= 0

### ISSUE THREAD

**Issue by LW-CVer** [onnx/tensorflow-onnx#1544]
when using “input_data:0[-1,299,299,3]”，i got the error “ValueError: Dimension -1 must be >= 0”

**Comment by TomWildenhain-Microsoft** [comment]
Hi @LW-CVer there was a similar issue that we solved recently.  Can you try using the latest tf2onnx from github?

`pip uninstall tf2onnx`
`pip install git+https://github.com/onnx/tensorflow-onnx`

Let me know if it works.

**Comment by LW-CVer** [comment]
the latest tf2onnx works successfully,but the onnx contains "Switch" op that the onnx converted with 1.5.6 version don't contain.
when converting onnx to trt，the “Switch” op is not supported

**Comment by TomWildenhain-Microsoft** [comment]
@LW-CVer can you upload a zip of the model?

**Comment by LW-CVer** [comment]
pb file？

**Comment by TomWildenhain-Microsoft** [comment]
That works too.  Either a zipped saved model or a .pb frozen model

**Comment by LW-CVer** [comment]
@TomWildenhain-Microsoft email？

**Comment by TomWildenhain-Microsoft** [comment]
@LW-CVer 

![image](https://user-images.githubusercontent.com/67606533/122100806-94a35580-cde1-11eb-8e42-b1b1405493eb.png)

**Comment by fatcat-z** [comment]
No response from user yet, close it.
