### ISSUE TITLE
Model Inference error converted by tf2onnx==1.8.5, but 1.8.4 works fine

### ISSUE THREAD

**Issue by iperov** [onnx/tensorflow-onnx#1545]
**Describe the bug**

Model Inference error converted by tf2onnx==1.8.5

```
2021-06-01 15:40:11.1895016 [E:onnxruntime:, sequential_executor.cc:339 onnxruntime::SequentialExecutor::Execute] 
Non-zero status code returned while running Conv node. 
Name:'Conv2D_62' Status Message: Input channels C is not equal to kernel channels * group. 
C: 1024 kernel channels: 1024 group: 0
```

but 1.8.4 works fine

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- Tensorflow Version: 2.4.0 with compat.v1
- Python version: 3.6.8

**To Reproduce**

download model from https://github.com/iperov/DeepFaceLive/releases/download/trash/model.pb

convert to onnx
```python -m tf2onnx.convert --opset 13 --graphdef model.pb --output model.onnx --inputs in_face:0,morph_value:0 --outputs out_face_mask:0,out_celeb_face:0,out_celeb_face_mask:0```

inference using inputs:
`in_face:0` - image float32 of shape (1,224,224,3)
`morph_value:0` - single float32 of shape (1,) = 0.5

**Comment by TomWildenhain-Microsoft** [comment]
Oops, group is not assigned properly if the dims are unknown.  This should fix it: #1552
