### ISSUE TITLE
 BackendIsNotSupposedToImplementIt: Squeeze version 13 is not implemented.

### ISSUE THREAD

**Issue by opconty** [onnx/tensorflow-onnx#1549]
Hi, I've converted pytorch model to onnx with `torch.onnx.export(opset_version=13)`,.and `onnx.checker.check_model`  has no error,  besides, I can still get the right result with `onnxruntime`, but when I tried to inference with onnx_tf it failed :

> raise BackendIsNotSupposedToImplementIt("{} version {} is not implemented.".format(node.op_type, cls.SINCE_VERSION))
> 
>     BackendIsNotSupposedToImplementIt: Squeeze version 13 is not implemented.

bellow is my version info:

Python version:
3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
ONNX version:
1.8.0
ONNX-TF version:
1.8.0
Tensorflow version:
2.4.1

Thanks.

**Comment by guschmue** [comment]
onnx-tf issues go here:
https://github.com/onnx/onnx-tensorflow/issues
