### ISSUE TITLE
ERROR - Unsupported ops: Counter({'DenseToDenseSetOperation': 2}) 

### ISSUE THREAD

**Issue by iotnikhil** [onnx/tensorflow-onnx#1555]
Hello, I am getting this error when I try to convert **matterport/Mask_RCNN**  MaskRCNN saved_model.pb. I am using the latest commit where Graph Deepcopy issue is fixed. [https://github.com/onnx/tensorflow-onnx/pull/972] 

My Saved_model = [https://drive.google.com/file/d/1uN7zi36jl4NaD3oVi1R95bl2oeROfC62/view?usp=sharing] url(saved_model.pb)

command : python -m tf2onnx.convert --saved-model saved_model --opset 11 --output nail.onnx

ERROR - Tensorflow op [mrcnn_detection/DenseToDenseSetOperation: DenseToDenseSetOperation] is not supported
ERROR - Tensorflow op [mrcnn_detection/DenseToDenseSetOperation_1: DenseToDenseSetOperation] is not supported
ERROR - Unsupported ops: Counter({'DenseToDenseSetOperation': 2})

stuck from a week , help will be appreciated , Thanks in advance :)

**Comment by TomWildenhain-Microsoft** [comment]
#1556 should fix your issue.  Let me know if it works.

**Comment by iotnikhil** [comment]
Hello, Thank you for your response . 
Sorry for the late reply.

I used tom/set_ops commit, but it still throwing me the same error.

**Comment by TomWildenhain-Microsoft** [comment]
> Hello, Thank you for your response .
> Sorry for the late reply.
> 
> I used tom/set_ops commit, but it still throwing me the same error.

It's merged so use master and make sure it is the latest version.  Also you need opset 11.

**Comment by iotnikhil** [comment]
Hi, I tried with opset 11 and it worked for me . Thank you.

**Comment by TomWildenhain-Microsoft** [comment]
Awesome, glad the fix worked!  Also @iotnikhil I'm doing an informal survey of tf2onnx use cases: what is your primary motivation for using tf2onnx, and do you plan on running your model on CPU or GPU (or both)?

**Comment by iotnikhil** [comment]
Hi @TomWildenhain-Microsoft , my primary motivation is to run Onnx model in Unity environment which usually runs on mobile/tablet devices.
