### ISSUE TITLE
using tf2onnx convert *.pb file to two onnx with different outputs, get different convolution weights

### ISSUE THREAD

**Issue by swordcheng** [onnx/tensorflow-onnx#1575]
Hello

When I use tf2onnx to convert one *.pb to two *.onnx with different outputs, I find the weights of the last convolutional layer (name: conv6/Conv2D) of the two onnx are different.

Why?

this is [pb file](https://drive.google.com/file/d/1y1RLJPtBF_wJI2gURfyp0b7INO21-GCL/view?usp=sharing)

this is one [converted onnx](https://drive.google.com/file/d/1aSJEhzMjhGrJaCbK_KRP2TxvWFxOqEJC/view?usp=sharing), 
convert commad is:  `python -m tf2onnx.convert --input ./model.pb --inputs input:0 --outputs dense_feat_map:0,score_vol_3:0 --output ./model-1.onnx `

this is other [converted onnx](https://drive.google.com/file/d/1vdMGI8qj4Re0Bh0VxEmP5JNqESC_tMzX/view?usp=sharing), 
convert commad is: `python -m tf2onnx.convert --input ./model.pb --inputs input:0 --outputs dense_feat_map:0 --output ./model-2.onnx `

**Comment by guschmue** [comment]
You mean the weight conv6/kernel/read:0 ? I compared them in netron and they look the same.
Of course for model-2.onnx we'll remove a bunch of nodes after the last conv since they are not used.

**Comment by TomWildenhain-Microsoft** [comment]
tf2onnx is trying to fuse the Conv and ReadDiv ops into a single op by changing the weights of the conv:

![image](https://user-images.githubusercontent.com/67606533/122422513-34382380-cf5b-11eb-9827-c6f5e6e016da.png)

However the Conv itself is an output so the fusion needs to be skipped.  The latest version of tf2onnx from GitHub solves the issue:
`pip uninstall tf2onnx`
`pip install git+https://github.com/onnx/tensorflow-onnx`

Using the latest tf2onnx, the weights remain unchanged with `--outputs dense_feat_map:0,score_vol_3:0` and `--outputs dense_feat_map:0`, but they are correctly fused when `--outputs score_vol_3:0` is the only output.

**Comment by guschmue** [comment]
Ah you are using tf2onnx 1.6.1. Its fairly old. Do a ```pip install tf2onnx -U```.

**Comment by swordcheng** [comment]
Thank you!!!
