### ISSUE TITLE
No Op registered for TFL_RFFT2D with domain_version of 13

### ISSUE THREAD

**Issue by xadupre** [onnx/tensorflow-onnx#1586]
**Describe the bug**
Conversion succeeded but onnxruntime fails because:

```
No Op registered for TFL_RFFT2D with domain_version of 13
```

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Tensorflow Version: 2.5
- Python version: 3.9

**To Reproduce**

Model [yamnet](https://tfhub.dev/google/coral-model/yamnet/classification/coral/1)
Command line:

```
python -m tf2onnx.convert --tflite "model.tflite" --output "yamnet-13.onnx" --opset 13
```

**Comment by TomWildenhain-Microsoft** [comment]
This edge-tpu-custom-op will be more problematic:
![image](https://user-images.githubusercontent.com/67606533/124029689-3f9f3c00-d9aa-11eb-97de-c6c1347017f9.png)

**Comment by guschmue** [comment]
yes, this is not going to work - its a device specific graph. 
If I understand this correctly, that op is the entry into the coral and the attribute has the instructions that coral will handle.

**Comment by TomWildenhain-Microsoft** [comment]
The model links to a non-coral version: https://tfhub.dev/google/yamnet/1
This one should work if we add RFFT2D.  Unfortunately only the 1D version is implemented.  @xadupre any chance you can do the 2D version?  You should be able to use TF's RFFT2D for testing and it should be pretty easy to bridge it to tflite.  We can assume it is followed by complexabs.

**Comment by xadupre** [comment]
I'll see what I can do.

**Comment by xadupre** [comment]
Closing it as FFT2D was added.
