### ISSUE TITLE
Add conversion from tf.image.resize_nearest_neigbor to onnx.Upsample

### ISSUE THREAD

**Issue by achernigin1987** [onnx/tensorflow-onnx#16]
Currently, there is no ResizeNearestNeigbor operation in ONXX, but there is [Upsample ](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Upsample) operation that does exactly the same. Could you please add such mapping to convertor?

**Comment by guschmue** [comment]
I think this might work but requires Shape() which came in with opset 5 or 6

**Comment by achernigin1987** [comment]
what is opset ? I beleive it should not be a problem

**Comment by guschmue** [comment]
opset ~ version of the ops ... 
I checked in some fix but I could not test it ... none of the runtimes I have implements this.
