### ISSUE TITLE
Onnx runtime failed to run an exported keras model with Split operator in float64

### ISSUE THREAD

**Issue by hotohoto** [onnx/tensorflow-onnx#1613]
**Describe the bug**
- made an ONNX model using tf2onnx.convert.from_keras()
- when the default type for Keras backend was set as float32 the saved model looked working as expected.  (`32.onnx`)
- when the default type for Keras backend was set as float64 the saved model looked not working. (`64.onnx`)
  - The error message was like the following.

```
---------------------------------------------------------------------------
Fail                                      Traceback (most recent call last)
<ipython-input-23-64698e6a1864> in <module>
      2 import onnxruntime as ort
      3 
----> 4 ort_session = ort.InferenceSession("64.onnx")
      5 
      6 outputs = ort_session.run(

~/.pyenv/versions/3.6.10/envs/onnx/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py in __init__(self, path_or_bytes, sess_options, providers, provider_options, **kwargs)
    281 
    282         try:
--> 283             self._create_inference_session(providers, provider_options, disabled_optimizers)
    284         except ValueError:
    285             if self._enable_fallback:

~/.pyenv/versions/3.6.10/envs/onnx/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py in _create_inference_session(self, providers, provider_options, disabled_optimizers)
    319 
    320         # initialize the C++ InferenceSession
--> 321         sess.initialize_session(providers, provider_options, disabled_optimizers)
    322 
    323         self._sess = sess

Fail: [ONNXRuntimeError] : 1 : FAIL : The node is not placed on any Execution Provider. Split(13) (node sequential_1/sequential/gru_0/while/gru_cell/split_1). 

```

**Urgency**
None for now.

**System information**
- Ubuntu 20.04
- Tensorflow Version: 2.3.0
- Python version:  3.6.13

**To Reproduce**
Describe steps/code to reproduce the behavior. Please upload/link the model you are trying to convert if possible.

It's not possible right now to upload the code but it was a Keras GRU model.

[onnx_models.zip](https://github.com/onnx/tensorflow-onnx/files/6808630/onnx_models.zip)

(test code)
```py
import numpy as np
import onnxruntime as ort

ort_session = ort.InferenceSession("64.onnx")

outputs = ort_session.run(
    None,
    {
        "['y_T+1', 'y_T+2']_(139998053519144)": np.array([[1.0, 2.0, 3.0, 4.0, 5.0, 6.0]], dtype=np.float32),  # 64.onnx
        #  "['y_T+1', 'y_T+2']_(140130087505648)": np.array([[1.0, 2.0, 3.0, 4.0, 5.0, 6.0]], dtype=np.float32),  # 32.onnx
    },
)
outputs[0][0]
```

**Screenshots**

(`64.onnx` - not working)
![image](https://user-images.githubusercontent.com/5404902/125448937-f397fe01-02b0-48f7-a363-8961c35885b7.png)
![image](https://user-images.githubusercontent.com/5404902/125448956-956a0a69-e991-4767-903e-624fac56f3af.png)
![image](https://user-images.githubusercontent.com/5404902/125448983-46e8a5db-7dc4-4c68-881b-3e612cf34e28.png)

(`32.onnx` - equivalent but working)

![image](https://user-images.githubusercontent.com/5404902/125448765-bf7451bf-5f5f-4194-b6ca-4f13a755523d.png)
![image](https://user-images.githubusercontent.com/5404902/125448860-5cafc848-5b92-4b33-b04d-5cc3e048ded9.png)
![image](https://user-images.githubusercontent.com/5404902/125448910-740ab8e3-ffe7-44d1-b410-c298e19bcd32.png)

**Additional context**
n/a

**Comment by guschmue** [comment]
Looks that onnxruntime does not implement float64 for split:
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/tensor/split.cc#L17https://github.com/

onnx itself supports it:
onnx/onnx/blob/master/docs/Operators.md#Split

I think you should open a bug against onnxruntime.

**Comment by guschmue** [comment]
closing this one since it is a onnxruntime issue.
