### ISSUE TITLE
ReverseV2 converted incorrectly

### ISSUE THREAD

**Issue by TomWildenhain-Microsoft** [onnx/tensorflow-onnx#1635]
https://github.com/microsoft/onnxruntime/issues/8504

**Comment by TomWildenhain-Microsoft** [comment]
@xjw00654 let me know if this is still an issue for you.

**Comment by Red-Eyed** [comment]
Yes, [here it is](https://1drv.ms/u/s!AvbfOiXsgf39g81XCwb0_IF3jRTiEA?e=TJl9LS)

**Comment by TomWildenhain-Microsoft** [comment]
@Red-Eyed thanks for the example model.  #1691 should resolve this issue.

**Comment by Red-Eyed** [comment]
> @Red-Eyed thanks for the example model. #1691 should resolve this issue.

Thank you!
