### ISSUE TITLE
Input disconnect from graph

### ISSUE THREAD

**Issue by Source82** [onnx/tensorflow-onnx#1643]
Hi,

Please what can be wrong. My converted onnx file has input that is disconnected from rest of the graph.

![Capture](https://user-images.githubusercontent.com/12441907/128182056-05a656da-0589-484b-9101-e3b3b3fc6615.JPG)

Thanks

**Comment by TomWildenhain-Microsoft** [comment]
Did you try running the model?  I know it looks strange but this is actually expected if the loop uses the input in the body graph.  Onnx subgraphs get access to nodes in the main graph even if they are not provided as inputs to the loop node.  You can view subgraphs in netron by clicking the input node and selecting from the drop-down.

**Comment by Source82** [comment]
Hi @TomWildenhain-Microsoft 
Thanks, my main aim is to eventually convert the onnx model to tensorrt. It seems trtexec just doesn't like it this way.
Again I am a bit surprised that the initial model I finetuned doesn't have that issue when I convert it to onnx.
Literally I just took an ssd model off Tensorflow garden and fine tuned it on my custom dataset. Then eported it and converted it.

**Comment by TomWildenhain-Microsoft** [comment]
@Source82 can you try running the model on onnxruntime to see if it produces correct results?  TensorRT can be a bit finicky.

**Comment by Source82** [comment]
Thanks I will do just that. From my initial check onnxruntime seems to read it fine

**Comment by fatcat-z** [comment]
No response from user yet, close it.

**Comment by Zrufy** [comment]
i have the same situation and i don't know how to solve it!
