### ISSUE TITLE
int64 -> string CategoryMapper support

### ISSUE THREAD

**Issue by rmarrugat** [onnx/tensorflow-onnx#1655]
**Describe the bug**
As the title suggests, offer support for int64 -> string CategoryMapper additionally to the current string -> int64 implementation.
This is supported by onnx as explained in [Operators-ml documentation](https://github.com/onnx/onnx/blob/master/docs/Operators-ml.md#ai.onnx.ml.CategoryMapper) as long as one of the types is used as input and the other as output.

**Urgency**
In my case it is pretty useful when dealing with String I/O models. As an example, a transformer model which outputs a sequence of labels.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Tensorflow Version: 2.5
- Python version: 3.7

**To Reproduce**
Create a simple tensorflow model which includes:
```python
vec = ['A', 'B', 'C']
tf.lookup.StaticHashTable(tf.lookup.KeyValueTensorInitializer(tf.convert_to_tensor(tf.range(len(vec), dtype=tf.int64)), tf.convert_to_tensor(vec)), 'D')
```
Then convert the model as:
```
python -m tf2onnx.convert --saved-model model --output model.onnx --opset 13
```

**Additional context**
I managed to get this working in my fork and ran the model successfully.
I made the following changes:
- `tf2onnx/custom_opsets/onnx_ml.py:45`
```python
utils.make_sure((dtype == TensorProto.INT64 and in_dtype == TensorProto.STRING or \
                         dtype == TensorProto.STRING and in_dtype == TensorProto.INT64),
                        "Only lookup tables of type string->int64 or int64->string are currently supported.")
```

- `tf2onnx/custom_opsets/onnx_ml.py:48`
```python
        if in_dtype == TensorProto.STRING:
            cats_strings, cats_int64s = initialized_tables[shared_name]
            attr = {'cats_int64s': cats_int64s, 'cats_strings': cats_strings, 'default_int64': default_val}
        else:
            cats_int64s, cats_strings = initialized_tables[shared_name]
            attr = {'cats_int64s': cats_int64s, 'cats_strings': cats_strings, 'default_string': default_val}
```

- `tf2onnx/custom_opsets/onnx_ml.py:64`
```python
            ctx.make_node("CategoryMapper", domain=constants.AI_ONNX_ML_DOMAIN,
                          name=node_name, inputs=[node_inputs[1]], outputs=node_outputs,
                          attr=attr,
                          shapes=[shape], dtypes=[dtype])
```

**Comment by TomWildenhain-Microsoft** [comment]
Hi @rmarrugat thanks for the detailed example.  Would you be able to submit a pull request with your changes?

**Comment by TomWildenhain-Microsoft** [comment]
@rmarrugat did you have a chance to look at the feedback on your PR?  I would love to get that merged.

**Comment by rmarrugat** [comment]
Yeah, sorry for my delay. I was trying to get the Seq2Seq model to work and I set the PR aside. I will try to update it ASAP.

**Comment by rmarrugat** [comment]
Yeah, sorry for my delay. I was trying to get the conversion of the Seq2Seq model to work and I set the PR aside. I will try to update it ASAP.

**Comment by fatcat-z** [comment]
No response from user yet, close it.
