### ISSUE TITLE
ValueError: slice index 1 of dimension 0 out of bounds. for 'ROI/strided_slice_8' (op: 'StridedSlice') with input shapes: [1,57567,4], [1], [1], [1] and with computed input tensors: input[1] = <1>, input[2] = <2>, input[3] = <1>.

### ISSUE THREAD

**Issue by pra-dan** [onnx/tensorflow-onnx#1656]
I am trying to optimise my Mask-RCNN model trained on`coco` weights and uses ResNet50 as backbone. I had the `h5` weights, along which I obtained the frozen graph (`pb` file) during training. 

Next, I converted this pb file to onnx format using `tf2onnx` as follows:
```console
!python -m tf2onnx.convert --input '/content/resnet50-coco-epoch1.pb' --inputs input_image:0 --outputs mrcnn_class/Reshape:0 --output resnet50-coco-epoch1.onnx --opset 20
```
On exploring this converted onnx model in Netron, I noticed that the input layer 
 I was able to do so when I did not mention the input layer dimensions data. When I went back and check the used `pb` file, I noticed the info to be missing there too. But luckily `tf2onnx` didn't throw any error. 
<img width="817" alt="Screenshot 2021-08-09 at 11 12 48 PM" src="https://user-images.githubusercontent.com/46529961/128749952-ad96c5e1-4128-4db9-a807-01c86a0e5084.png">

(notice how the input layer is missing from the input layer in .pb frozen graph)

I came across [this issue](https://github.com/onnx/tensorflow-onnx/issues/651#issuecomment-514867634) where @zhijxu-MS suggested adding this info in the input arguments. So, I tried the conversion again , this time, as
```console
!python -m tf2onnx.convert --input '/content/resnet50-coco-epoch1.pb' --inputs input_image:0[1,480,480,3] --outputs mrcnn_class/Reshape:0 --output resnet50-coco-epoch1.onnx --opset 20
```

But to this, I get the following error + log
```console
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2021-08-09 13:26:13,300 - WARNING - From /usr/local/lib/python3.7/dist-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2021-08-09 13:26:18,857 - INFO - Using tensorflow=1.15.0, onnx=1.10.1, tf2onnx=1.8.2/05babf
2021-08-09 13:26:18,857 - INFO - Using opset <onnx, 20>
2021-08-09 13:26:18,857 - WARNING - Currently installed onnx package 1.10.1 is too low to support opset 20, please upgrade onnx package to avoid potential conversion issue.
2021-08-09 13:26:18,857 - INFO - Apply shape override:
2021-08-09 13:26:18,857 - INFO - 	Set input_image:0 shape to [1, 480, 480, 3]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 1 of dimension 0 out of bounds. for 'ROI/strided_slice_8' (op: 'StridedSlice') with input shapes: [1,57567,4], [1], [1], [1] and with computed input tensors: input[1] = <1>, input[2] = <2>, input[3] = <1>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/convert.py", line 221, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/convert.py", line 199, in main
    tflite_path=tflite_path)
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/tfonnx.py", line 450, in process_tf_graph
    tf_graph = infer_shape(tf_graph, shape_override)
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/shape_inference.py", line 32, in infer_shape
    tf_graph = tf_reload_graph(tf_graph)
  File "/usr/local/lib/python3.7/dist-packages/tf2onnx/tf_loader.py", line 560, in tf_reload_graph
    tf.import_graph_def(graph_def, name="")
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/framework/importer.py", line 505, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: slice index 1 of dimension 0 out of bounds. for 'ROI/strided_slice_8' (op: 'StridedSlice') with input shapes: [1,57567,4], [1], [1], [1] and with computed input tensors: input[1] = <1>, input[2] = <2>, input[3] = <1>.
```

**Urgency**
The TensorRT team has been breaking TensorRT based applications (especially related to Mask-RCNN) frequently now; they are forcing people to switch to onnx parser from of the uff parser. This new method is not documented well and is creating long delay in our projects. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04 
- Tensorflow Version: 1.15
- ONNX version: 1.10.1
- Python version: 3.9

**To Reproduce**
I am providing a Google Collaboratory notebook for reproduction : [HERE](https://colab.research.google.com/drive/1buSdXZnLuM6IvxJXuS3xPhLM9NYC_rSb?usp=sharing)
The model used (frozen graph/pb) is [HERE](https://www.dropbox.com/s/gwl993ia6wt5op5/resnet50-coco-epoch1.pb?dl=0)

**Additional context**
I am trying to use the onnx model to generate a TensorRT engine (`.plan` file). For this I do
```python3
import engine as eng
from onnx import ModelProto
import tensorrt as trt


engine_name = 'semantic.plan'
onnx_path = "resnet50-coco-epoch1.onnx"
batch_size = 1

model = ModelProto()
with open(onnx_path, "rb") as f:
  model.ParseFromString(f.read())

d0 = model.graph.input[0].type.tensor_type.shape.dim[1].dim_value
d1 = model.graph.input[0].type.tensor_type.shape.dim[2].dim_value
d2 = model.graph.input[0].type.tensor_type.shape.dim[3].dim_value
```

But I get error when I try to read the `dim_value` in the last 3 lines. as the dimensions are absent. 
```console
>>> model.graph.input
[name: "input_image_meta:0"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_param: "unk__3457"
      }
      dim {
        dim_value: 16
      }
    }
  }
}
, name: "input_image:0"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_param: "unk__3458"
      }
      dim {
        dim_param: "unk__3459"
      }
      dim {
        dim_param: "unk__3460"
      }
      dim {
        dim_value: 3
      }
    }
  }
}
, name: "input_gt_class_ids:0"
type {
  tensor_type {
    elem_type: 6
    shape {
      dim {
        dim_param: "unk__3461"
      }
      dim {
        dim_param: "unk__3462"
      }
    }
  }
}
, name: "input_gt_boxes:0"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_param: "unk__3463"
      }
      dim {
        dim_param: "unk__3464"
      }
      dim {
        dim_value: 4
      }
    }
  }
}
]

```

**Comment by TomWildenhain-Microsoft** [comment]
A few things here: opset 20 doesn't exist yet so you should use `--opset 14`.  I'm surprised you would actually get a model with that since it should raise an exception.

When I convert your graph I get some errors:
```
2021-08-09 16:49:54,115 - ERROR - Tensorflow op [proposal_targets/RandomShuffle_3: RandomShuffle] is not supported
2021-08-09 16:49:54,120 - ERROR - Tensorflow op [proposal_targets/RandomShuffle_2: RandomShuffle] is not supported
2021-08-09 16:49:54,211 - ERROR - Tensorflow op [proposal_targets/RandomShuffle_1: RandomShuffle] is not supported
2021-08-09 16:49:54,217 - ERROR - Tensorflow op [proposal_targets/RandomShuffle: RandomShuffle] is not supported
2021-08-09 16:49:58,367 - ERROR - Unsupported ops: Counter({'RandomShuffle': 4})
```

The graph contains the `RandomShuffle` op which we can't convert.  I'm working on a conversion now.

Once there errors are resolved, I'll be able to convert and run the model and see when is causing the issue when setting the shape.  The error from TF suggests you are setting the shape to something incompatible with the original model.

**Comment by guschmue** [comment]
I think we'd just fall back to the newest op we can find but would write opset-20 into the onnx file and onnxrutime would bark on us. We should maybe check but never did.

**Comment by TomWildenhain-Microsoft** [comment]
Yeah that's what we used to do but we now raise an exception, or should:

https://github.com/onnx/tensorflow-onnx/blob/becdcba538338741a93129574c64a33e7e18c8a9/tf2onnx/graph.py#L1204

**Comment by TomWildenhain-Microsoft** [comment]
Actually I just tried setting the shape like you did and ran into the same error.  That error is coming from *tensorflow* not us, and it looks like your model has an op that slices along the batch dimension with starting index of 1.  I ran the model on some test data:

```python
import tensorflow as tf
import numpy as np

img = np.zeros([1, 480, 480, 3], np.float32)

input = {
    "input_image:0": img,
    "input_image_meta:0": np.zeros([1, 16], np.float32),
    "input_gt_class_ids:0": np.zeros([1, 16], np.float32),
    "input_gt_boxes:0": np.zeros([1, 10, 4], np.float32),
}

with tf.compat.v1.Session() as sess:
    graph_def = tf.compat.v1.GraphDef()
    with open(r"C:\Users\tomwi\Downloads\resnet50-coco-epoch1.pb", "rb") as f:
        graph_def.ParseFromString(f.read())
    tf.import_graph_def(graph_def, name='')
    print(sess.run("mrcnn_class/Reshape:0", input))
```
And I got this error:
`2021-08-09 17:27:49.059868: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index 1 of dimension 0 out of bounds.`

It appears that your model will not run with a batch dimension of 1.  But on a batch dimension of 2 I was able to run the model and get results.

Similarly I was able to convert your model with `--inputs input_image:0[2,480,480,3]`

**Comment by TomWildenhain-Microsoft** [comment]
#1658 RandomShuffle

**Comment by pra-dan** [comment]
> Similarly I was able to convert your model with `--inputs input_image:0[2,480,480,3]`

I tried with the new batch size of 2, just like you and still got:
```console
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2021-08-11 04:04:34,335 - WARNING - From /usr/local/lib/python3.7/dist-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2021-08-11 04:04:39,420 - INFO - Using tensorflow=1.15.0, onnx=1.10.1, tf2onnx=1.8.2/05babf
2021-08-11 04:04:39,420 - INFO - Using opset <onnx, 12>
2021-08-11 04:04:39,421 - INFO - Apply shape override:
2021-08-11 04:04:39,421 - INFO - 	Set input_image:0 shape to [2, 480, 480, 3]
2021-08-11 04:04:46,418 - INFO - Computed 10 values for constant folding
2021-08-11 04:04:56,575 - INFO - folding node using tf type=Pack, name=rpn_model_3/lambda_2/Reshape/shape
2021-08-11 04:04:56,575 - INFO - folding node using tf type=Pack, name=rpn_model_3/lambda_3/Reshape/shape
2021-08-11 04:04:56,576 - INFO - folding node using tf type=Pack, name=rpn_model_4/lambda_2/Reshape/shape
2021-08-11 04:04:56,576 - INFO - folding node using tf type=Pack, name=rpn_model_4/lambda_3/Reshape/shape
2021-08-11 04:04:56,576 - INFO - folding node using tf type=Pack, name=rpn_model_2/lambda_2/Reshape/shape
2021-08-11 04:04:56,576 - INFO - folding node using tf type=Pack, name=rpn_model_2/lambda_3/Reshape/shape
2021-08-11 04:04:56,576 - INFO - folding node using tf type=Pack, name=rpn_model_1/lambda_2/Reshape/shape
2021-08-11 04:04:56,576 - INFO - folding node using tf type=Pack, name=rpn_model_1/lambda_3/Reshape/shape
2021-08-11 04:04:56,577 - INFO - folding node using tf type=Pack, name=rpn_model/lambda_2/Reshape/shape
2021-08-11 04:04:56,577 - INFO - folding node using tf type=Pack, name=rpn_model/lambda_3/Reshape/shape
2021-08-11 04:04:57,487 - ERROR - Tensorflow op [proposal_targets/RandomShuffle_3: RandomShuffle] is not supported
2021-08-11 04:04:57,488 - ERROR - Tensorflow op [proposal_targets/RandomShuffle_2: RandomShuffle] is not supported
2021-08-11 04:04:57,507 - ERROR - Tensorflow op [proposal_targets/RandomShuffle_1: RandomShuffle] is not supported
2021-08-11 04:04:57,508 - ERROR - Tensorflow op [proposal_targets/RandomShuffle: RandomShuffle] is not supported
2021-08-11 04:04:58,487 - ERROR - Unsupported ops: Counter({'RandomShuffle': 4})
2021-08-11 04:04:58,569 - INFO - Optimizing ONNX model
2021-08-11 04:05:04,625 - INFO - After optimization: Add -1 (102->101), Cast -69 (142->73), Concat -2 (65->63), Const -884 (1252->368), Gather +3 (24->27), Identity -11 (15->4), NonZero -2 (18->16), Reshape +1 (50->51), Shape -25 (55->30), Slice -18 (148->130), Squeeze -26 (104->78), Transpose -167 (211->44), Unsqueeze -39 (85->46)
2021-08-11 04:05:04,687 - INFO - 
2021-08-11 04:05:04,687 - INFO - Successfully converted TensorFlow model /content/resnet50-coco-epoch1.pb to ONNX
2021-08-11 04:05:04,887 - INFO - ONNX model is saved at resnet50-coco-epoch1.onnx
```

Did you encounter this ?

**Comment by pra-dan** [comment]
Also, I suppose the `RandomShuffle` op is inherent in all ResNet architectures (50, 101, etc) and the parser will probably fail in all of them. Thanks for the efforts btw.

**Comment by TomWildenhain-Microsoft** [comment]
Please try again with the latest tf2onnx from master.

`pip uninstall tf2onnx`
`pip install git+https://github.com/onnx/tensorflow-onnx`

**Comment by pra-dan** [comment]
It resolves the issue perfectly, so closing the issue. Thanks Tom.

---

Btw, while converting the onnx model into a TensorRT engine, I get the the error
```console
>>> engine = eng.build_engine(onnx_path, shape= shape)
[TensorRT] ERROR: Parameter check failed at: ../builder/Network.cpp::addInput::671, condition: isValidDims(dims, hasImplicitBatchDimension())
[TensorRT] ERROR: Network must have at least one output
```

On observing the onnx model's output using Netron, I notice that the output layer has incomplete dims 

<img width="953" alt="Screenshot 2021-08-14 at 2 44 16 PM" src="https://user-images.githubusercontent.com/46529961/129441166-fa4dd4b7-eac1-45db-bf4a-f35ea4b9651e.png">

Can you suggest what this might mean ? I think I need to to specify the output layer dims during the conversion. But can't figure out what the dimensions should be. The 4 (in the layer dims in the pic), represent my 4 classes used to train.

**Comment by TomWildenhain-Microsoft** [comment]
If Tensor-RT fails to load the model, test it in onnxruntime to make sure it converted correctly.  As for the unknown output dimensions, they might come from unknown input dimensions.  In your image, the input dims of input_image:0 are fixed, but there are unknown dims in the other 3 inputs.  In most cases, the output dims should become fixed if all the input dims are fixed.

**Comment by pra-dan** [comment]
> If Tensor-RT fails to load the model, test it in onnxruntime to make sure it converted correctly. As for the unknown output dimensions, they might come from unknown input dimensions. In your image, the input dims of input_image:0 are fixed, but there are unknown dims in the other 3 inputs. In most cases, the output dims should become fixed if all the input dims are fixed.

That's a problem in itself: to figure out what the other 3 input dims should be. Is there any way to find this ?

**Comment by TomWildenhain-Microsoft** [comment]
What do those inputs represent?  What does the model do?

**Comment by pra-dan** [comment]
> What do those inputs represent? What does the model do?

The model is a Mask-RCNN model that returns segmentation mask for the classes of images its trained for( 4 in my case). 

To investigate on the inputs/outputs, I went through the model definition (defined in [model.py]()) and in this,

'''python3

        # Inputs
        input_image = KL.Input(
            shape=[None, None, config.IMAGE_SHAPE[2]], name="input_image")
        input_image_meta = KL.Input(shape=[config.IMAGE_META_SIZE],
                                    name="input_image_meta")
        if mode == "training":
            # RPN GT
            input_rpn_match = KL.Input(
                shape=[None, 1], name="input_rpn_match", dtype=tf.int32)
            input_rpn_bbox = KL.Input(
                shape=[None, 4], name="input_rpn_bbox", dtype=tf.float32)

            # Detection GT (class IDs, bounding boxes, and masks)
            # 1. GT Class IDs (zero padded)
            input_gt_class_ids = KL.Input(
                shape=[None], name="input_gt_class_ids", dtype=tf.int32)
            # 2. GT Boxes in pixels (zero padded)
            # [batch, MAX_GT_INSTANCES, (y1, x1, y2, x2)] in image coordinates
            input_gt_boxes = KL.Input(
                shape=[None, 4], name="input_gt_boxes", dtype=tf.float32)
            # Normalize coordinates
            gt_boxes = KL.Lambda(lambda x: norm_boxes_graph(
                x, K.shape(input_image)[1:3]))(input_gt_boxes)
            # 3. GT Masks (zero padded)
            # [batch, height, width, MAX_GT_INSTANCES]
            if config.USE_MINI_MASK:
                input_gt_masks = KL.Input(
                    shape=[config.MINI_MASK_SHAPE[0],
                           config.MINI_MASK_SHAPE[1], None],
                    name="input_gt_masks", dtype=bool)
            else:
                input_gt_masks = KL.Input(
                    shape=[config.IMAGE_SHAPE[0], config.IMAGE_SHAPE[1], None],
                    name="input_gt_masks", dtype=bool)
        elif mode == "inference":
            # Anchors in normalized coordinates
            input_anchors = KL.Input(shape=[None, 4], name="input_anchors")

#..... #Some more code

# Model for training
inputs = [input_image, input_image_meta,
          input_rpn_match, input_rpn_bbox, input_gt_class_ids, input_gt_boxes, input_gt_masks]
if not config.USE_RPN_ROIS:
    inputs.append(input_rois)
outputs = [rpn_class_logits, rpn_class, rpn_bbox,
           mrcnn_class_logits, mrcnn_class, mrcnn_bbox, mrcnn_mask,
           rpn_rois, output_rois,
           rpn_class_loss, rpn_bbox_loss, class_loss, bbox_loss, mask_loss]
model = KM.Model(inputs, outputs, name='mask_rcnn')

# Model for inference
mrcnn_mask = build_fpn_mask_graph(detection_boxes, mrcnn_feature_maps,
                                        input_image_meta,
                                        config.MASK_POOL_SIZE,
                                        config.NUM_CLASSES,
                                        train_bn=config.TRAIN_BN)

model = KM.Model([input_image, input_image_meta, input_anchors], #inputs
                 [detections, mrcnn_class, mrcnn_bbox,           #outputs
                     mrcnn_mask, rpn_rois, rpn_class, rpn_bbox],
                 name='mask_rcnn')
```

I could make out the following:
inputs | description | type |
|--|-|-|
input_image | f | float32[2,480,480,3]
input_image_meta | size= 1 + 3 + 3 + 4 + 1 + NUM_CLASSES | float32[unk__2466,16]
input_gt_class_ids | only needed during training | int32[unk__2467,unk__2468]
input_gt_boxes | only needed during training | float32[unk__2469,unk__2470,4]

whereas the outputs are not found (as the should be) in the ONNX file. This maybe because I am obtaining the frozen graph during training by modifying the weights saving part within `model.py`.

'''console
+    def freeze_session(self, session, keep_var_names=None, output_names=None, clear_devices=True):
+        """
+        Freezes the state of a session into a pruned computation graph.
+
+        Creates a new computation graph where variable nodes are replaced by
+        constants taking their current value in the session. The new graph will be
+        pruned so subgraphs that are not necessary to compute the requested
+        outputs are removed.
+        @param session The TensorFlow session to be frozen.
+        @param keep_var_names A list of variable names that should not be frozen,
+                              or None to freeze all the variables in the graph.
+        @param output_names Names of the relevant graph outputs.
+        @param clear_devices Remove the device directives from the graph for better portability.
+        @return The frozen graph definition.
+        """
+        graph = session.graph
+        with graph.as_default():
+            freeze_var_names = list(set(v.op.name for v in tf.global_variables()).difference(keep_var_names or []))
+            output_names = output_names or []
+            output_names += [v.op.name for v in tf.global_variables()]
+            input_graph_def = graph.as_graph_def()
+            if clear_devices:
+                for node in input_graph_def.node:
+                    node.device = ""
+            frozen_graph = tf.graph_util.convert_variables_to_constants(
+                session, input_graph_def, output_names, freeze_var_names)
+            return frozen_graph
+
     def train(self, train_dataset, val_dataset, learning_rate, epochs, layers,
               augmentation=None, custom_callbacks=None, no_augmentation_sources=None):
         """Train the model.
@@ -2373,6 +2401,12 @@ class MaskRCNN():
             workers=workers,
             use_multiprocessing=True,
         )
+        #######using session and saving .pb file##
+        frozen_graph = self.freeze_session(K.get_session(),
+                              output_names=[out.op.name for out in self.keras_model.outputs])
+        print('\n\n\t\t******* Writing Frozen Graph in logs directory *******\n\n')
+        tf.train.write_graph(frozen_graph, self.log_dir, "my_model.pb", as_text=False)
+
         self.epoch = max(self.epoch, epochs)

```

I had to do this because all Mask-RCNN saves weights as `h5` and I needed `pb`/frozen graph to obtain ONNX model.

---

**Comment by TomWildenhain-Microsoft** [comment]
Instead of freezing the model, try doing model.save("savedmodel").  Than use the --saved-model flag instead of --input in tf2onnx.  We will freeze it for you.

**Comment by pra-dan** [comment]
using saved-model isn't possible with Mask-RCNN. This is because it uses older versions of Keras and TF. Still trying some other methods, will update here possibly.
