### ISSUE TITLE
centerNet exported ONNX seems not correct

### ISSUE THREAD

**Issue by ttyio** [onnx/tensorflow-onnx#1659]
**Describe the bug**
The exported ONNX for centerNet ( http://download.tensorflow.org/models/object_detection/tf2/20210210/centernet_mobilenetv2fpn_512x512_coco17_kpts.tar.gz ) seems not correct.

For the original model:
we are trying to mark NaN as 0 in the sqrt output. 
![image](https://user-images.githubusercontent.com/365590/128809627-fbad379c-7e08-4ce1-98ca-a6fbb971b607.png)

For the exported onnx:
seems we are fill the sqrt output with NaNs.
See below image when I tried to apply the below formulas:
- Sqrt(Negative) = NaN
- 0 * NaN = NaN
- 0 * Inf = NaN
- 1 * Inf = Inf    
- a + NaN = NaN    (a is normalized number in IEEE 754)
- Inf + NaN = NaN

![image](https://user-images.githubusercontent.com/365590/128809683-c7659e02-a491-4722-a873-964a61f6156f.png)

**Urgency**
N/A

**System information**
- Linux Ubuntu 18.04
- Tensorflow Version: 2.5.0
- Python version: 3.6.9

**To Reproduce**
python3 -m pip install tensorflow onnxruntime
python3 -m pip install git+https://github.com/onnx/tensorflow-onnx

download http://download.tensorflow.org/models/object_detection/tf2/20210210/centernet_mobilenetv2fpn_512x512_coco17_kpts.tar.gz

python3 -m tf2onnx.convert --saved-model centernet_mobilenetv2_fpn_kpts/saved_model/  --opset 13 --output centernet_mobilenetv2_fpn_kpts.onnx

using Netron to visualize the onnx.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by TomWildenhain-Microsoft** [comment]
Hi @ttyio, thanks for the detailed report.  You are correct, we replace SelectV2 with an Add/Mul pattern to accelerate some models, but this is not 100% correct for NaN values.  We attempt to determine if NaN values are present and fall back to the ONNX Where op if this is the case, but we didn't match this pattern.  I've made a fix here: #1663

**Comment by ttyio** [comment]
Cool, thank you @TomWildenhain-Microsoft  for the quick fix!
