### ISSUE TITLE
Impossible to load a model due to a boolean input in SelectV2 node

### ISSUE THREAD

**Issue by LoicDagnas** [onnx/tensorflow-onnx#1669]
**Describe the bug**
After the resolution of [this issue](https://github.com/onnx/tensorflow-onnx/issues/1651) I am now able to convert my two models to ONNX format. But one of them is not loadable then.

It gives the following error:
> ```onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from [...]\ner.onnx failed:This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (StatefulPartitionedCall/SelectV2_2__776:0) of operator (Mul) in node (StatefulPartitionedCall/SelectV2_2__785) is invalid.```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10.0.19042
- Tensorflow Version: 2.5.0
- Python version: 3.7.6

**To Reproduce**
You'll fin the saved_model and the ONNX conversion in the archive droped [here](https://drive.google.com/drive/folders/1FJnxkA37PhMSUKhyWHM5R5d6CWP_lgEE?usp=sharing).

To reproduce the error above, I just run:

```python
import onnxruntime

sess_options = onnxruntime.SessionOptions()
sess_options.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_DISABLE_ALL
session = onnxruntime.InferenceSession('path/to/model.onnx', sess_options, providers=["CPUExecutionProvider"])
```

**Additional context**
It seems that it appears in a selectV2, and indeed I use a lot of `tf.where` operations, but these operations accept boolean input, right?

**Comment by TomWildenhain-Microsoft** [comment]
Try again with the latest tf2onnx from master.  I've fixed a few bugs which may help.

**Comment by LoicDagnas** [comment]
Indeed, it works! Thank you
