### ISSUE TITLE
ONNX model serving: brodcasting error in Where node.

### ISSUE THREAD

**Issue by LoicDagnas** [onnx/tensorflow-onnx#1670]
**Describe the bug**
After the resolution of [this issue](https://github.com/onnx/tensorflow-onnx/issues/1651) I am now able to convert my two models to ONNX format. But one of them is loadable but not serveable.

It gives the following error:
> ```onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Where node. Name:'Where__462' Status Message: D:\a\_work\1\s\onnxruntime\core/providers/cpu/math/element_wise_ops.h:497 onnxruntime::BroadcastIterator::Init axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 2 by 3```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10.0.19042
- Tensorflow Version: 2.5.0
- Python version: 3.7.6

**To Reproduce**
You'll fin the saved_model and the ONNX conversion in the archive droped [here](https://drive.google.com/drive/folders/1JiHj4mpO5TtaU9N8PAXwPHEDCyAg4Y-U?usp=sharing)

To reproduce the error above, I just run:

```python
import onnxruntime

sess_options = onnxruntime.SessionOptions()
sess_options.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_DISABLE_ALL
session = onnxruntime.InferenceSession('path/to/model.onnx', sess_options, providers=["CPUExecutionProvider"])

input_feed = {
    "categorical_ids": [[1] * 167],
    "text_word_ids": [[[101] + [102] + [0] * 254] * 2],
    "textualmetadata_word_ids": [[[101] + [102] + [0] * 254]]
}

output = session.run(output_names=None, input_feed=input_feed)
```

**Comment by TomWildenhain-Microsoft** [comment]
This was my mistake.  the RaggedTensorToTensor implementation didn't account for uniform (dense) dimensions.  #1676 has a fix.  I tested your model and it converts and produces matching results on your data.

**Comment by LoicDagnas** [comment]
@TomWildenhain-Microsoft thank you, it does work 😄
