### ISSUE TITLE
ValueError: symmetric pad mode is not supported

### ISSUE THREAD

**Issue by lamhoangtung** [onnx/tensorflow-onnx#1686]
**Describe the bug**
I'm trying to convert a MaskRCNN model trained with tensorpack example from .pb format to .onnx format

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 11.5.1
- Tensorflow Version: 1.15, 2.0
- Python version: 3.7.9

**To Reproduce**
Use the pretrained Resnet50 MaskRCNN model from Tensorpack, convert it to pb, and then onnx with this:
```
python3 -m tf2onnx.convert \
    --graphdef weights/model.pb \
    --output model.onnx \
    --inputs image:0 \
    --outputs output/boxes:0,output/scores:0,output/labels:0,output/masks:0 \
    --opset 15 \
    --inputs-as-nchw image:0
```
Then we can see the problem:
```
...
2021-08-26 15:48:15,838 - ERROR - Failed to convert node 'multilevel_roi_align/roi_level2/roi_align/crop_and_resize/MirrorPad' (fct=<bound method Pad.version_11 of <class 'tf2onnx.onnx_opset.nn.Pad'>>)
'OP=Pad\nName=multilevel_roi_align/roi_level2/roi_align/crop_and_resize/MirrorPad\nInputs:\n\tfpn/posthoc_3x3_p2/output:0=Identity, [-1, 256, -1, -1], 1\n\tmultilevel_roi_align/roi_level2/roi_align/crop_and_resize/MirrorPad/paddings:0=Const, [4, 2], 6\nOutpus:\n\tmultilevel_roi_align/roi_level2/roi_align/crop_and_resize/MirrorPad:0=[-1, 256, -1, -1], 1'
Traceback (most recent call last):
  File "/Users/linus/anaconda3/envs/tf2/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 292, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File "/Users/linus/anaconda3/envs/tf2/lib/python3.7/site-packages/tf2onnx/onnx_opset/nn.py", line 846, in version_11
    raise ValueError(mode + " pad mode is not supported")
ValueError: symmetric pad mode is not supported
```

Are there any thing that I'm doing wrong here? Thanks for checking by

**Comment by lamhoangtung** [comment]
Thanks for the quick reply

You can get the model from [here](http://models.tensorpack.com/FasterRCNN/COCO-MaskRCNN-R50C41x.npz). It's the MaskRCNN R-50-C4 in [Tensorpack model zoo](https://github.com/tensorpack/tensorpack/tree/master/examples/FasterRCNN)

**Comment by TomWildenhain-Microsoft** [comment]
Hi @lamhoangtung that's a .npz file with the model weights.  It would save me some time if you could upload the "weights/model.pb" file you were converting instead.  Otherwise I'll need to install TensorPack.

**Comment by lamhoangtung** [comment]
Here you go @TomWildenhain-Microsoft
https://drive.google.com/file/d/1nGw5kA96gBnCy2b__a1tVy6r3eXz6EpN/view?usp=sharing
