### ISSUE TITLE
LookupTableFindV2 ONNX conversion Error 

### ISSUE THREAD

**Issue by Hadrien-Cornier** [onnx/tensorflow-onnx#1689]
**Describe the bug**
When converting a tensorflow saved model into ONNX an error happens despite enabling the latest opset and installing onnx-extensions. It seems that the error happens because of an usupported tensorflow operation related to 'tf.lookup'

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Amazon Linux 2
- Tensorflow Version: 2.5.0
- Python version: 3.6

**To Reproduce**
I cannot share my model because it contains sensitive information.
But here is a layer that I use in the model that I think might be causing the issue : 

```python
class TspIntegerLookup(keras.layers.Layer):
  
  def __init__(self, vocabulary, **kwargs):
    import tensorflow as tf
    
    super(TspIntegerLookup, self).__init__(**kwargs)
    self.vocabulary = vocabulary
    
    values = tf.range(tf.size(vocabulary, out_type=tf.int64), dtype=tf.int64)
    initializer = tf.lookup.KeyValueTensorInitializer(
      vocabulary,
      values,
      key_dtype=tf.dtypes.int64,
      value_dtype=tf.dtypes.int64
    )
    self.table = tf.lookup.StaticVocabularyTable(initializer, 1)

  def call(self, keys):
    return self.table.lookup(keys)
  
  def get_config(self):
    return {
      **super(TspIntegerLookup, self).get_config(),
      "vocabulary": self.vocabulary
    }
```

**Logs**

```
(tf25onnx) [ec2-user@ip-172-23-14-153 triton]$ python -m tf2onnx.convert --saved-model models/c9726d23e9c04*1a33111e03198a1ac/***/1/model.savedmodel/  --output models/c9726d23e9c04*1a33111e03198a1ac/***/1/model.onnx/model.onnx --opset 13
...
[skipped 973 lines]
...
2021-08-27 21:40:58,105 - ERROR - Failed to convert node 'StatefulPartitionedCall/***/*model_name*/*_preprocessing/absolute_position_power_normalization/Log' (fct=<bound method DirectOp.version_6 of <class 'tf2onnx.onnx_opset.math.DirectOp'>>)
'OP=Log\nName=StatefulPartitionedCall/***/*model_name*/*_preprocessing/absolute_position_power_normalization/Log\nInputs:\n\tStatefulPartitionedCall/***/*model_name*/*_preprocessing/absolute_position_power_normalization/truediv:0=Mul, [-1, 1], 10\nOutpus:\n\tStatefulPartitionedCall/***/*model_name*/*_preprocessing/absolute_position_power_normalization/Log:0=[-1, 1], 10'
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/tf25onnx/lib/python3.9/site-packages/tf2onnx/tfonnx.py", line 291, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File "/home/ec2-user/anaconda3/envs/tf25onnx/lib/python3.9/site-packages/tf2onnx/onnx_opset/math.py", line 51, in version_6
    if node.maybe_cast_input([[onnx_pb.TensorProto.FLOAT]], double_to_float):
  File "/home/ec2-user/anaconda3/envs/tf25onnx/lib/python3.9/site-packages/tf2onnx/graph.py", line 432, in maybe_cast_input
    raise RuntimeError("don't know how to cast type {} on node {}".format(dtype, name))
RuntimeError: don't know how to cast type 10 on node StatefulPartitionedCall/***/*model_name*/*_preprocessing/absolute_position_power_normalization/truediv:0
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/tf25onnx/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ec2-user/anaconda3/envs/tf25onnx/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/anaconda3/envs/tf25onnx/lib/python3.9/site-packages/tf2onnx/convert.py", line 605, in <module>
    main()
  File "/home/ec2-user/anaconda3/envs/tf25onnx/lib/python3.9/site-packages/tf2onnx/convert.py", line 245, in main
    model_proto, _ = _convert_common(
  File "/home/ec2-user/anaconda3/envs/tf25onnx/lib/python3.9/site-packages/tf2onnx/convert.py", line 154, in _convert_common
    g = process_tf_graph(tf_graph, const_node_values=const_node_values, **kwargs)
  File "/home/ec2-user/anaconda3/envs/tf25onnx/lib/python3.9/site-packages/tf2onnx/tfonnx.py", line 530, in process_tf_graph
    g = process_parsed_graph(g, custom_op_handlers, inputs_as_nchw, continue_on_error, custom_rewriter, target,
  File "/home/ec2-user/anaconda3/envs/tf25onnx/lib/python3.9/site-packages/tf2onnx/tfonnx.py", line 637, in process_parsed_graph
    raise exceptions[0]
  File "/home/ec2-user/anaconda3/envs/tf25onnx/lib/python3.9/site-packages/tf2onnx/tfonnx.py", line 291, in tensorflow_onnx_mapping
    func(g, node, **kwargs, initialized_tables=initialized_tables, dequantize=dequantize)
  File "/home/ec2-user/anaconda3/envs/tf25onnx/lib/python3.9/site-packages/tf2onnx/custom_opsets/onnx_ml.py", line 34, in version_8
    utils.make_sure(shared_name is not None, "Could not determine table shared name for node %s", node.name)
  File "/home/ec2-user/anaconda3/envs/tf25onnx/lib/python3.9/site-packages/tf2onnx/utils.py", line 260, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Could not determine table shared name for node StatefulPartitionedCall/***/*model_name*/shared_preprocessing/*_*_*_id_*_*_*_id_*_id_previous_1_*_*_*_id_network_2_week_previous_2_*_*_*_id_network_2_week_categorical_embedding/integer_lookup_12/None_lookup_table_find_4/LookupTableFindV2
```

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by rmarrugat** [comment]
Looking at the code you shared:
- You set the initializer key and values types to int64, which is not permitted by the CategoryMapper (only String -> int64 allowed).
- I would suggest you to take out this code from your custom keras.Layer and place it inside the keras.Model functions (so effectively, remove your custom layer). I know this is not ideal, but it might help in your problem. 
 
After loading your saved_model, tf2onnx tries to run a constant and function optimizer which usually converts the graph functions (and subgraphs) into other nodes, which makes it possible for subgraph nodes (like the ones from your custom layer) to access the HashTable nodes. In this case, the optimizer was probably not successful (it might be due to the keras.Layer abstraction), so onnx is not able to find the HashTable reference when processing the Layer subgraph.

**Comment by TomWildenhain-Microsoft** [comment]
The 973 lines you skipped might include important information.  Specifically output at the start of conversion should have info about model loading, which should say if tf2onnx was able to find/load any hash table info from the model.  tf2onnx maps lookup ops to categorymapper, which only supports int<->string lookups, but ideally tf2onnx would succeed at loading the table and only fail later.

**Comment by TomWildenhain-Microsoft** [comment]
@Hadrien-Cornier please post the first 20 or so lines of output and I'll take a look.

**Comment by Hadrien-Cornier** [comment]
@TomWildenhain-Microsoft 
Here is attached the full output as a .txt file. 
[error.txt](https://github.com/onnx/tensorflow-onnx/files/7081297/error.txt)
So far I have found that the function : 
```python
tf.keras.layers.experimental.preprocessing.IntegerLookup()
```
cannot be converted to ONNX as @ rmarrugat was saying.

I might have found a workaround by changing my **Int64 -> Int64** lookup into **Int64 -> String -> Int64** doing this : 

```python 

def categorical_embedding(vocabulary, embedding_dimensions, max_norm_embedding, name, num_biases):
    import tensorflow.keras as keras

    categorical_input = keras.Input(shape=1, dtype="int64", name=name)

    lookup_layer = keras.layers.experimental.preprocessing.StringLookup(
        max_tokens=None,
        num_oov_indices=1,
        mask_token=None,
        oov_token="[UNK]",
        vocabulary=vocabulary,
        encoding=None,
        invert=False,
        output_mode="int",
        sparse=False,
        pad_to_max_tokens=False,
    )

    lookup = lookup_layer(tf.strings.as_string(categorical_input))

    embedding = keras.layers.Embedding(
        len(vocabulary) + 1, embedding_dimensions, input_length=1, name="embedding"
    )(lookup)
    bias = keras.layers.Embedding(
        len(vocabulary) + 1, num_biases, input_length=1,
        embeddings_initializer=keras.initializers.Zeros(),
        name="bias"
    )(lookup)

    squeeze = keras.layers.Lambda(lambda net: tf.squeeze(net, -2), name="squeeze_to_one_embedding")

    return categorical_input, keras.Model(
        inputs=categorical_input, outputs=[squeeze(embedding), squeeze(bias)], name=f"{name}_categorical_embedding"
    )
```

However I am still testing that code

**Comment by TomWildenhain-Microsoft** [comment]
@Hadrien-Cornier looking at the log file, the first lines include:
```
2021-08-27 21:40:38,619 - ERROR - Could not find table resource to replace placeholder unknown_78
2021-08-27 21:40:38,619 - ERROR - Could not find table resource to replace placeholder unknown_82
2021-08-27 21:40:38,619 - ERROR - Could not find table resource to replace placeholder unknown_86
2021-08-27 21:40:38,619 - ERROR - Could not find table resource to replace placeholder unknown_90
```
These are while the model is loading and indicate tf2onnx did not find a table for these inputs (tf adds implicit inputs for tables).

Using int64->string->int64 is a good workaround.

**Comment by TomWildenhain-Microsoft** [comment]
@Hadrien-Cornier if you are still having an issue, see if you can create a minimal/untrained model that you can share with the same issue.  Also try viewing the frozen model in Netron and see where the lookup ops are.  Convert with --output_frozen_graph to generate a frozen model.

**Comment by Hadrien-Cornier** [comment]
I had 3 errors in converting my model: 
 1) an error related to regex string manipulation operations that were not convertible in ONNX and that I fixed by adding the flag ```--extra_opset ai.onnx.contrib:1```to the call 
```
python -m tf2onnx.convert --saved-model models/c9726d23e9c04*1a33111e03198a1ac/***/1/model.savedmodel/  --output models/c9726d23e9c04*1a33111e03198a1ac/***/1/model.onnx/model.onnx --opset 13
```

2) an error in translating a normalization preprocessing function that I fixed by wrapping the problematic function in a Keras.Model() thanks to the recommendation of @rmarrugat.
3) The LookupTableFindV2 error related to the IntergerLookup function of Keras which I described above.

Now I have fixed 1 and 2 and I tried fixing 3 by using the method I described above. However I have a very similar error message, related to the same layers where the only difference is that the ```integer_lookup_12``` is replaced by ```string_lookup_12``` in the following error thrown by the onnx converter : 

```
ValueError: make_sure failure: Could not determine table shared name for node StatefulPartitionedCall/***/*model_name*/shared_preprocessing/*_*_*_id_*_*_*_id_*_id_previous_1_*_*_*_id_network_2_week_previous_2_*_*_*_id_network_2_week_categorical_embedding/integer_lookup_12/None_lookup_table_find_4/LookupTableFindV2
```

**Comment by Hadrien-Cornier** [comment]
This is very strange because when I convert directly the model from 
```

def categorical_embedding(vocabulary, embedding_dimensions, max_norm_embedding, name, num_biases):
    import tensorflow.keras as keras

    categorical_input = keras.Input(shape=1, dtype="int64", name=name)

    lookup_layer = keras.layers.experimental.preprocessing.StringLookup(
        max_tokens=None,
        num_oov_indices=1,
        mask_token=None,
        oov_token="[UNK]",
        vocabulary=vocabulary,
        encoding=None,
        invert=False,
        output_mode="int",
        sparse=False,
        pad_to_max_tokens=False,
    )

    lookup = lookup_layer(tf.strings.as_string(categorical_input))

    embedding = keras.layers.Embedding(
        len(vocabulary) + 1, embedding_dimensions, input_length=1, name="embedding"
    )(lookup)
    bias = keras.layers.Embedding(
        len(vocabulary) + 1, num_biases, input_length=1,
        embeddings_initializer=keras.initializers.Zeros(),
        name="bias"
    )(lookup)

    squeeze = keras.layers.Lambda(lambda net: tf.squeeze(net, -2), name="squeeze_to_one_embedding")

    return categorical_input, keras.Model(
        inputs=categorical_input, outputs=[squeeze(embedding), squeeze(bias)], name=f"{name}_categorical_embedding"
    )
```

into an onnx model it works ! But when I have the same code within my larger model, it fails...

**Comment by TomWildenhain-Microsoft** [comment]
Are the string lookup ops in your large model within a subgraph?  Use --output_frozen_graph in tf2onnx, then open the result in Netron and see.  We scan for lookup ops but I think we only search the outer graph currently.

**Comment by fatcat-z** [comment]
No response from user yet, close it.

**Comment by LinGeLin** [comment]
> This is very strange because when I convert directly the model from这很奇怪，因为当我直接转换模型时
> 
> ```python
> def categorical_embedding(vocabulary, embedding_dimensions, max_norm_embedding, name, num_biases):
>     import tensorflow.keras as keras
> 
>     categorical_input = keras.Input(shape=1, dtype="int64", name=name)
> 
>     lookup_layer = keras.layers.experimental.preprocessing.StringLookup(
>         max_tokens=None,
>         num_oov_indices=1,
>         mask_token=None,
>         oov_token="[UNK]",
>         vocabulary=vocabulary,
>         encoding=None,
>         invert=False,
>         output_mode="int",
>         sparse=False,
>         pad_to_max_tokens=False,
>     )
> 
>     lookup = lookup_layer(tf.strings.as_string(categorical_input))
> 
>     embedding = keras.layers.Embedding(
>         len(vocabulary) + 1, embedding_dimensions, input_length=1, name="embedding"
>     )(lookup)
>     bias = keras.layers.Embedding(
>         len(vocabulary) + 1, num_biases, input_length=1,
>         embeddings_initializer=keras.initializers.Zeros(),
>         name="bias"
>     )(lookup)
> 
>     squeeze = keras.layers.Lambda(lambda net: tf.squeeze(net, -2), name="squeeze_to_one_embedding")
> 
>     return categorical_input, keras.Model(
>         inputs=categorical_input, outputs=[squeeze(embedding), squeeze(bias)], name=f"{name}_categorical_embedding"
>     )
> ```
> 
> into an onnx model it works ! But when I have the same code within my larger model, it fails...进入 onnx 模型，它可以工作！但是当我在更大的模型中使用相同的代码时，它会失败......

same with you， large model failed
