### ISSUE TITLE
Input name include '.'

### ISSUE THREAD

**Issue by HanYuanyuaner** [onnx/tensorflow-onnx#169]
I use tensorboard to get inputs of my model like this "mobilenet_1.00_224_input". It looks that onnx can not recognize "." in this name. The error is 

AssertionError: mobilenet_1 is not in graph

Can anyone solve this problem?

**Comment by pengwa** [comment]
not sure what's going wrong. need some time to repro and fix. pr is welcomed if you would like. :)

**Comment by HanYuanyuaner** [comment]
> not sure what's going wrong. need some time to repro and fix. pr is welcomed if you would like. :)

Did I need to modify untils.py in tf2onnx ?

**Comment by guschmue** [comment]
I smell that one.
In utils.py split_nodename_and_shape()
    name_pattern = r"(?:([\w\d/\-_:]+)(\[[\d,]+\])?),?"
add  \. in front of _

I can fix it in a couple of hours or you can send a pr too if you like.

**Comment by guschmue** [comment]
fixed this  here https://github.com/onnx/tensorflow-onnx/pull/171
