### ISSUE TITLE
Cannot infer shape for model/multi_category_encoding/string_lookup_6/None_lookup_table_find/LookupTableFindV2

### ISSUE THREAD

**Issue by hanzigs** [onnx/tensorflow-onnx#1690]
Prediction values differs between python model and onnx model
```
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from autokeras import StructuredDataClassifier
```
![image](https://user-images.githubusercontent.com/30790120/131276038-96d2323a-5eba-4cf1-bff1-94e070d6d486.png)
```
num_columns = data.dtypes[data.dtypes != "object"].index.tolist()
data[num_columns] = MinMaxScaler().fit_transform(data[num_columns])
predictors = data.drop(["accepted"], axis=1)
input_x = predictors.loc[:].values
input_y = data.loc[:, ["accepted"]].values
input_y = input_y.reshape(len(input_y),)
seed = 7
np.random.seed(seed)
X_train, X_valid, y_train, y_valid = train_test_split(input_x,
                                                      input_y,
                                                      test_size=0.20,
                                                      stratify=input_y,
                                                      random_state=seed)
akmodel = StructuredDataClassifier(max_trials=100)
akmodel.fit(x=X_train,
            y=y_train,
            validation_data=(X_valid, y_valid),
            epochs=10)
autoKeras_model = akmodel.export_model()

def PrepareTestData(Test_Data, record):
    test_1 = Test_Data.iloc[record].values
    test_data = test_1.reshape(1,-1)
    return test_data
testData_for_model = PrepareTestData(predictors, record = 101)
autoKeras_model.predict(testData_for_model)[0][0]
0.61588526

!pip install tf2onnx==1.9.2
import tf2onnx.convert
import onnxruntime
onnx_model, _ = tf2onnx.convert.from_keras(autoKeras_model)
content = onnx_model.SerializeToString()
sess = onnxruntime.InferenceSession(content)
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
sess.run([label_name], {input_name: testData_for_model})[0][0][0]
0.27621585
```
onnx conversion throws the following warnings
```
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tf2onnx/tf_loader.py:703: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
Cannot infer shape for model/multi_category_encoding/string_lookup_6/None_lookup_table_find/LookupTableFindV2: model/multi_category_encoding/string_lookup_6/None_lookup_table_find/LookupTableFindV2:0
Cannot infer shape for model/multi_category_encoding/string_lookup_7/None_lookup_table_find/LookupTableFindV2: model/multi_category_encoding/string_lookup_7/None_lookup_table_find/LookupTableFindV2:0
Cannot infer shape for model/multi_category_encoding/string_lookup_8/None_lookup_table_find/LookupTableFindV2: model/multi_category_encoding/string_lookup_8/None_lookup_table_find/LookupTableFindV2:0
Cannot infer shape for model/multi_category_encoding/string_lookup_9/None_lookup_table_find/LookupTableFindV2: model/multi_category_encoding/string_lookup_9/None_lookup_table_find/LookupTableFindV2:0
Cannot infer shape for model/multi_category_encoding/string_lookup_10/None_lookup_table_find/LookupTableFindV2: model/multi_category_encoding/string_lookup_10/None_lookup_table_find/LookupTableFindV2:0
Cannot infer shape for model/multi_category_encoding/string_lookup_11/None_lookup_table_find/LookupTableFindV2: model/multi_category_encoding/string_lookup_11/None_lookup_table_find/LookupTableFindV2:0
Cannot infer shape for model/multi_category_encoding/Cast_1: model/multi_category_encoding/Cast_1:0
Cannot infer shape for model/multi_category_encoding/Cast_2: model/multi_category_encoding/Cast_2:0
Cannot infer shape for model/multi_category_encoding/Cast_3: model/multi_category_encoding/Cast_3:0
Cannot infer shape for model/multi_category_encoding/Cast_4: model/multi_category_encoding/Cast_4:0
Cannot infer shape for model/multi_category_encoding/Cast_5: model/multi_category_encoding/Cast_5:0
Cannot infer shape for model/multi_category_encoding/Cast_6: model/multi_category_encoding/Cast_6:0
ONNX does not support precision, scientific and fill attributes for AsString
ONNX does not support precision, scientific and fill attributes for AsString
ONNX does not support precision, scientific and fill attributes for AsString
ONNX does not support precision, scientific and fill attributes for AsString
ONNX does not support precision, scientific and fill attributes for AsString
ONNX does not support precision, scientific and fill attributes for AsString
```
referring to https://github.com/onnx/tensorflow-onnx/issues/1645

The issue is some thing to do with onnx model conversion.
Thanks for help

**Comment by TomWildenhain-Microsoft** [comment]
@hanzigs  Please upload a saved_model and provide a concrete input to test the model on.

**Comment by hanzigs** [comment]
Hi,
Added a Colab notebook with data and autokeras model building with the prediction difference (shared in the drive)
https://colab.research.google.com/drive/1DqlJgGZuKf5nev9G6Do7DYEMEU4aAQhy

https://drive.google.com/drive/folders/1HfB00dOuk-awSmIrSg92hmJFYzTpQNCr?usp=sharing

Let me know whether its possible to convert, Thanks

**Comment by TomWildenhain-Microsoft** [comment]
Hi @hanzigs,

I don't think this model can be easily converted to onnx without some modification, since it uses AsString and a lookup table on float32 values, which may be converted to strings with different levels of precision in onnx.  However, I'm also not sure that it's a very good model, since it looks like it is very overfit to the data.  A lookup means it might give a completely different prediction for a credit amount of 5951.0 (in the dataset) and 5952.0 (not in the dataset).

Just curious, what is this model for and why do you want to convert it to onnx?

If you really want the model to do string lookups of the inputs, it is probably best to convert the inputs to strings to begin with.  Just add `astype(np.str)` to all the model inputs.  Modifying your colab code, I got a model with consistent onnx/tf results.

**Comment by hanzigs** [comment]
Hi @TomWildenhain-Microsoft 
Thank you very much for letting me know the issues. I have tested in bigger dataset with callbacks and patience, found model worked fairly well as python model in prediction and LIME explanation, but onnx was my main concern.

Actually building an AutoML Framework, having Keras Sequential model, and others as well, found this Functional Model, so thought of having it. ONNX conversion mainly for consuming the model in .NET for prediction, If that's not working then we have to drop the model. 

Thanks for the support, much appreciated.

**Comment by hanzigs** [comment]
Hi @TomWildenhain-Microsoft 
Based on your suggestions for np.str conversion I gone through their code in 
https://github.com/keras-team/autokeras/blob/master/autokeras/keras_layers.py
in line 55 for MultiCategoryEncoding, mentioned Encode the categorical features to numerical features.
![image](https://user-images.githubusercontent.com/30790120/131601123-d7585902-1143-47e2-a3f6-57db96af7873.png)

I tried manually encoding before building model, it worked,
updated the test in the colab for you (added codes to get column_types and column_names in StructuredDataClassifier).
got model with consistent onnx/tf results

Thanks

**Comment by TomWildenhain-Microsoft** [comment]
Glad to hear it!
