### ISSUE TITLE
Python API not passing custom ops and rewriters properly

### ISSUE THREAD

**Issue by vloncar** [onnx/tensorflow-onnx#1707]
**Describe the bug**
[`from_keras()`](https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/convert.py#L388), [`from_function()`](https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/convert.py#L492) and [`from_graph_def()`](https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/convert.py#L554) functions incorrectly process `custom_op_handlers` and `custom rewriter` parameters (maybe others as well, but these two I need). The `custom_op_handlers` is not used, and instead `custom_ops` is passed to `process_tf_graph` in its place. The `custom_rewriter` is ignored altogether, removing the possibility to use this feature.

**Urgency**
None

**System information**
Doesn't matter

**To Reproduce**
Just try to pass something `custom_op_handlers` or `custom_rewriter` to `tf2onnx.convert.from_keras()`

**Screenshots**
Not needed

**Additional context**
Not needed

**Comment by TomWildenhain-Microsoft** [comment]
Hi @vloncar, you are correct.  Thanks for the investigation and report.  #1708 should fix the issue.

By the way, custom_op_handlers is deprecated and you may find it easier to use `@tf_op` to register an op handler.

`from tf2onnx.handler import tf_op`

Example:
https://github.com/onnx/tensorflow-onnx/blob/47acb8ac6ef98c4582c1d17605742fa997f54cc6/tf2onnx/custom_opsets/string_ops.py#L36

Just curious, what op handlers are you registering?

**Comment by vloncar** [comment]
Hi, thanks for the quick fix. I'm using the feature to parse quantized layers to a custom onnx op. 

One extra question: is there maybe a way to use the graph manipulation tools on an existing ONNX model? For example I would like to insert nodes after the model was fully optimized (i.e. it has gemm nodes and the bias has been fused into the conv layer)

**Comment by TomWildenhain-Microsoft** [comment]
@vloncar Maybe the easiest thing would be cloning the tf2onnx repo.  Then you can edit/add any editing steps you want.
