### ISSUE TITLE
Feature Request: Singular-Value Decomposition Support (SVD)

### ISSUE THREAD

**Issue by coltonpeltierSE** [onnx/tensorflow-onnx#1720]
Hi,

I am creating a model where I perform a [SVD](https://www.tensorflow.org/api_docs/python/tf/linalg/svd) using TensorFlow at one point. When converting the model to ONNX I get the following message:

```
2021-09-14 19:51:50,130 - ERROR - Tensorflow op [PartitionedCall/Compression/lambda/Svd: Svd] is not supported
2021-09-14 19:51:50,135 - ERROR - Unsupported ops: Counter({'Svd': 1})
```

I would like to request formal support for conversion of Tensorflow's SVD to ONNX. I've found a similar request on the pytorch github [here](https://github.com/pytorch/pytorch/issues/63861), so there may already be some work done on how this can be performed in ONNX.

**Comment by TomWildenhain-Microsoft** [comment]
Hi @coltonpeltierSE SVD is commonly used as a training op, and tf2onnx only supports converting tf models to onnx for inference.  Are you sure the SVD needs to be evaluated at inference time and its inputs are non-constant?

**Comment by coltonpeltierSE** [comment]
Hi @TomWildenhain-Microsoft ! Yes, in my case we have a signal which is being monitored at the embedded level (Electrical voltage and current waveforms). We are looking at two use cases for ONNX here:

- Inference on models which are trained on the most significant components of the SVD
- Compression of signals before being moved elsewhere in the system.

**Comment by TomWildenhain-Microsoft** [comment]
Ah cool, that makes sense. The ONNX spec does not currently include an SVD op of any type.  If you can pull the SVD outside the model you might be able to work around it.  You can also implement a custom op in C++ using onnxruntime-extensions and register it.  Or it may be possible to convert SVD into a composition of ONNX ops (using MatMul and Loop and such)

https://github.com/microsoft/onnxruntime-extensions

**Comment by coltonpeltierSE** [comment]
Thanks for the reply. How do I go about getting it onto the official roadmap?

**Comment by TomWildenhain-Microsoft** [comment]
Open an issue with the ONNX repo.  Give them a few examples of models that need it, since ONNX is a standard and ops are only added if they benefit multiple models.

https://github.com/onnx/onnx/issues

**Comment by coltonpeltierSE** [comment]
Request raised on ONNX github. Closing this.
