### ISSUE TITLE
Serialize directly? 

### ISSUE THREAD

**Issue by microprediction** [onnx/tensorflow-onnx#1721]
Hi, 
 Is it possible to avoid saving the keras model to disk (as with [this example](https://github.com/onnx/tensorflow-onnx/blob/master/examples/end2end_tfkeras.py))? Can I serialize directly to binary string or an object?

**Comment by TomWildenhain-Microsoft** [comment]
I think you answered your own question 😀 #1722

**Comment by hwangdeyu** [comment]
Closing due to lack of reply from the creator. If this is still an issue in the latest nightly tf2onnx, please open a new issue with clear repro instructions.

**Comment by microprediction** [comment]
Yes agree
