### ISSUE TITLE
Only Stride=1 supported

### ISSUE THREAD

**Issue by TheGreenMiles** [onnx/tensorflow-onnx#1738]
Hello,

So the Problem is that i want to convert a tf saved Model to onnx with opset. It has to be opset 9 because i Use barracuda and this package needs that specific Version. So if i try to convert it (tf Version 2.5) then tf2onnx only Supports stride=1. The architecture behind the tf Model is tinyyolov3. All convolutional layers have stride 1 except the pooling layers which have stride 2. So if i choose opset 10 and above it coverts perfectly but i need opset 9 explicitly! I think it has something to Do with Support for it or what can i Do?

**Comment by fatcat-z** [comment]
It's been over 2 months, so closing this. Feel free to open a new one if the issue still exists.
