### ISSUE TITLE
Is there any way to initialize the LookupTableFindV2 op in the exported frozen graph?

### ISSUE THREAD

**Issue by tanglang96** [onnx/tensorflow-onnx#1755]
Hi, I'm trying to use the exported frozen graph ([_from_saved_model_v2](https://github.com/onnx/tensorflow-onnx/blob/32b9cfc481c9adb7c9508d4bcf4e52324c6cfdca/tf2onnx/tf_loader.py#L530)) for tf serving (which is much faster than the native saved_model format), but if the native tf model has LookupTableFindV2 op, the input resource placeholder of LookupTableFindV2 op will be replaced with a HashTableV2 op ([replace_placeholders_with_tables](https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/tf_loader.py#L260)), and when I deploy the exported frozen graph with tfserving I got the Table not initialized error. Is there any way to manually initialize the LookupTableFindV2 op with the captured [initialized_tables](https://github.com/onnx/tensorflow-onnx/blob/32b9cfc481c9adb7c9508d4bcf4e52324c6cfdca/tf2onnx/tf_loader.py#L213) ?

**Comment by fatcat-z** [comment]
Probably this is an issue relative to Tensorflow because it is not aiming to convert it to an ONNX file.

Closing it and feel free to file a new one if I'm not correct.
