### ISSUE TITLE
BUG: convert_keras imports tf2onnx first and tests afterwards if it is installed

### ISSUE THREAD

**Issue by ahallermed** [onnx/tensorflow-onnx#1756]
**Describe the bug**
In [convert_keras](https://github.com/onnx/onnxmltools/blob/adc41eeb8ce69396970b7c79ba9a218d8a7e20bc/onnxmltools/convert/main.py#L43)

Current code:
```python
    else:
        # For tensorflow>=2.0, new converter based on tf2onnx.
        import tf2onnx

        if not utils.tf2onnx_installed():
            raise RuntimeError('tf2onnx is not installed. Please install it to use this feature.')
```

Code as is should be:

```python
    else:
        # For tensorflow>=2.0, new converter based on tf2onnx.

        if not utils.tf2onnx_installed():
            raise RuntimeError('tf2onnx is not installed. Please install it to use this feature.')

        import tf2onnx
```

**Urgency**
None

**To Reproduce**
Don't install tf2onnx and run convert_keras

**Additional context**
This bug should be resolved very easily for somebody who has already setup this repository including test setup. Thank you for doing this for me.

**Comment by fatcat-z** [comment]
The link of code you provided is under onnx/onnxmltools, not this repo.

**Comment by ahallermed** [comment]
My bad!
Opened a new issue in the correct repository: https://github.com/onnx/onnxmltools/issues/521
