### ISSUE TITLE
README.md inquiry

### ISSUE THREAD

**Issue by eagomez2** [onnx/tensorflow-onnx#1776]
Hi,

I am trying to convert a model in ONNX to TensorFlow SavedModel. However, I saw the following text in your [`README.md`](https://github.com/onnx/onnx-tensorflow):

---
 
## Migrating from `onnx-tf` to `tf-onnx`
We have joined force with Microsoft to co-develop ONNX TensorFlow frontend. For current onnx-tf frontend users, please migrate to use tf-onnx (https://github.com/onnx/tensorflow-onnx) where our code had been merged into. 

---

As of today, I don't think `tf-onnx` allows `onnx` to` tensorflow` conversion (please correct me if I'm wrong) so I am not sure what those lines really mean. Does it mean that `onnx-tf` be deprecated in a foreseeable future and that functionality will be included in `tf-onnx` instead or am I misunderstanding it?

Thanks,

**Comment by guschmue** [comment]
Only the tf->onnx part of onnx-tf have been moved to tf2onnx.
The onnx->tf part is still done by onnx-tf.
Lots of onnx folks use the term ```frontend``` or ```backend``` (like in the readme) - tf2onnx is a frontend converter and produces onnx, onnx-tf is a backend converter and consumes onnx.
