### ISSUE TITLE
Unsupported ops: TensorScatterAdd, TensorListConcatV2, Rank

### ISSUE THREAD

**Issue by igalkr** [onnx/tensorflow-onnx#1778]
Hi, are the above ops to be supported, or am I running the command incorrectly? 
python -m tf2onnx.convert --saved-model saved_model --output model.onnx -v --target tensorrt --tag serve

**Comment by armbuster** [comment]
I am having a very confusing problem with tf2onnx giving me `TensorScatterAdd` nodes. The tf code I am trying to convert to onnx used `tf.tensor_scatter_nd_add`. I replaced this with `tf.scatter_nd` and `tf.math.add` in the hopes that tf2onnx would stop giving me this `TensorScatterAdd` node, but I am still getting it. It is almost as if tf2onnx is fusing these two operations for me.

More generally, I am confused why the tf2onnx parser is giving me a node that is not supported by onnx. I would love an explanation of what is going on here!

**Comment by guschmue** [comment]
Yes, TensorScatterAdd, TensorListConcatV2 are not mapped - we'd need to add it.

**Comment by igalkr** [comment]
What should I do in the meantime? I really need the onnx converted file.

**Comment by fatcat-z** [comment]
> What should I do in the meantime? I really need the onnx converted file.

Could you please share the TF code of your model so that we can validate it once there is a fix?

**Comment by igalkr** [comment]
Hi,
I had to get in contact with our management, we cannot share the code at the moment.

**Comment by r-remus** [comment]
:+1: I'd really like to see TensorScatterAdd be added to tf2onnx as well.

**Comment by hwangdeyu** [comment]
Hi @r-remus @igalkr, thanks for your comments!
`TensorScatterAdd` has added with this PR [Add TensorScatterAdd op for opset 16](https://github.com/onnx/tensorflow-onnx/pull/1949).
You can try to convert it using latest main branch code or waitting for the next tf2onnx release.

**Comment by fatcat-z** [comment]
It's been over 2 months, so closing this. Feel free to open a new one if the issue still exists.

**Comment by k-maheshkumar** [comment]
Hi, I am getting the following error with opset=18:

Tensorflow op [TensorListConcatV2_4: TensorListConcatV2] is not supported
Tensorflow op [TensorListConcatV2_3: TensorListConcatV2] is not supported
Tensorflow op [TensorListConcatV2_2: TensorListConcatV2] is not supported
Tensorflow op [TensorListConcatV2_1: TensorListConcatV2] is not supported
Tensorflow op [TensorListConcatV2: TensorListConcatV2] is not supported
Unsupported ops: Counter({'TensorListConcatV2': 5})

could you please help me?

**Comment by fatcat-z** [comment]
> Hi, I am getting the following error with opset=18:
> 
> Tensorflow op [TensorListConcatV2_4: TensorListConcatV2] is not supported Tensorflow op [TensorListConcatV2_3: TensorListConcatV2] is not supported Tensorflow op [TensorListConcatV2_2: TensorListConcatV2] is not supported Tensorflow op [TensorListConcatV2_1: TensorListConcatV2] is not supported Tensorflow op [TensorListConcatV2: TensorListConcatV2] is not supported Unsupported ops: Counter({'TensorListConcatV2': 5})
> 
> could you please help me?

This op is not supported yet. Please feel free to open a new issue with some details, like code or model, for this requirement so that we can put it into the plan.
