### ISSUE TITLE
Nightly CI pipeline was broken by nightly job of ORT.

### ISSUE THREAD

**Issue by fatcat-z** [onnx/tensorflow-onnx#1783]
CI details:

tensorflow=2.7.0, onnx=1.10.2, tf2onnx=1.10.0/a1a934

2021-11-22 12:16:09.5769661 [W:onnxruntime:, execution_frame.cc:770 onnxruntime::ExecutionFrame::VerifyOutputSizes] Expected shape from model of {} does not match actual shape of {1} for output pred

https://dev.azure.com/tensorflow-onnx/tensorflow-onnx/_build/results?buildId=16167&view=logs&j=5e8154f0-c0c3-5cd0-4603-0c632ae0c119&t=cf04f308-6cee-55aa-a0ba-eaded3d632b7

**Comment by fatcat-z** [comment]
This issue has been resolved by fixing a bug in ORT.

**Comment by Slyne** [comment]
@fatcat-z Hi, I met the same issue. Could you show your solution ?

**Comment by fatcat-z** [comment]
> @fatcat-z Hi, I met the same issue. Could you share your solution ?

Please update ORT to latest version 1.10.0.
