### ISSUE TITLE
Does tf2onnx output a deterministic output for the same input?

### ISSUE THREAD

**Issue by arangasa** [onnx/tensorflow-onnx#1789]
Description:
We observe that when the output of tf2onnx is serialized, the contents of the generated onnx model file is non-deterministic, across different runs, for the same input. Sometimes the onnx model file size is also different; sometimes the file size is same, but diff says that the files differ.

System Information
- tf2onnx version: We tried with tf2onnx 1.9.1 and 1.8.5
- OS Platform and Distribution (Linux Ubuntu 16.04):
- Tensorflow Version: 2.5.0
- Python version: 3.6.9
- ONNX version: 1.9.0

Reproducing:
Pasting the script cvt_to_onnx.py we used below. Assumes frozen_graph.pb is present in the directory (we are unable to share the model): Usage python cvt_to_onnx.py <output_file_name>
___________________________________________________________________________________________
import onnx
from array import array
import tf2onnx
import sys
import tensorflow as tf

dtype_dict = {"ImageTensor:0": "float32"}
shape_dict = {"ImageTensor:0": [1,512,512,3]}

tf_compat_v1 = tf.compat.v1
with tf_compat_v1.gfile.GFile("./frozen_graph.pb", "rb") as f:
    graph_def = tf_compat_v1.GraphDef()
    graph_def.ParseFromString(f.read())

onnx_model, _ = tf2onnx.convert.from_graph_def(graph_def, input_names=["ImageTensor:0"], output_names=["ArgMax:0"], opset=11, shape_override=shape_dict)
onnx.save(onnx_model, sys.argv[1])
___________________________________________________________________________________________

Is this an expected behavior?

Thank you.

**Comment by guschmue** [comment]
As long the model does not use random generators the output should be the same on on ever run and it should be very very close to the tensorflow output. Our unit tests are checking for this. There might be some slight difference in the results compared to tensorflow due to implementation differences in the runtime but those must be pretty small.

You see something differenrt?

**Comment by arangasa** [comment]
Hi @guschmue ,

Sorry if I am not clear. When I run tf2onnx to convert a tflite model to onnx, I get different onnx files for different runs (for the same tflite model).

We can reproduce this issue with this tflite model: https://storage.googleapis.com/download.tensorflow.org/models/tflite/mobilenet_v1_1.0_224_quant_and_labels.zip

If we run tf2onnx and serialize (for instance, using the below script), we get different onnx files for different runs.

tf2onnx version: We tried with tf2onnx 1.9.1 for this test case.
OS Platform and Distribution (Linux Ubuntu 16.04):
Tensorflow Version: 2.5.0
Python version: 3.6.9
ONNX version: 1.9.0

Script cvt_to_onnx.py:
_________________________________________________________________________________________
import onnx
import tf2onnx
import sys

onnx_graph = tf2onnx.tfonnx.process_tf_graph(None, opset=11, tflite_path=sys.argv[1])
onnx_graph = tf2onnx.optimizer.optimize_graph(onnx_graph, catch_errors=True)
onnx_model = onnx_graph.make_model("tf2onnx")
onnx.save(onnx_model, sys.argv[2])
_________________________________________________________________________________________

Usage:
python cvt_to_onnx.py ./mobilenet_v1_1.0_224_quant.tflite model1.onnx

**Comment by fatcat-z** [comment]
> Hi @guschmue ,
> 
> Sorry if I am not clear. When I run tf2onnx to convert a tflite model to onnx, I get different onnx files for different runs (for the same tflite model).
> 
> We can reproduce this issue with this tflite model: https://storage.googleapis.com/download.tensorflow.org/models/tflite/mobilenet_v1_1.0_224_quant_and_labels.zip
> 
> If we run tf2onnx and serialize (for instance, using the below script), we get different onnx files for different runs.
> 
> tf2onnx version: We tried with tf2onnx 1.9.1 for this test case. OS Platform and Distribution (Linux Ubuntu 16.04): Tensorflow Version: 2.5.0 Python version: 3.6.9 ONNX version: 1.9.0
> 
> Script cvt_to_onnx.py:
> 
> import onnx import tf2onnx import sys
> 
> onnx_graph = tf2onnx.tfonnx.process_tf_graph(None, opset=11, tflite_path=sys.argv[1]) onnx_graph = tf2onnx.optimizer.optimize_graph(onnx_graph, catch_errors=True) onnx_model = onnx_graph.make_model("tf2onnx") onnx.save(onnx_model, sys.argv[2])
> 
> Usage: python cvt_to_onnx.py ./mobilenet_v1_1.0_224_quant.tflite model1.onnx

Hi @arangasa ,

Use the files downloaded from this URL. And same environment settings except the 2 below:

OS Platform and Distribution: Linux Ubuntu 20.04
Python version: 3.8

Update the code as below to execute the code 100 times for every run, but didn't see the files are different. Could you please take a try with my above environment settings?

import onnx
import tf2onnx
import sys

for i in range(100):
    print(str(i) + " loop:")
    onnx_graph = tf2onnx.tfonnx.process_tf_graph(None, opset=13, tflite_path=sys.argv[1])
    onnx_graph = tf2onnx.optimizer.optimize_graph(onnx_graph, catch_errors=True)
    onnx_model = onnx_graph.make_model("tf2onnx")
    onnx.save(onnx_model, sys.argv[2].split(".")[0] + "_" + str(i) + ".onnx")

print("Success!")

**Comment by fatcat-z** [comment]
Close it since no more questions.

**Comment by ceruleangu** [comment]
hey @arangasa is this prlblem resolved?

**Comment by arangasa** [comment]
Hi @ceruleangu I don't have access to Ubuntu 20 machine, but I have noted the fix. Thank you.
