### ISSUE TITLE
Fail to convert model from onnx to .pb

### ISSUE THREAD

**Issue by arseniymerkulov** [onnx/tensorflow-onnx#1793]
### Describe the bug
issue copied from https://github.com/onnx/onnx-tensorflow cause project page saying authors migrated to this rep

I have onnx model converted from pytorch. I want to convert it to .pb via onnx_tf. Then i get following error:
`RuntimeError: Resize coordinate_transformation_mode=pytorch_half_pixel is not supported in Tensorflow.`
Looks like my problem is similair to this https://github.com/onnx/onnx-tensorflow/issues/632, but proposed solutions isnt working for me. Proposed solutions:

1. lowering opset version to 9 in onnx.export
2. changing 'align_corners' property to True in torch.nn.Upsample while building model in pytorch
should fix the problem

pytorch model comes to me like a black box and i cant change inner structure or tensor properties. Also, model uses dynamic padding and lowering version from 11 to 9-10 leads to this error:
`RuntimeError: Unsupported: ONNX export of Pad in opset 9. The sizes of the padding must be constant. Please try opset version 11.`
Because of this, i dont know how to apply proposed solutions in my case.

### To Reproduce
pytorch_half_pixel error occurs while executing following code (in func prepare):
```
from onnx_tf.backend import prepare
import onnx

onnx_model = onnx.load('model.onnx')

tf_rep = prepare(onnx_model)
tf_rep.export_graph('model.pb')
```

### ONNX model file
https://drive.google.com/file/d/147eZku7KXDFFD_oauijQMZKZ2-UdRTtq/view?usp=sharing

### Python, ONNX, ONNX-TF, Tensorflow version

Python version: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
ONNX version: 1.10.2
ONNX-TF version: 1.9.0
Tensorflow version: 2.5.0

How can solve this problem? Thanks in advance

**Comment by guschmue** [comment]
For
```onnx->tf``` use https://github.com/onnx/onnx-tensorflow

For
```tf->onnx```  use https://github.com/onnx/tensorflow-onnx

 Your repo case looks to me like onnx->tf

**Comment by felker** [comment]
@guschmue, would it be possible to add some variant of your comment to the `README.md`? As a user, it took me a bit of time to understand the relationship between the two projects. At first, I thought this was a complete frontend/backend replacement for `onnx-tf`. Only searching through the Issues of both repositories did it become clear.

**Comment by felker** [comment]
Let me know if I should open an Issue about this documentation request, like I did for https://github.com/onnx/onnx-tensorflow/issues/1010. It would be great if a nearly identical snippet could also be added here:
> This is one of the two TensorFlow converter projects which serve different purposes in the ONNX community:
> - [onnx-tensorflow](https://github.com/onnx/onnx-tensorflow) converts ONNX models to TensorFlow
> - [tf2onnx](https://github.com/onnx/tensorflow-onnx) converts TensorFlow models to ONNX
