### ISSUE TITLE
Tensorflow GNN Support

### ISSUE THREAD

**Issue by samvanstroud** [onnx/tensorflow-onnx#1795]
Hi, 

Are there any plans to support conversion of models built using [TF GNN](https://github.com/tensorflow/gnn)?

Thanks

**Comment by hwangdeyu** [comment]
Yeah, you can try to refer https://github.com/onnx/tensorflow-onnx#getting-started to convert your model to ONNX as long as  it's a tf model.

**Comment by hwangdeyu** [comment]
It's been over 2 months, so closing this. Feel free to open a new one.
