### ISSUE TITLE
Is there any plan to support tf.uint32?

### ISSUE THREAD

**Issue by wm2012011492** [onnx/tensorflow-onnx#1802]
**Describe the bug**
Why tf.uint32 and tf.uint64 is not supported? I think ONNX support these two datatypes according to the [link](https://github.com/onnx/onnx/blob/e2072611aaac0f86414f4b5cc69d8496a86cc5fd/onnx/onnx.proto3#L503) 

**System information**
- OS Platform and Distribution (Linux Ubuntu 18.04):
- Tensorflow Version: (TF1.15.5)
- Python version: (Python 3.8)
- tf2onnx version: (tf2onnx 1.9.1)

**Additional context**
**Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/convert.py", line 605, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/convert.py", line 245, in main
    model_proto, _ = _convert_common(
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/convert.py", line 154, in _convert_common
    g = process_tf_graph(tf_graph, const_node_values=const_node_values, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tfonnx.py", line 504, in process_tf_graph
    tensorflow_to_onnx(tf_graph, shape_override, const_node_values, ignore_default, use_default)
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tf_utils.py", line 461, in tensorflow_to_onnx
    return tflist_to_onnx(graph, shape_override, const_node_values, ignore_default, use_default)
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tf_utils.py", line 406, in tflist_to_onnx
    dtypes[out.name] = map_tf_dtype(out.dtype)
  File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tf_utils.py", line 112, in map_tf_dtype
    dtype = TF_TO_ONNX_DTYPE[dtype]
KeyError: tf.uint32**

**Comment by hwangdeyu** [comment]
> **Describe the bug** Why tf.uint32 and tf.uint64 is not supported? I think ONNX support these two datatypes according to the [link](https://github.com/onnx/onnx/blob/e2072611aaac0f86414f4b5cc69d8496a86cc5fd/onnx/onnx.proto3#L503)
> 
> **System information**
> 
> * OS Platform and Distribution (Linux Ubuntu 18.04):
> * Tensorflow Version: (TF1.15.5)
> * Python version: (Python 3.8)
> * tf2onnx version: (tf2onnx 1.9.1)
> 
> **Additional context** **Traceback (most recent call last): File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/usr/local/lib/python3.8/dist-packages/tf2onnx/convert.py", line 605, in main() File "/usr/local/lib/python3.8/dist-packages/tf2onnx/convert.py", line 245, in main model_proto, _ = _convert_common( File "/usr/local/lib/python3.8/dist-packages/tf2onnx/convert.py", line 154, in _convert_common g = process_tf_graph(tf_graph, const_node_values=const_node_values, **kwargs) File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tfonnx.py", line 504, in process_tf_graph tensorflow_to_onnx(tf_graph, shape_override, const_node_values, ignore_default, use_default) File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tf_utils.py", line 461, in tensorflow_to_onnx return tflist_to_onnx(graph, shape_override, const_node_values, ignore_default, use_default) File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tf_utils.py", line 406, in tflist_to_onnx dtypes[out.name] = map_tf_dtype(out.dtype) File "/usr/local/lib/python3.8/dist-packages/tf2onnx/tf_utils.py", line 112, in map_tf_dtype dtype = TF_TO_ONNX_DTYPE[dtype] KeyError: tf.uint32**

Thanks @wm2012011492 , now the latest code can support this type.

**Comment by wm2012011492** [comment]
Thanks for your great support!
