### ISSUE TITLE
The inference results are pretty different after converting to onnx representation

### ISSUE THREAD

**Issue by liamsun2019** [onnx/tensorflow-onnx#1804]
Hi, I encountered a problem when I converted a tf model to onnx format.

1. The tf model can be downloaded from:
https://tfhub.dev/google/movenet/multipose/lightning/1

2. use tf2onnx to convert to onnx format:
python3.6 -m tf2onnx.convert --saved-model movenet_multipose_lightning_1 --output model.onnx --opset=11 --inputs-as-nchw input
where movenet_multipose_lightning_1 is the directory to which the downloaded gz file is uncompressed.

For the same inference code, the results between the tf model and the converted onnx model are pretty different. I am curious what could be the reason.

**Comment by fatcat-z** [comment]
The results for me are same, could you please try them with latest version of tensorflow, onnxruntime and tf2onnx?

**Comment by fatcat-z** [comment]
It's been over 3 months, so closing this. Feel free to open a new one if the issue still exists.
