### ISSUE TITLE
Failed to convert model when using opset 15 but success on opset 8

### ISSUE THREAD

**Issue by maybeLee** [onnx/tensorflow-onnx#1811]
**Describe the bug**
I was trying to convert a Keras model with two `keras.layers.ThresholdedReLU()` using tf2onnx but failed. The information of the model is as follows:
```
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 input_4 (InputLayer)        [(None, 10, 3, 3)]        0         
                                                                 
 thresholded_re_lu_4 (Thresh  (None, 10, 3, 3)         0         
 oldedReLU)                                                      
                                                                 
 thresholded_re_lu_5 (Thresh  (None, 10, 3, 3)         0         
 oldedReLU)                                                      
                                                                 
=================================================================
Total params: 0
Trainable params: 0
Non-trainable params: 0
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Tensorflow Version: 2.7.0
- Python version: 3.6

**To Reproduce**
```
import tensorflow as tf
import tf2onnx

# create model
input = tf.keras.Input((10, 3, 3))
in1 = tf.keras.layers.ThresholdedReLU()(input)
output = tf.keras.layers.ThresholdedReLU()(in1)
model = tf.keras.Model(input, output)
model.summary()

# transform model
input_shape = model.layers[0].input_shape[0]
spec = (tf.TensorSpec(input_shape, tf.float32, name="input"),)
model, _ = tf2onnx.convert.from_keras(model, input_signature=spec, \
    opset=15, output_path="temp")

```
You may access the code here:
https://colab.research.google.com/drive/1ai4AeoWWUuZqEOdAeyAPy390QlWOuyki?usp=sharing

**Screenshots**
![image](https://user-images.githubusercontent.com/32777264/147317430-dd81d471-f379-4725-9919-56bdc5ef28e1.png)

However, I find that when changing the `opset` to 8, tf2onnx can transform this model. Can you help check what's the root cause?

**Comment by hwangdeyu** [comment]
It's a bug from [rewrite_thresholded_relu](https://github.com/onnx/tensorflow-onnx/blob/936cec62fa815d121a11994307c9f45a1dbba536/tf2onnx/rewriter/thresholded_relu_rewriter.py) after opset version 9. So it will be crushed when the onnx graph transfer into proto form. Now I don't find a good way to fix it.
But you can try to comment this line [tfonnx.py#L569](https://github.com/onnx/tensorflow-onnx/blob/5cd3b5b87ca8fbe38e90d2ecce6f9bda891792bf/tf2onnx/tfonnx.py#L569) to make your model conversion successfully.

**Comment by maybeLee** [comment]
Thanks for your walk around, it works good on my program!
