### ISSUE TITLE
tf2.x StatefulPartitionedCall support in freeze pb format?

### ISSUE THREAD

**Issue by ltcs11** [onnx/tensorflow-onnx#1813]
**Dubugging advice**
cpu with tf 2.3.2

**Describe the bug**
try use convert.py with freeze pb but failed

**System information**
- mac os catalina 10.15.7 
- Tensorflow Version:  2.3.4
- Python version: 3.7

**To Reproduce**
download in tensorflow hub https://tfhub.dev/google/imagenet/efficientnet_v2_imagenet1k_s/classification/2
used saved model
and following code try change saved model into freezePb

```
from tensorflow.python.tools import freeze_graph
from tensorflow.python.tools import saved_model_utils

output_graph_def = saved_model_utils.get_meta_graph_def(saved_model_dir, tags[0]).graph_def
freeze_graph.freeze_graph_with_def_protos(output_graph_def, None, None, output_node_name, None, None, freeze_file, True, '', input_saved_model_dir=saved_model_dir, saved_model_tags=tags)
```

**Additional context**
from netron we can check that whole pb  is just a StatefulPartitionedCall
![image](https://user-images.githubusercontent.com/3413342/147459903-51902d77-c570-4df3-bd1e-a14c22d5c204.png)

so i try use convert directly use freezPb

```
python3 tf2onnx/convert.py --input ${cur_path}/${model_path}/${PB_FILE} \
                           --inputs inputs \
                           --outputs logits \
                           --output ${cur_path}/${output_path}/tf2onnx.onnx \
                           --opset 11 \
                          --inputs-as-nchw inputs
```

but failed with ❌（freezePb）

```
Traceback (most recent call last):
  File "/Users/ltss/py_envs/tf2.0+/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 497, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 1 of node StatefulPartitionedCall was passed float from InceptionV3/Conv2d_1a_3x3/weights:0 incompatible with expected resource.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tf2onnx/convert.py", line 621, in <module>
    main()
  File "tf2onnx/convert.py", line 223, in main
    graph_def, inputs, outputs = tf_loader.from_graphdef(args.graphdef, args.inputs, args.outputs)
  File "/Users/ltss/project/easyedge/tensorflow2onnx/tf2onnx/tf_loader.py", line 357, in from_graphdef
    tf.import_graph_def(graph_def, name='')
  File "/Users/ltss/py_envs/tf2.0+/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/Users/ltss/py_envs/tf2.0+/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/Users/ltss/py_envs/tf2.0+/lib/python3.7/site-packages/tensorflow/python/framework/importer.py", line 501, in _import_graph_def_internal
    raise ValueError(str(e))
ValueError: Input 1 of node StatefulPartitionedCall was passed float from InceptionV3/Conv2d_1a_3x3/weights:0 incompatible with expected resource.

```

but convert succeed using saved model format ✅（saved_model）

while my appication only support freezePb input 

**can this StatefulPartitionedCall struct be parserd in  freezePb format?**

**Comment by hwangdeyu** [comment]
It looks like this is a similar issue with https://github.com/tensorflow/tensorflow/issues/43833 and https://github.com/tensorflow/tensorflow/issues/51664.

You can try to use the advices from above issues:
enable the following flag:
```
converter.experimental_enable_resource_variables = True
````
And also using latest stable version of TF.

**Comment by ltcs11** [comment]
i'm using `convert_variables_to_constants_v2_as_graph` api referenced from pipeline of saved_model format converting

found that the graph_def i got have no StatefulPartitionedCall Unit anymore(instead, the layer structure is already extracted), then export the graph_def as new FreezePb file

now the convert using FreezePb is done!
