### ISSUE TITLE
Python API for tflite2onnx conversion

### ISSUE THREAD

**Issue by r-remus** [onnx/tensorflow-onnx#1821]
I successfully converted a TF Lite model to ONNX using the command line. Is there any way of doing this programatically (i.e., using tf2onnx's Python API), too?

Many thanks in advance!

**Comment by hwangdeyu** [comment]
Yes, please refer the python `api from_function` and `from_graph_def` in https://github.com/onnx/tensorflow-onnx#python-api-reference.
Actually, when you use the command line. What the code works is calling this file https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/convert.py.

**Comment by fatcat-z** [comment]
It's been over 2 months, so closing this. Feel free to open a new one if the issue still exists.
