### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Split node. Name:'' Status Message: Input cannot be split evenly on selected axis. Input shape={244,1,384} axis=0,NUMOUTPUTS=16

### ISSUE THREAD

**Issue by SherlockHua1995** [onnx/tensorflow-onnx#1822]
HI,
I have transform the tf pb model to the onnx model.
But when I infer with the onnx model,the above error occured.
Any advice?

**Comment by hwangdeyu** [comment]
As the `Split` ORT kernel shown https://github.com/microsoft/onnxruntime/blob/cb8d8464bc6ee39a894ecc76e05574095f5eb489/onnxruntime/core/providers/cpu/tensor/split.cc#L69. You are using the `Split` operator with
```
Input shape={244,1,384} axis=0,NUMOUTPUTS=16
```
However, the 244 can not exact division the 16. Could you check the input shape in your model?

**Comment by fatcat-z** [comment]
It's been over 2 months, so closing this. Feel free to open a new one if the issue still exists.
