### ISSUE TITLE
RunTimeWarning: tf2onnx.convert sysmodules 

### ISSUE THREAD

**Issue by DeveloperNo579212** [onnx/tensorflow-onnx#1831]
I get this below and tried to uninstall and then reinstall based on info on:
https://github.com/onnx/tensorflow-onnx

I get unexpected results in the conversion and would like to fix this, but why is it appearing when following install procedure above?  Seems that some precondition is not met (not listed?) or the install documentation needs to be reviewed?

**"AppData\Local\Programs\Python\Python37\lib\runpy.py:125: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour"**

I tried Python 3.9 and downgraded to Python 3.7.9 just incase.

**Comment by DeveloperNo579212** [comment]
I confirmed my conversion is valid and comparable with the source in saved model format, in python.
Using the section "Verifying a Converted Model" here https://onnxruntime.ai/docs/tutorials/tf-get-started.html

**Comment by fatcat-z** [comment]
Given the conversion is valid so closing this. Please feel free to file a new one if any further questions.
