### ISSUE TITLE
Convert Dense to "FC" instead of "GEMM"

### ISSUE THREAD

**Issue by aviaisr** [onnx/tensorflow-onnx#1835]
Is there a way to convert force the conversion of tf.Densse layer to MatMul + Add instead of GEMM? I'm converting onnx to DLC and GEMM is causing problems.

**Comment by hwangdeyu** [comment]
This was a gemm_rewriter to rewriter the `MatMul + Add` op to `GEMM` . 
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/rewriter/gemm_rewriter.py.

You can just remove the related code from this PR [add gemm_rewriter and the corresponding test](https://github.com/onnx/tensorflow-onnx/pull/597)

By the way, is the `GEMM` op causing which problems?

**Comment by fatcat-z** [comment]
It's been over 3 months, so closing this. Feel free to open a new one if the issue still exists.
