### ISSUE TITLE
Op type not registered 'FeatureSize'. Failing to convert Tensorflow syntaxnet model to Onnx

### ISSUE THREAD

**Issue by miraclecorp** [onnx/tensorflow-onnx#1836]
**Describe the bug**
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'FeatureSize' in binary running on XXXXXXXXXX. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

- FeatureSize comes from parser_ops.cc (syntaxnet). https://git.dst.etit.tu-chemnitz.de/external/tf-models/-/blob/dfafba4a017c21c19dfdb60e1580f0b2ff5d361f/research/syntaxnet/syntaxnet/ops/parser_ops.cc
- Attempted to add the method in "~tf2onnx/custom_opset/ms.py" and use the flag "--custom-ops", but same error
- Attempted to copy "parser_ops.so" (which was created from docker) and placed into the custom_opset, but same error

**Urgency**
Early February

**System information**
- macOS Mojave
- Tensorflow Version: 2.7.0
- Python version: 3.9.7

**To Reproduce**
Model: syntaxnet
Describe steps/code to reproduce the behavior. Please upload/link the model you are trying to convert if possible.
python3 -m tf2onnx.convert --saved-model [my_model_here] --inputs inputs:0[-1] --output model.onnx --opset 13 --extra_opset ai.onnx.contrib:1 --tag serve;

Thank you so much!

**Comment by hwangdeyu** [comment]
Could you also provide the repro code and model? Then we can try to repro this issue.

**Comment by miraclecorp** [comment]
Model sent to you via email. The commands we tried are:

(1) python3 -m tf2onnx.convert --saved-model ~/Desktop/ud/syntaxnet-jni/en_US/SAVED_MODEL_TAGGER/ --output ~/Desktop/model.onnx --opset 13

(2) python3 -m tf2onnx.convert --saved-model ~/Desktop/ud/syntaxnet-jni/en_US/SAVED_MODEL_TAGGER/ --inputs inputs:0[-1] --output ~/Desktop/model.onnx --opset 13 --extra_opset ai.onnx.contrib:1 --tag serve;

Btw, this model will only work if both "SAVED_MODEL_PARSER" and "SAVED_MODEL_TAGGER" are converted...
Thank you so much!

**Comment by hwangdeyu** [comment]
Thanks @miraclecorp , I received your email and repro this issues.

According to the error message:
>  File "/code/tensorflow-onnx/tf2onnx/convert.py", line 636, in <module>
    main()
  File "/code/tensorflow-onnx/tf2onnx/convert.py", line 233, in main
    graph_def, inputs, outputs, initialized_tables, tensors_to_rename = tf_loader.from_saved_model(
  File "/code/tensorflow-onnx/tf2onnx/tf_loader.py", line 614, in from_saved_model
    _from_saved_model_v2(model_path, input_names, output_names,

This error is arised in loading the saved_model. So it's not issue related tf2onnx.

And in term of the model pb file as below: 
![image](https://user-images.githubusercontent.com/10047193/153565730-f182ca58-837b-4cc9-aeea-186aa8e2f455.png)
we can see that the `FeatureSize` is not used in this model.

So I suggest you to check the save model again or create an issue in tensorflow repo.

**Comment by garymm** [comment]
`--load_op_libraries` should allow us to load the model, but converter will fail because it doesn't know how to convert the op.
The two options are to provide a custom conversion via Python, or pass through the custom ops and implement them in the runtime. This would have to be done for every custom op in the model. 

@hwangdeyu can you please add `--load_op_libraries` to the README.md?

**Comment by miraclecorp** [comment]
Hi @garymm , can you please give us a more guidance on the 2 options that we should take

(1) custom conversion via python?
(2) pass through the custom ops and implement them in runtime?

tysm!

**Comment by garymm** [comment]
This issue is requesting documentation for that: https://github.com/onnx/tensorflow-onnx/issues/1852 so I'd follow that issue and make sure the documentation added as part of that answers your questions.

**Comment by hwangdeyu** [comment]
@miraclecorp  
Firstly, you can use the `--load_op_libraries tensorflow_library_path` parameter to load the tf custom ops.
And then refer to https://github.com/onnx/tensorflow-onnx#creating-custom-op-mappings-from-python, create the `custom_op_handler` to support conversion for each custom ops. Then the model can be exported to onnx and run in runtime.

**Comment by miraclecorp** [comment]
We tried the above step mentioned @hwangdeyu , but we still get:

Op type not registered 'FeatureSize' in binary running on ---------. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

tysm

**Comment by hwangdeyu** [comment]
Hi @miraclecorp, 
Tf2onnx is not supported `tf.contrib` ops currently by the converter.
The only solution is load the tensorflow_library with `.so` file. And then implement all the ops by conbinding with exsiting ONNX ops or implement ops kernel in ONNXRuntime.
I wrote a doc for how to convert with custom ops example. [custom_op.md](https://github.com/onnx/tensorflow-onnx/blob/3c4bd4e9a93c17dde723bd365f45c229dc1d379d/examples/tf_custom_op/custom_op.md)
Free free to reply if you have further questions.
