### ISSUE TITLE
Unsure how to use dequantize flag so that the onnx model can be used with unity barracuda

### ISSUE THREAD

**Issue by LauraMarieRam** [onnx/tensorflow-onnx#1854]
**Describe the bug**
receiving message "ValueError: Opset 10 is required for quantization. Consider using the --dequantize flag or --opset 10."

After trying to `python -m tf2onnx.convert --opset 9 --dequantize --tflite C:\Users\Me\MyFirstImageRecog\model.tflite --output model.onnx` 

**Urgency**
18 feb 2022

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Tensorflow Version: latest 2
- Python version: 3.9

**Additional context**
Am trying to dequantize and export as opset9 as i am having issues getting my opset13 version into unity due to unsupported dequantization method
need to dequantize but can't figure out how the dequantization flag should be used and can't find any examples

**Comment by fatcat-z** [comment]
Is it possible to share your model with us for a further investigation? Did you try opset 10?

**Comment by fatcat-z** [comment]
It's been over 3 months, so closing this. Feel free to open a new one if the issue still exists.
