### ISSUE TITLE
Failure to assign/calculate groups in Conv3D

### ISSUE THREAD

**Issue by reach-satori** [onnx/tensorflow-onnx#1868]
As seen in the last few posts of #1434. The fix made in #1435 doesn't work for Conv3D. Node group numbers are incorrect because the 5d data formats aren't accounted for in ConvOp. The conversion produces an onnx model, but it fails at inference time with `Input channels C is not equal to kernel channels * group.` 

I did a small hack just to quickly get what I needed working and you can check it in the previous issue, and it should be a relatively easy fix, but I don't really understand the codebase well enough to submit a PR I'd trust myself.
I ran across this issue when converting the following model: https://github.com/Chianugoogidi/X3D-tf

**Comment by fatcat-z** [comment]
You are welcome to submit a PR like you did in another issue as a contribution. We will help on the review and the CI will guarantee it won't break our existing scenarios.

**Comment by fatcat-z** [comment]
It's been over 6 months, so closing this. Feel free to open a new one if the issue still exists.
