### ISSUE TITLE
TFLite conversion hangs or crashes with segfault

### ISSUE THREAD

**Issue by SludgePhD** [onnx/tensorflow-onnx#1877]
**Describe the bug**
Attempting to convert https://github.com/google/mediapipe/tree/master/mediapipe/modules/face_detection/face_detection_full_range_sparse.tflite to ONNX either results in a hang with no CPU/GPU usage, or in a segmentation fault.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- Tensorflow Version: 2.8.0
- Python version: 3.10.2

**To Reproduce**

Command used:

```
python -m tf2onnx.convert --tflite face_detection_full_range_sparse.tflite --output face_detection_full_range_sparse.onnx
```

Output:

```
/usr/lib/python3.10/runpy.py:126: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2022-03-10 00:45:27,863 - INFO - Using tensorflow=2.8.0, onnx=1.11.0, tf2onnx=1.10.0/8f2e84
2022-03-10 00:45:27,863 - INFO - Using opset <onnx, 9>
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
fish: Job 1, 'python -m tf2onnx.convert --tfl…' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by hwangdeyu** [comment]
After my debugging, the code is crashed in https://github.com/onnx/tensorflow-onnx/blob/8f2e84bd8c7c37bda4bae0d549ea195a419b1e80/tf2onnx/tflite_utils.py#L202 when tflite wants to get the interpreter tensor detail when `i == 15`.
Get the same issue in tf repo https://github.com/tensorflow/tensorflow/issues/55040. I guess we can also trace it at the same time.

**Comment by Mr-bor** [comment]
The same question is happen when i convert model from [https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection/pose_detection.tflite](url)

**Comment by fatcat-z** [comment]
Looks like this is relative to how tensorflow processes this model, has filed an issue https://github.com/tensorflow/tensorflow/issues/56283 to trace this problem to tensorflow.

**Comment by fatcat-z** [comment]
Please refer to above tf issue for further progress. Closing this right now.

**Comment by wndfly** [comment]
> The same question is also happen when i convert model from [https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection/pose_detection.tflite](url)

Have you converted this model to ONNX format successfully now?
I have a problem that when I run this command above finished with no errors, but no ONNX file output.
 ```python -m tf2onnx.convert --tflite pose_detection.tflite --output pose_detection.onnx```

**Comment by Mrcaoyu1** [comment]
> > The same question is also happen when i convert model from [https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection/pose_detection.tflite](url)
> 
> Have you converted this model to ONNX format successfully now? I have a problem that when I run the command below finished with no errors, but no ONNX file output. `python -m tf2onnx.convert --tflite pose_detection.tflite --output pose_detection.onnx`

Have you solved this problem？I met the same problem when I try to convert pose_detection.tflite

**Comment by Sukeysun** [comment]
> > > The same question is also happen when i convert model from [https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection/pose_detection.tflite](url)
> > 
> > 
> > Have you converted this model to ONNX format successfully now? I have a problem that when I run the command below finished with no errors, but no ONNX file output. `python -m tf2onnx.convert --tflite pose_detection.tflite --output pose_detection.onnx`
> 
 Hi Have you solved this problem？

**Comment by Som5ra** [comment]
@wndfly @Mrcaoyu1 And to whom still looking for this:
https://github.com/PINTO0309/PINTO_model_zoo/blob/main/053_BlazePose/download.sh

You can solve this by converting the original .tflite into .pb, then to .onnx, pls refer: 
https://github.com/PINTO0309/tflite2tensorflow/issues/18
https://github.com/PINTO0309/tflite2tensorflow/issues/11
