### ISSUE TITLE
Shape inference mismatch error for the graph output node

### ISSUE THREAD

**Issue by Dev1158** [onnx/tensorflow-onnx#188]
@guschmue 
During conversion when a new node is added to the node output in case of Stridedslice, Sqrt, Relu6, etc. the node output name contains numbers in suffix separated by "__" in order to make it unique from the parent node. It could be interpreted from the code that for the rest portion of the graph, the parent name is replaced by the new node name. But when the parent node is the graph's final output, the name given in the yaml file does not match with the new node name. So it throws Shape Inference Mismatch Error with Caffe2 backend. 
What would be the generic solution to this issue?

**Comment by pengwa** [comment]
@Dev1158 I think this is a general problem we recently decides to make a fix. I will take a look at this. thanks for reporting this.

**Comment by pengwa** [comment]
this should be fixed in master. @Dev1158  please feel free to have a try. if still have this problem, let me know.

**Comment by PreethaVeera** [comment]
@guschmue @pengwa  The Shape inference mismatch issue is sorted if the node is mentioned as the final output. That's a nice fix.

I am now trying to compare the **layer-wise outputs** of nodes between the TF model and the converted ONNX model inference. I am facing **shape inference issues** at multiple locations notably from ops like Stridedslice, Sqrt, Relu6, etc as quoted by @Dev1158 . The ideal solution would be to retain the original TF node name for the equivalent ONNX pattern output node. If a **1: N** (Single TF node decomposed into more simpler ONNX nodes) pattern exists then the Nth ONNX node in the pattern should retain the original TF node name.  For eg : StridedSlice (TF node) -> Slice + Squeeze + Cast (ONNX pattern). The Cast node should retain the actual StridedSlice node name for these shape inference errors to be handled.  

Also previously at the op handlers the handled nodes were returned as a list but now I find it removed. With the list of nodes returned from the op handlers it was easy to identify the Nth node in a 1: N ( TF : ONNX ) pattern but now we don't have any such reference.
Are there any specific reasons for removing them?
Can you add support to return the list of nodes from the op handlers? If it is brought back that will be really helpful to compare the layer-wise results of the two graphs.
