### ISSUE TITLE
Unable to convet tflite to onnx model

### ISSUE THREAD

**Issue by kafan1986** [onnx/tensorflow-onnx#1882]
I am unable to convert the following model from tflite to onnx. It throws some assertion error assert(rank == len(ot.shape)) I have attached model
[sample_model.zip](https://github.com/onnx/tensorflow-onnx/files/8290868/sample_model.zip)

**Comment by hwangdeyu** [comment]
I can convert it successfully by using
```
python -m tf2onnx.convert --opset 9 --tflite sample_model.tflite --output sample_model.onnx
```
tensorflow=2.7.0, onnx=1.10.2

[sample_model_onnx.zip](https://github.com/onnx/tensorflow-onnx/files/8302284/sample_model_onnx.zip)

**Comment by kafan1986** [comment]
@hwangdeyu Is there a provision of adding a dynamic axis for batch inference while converting from tflite to onnx?

**Comment by hwangdeyu** [comment]
> @hwangdeyu Deyu Huang FTE Is there a provision of adding a dynamic axis for batch inference while converting from tflite to onnx?

You can try to use the parameter [--inputs---outputs](https://github.com/onnx/tensorflow-onnx#--inputs---outputs) and use  `-1` to indicate unknown dimensions.
