### ISSUE TITLE
how to assign batchsize to 1

### ISSUE THREAD

**Issue by liguang-ops** [onnx/tensorflow-onnx#1891]
**Describe the bug**
Here are my python model
```python
model=Sequential()
model.add(Conv3D(filters=128,kernel_size=(11,11,1),strides=(4,4,1),padding='same',input_shape=(h,w,t_length,1),activation='tanh'))
model.add(Conv3D(filters=64,kernel_size=(5,5,1),strides=(2,2,1),padding='same',activation='tanh'))
model.add(ConvLSTM2D(filters=64,kernel_size=(3,3),strides=1,padding='same',dropout=0.4,recurrent_dropout=0.3,return_sequences=True))
model.add(ConvLSTM2D(filters=32,kernel_size=(3,3),strides=1,padding='same',dropout=0.3,return_sequences=True))
model.add(ConvLSTM2D(filters=64,kernel_size=(3,3),strides=1,return_sequences=True, padding='same',dropout=0.5))
model.add(Conv3DTranspose(filters=128,kernel_size=(5,5,1),strides=(2,2,1),padding='same',activation='tanh'))
model.add(Conv3DTranspose(filters=1,kernel_size=(11,11,1),strides=(4,4,1),padding='same',activation='tanh'))
model.compile(optimizer='adam',loss='mean_squared_error',metrics=['accuracy'])
#train ... skip
model.save({filename.h5}, save_format="h5")
```
then, in shell
```shell
python -m tf2onnx.convert ${filename.h5} --output.onnx --opset 13 --target tensorrt --debug
```
when i see the structure of onnx model using Netron
![image](https://user-images.githubusercontent.com/55933360/159632523-cfa4df1c-b121-4344-aaf8-20707c4b659f.png)
,the batchsize and the output size is not constant. it prevents me from using tensorrt to convert onnx model to trt.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- Tensorflow Version:2.4.0
- Python version:3.6.13
- onnx":1.10.2
- onnxruntime:1.10.0
- tf2onnx"1.9.3

**Comment by hwangdeyu** [comment]
This should be a keras issue. Please refer to https://stackoverflow.com/questions/55882176/how-to-fix-the-batch-size-in-keras or set the `batch_input_shape`. Or create a issue in keras repo.
