### ISSUE TITLE
Please add a op of ”ResizeNearestNeighbor”

### ISSUE THREAD

**Issue by lllsiriuslll** [onnx/tensorflow-onnx#19]
Hi.
I am using tensorflow-onnx to convert the TensorFlow model(pb file) into a model for ONNX. However, ”ResizeNearestNeighbor” does not support it and it can not be converted. Could you please add a operator of ”ResizeNearestNeighbor”?

**Comment by guschmue** [comment]
ResizeNearestNeighbor should be supported with https://github.com/onnx/tensorflow-onnx/pull/20
