### ISSUE TITLE
Add support for user-defined ONNX metadata

### ISSUE THREAD

**Issue by r-remus** [onnx/tensorflow-onnx#1905]
Are there plans to support adding ONNX meta data to an exported model, or is it even already possible to include ONNX metadata when using tf2onnx?

**Comment by fatcat-z** [comment]
Could you please provide details about what meta data you are looking for? Currently, tf2onnx will include some meta data, like producer, op domain and version, in the final ONNX file.

**Comment by r-remus** [comment]
Sorry, I wasn't specific enough. I'm talking about **user-defined meta data**, i.e. arbitrary key-value pairs that one could use to store whatever may be needed (e.g., expected input value ranges, output value ranges, own versioning etc.).

I adapted the issue title accordingly.

**Comment by r-remus** [comment]
Will you consider this at all or should we just close this issue then? I'm happy to contribute in this regard, by the way.

**Comment by r-remus** [comment]
Okay, let's close it then.
