### ISSUE TITLE
float type mismatch

### ISSUE THREAD

**Issue by utkarsh-VRL** [onnx/tensorflow-onnx#191]
Converting an ONNX model to tensorflow.

This was how I converted it from MXNet to ONNX:
`converted_model_path = onnx_mxnet.export_model(sym, params, [input_shape], np.float32, onnx_file)`
When I try to import it into tensorflow:
```
model = onnx.load('av-mobilenet.onnx')
tf_rep = prepare(model)
```
I get thess errors:
```
TypeError: Input 'y' of 'Sub' Op has type float64 that does not match type float32 of argument 'x'.
ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float64: 'Tensor("Const:0", shape=(1,), dtype=float64)'
```

Similar errors occur if I use np.float64 when creating the ONNX model file. 
Any ideas what is happening here and what I can do?

**Comment by pengwa** [comment]
so this is not tf-onnx converter issue, right?

**Comment by utkarsh-VRL** [comment]
Oh, my bad, this is a onnx-tensorflow issue, not a tensorflow-onnx one (...).
I will close this and repost it there. Thanks.
