### ISSUE TITLE
How can i specified the layout of LSTM operator from tensorflow to onnx?

### ISSUE THREAD

**Issue by buptqq** [onnx/tensorflow-onnx#1916]
LSTM operator in ONNX has an attribute which is layout.
![image](https://user-images.githubusercontent.com/20453241/163808903-ebb3a6a8-ba73-4284-92c9-4fa15861df01.png)
But I use tf2onnx convert a protobuf which has lstm, i found that the onnx has insert Transpose operator after input and before output.
If I want the lstm layout in onnx model is:  X.shape : [batch_size, seq_len, num_directions, hidden_size] ....(the batchsize is the first dimensions in input and output of lstm), how can I do?

**Comment by fatcat-z** [comment]
Unfortunately, it's not supported yet and there is no plan for it so far.
