### ISSUE TITLE
Recurrent layers give rise to Loop layer with M=maxint

### ISSUE THREAD

**Issue by yuanyao-nv** [onnx/tensorflow-onnx#1948]
**Describe the bug**
For some recurrent keras layers, tf2onnx returns a Loop layer with the `M` field set to maxint. This can give rise to memory issues for libraries that allocate memory based on this field (such as TensorRT).

Here is a minimal example involving `keras.SimpleRNN`:
```
model = keras.Sequential()
model.add(keras.layers.SimpleRNN(10))
model.build(input_shape = (1,32,32))
model.save('./model')
```
Then convert to onnx with:
```
python3 -m tf2onnx.convert --saved-model model/ --output model.onnx --opset 15
```
![image](https://user-images.githubusercontent.com/99693700/170135256-ad6afc0c-9d6f-42b6-b46d-0fd7363f42c1.png)

Similar issue is also observed for the `keras.ConvLSTM1D` layer.

Other recurrent layers, such as `keras.LSTM` and `keras.GRU` get converted to an LSTM layer in onnx and don't run into this issue.

**System information**
- OS Platform and Distribution: Linux Ubuntu 20.04
- Tensorflow Version: 2.9.1
- Python version: 3.8.5
- tf2onnx: 1.10.1

**Comment by yuanyao-nv** [comment]
In fact, looking at the Loop node more closely, the `cond` input is from the Less node's output, but A=0 and B=32 are const folded into the Less node, so the `cond` condition will always be true and `M` is also set to int max. Is this a bug?

**Comment by hwangdeyu** [comment]
Hi @yuanyao-nv , thanks for your issue contribution and sorry for the slowly reply.
After my debug, this max_int is originally from
https://github.com/onnx/tensorflow-onnx/blob/a8f78ac7903493dee579304b7b1717aa9ec9706f/tf2onnx/onnx_opset/controlflow.py#L391
`-1` means infinity in tf, but in onnx it should be max_int to get the same behavior.
Could you tell me why this constant would rise to memory issues. Does TensorRT would allocate memory by this constant?

**Comment by hwangdeyu** [comment]
> In fact, looking at the Loop node more closely, the `cond` input is from the Less node's output, but A=0 and B=32 are const folded into the Less node, so the `cond` condition will always be true and `M` is also set to int max. Is this a bug?

As for `Less` node as input node in `Loop` op, I think it's not a bug. This is an input to the op that determines whether to run the *first iteration*, refer to https://github.com/onnx/onnx/blob/main/docs/Changelog.md#loop-16.
As the below picture shown, there is a subgraph in `Loop` attributes `body`.
<img width="703" alt="image" src="https://user-images.githubusercontent.com/10047193/173106722-729dc870-6266-489c-a306-b66266818d45.png">

If we click into the subgraph, we can see there is a `Less` op which would produce a new boolean value for the next iteration condition. That's how the looping construct works.
<img width="698" alt="image" src="https://user-images.githubusercontent.com/10047193/173107146-b840065e-e44a-46f5-b052-672c66479fd0.png">

In the meantime, I also tried to run the onnx model using [ORT](https://github.com/microsoft/onnxruntime), which could get the result and not stuck in an infinite loop. 
![image](https://user-images.githubusercontent.com/10047193/173108625-b65e1ed8-6643-4b2a-af6e-18384fb80706.png)

**Comment by yuanyao-nv** [comment]
Hi @hwangdeyu thank you for your reply!

I couldn't find any TF documentation that says -1 stands for inf. Can you point me to where this is documented?
In the TF doc for loop, it says 
```
    maximum_iterations: Optional maximum number of iterations of the while loop
      to run.  If provided, the `cond` output is AND-ed with an additional
      condition ensuring the number of iterations executed is no greater than
      `maximum_iterations`.
```
which is the same as the ONNX loop, ie. max trip count `M` should be left as empty if not used. 
So in the conversion shouldn't the `M` field just be left empty?

The reason maxint causes a problem for TRT is that TRT allocates memory for output tensor based on `M` if the loop exit condition cannot be determined at build time.

**Comment by hwangdeyu** [comment]
> Hi @hwangdeyu thank you for your reply!
> 
> I couldn't find any TF documentation that says -1 stands for inf. Can you point me to where this is documented? In the TF doc for loop, it says
> 
> ```
>     maximum_iterations: Optional maximum number of iterations of the while loop
>       to run.  If provided, the `cond` output is AND-ed with an additional
>       condition ensuring the number of iterations executed is no greater than
>       `maximum_iterations`.
> ```
> 
> which is the same as the ONNX loop, ie. max trip count `M` should be left as empty if not used. So in the conversion shouldn't the `M` field just be left empty?
> 
> The reason maxint causes a problem for TRT is that TRT allocates memory for output tensor based on `M` if the loop exit condition cannot be determined at build time.

About TF `maxinum_iterations` , we get it from the `input[1]` of `While` TF operator.
The default value is `-1`, we can find it in  https://github.com/tensorflow/tensorflow/blob/363ef860e56b19f8e62b42950b23f84857d80bfb/tensorflow/python/ops/while_v2.py#L1399. 

For the `Loop` maxint issue, the maxint `M` is approximately equal with empty `M`. But I really agree with you to express it with empty which would more match ONNX standard. I created an issue https://github.com/onnx/tensorflow-onnx/issues/1969 to trace it.

**Comment by hwangdeyu** [comment]
Hi @yuanyao-nv,
back to the `Out of memory issue`, the root cause should be relative to the **tensorrt maximum workspace limits** instead of the Loop M issue.

I converted both the `SimpleRNN` and `LSTM` model to onnx and tried to run it with `TensorrtExecutionProvider` using onnxruntime.
However, I found both of the models could be run successfully if I set a small `batch size` as input. And if I increased the `batch size` of input, the `out of memory` exception would be thrown out for both of them. At the same time, there were still a lot of free memories on the machine. However, if I set a high 'trt_max_workspace_size' in `TensorrtExecutionProvider`, the models could be run successfully again.


Finally, I think the error should come from TensorRT 8.2 tensorrt maximum workspace limits. TensorRT 8.4 will eliminate this limit.
https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-8.html#rel-8-4-1
Refer from [nvidia tensorrt documentaion ](https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-8.html#rel-8-4-1)
>The --workspace flag in trtexec has been deprecated. TensorRT now allocates as much workspace as available GPU memory by default when the --workspace/--memPoolSize flags are not added, instead of having 16MB defaulhttps://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntaxt workspace size limit in the trtexec in TensorRT 8.2.


I think of two ways may help you to fix this issue:
1. Set a high 'trt_max_workspace_size' in `TensorrtExecutionProvider` or `--memPoolSize=workspace:<size>` flag in TensorRT.
my test code
```
import onnx
import numpy as np
saved_model_path = "SimpleRNNmodel.onnx"
onnx_model = onnx.load(saved_model_path)
onnx.checker.check_model(onnx_model)

## Run the model in ONNXRuntime to verify the result.
import onnxruntime as ort
input = np.arange(1024**3).reshape(1024**2, 32, 32).astype(np.float32)
ort_session = ort.InferenceSession(saved_model_path, providers=[('TensorrtExecutionProvider', {'trt_max_workspace_size': 107374182400})]) # default value 1073741824
ort_inputs = {ort_session.get_inputs()[0].name: input}
print("providers:", ort_session.get_provider_options())

## Measure inference time
import datetime
start_time = datetime.datetime.now()
ort_outs = ort_session.run(None, ort_inputs)
end_time = datetime.datetime.now()
print("input:", input.shape, "\nort_outs:", ort_outs, (end_time - start_time))
```
2. Upgrade your TensorRT version to 8.4

**Comment by yuanyao-nv** [comment]
Thanks @hwangdeyu for opening the ticket for empty `M`. Hopefully it will be addressed soon.
When I run with TRT 8.4 using the `trtexec` CLI I get this error 
```
Error Code 4: Internal Error (StatefulPartitionedCall/sequential/simple_rnn/while_loop:6: tensor volume exceeds (2^31)-1, dimensions are [2147483647,1,10])
```
It's not related to batch size since bs=1 here. It comes from TRT trying to be conservative and allocating memory based on `M` (after casting to int32).

**Comment by yuanyao-nv** [comment]
I verified that now TRT works with `M` set to empty string. Thanks very much for your help, @hwangdeyu !
