### ISSUE TITLE
Is it possible to stop tf2onnx from removing subgraphs with constant outputs from TensorFlow SavedModel

### ISSUE THREAD

**Issue by meghendra** [onnx/tensorflow-onnx#1956]
I am trying to convert a TF 2.0 object detection model: [SSD MobileNet v2 320x320](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz) to ONNX using tf2onnx using opset 13 as follows:

`python -m tf2onnx.convert --saved-model .\SSD_mobilenet\ --output .\SSDMobilenet_v2.onnx --opset 13`

What I observe is that the ONNX model removes certain subgraphs from the TF model that seem to have constant output tensors and replace them with initializer inputs in destination nodes. 

For example, in the original TF model the node `StatefulPartitionedCall/Postprocessor/Decode/mul` has two inputs, one of which is coming in from the subgraph `StatefulPartitionedCall/Postprocessor/Decode/get_center_coordinates_and_sizes`, i.e., `StatefulPartitionedCall/Postprocessor/Decode/get_center_coordinates_and_sizes/sub:0` (See TensorBoard screenshot below):
![image](https://user-images.githubusercontent.com/4872638/171237055-de3e2346-a7df-4cd4-b0cb-998f11e38bf1.png)

In the converted ONNX model `SSDMobilenet_v2.onnx` the `StatefulPartitionedCall/Postprocessor/Decode/get_center_coordinates_and_sizes` subgraph is absent and the second input of `StatefulPartitionedCall/Postprocessor/Decode/mul` has been replaced by an Initializer (See Netron screenshot of the ONNX model below):
![image](https://user-images.githubusercontent.com/4872638/171243121-c89d5fdb-c135-420f-82c0-edc989a36c48.png)

It would be very helpful if someone can answer the following for me:
1. Is this a consequence of constant-folding? If yes, how can I disable it?
2. As suggested in [1027](https://github.com/onnx/tensorflow-onnx/issues/1027), I commented out all of the optimizers (Lines 24 to 37) in `tf2onnx\optimizer\__init__py`, but the  subgraph `StatefulPartitionedCall/Postprocessor/Decode/get_center_coordinates_and_sizes` still gets removed and the second input of `StatefulPartitionedCall/Postprocessor/Decode/mul` still gets converted to an initializer. Is there any way to avoid the removal of this subgraph and this constant folding behavior?
3.  I also tried commenting out calls to `fold_constants_using_tf` from `tf2onnx\tfonnx.py` but I don't see a difference in output. Is the constant folding happening somewhere else, how can I disable it?

**Comment by hwangdeyu** [comment]
Hi @meghendra , thanks for your contributing issue. Yes it's a consequence from const-fold.
tf2onnx would do twice different const-folding during one conversion. You removed the second one in optimizer.
And the first one is bassically from https://github.com/onnx/tensorflow-onnx/blob/a8f78ac7903493dee579304b7b1717aa9ec9706f/tf2onnx/tf_loader.py#L687 If you do want to remove the behavior in this issue, you can just comment `constfold` in this line.
