### ISSUE TITLE
Validate ONNX 1.12.0 release candidate

### ISSUE THREAD

**Issue by garymm** [onnx/tensorflow-onnx#1966]
Please help us test ONNX 1.12.0 by running your tests with it installed.
https://test.pypi.org/project/onnx/1.12.0rc5/

**Comment by garymm** [comment]
rc5 is ready now, please use that

**Comment by fatcat-z** [comment]
rc4 has passed without any issues.

**Comment by fatcat-z** [comment]
rc5 has passed without any issues.

**Comment by garymm** [comment]
Thanks.
