### ISSUE TITLE
Force output to have chw layout

### ISSUE THREAD

**Issue by devalexqt** [onnx/tensorflow-onnx#1973]
Even if I specify my input is `chw`, output still has `hwc` layout. 
How to fix this?
```
python -m tf2onnx.convert  --opset 13 --saved-model  model --output  model.onnx --inputs input:0[1,256,256,3] --inputs-as-nchw input:0 --rename-inputs input
```

![onnx_input-chw](https://user-images.githubusercontent.com/865007/174071287-0980b389-ba8f-4941-9cfc-048fc4fab457.png)
![onnx_output-edit](https://user-images.githubusercontent.com/865007/174071233-b157f788-7caa-4409-a5c8-40b9a36ea3fe.png)

**Comment by hwangdeyu** [comment]
hi @devalexqt  Could you share your save_model then we can take a look if it‘s something about optimizer in tf2onnx?

**Comment by devalexqt** [comment]
Model can be downloaded here:
https://drive.google.com/file/d/1tdim-rnz6xK2zbZ-_NO9FW6__wF0DRCU/view?usp=sharing
It's just simple autoencoder model with bunch of Conv/Deconv layers, nothing special.

**Comment by hwangdeyu** [comment]
Thanks @devalexqt for providing it, the `--inputs-as-nchw` is only for specifying input as `nchw` to match the ONNX standard.
Now tf2onnx don't support  `--outputs-as-nchw` so far, we have not seen much models where this applies. 
We can do it manually. Could you tell us which scenario requires it?

**Comment by devalexqt** [comment]
Thanks.
In my case it's about performance, as you can see provided model is for upscale image by 4x, where output is about 1024x1024 or even 2048x2048. And output transpose layer can take up to 50% of total model execution time, and then I need transpose it again to chw, so I just lost lot of milliseconds.
In production I use converted onnx model on CPU where chw format is up  to 2x faster in comparison to hwc. 

Please add option to force output to chw.

**Comment by andife** [comment]
I would also be very interested in this functionaliy, also because of speed issues. My use case would be semantic segmentation.
With for example using the dnn module of opencv with onnx, it is quite nice using selecting the output layer for different classes when I have the nchw format. For the current hwc format I've to manually reorder the output, which is quite slow.

**Comment by hwangdeyu** [comment]
> I would also be very interested in this functionaliy, also because of speed issues. My use case would be semantic segmentation. With for example using the dnn module of opencv with onnx, it is quite nice using selecting the output layer for different classes when I have the nchw format. For the current hwc format I've to manually reorder the output, which is quite slow.

Thanks for sharing your case, we'll add this feature later.

**Comment by hwangdeyu** [comment]
@devalexqt  We have added `--outputs_as_nchw` option is supported it in latest main branch. Please tell me if it's work for your model demand Thanks!

**Comment by devalexqt** [comment]
Thnks!
Now its working as expected!
