### ISSUE TITLE
Add support for `flatbuffers>=2.0`

### ISSUE THREAD

**Issue by stancld** [onnx/tensorflow-onnx#1977]
Hello all 👋

First of all, I'd like to thank you for this great repo and package!

I would like to ask you if there's any plan to add support for `flatbuffers>=2.0` in a perceivable future? :] Also, if interested, I'm definitely willing to give a try to handle these breaking changes and try to accommodate supports for both versions (It looks like there are some breaking changes between versions `1.12` and `2.0`).

**Comment by stancld** [comment]
Oh, sorry for the false alarm. It's rather an issue of TF itself. :]

**Comment by janbernloehr** [comment]
tf 2.10 switched to flatbuffers 2.0 so we should reopen this

**Comment by benquan** [comment]
When installing:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.10.0 requires flatbuffers>=2.0, but you have flatbuffers 1.12 which is incompatible.
```

**Comment by stancld** [comment]
@fatcat-z Thanks a lot for the fix! 🚀
