### ISSUE TITLE
Python 2.7 support

### ISSUE THREAD

**Issue by lutzroeder** [onnx/tensorflow-onnx#198]
```
~: pip install tf2onnx
Collecting tf2onnx
  Could not find a version that satisfies the requirement tf2onnx (from versions: )
No matching distribution found for tf2onnx
```

**Comment by guschmue** [comment]
we don't fully support python 2.7, but it comes up from time to time and we might add it.
We depend on tensorflow which does not support 2.7 on windows so this will only work on linux.
