### ISSUE TITLE
Inquiry/Request for TF-2.9.x Support

### ISSUE THREAD

**Issue by q-ycong-p** [onnx/tensorflow-onnx#1991]
**Describe the issue**
Tensorflow-2.9.0 was released on May 16. Looking at the tf2onnx README on `main`, it supports until TF-2.8.0 at the moment. Is there any plan/timeline for extending tf2onnx's support of TF-2.9.x? Would really appreciate if any known issue that's blocking this support can be shared for tracking/contribution purpose? Thanks a lot!

**Comment by fatcat-z** [comment]
So far, we don't see any block issues for supporting tf-2.9.0, we will update the document soon along with our next release.

At this moment, please feel free to start working with tf-2.9.x and file an issue here if any problem.

**Comment by q-ycong-p** [comment]
Got it, thank you for your prompt response @fatcat-z. I'll work on local testing for tf-2.9.1 and post update/issue in this thread.

**Comment by fatcat-z** [comment]
> Got it, thank you for your prompt response @fatcat-z Jay Zhang FTE. I'll work on local testing for tf-2.9.1 and post update/issue in this thread.

Thanks for your support. I'd like to suggest you close this issue and file new issues for any problem you met so we can take a good track for each of them.

**Comment by q-ycong-p** [comment]
Got it, make sense. Closing this issue. Thank you!

**Comment by q-ycong-p** [comment]
Hi @fatcat-z, is there a rough estimate of the next release date (where TF-2.9.x will be listed as supported)? Thanks!

**Comment by fatcat-z** [comment]
> Hi @fatcat-z Jay Zhang FTE, is there a rough estimate of the next release date (where TF-2.9.x will be listed as supported)? Thanks!

Will deliver a release for this no later than the end of July.
