### ISSUE TITLE
ZerosLike inserts Casts before Mul

### ISSUE THREAD

**Issue by guschmue** [onnx/tensorflow-onnx#1997]
Happens for example in ssd-mobilenet from here:
https://github.com/mlcommons/inference/tree/master/vision/classification_and_detection
Large amount of Mul nodes in the model, sandwiched between two cast nodes, which is fairly costly.

![image](https://user-images.githubusercontent.com/10047193/179469732-7fd59173-b446-4abb-888f-1811d972c887.png)

I belief this Casts came in because pre opset-7 onnx and onnxruntime did not support int64 for mul.

**Comment by hwangdeyu** [comment]
Replace `cast + mul(value 0) + cast` to `shape + ConstantShape(value 0)`, which can make a significant latency reduction.
