### ISSUE TITLE
'TypeError: value "unknown_rank: true " is not valid attribute data type' for model with TensorArrayConcatV3

### ISSUE THREAD

**Issue by pks** [onnx/tensorflow-onnx#2025]
Hi,

I'm trying to convert a seq2seq Tensorflow v1.x model but get the following error when calling `python -m tf2onnx.convert --checkpoint [...]`:

```
2022-08-12 12:00:41,703 - INFO - Using tensorflow=2.9.1, onnx=1.12.0, tf2onnx=1.12.0/a58786
2022-08-12 12:00:41,703 - INFO - Using opset <onnx, 17>
2022-08-12 12:00:50,655 - ERROR - pass1 convert failed for name: "[redacted]/cond/while/TensorArrayConcatV3"
op: "TensorArrayConcatV3"
input: "[redacted]/cond/while/TensorArrayConcatV3/Enter"
input: "[redacted]/cond/while/Identity_2"
attr {
  key: "dtype"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "element_shape_except0"
  value {
    shape {
      unknown_rank: true
    }
  }
}
, ex=value "unknown_rank: true
" is not valid attribute data type.
[redacted stacktrace]
TypeError: value "unknown_rank: true
" is not valid attribute data type.
```

I'd appreciate any pointer to make this work. I could only find this https://github.com/onnx/tensorflow-onnx/issues/1395 issue, but it is different from mine.

**Comment by fatcat-z** [comment]
Somehow, the frozen tensorflow graph contains an attribute "unknown_rank" which is not valid.

Since the model is TF v1.x version, could you please try this with TF v1.15? If still got the same issue, is it possible you can share the checkpoint with us so we can have a local debug?

**Comment by pks** [comment]
Thanks @fatcat-z. Unfortunately we cannot go back to TF1.15 with our codebase. However, in the meantime we gave up on this approach. Thanks for looking into it anyway!
