### ISSUE TITLE
should we put None in output_shapes if there is no shape returned from TF API call

### ISSUE THREAD

**Issue by pengwa** [onnx/tensorflow-onnx#203]
in following code, if there is exception happens, shape is assigned to []. My understanding is that scalar will have shape (), right? 

so we will have conflict?  @guschmue 

```

    for node in ops:
        for out in node.outputs:
            shape = shape_override.get(out.name)
            if shape is None:
                try:
                    shape = out.get_shape().as_list()
                except Exception as ex:
                    shape = None
            dtypes[out.name] = utils.map_tf_dtype(out.dtype)
            output_shapes[out.name] = shape
```

**Comment by pengwa** [comment]
the left is output_shapes with "shape=None" when exception happens
the right is with "shape=[]" when exception happens. 

be noted: 'rnn/time:0' is a scalar, but in the right part, we can distinguish whether rnn/time:0's shape is valid or not. 

![image](https://user-images.githubusercontent.com/10530022/48834114-eca78600-edb7-11e8-8b16-09f01357b89f.png)


![image](https://user-images.githubusercontent.com/10530022/48834130-f6c98480-edb7-11e8-8a04-7c881a55e0d2.png)

**Comment by guschmue** [comment]
yes, [] should be better. I don't know if this ever throws, maybe a log.warning() might be good too.

**Comment by pengwa** [comment]
@guschmue  now it's [] in code. I suggested to change to None. So any specific historical reason why [] is better?

**Comment by guschmue** [comment]
tf will use [].

**Comment by pengwa** [comment]
the problem for me is: when I use ctx.get_shape(), it returns [], how could we know it is a Unknown shape or a known scalar value.

**Comment by guschmue** [comment]
if I remember correctly for unknown rank tensorflow returns [] with another attribute unknown_rank set.
How about using [] for scalar and None for unknown rank?

**Comment by pengwa** [comment]
yeah, "How about using [] for scalar and None for unknown rank?" is actual the point I mentioned here. One change for doing this, is to change line https://github.com/onnx/tensorflow-onnx/blob/f034e55fa6064954105e6477a74686937cd98aef/tf2onnx/tfonnx.py#L80 to "shape = None". How do you think about this?

**Comment by pengwa** [comment]
@guschmue as far as I tested, if no shaped got from original tf graph, it will hit there.

**Comment by pengwa** [comment]
fix already in master. https://github.com/onnx/tensorflow-onnx/pull/206
