### ISSUE TITLE
Error loading   oidv2-resnet_v1_101.ckpt  after converting to tflite 

### ISSUE THREAD

**Issue by creativesh** [onnx/tensorflow-onnx#2037]
Hi , 

I got oidv2-resnet_v1_101.ckpt from [https://storage.googleapis.com/openimages/web/extras.html](url) and convert it to tflite with this code : 

`SAVED_MODEL_DIR='saved_model1/'
converter = tf.lite.TFLiteConverter.from_saved_model(
    saved_model_dir=SAVED_MODEL_DIR)
converter.optimizations = {tf.lite.Optimize.DEFAULT} #optional sh
converter.change_concat_input_ranges = True #optional sh
converter.target_spec.supported_ops = [  #should be
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_model = converter.convert()
open("new1.tflite", "wb").write(tflite_model)`

it was converted successfully and I could load it with python interpreter and get valid results.

However, when I want to load the file in android it is not loaded with this error: 

![screen](https://user-images.githubusercontent.com/22853189/188314681-72e0b45c-ddd9-4346-9d9a-eb31b1ea2a24.jpg)

apparently the problem is with model input type :

![nepton_tagging](https://user-images.githubusercontent.com/22853189/188314768-7b478cc0-ee77-4df1-9746-f0208dbc8491.png)

How can  I fix it ?

**Comment by fatcat-z** [comment]
Could you please share me the exact download url of oidv2-resnet_v1_101.ckpt so I could do a local debug?

**Comment by creativesh** [comment]
@fatcat-z 

yes,  this is the link of the model checkpoint:

[](https://storage.googleapis.com/openimages/2017_07/oidv2-resnet_v1_101.ckpt.tar.gz) 

and the other necessary items are in the page :
https://storage.googleapis.com/openimages/web/extras.html

**Comment by fatcat-z** [comment]
Looks like I missed something before. If you are trying to convert a tf model to tflite, probably this issue should be opened under tensorflow repo. Tf2onnx focuses on converting a tf model or tflite model to ONNX.
