### ISSUE TITLE
Question/help: model.predict_on_batch equivalent

### ISSUE THREAD

**Issue by alanwilter** [onnx/tensorflow-onnx#2039]
I'm trying to refactor our code (yet I'm new to ML/AI).

My current code using `TF` is like:

```python
...
from tensorflow.keras.models import load_model
...
model = load_model("models/layer.h5", compile=False)
...
def process(model, img):
    x_h, x_w = 1024, 768
    x_in = np.zeros((1, x_h, x_w, 1))

    h, w = img.shape
    dh = (x_h - h) // 2
    dw = (x_w - w) // 2

    x_in[0, dh : dh + h, dw : dw + w, 0] = img / 255

    ensemble = np.array([model.predict_on_batch(x_in[:, :, ::-1, :])[0, :, ::-1, :], model.predict_on_batch(x_in)[0]])
...
```

I had no problem refactoring cases with `model.predict()` and though I do know what `model.predict_on_batch()` is supposed to do, I'm failing to abstract how to implement that using module `onnxruntime`.

Any help is very appreciated.

**Comment by fatcat-z** [comment]
Do you mean you are trying to find a way to inference the model/layer.h5 by onnxruntime?

**Comment by alanwilter** [comment]
I mean, I did something quick and dirty:

```python
import onnxruntime as rt
...
def pred_onnx(model, x):
    x = x.astype(np.float32)
    input_name = model.get_inputs()[0].name
    label_name = model.get_outputs()[0].name
    results_ort = model.run([label_name], {input_name: x})
    return results_ort[0]
```
then:

```python
...
ensemble = np.array([pred_onnx(model, x_in[:, :, ::-1, :])[0, :, ::-1, :], pred_onnx(model, x_in)[0]])
# ensemble = np.array([model.predict_on_batch(...
...
```
which, to my understand, `pred_onnx()` is a simple replacement of `model.predict()` under `onnxruntime`.

But I got the same results 3x faster compared to TF. However, I know `model.predict_on_batch()` is faster than just `model.predict()` so it left me wondering if I could tailor my input batch for `pred_onnx()`, I just don't know how, whether it's actually the case.

**Comment by fatcat-z** [comment]
According to your code, pred_onnx() didn't call onnxruntime, so the result has no relationship with onnxruntime.

If you want to leverage onnxruntime, you have to call tf2onnx to convert the tf model to onnx. Then you can load and inference it by onnxruntime.

**Comment by alanwilter** [comment]
Sorry, it does! I just forgot to emphasise that, I've amended my example above. And yes, I've used `tf2onnx`.

**Comment by fatcat-z** [comment]
Got your points.

The way you convert a TF model to ONNX model is not related to predict() and predict_on_batch() methods. ONNXRUNTIME will use the converted onnx file to do an inference, so this process has no relationship to either predict() or predict_on_batch() method.

IIUC, model.predict_on_batch() is faster than model.predict() just because the assumption of their inputs is different, so this won't be impacted by onnxruntime.

**Comment by alanwilter** [comment]
Thanks @fatcat-z. It's a non-issue and it's working and it's faster anyway than TF. Just learning.
