### ISSUE TITLE
(extract_sub_graph is deprecated and will be removed in a future version) Python API from_keras

### ISSUE THREAD

**Issue by benquan** [onnx/tensorflow-onnx#2049]
**Describe the bug**
When running tf2onnx.convert.from_keras(model) I get the following warning:
```
WARNING:tensorflow:From /Users/ben/tensorflow/lib/python3.8/site-packages/tf2onnx/tf_loader.py:715: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
```

**Urgency**
Warning

**System information**
- MacOS
- TensorFlow Version: 2.10
- Python version: 3.8.2

**To Reproduce**
convert from keras from the python api
```
  import tf2onnx, onnx
  onnx_model, _ = tf2onnx.convert.from_keras(model)
  onnx.save(onnx_model, "model.onnx")
```

**Comment by fatcat-z** [comment]
What's the version of your tf2onnx?

In latest version of tf2onnx, if your TensorFlow version is 2.x, you will call extract_sub_graph() for conversion.
