### ISSUE TITLE
Support for Tensorflow 2.10

### ISSUE THREAD

**Issue by gcuder** [onnx/tensorflow-onnx#2060]
# Ask a Question

### Question
Are there any plans to support `tensorflow 2.10` in the future? If yes, can you give an approximate time estimate?

**Comment by graille** [comment]
Well, It seems that the only real issue with Tensorflow 2.10 is the version of flatbuffers. This issue has been addressed in #1977 and fixed in #2050 . But I don't know why any minor update hasn't been published since...

**Comment by gcuder** [comment]
Thank you for the fast answer to my question @graille. Do you know who is responsible for doing releases? Maybe we can tag the responsible person here?

**Comment by fatcat-z** [comment]
The next release will be published along with latest ORT 13. It will probably be published this week and no later than the end of next week.

**Comment by fsvenson** [comment]
ORT 13 was released a week ago, when will this fix be published?

**Comment by fatcat-z** [comment]
> ORT 13 was released a week ago, when will this fix be published?

Sorry for the delay, it has been published https://github.com/onnx/tensorflow-onnx/releases/tag/v1.13.0.
