### ISSUE TITLE
"compute_const_folding_using_tf" can result in infinite loop when converting well-formed model

### ISSUE THREAD

**Issue by christopherbate** [onnx/tensorflow-onnx#2068]
**Describe the bug**

When converting a model that has dynamic strided slice operations, the function `compute_const_folding_using_tf` can result in an infinite loop.

**System information**
- TensorFlow Version: Built from souce a couple days ago
- Python version: 3.8

**To Reproduce**

Unfortunately I cannot share the reproducer model, but it is a well-formed tensorflow saved model. The conversion succeeds if I manually disable the constant folding for the StridedSlice operation here https://github.com/onnx/tensorflow-onnx/blob/main/tf2onnx/tf_utils.py#L212. 

The original PR for this feature (https://github.com/onnx/tensorflow-onnx/pull/1145/files#diff-31e088e0e9d455d2164fd6251e7c23a77afc5561b3746cdf83e08d6a05142154) had very limited tests and did not include the dynamic bounds case.

**Comment by fatcat-z** [comment]
It is totally understood that some models are not allowed to be shared. Is it possible to cut your scenario so that you can provide a small case which could possibly reproduce this issue?

**Comment by christopherbate** [comment]
My workaround is to disable the strided slice constant folding and handle it elsewhere in my workflow. If I have additional time, I'll probably spend it directly troubleshooting. I think the best place to start is to upgrade the unit tests I mentioned above. Otherwise, I'll let you know if I find out a better root cause.

**Comment by fatcat-z** [comment]
> My workaround is to disable the strided slice constant folding and handle it elsewhere in my workflow. If I have additional time, I'll probably spend it directly troubleshooting. I think the best place to start is to upgrade the unit tests I mentioned above. Otherwise, I'll let you know if I find out a better root cause.

Thanks for your efforts and share. Will definitely take a look to review related test case to see if there is a chance to repro your issue.

**Comment by hgong-snap** [comment]
https://github.com/onnx/tensorflow-onnx/issues/1965

@fatcat-z   this is a similar issue  and it has a reproduce file.  can you also take a look?  thanks !

**Comment by christopherbate** [comment]
Can you remove "pending user response"? I'm not planning on working on this anymore as I went with a different route.

**Comment by hgong-snap** [comment]
@christopherbate   wondering any other workaround for this infinite loop?

**Comment by fatcat-z** [comment]
> Can you remove "pending user response"? I'm not planning on working on this anymore as I went with a different route.

Sorry for misunderstanding, this is only for us to manage these issues and no impact to you. But will take your advice to remove it from this issue.

**Comment by goha111** [comment]
@fatcat-z   Hi! any update on this bug? this can happen quite common for several models on my hand
