### ISSUE TITLE
ONNX MatMulInteger support

### ISSUE THREAD

**Issue by GregoryMorse** [onnx/tensorflow-onnx#2071]
### Describe the feature request

The ONNX specification since opset 10 has specified a MatMulInteger operation which allows uint8/int8 types among other things.  MatMul specifically does not allow this size.

Currently only MatMul is support, and uint8/int8 will fail to compile per the ONNX spec on that operation.

### Describe scenario use case

Any places where small integer arithmetic is used, specifically when computing matrix multiplication with uint8/int8 matrix x uint8/int8 matrix -> int32 matrix.

**Comment by fatcat-z** [comment]
Close this issue since the PR has been merged. Feel free to reopen it if necessary.
