### ISSUE TITLE
How to replace custom tf-op in a network with onnx op? 

### ISSUE THREAD

**Issue by FabianSchuetze** [onnx/tensorflow-onnx#2078]
I like to convert an existing tf model containing a custom tf op (written in c++) in its graph to onnx. The custom op does not need to be trained and holds no weights but is used for post-processing. The onnx conversion of the entire model works with the `--custom-ops` and `--load_op_libraries` options.

However,  when I want to run the in triton, I still need to link against tf which I want to avoid. Should I, therefore, write a custom onnx op? I read two nice tutorials [here](https://github.com/microsoft/onnxruntime-extensions/blob/main/tutorials/tf2onnx_custom_ops_tutorial.ipynb) and [here](https://github.com/onnx/tensorflow-onnx/blob/main/examples/tf_custom_op/custom_op.md) but I do not understand how to replace a custom tf-op with the onnx op. In the tutorial, the custom-ops seem to me to be used as a standalone network. 

What should I do to convert tf-model with a custom-op to onnx so that it can be loaded in triton without linking against tensorflow?

**Comment by fatcat-z** [comment]
(I assume you are trying to run the ONNX model in Triton.)
Firstly, you need to know how to implement this custom tf op in ONNX.
We have 2 ways to do this:
1. For a custom tf op, we might implement its function by combining different existing ONNX ops together. This [example](https://github.com/onnx/tensorflow-onnx/blob/main/examples/tf_custom_op/custom_op.md#convert-the-operator-to-onnx) demonstrates how to use existing ONNX op to implement the function of new tf op DoubleAndAddOne. So when ONNXRuntime loads this onnx file, it recognizes every op. We don't need to do anything new in ONNX runtime.

2. We can't find a solution to combine existing ONNX ops together to implement the function of new tf custom op. Then we need to define a new ONNX op which has the same function as that tf custom op. In the op handler of tf2onnx, we directly put the new custom onnx op into the ONNX graph. And then follow [this document](https://github.com/microsoft/onnxruntime/blob/main/docs/onnxruntime_extensions.md#onnxruntime-extensions) to implement a new onnx op in ONNX runtime. Then you can run this new ONNX model in triton without TF.

**Comment by FabianSchuetze** [comment]
Thanks for your reply, @fatcat-z  - that was very helpful to me.

**Comment by KingsleyLiu-NV** [comment]
@fatcat-z For the first case (custom TF op can be replaced by combining existing ONNX ops), can we do it in a CLI manner? I do not like using the tf2onnx Python APIs as the [example](https://github.com/onnx/tensorflow-onnx/blob/main/examples/tf_custom_op/custom_op.md#convert-the-operator-to-onnx) shows.

**Comment by fatcat-z** [comment]
> My use case is that there is a TF2 SavedModel that has a custom TF op (combining existing ONNX ops can make it). The [example](https://github.com/onnx/tensorflow-onnx/blob/main/examples/tf_custom_op/custom_op.md#convert-the-operator-to-onnx) does not really demonstrate how to deal with this case.
> 
> * While implementing the custom TF op handler, the `ctx.make_node` and `ctx.insert_new_node_on_output` APIs are confusing for me.
> * Not sure how to enable this TF op handler in the CLI usage of tf2onnx.

Unfortunately, there is no plan to support such work to be done in a CLI manner. The TF op handler in tf2onnx, actually is trying to transfer each TF op/custom op into a (or a set of) ONNX ops. 

ctx.make_node() will create a new ONNX node in the final ONNX graph, with specified inputs and outputs. The new node has no relationship with any existing nodes in the ONNX graph. ctx.insert_new_node_on_output() will create and insert one new node into the outputs of current node in the final ONNX graph.

**Comment by KingsleyLiu-NV** [comment]
Thanks for the reply, than I will load SavedModel and then convert with Python APIs to handle the custom TF op.
