### ISSUE TITLE
Supporting onnx opset 18

### ISSUE THREAD

**Issue by fsalv** [onnx/tensorflow-onnx#2083]
Is it possible to have an approximate time estimate for supporting onnx opset 18?

In particular, I'm interested in [BitwiseAnd](https://github.com/onnx/onnx/blob/main/docs/Operators.md#BitwiseAnd) and [BitwiseXor](https://github.com/onnx/onnx/blob/main/docs/Operators.md#BitwiseXor) operators.

Since onnx appears to already support them, are there any workarounds to make them work with current tf2onnx version?

**Comment by fatcat-z** [comment]
Since ONNXRuntime doens't support opset 18 yet, there is no plan for tf2onnx to deliver a new release to support it at this moment.
