### ISSUE TITLE
huge memory consumption on loop-model

### ISSUE THREAD

**Issue by fischeruben** [onnx/tensorflow-onnx#2108]
**Describe the bug**
I have a gram schmidt orthogonalization implemented in tensorflow that I export in the onnx format.
When running the model in tensorflow it requires 1.8 GB on the GPU. When running the exported onnx-model it requires 4.3 GB.

The involved matrix is 600MB big, so I would expect a memory consumption of around 1.2 GB. tf is close enough, but onnx uses too much memory.

Is this a limitation of the underlying onnx-framework or is this an issue of the conversion?

**Urgency**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04*): Windows 10
- TensorFlow Version: 2.6
- Python version: 3.9
- ONNX version (if applicable, e.g. 1.11*): 1.13.0
- ONNXRuntime version (if applicable, e.g. 1.11*): 1.13.1

**To Reproduce**
```
import os
import numpy as np
import tensorflow as tf
import tf2onnx
import onnx


class Orthonormalisation (tf.Module):

     def __init__(self, name="orthonormalisation"):
         super().__init__(name)

     """
     Orthonormalises input vectors via Gram-Schmidt.

     @params:
       - vector: double matrix containing N vectors from an D-Dimensional space,
                 where N << D. vectors has shape [N, D]
     @returns: orthonormalised vectors of same shape and dtype
     """
     @tf.function(input_signature=(tf.TensorSpec(shape=(None, None), dtype=tf.float64),))
     def __call__(self, vectors):
        N = tf.shape(vectors)[0]

        orthn_vectors = vectors[0:1, :]
        orthn_vectors /= tf.norm(orthn_vectors)

        for n in range(1, N):
            v = vectors[n:n+1, :]
            orthn_v = v - tf.reduce_sum(tf.reduce_sum(v*orthn_vectors, axis=1, keepdims=True)*orthn_vectors, axis=0)
            orthn_v /= tf.norm(orthn_v)
            orthn_vectors = tf.concat([orthn_vectors, orthn_v], axis=0)

        return orthn_vectors

model = Orthonormalisation()
model_proto, _ = tf2onnx.convert.from_function(model.__call__, input_signature=(tf.TensorSpec(shape=(None, None), dtype=tf.float64),))

dir_out = "."
onnx.save(model_proto, os.path.join(dir_out, model.name + '.onnx'))

# run in tf
tf.config.LogicalDeviceConfiguration(memory_limit=2000)
model(np.random.normal(size=(50, 1500000)).astype(np.float64))

print("peak memory consumption (MB):", tf.config.experimental.get_memory_info("GPU:0")["peak"]/1e6)
```

and then
```
import onnxruntime as ort
import numpy as np
import os

ort.set_default_logger_severity(0)

dim = 1500000
n_base = 50

matrix_in = np.random.normal(size=(n_base, dim)).astype(np.float64)

# onnx orthonormalisation
ort_sess = ort.InferenceSession(os.path.join(".", "orthonormalisation.onnx"), providers=['CUDAExecutionProvider'])
ort_sess.run(None, {"vectors": matrix_in})
```

Output when running in tensorflow:
2023-01-30 07:53:49.306066: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-30 07:53:50.182724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 20110 MB memory:  -> device: 0, name: NVIDIA RTX A5000, pci bus id: 0000:21:00.0, compute capability: 8.6
2023-01-30 07:53:50.184130: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 20110 MB memory:  -> device: 1, name: NVIDIA RTX A5000, pci bus id: 0000:4a:00.0, compute capability: 8.6
2023-01-30 07:53:50.809163: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
peak memory consumption (MB): 1800.00128

Parts of the verbose output of the onnx session:
2 0 2 3 - 0 1 - 3 0   0 7 : 4 0 : 2 4 . 0 6 1 2 7 8 8   [ I : o n n x r u n t i m e : ,   i n f e r e n c e _ s e s s i o n . c c : 2 6 3   o n n x r u n t i m e : : I n f e r e n c e S e s s i o n : : C o n s t r u c t o r C o m m o n : : < l a m b d a _ c 0 8 c 6 d e 2 4 2 b 5 d 7 a 4 a 5 a 2 7 d 7 4 f 0 c 7 d 6 a 3 > : : o p e r a t o r   ( ) ]   F l u s h - t o - z e r o   a n d   d e n o r m a l - a s - z e r o   a r e   o f f
 2 0 2 3 - 0 1 - 3 0   0 7 : 4 0 : 2 4 . 0 7 4 5 6 7 9   [ I : o n n x r u n t i m e : ,   i n f e r e n c e _ s e s s i o n . c c : 2 7 1   o n n x r u n t i m e : : I n f e r e n c e S e s s i o n : : C o n s t r u c t o r C o m m o n ]   C r e a t i n g   a n d   u s i n g   p e r   s e s s i o n   t h r e a d p o o l s   s i n c e   u s e _ p e r _ s e s s i o n _ t h r e a d s _   i s   t r u e
 2 0 2 3 - 0 1 - 3 0   0 7 : 4 0 : 2 4 . 0 7 7 7 3 2 3   [ I : o n n x r u n t i m e : ,   i n f e r e n c e _ s e s s i o n . c c : 2 9 2   o n n x r u n t i m e : : I n f e r e n c e S e s s i o n : : C o n s t r u c t o r C o m m o n ]   D y n a m i c   b l o c k   b a s e   s e t   t o   0
 2 0 2 3 - 0 1 - 3 0   0 7 : 4 0 : 2 4 . 0 8 3 9 4 6 3   [ I : o n n x r u n t i m e : ,   i n f e r e n c e _ s e s s i o n . c c : 1 2 2 2   o n n x r u n t i m e : : I n f e r e n c e S e s s i o n : : I n i t i a l i z e ]   I n i t i a l i z i n g   s e s s i o n .
 2 0 2 3 - 0 1 - 3 0   0 7 : 4 0 : 2 4 . 0 8 7 6 5 4 1   [ I : o n n x r u n t i m e : ,   i n f e r e n c e _ s e s s i o n . c c : 1 2 5 9   o n n x r u n t i m e : : I n f e r e n c e S e s s i o n : : I n i t i a l i z e ]   A d d i n g   d e f a u l t   C P U   e x e c u t i o n   p r o v i d e r .
 2 0 2 3 - 0 1 - 3 0   0 7 : 4 0 : 2 4 . 0 9 1 2 0 7 0   [ I : o n n x r u n t i m e : D e f a u l t ,   b f c _ a r e n a . c c : 2 6   o n n x r u n t i m e : : B F C A r e n a : : B F C A r e n a ]   C r e a t i n g   B F C A r e n a   f o r   C p u   w i t h   f o l l o w i n g   c o n f i g s :   i n i t i a l _ c h u n k _ s i z e _ b y t e s :   1 0 4 8 5 7 6   m a x _ d e a d _ b y t e s _ p e r _ c h u n k :   1 3 4 2 1 7 7 2 8   i n i t i a l _ g r o w t h _ c h u n k _ s i z e _ b y t e s :   2 0 9 7 1 5 2   m e m o r y   l i m i t :   1 8 4 4 6 7 4 4 0 7 3 7 0 9 5 5 1 6 1 5   a r e n a _ e x t e n d _ s t r a t e g y :   0
 2 0 2 3 - 0 1 - 3 0   0 7 : 4 0 : 2 4 . 0 9 8 2 7 9 8   [ V : o n n x r u n t i m e : D e f a u l t ,   b f c _ a r e n a . c c : 6 2   o n n x r u n t i m e : : B F C A r e n a : : B F C A r e n a ]   C r e a t i n g   2 1   b i n s   o f   m a x   c h u n k   s i z e   2 5 6   t o   2 6 8 4 3 5 4 5 6
 2 0 2 3 - 0 1 - 3 0   0 7 : 4 0 : 2 4 . 1 0 7 0 4 8 7   [ I : o n n x r u n t i m e : D e f a u l t ,   b f c _ a r e n a . c c : 3 1 7   o n n x r u n t i m e : : B F C A r e n a : : A l l o c a t e R a w I n t e r n a l ]   E x t e n d i n g   B F C A r e n a   f o r   C p u .   b i n _ n u m : 0   ( r e q u e s t e d )   n u m _ b y t e s :   2   ( a c t u a l )   r o u n d e d _ b y t e s : 2 5 6
 2 0 2 3 - 0 1 - 3 0   0 7 : 4 0 : 2 4 . 1 1 1 9 6 8 5   [ I : o n n x r u n t i m e : D e f a u l t ,   b f c _ a r e n a . c c : 1 9 7   o n n x r u n t i m e : : B F C A r e n a : : E x t e n d ]   E x t e n d e d   a l l o c a t i o n   b y   1 0 4 8 5 7 6   b y t e s .
 2 0 2 3 - 0 1 - 3 0   0 7 : 4 0 : 2 4 . 1 1 4 8 9 9 0   [ I : o n n x r u n t i m e : D e f a u l t ,   b f c _ a r e n a . c c : 2 0 0   o n n x r u n t i m e : : B F C A r e n a : : E x t e n d ]   T o t a l   a l l o c a t e d   b y t e s :   1 0 4 8 5 7 6
 2 0 2 3 - 0 1 - 3 0   0 7 : 4 0 : 2 4 . 1 1 7 9 3 1 8   [ I : o n n x r u n t i m e : D e f a u l t ,   b f c _ a r e n a . c c : 2 0 3   o n n x r u n t i m e : : B F C A r e n a : : E x t e n d ]   A l l o c a t e d   m e m o r y   a t   0 0 0 0 0 2 8 A C D C 6 1 0 6 0   t o   0 0 0 0 0 2 8 A C D D 6 1 0 6 0

...

2 0 2 3 - 0 1 - 3 0   0 7 : 4 0 : 2 6 . 6 0 8 7 1 3 9   [ I : o n n x r u n t i m e : D e f a u l t ,   b f c _ a r e n a . c c : 3 1 7   o n n x r u n t i m e : : B F C A r e n a : : A l l o c a t e R a w I n t e r n a l ]   E x t e n d i n g   B F C A r e n a   f o r   C p u .   b i n _ n u m : 2 0   ( r e q u e s t e d )   n u m _ b y t e s :   5 4 0 0 0 0 0 0 0   ( a c t u a l )   r o u n d e d _ b y t e s : 5 4 0 0 0 0 0 0 0
 2 0 2 3 - 0 1 - 3 0   0 7 : 4 0 : 2 6 . 6 1 3 5 3 1 4   [ I : o n n x r u n t i m e : D e f a u l t ,   b f c _ a r e n a . c c : 1 9 7   o n n x r u n t i m e : : B F C A r e n a : : E x t e n d ]   E x t e n d e d   a l l o c a t i o n   b y   2 1 4 7 4 8 3 6 4 8   b y t e s .
 2 0 2 3 - 0 1 - 3 0   0 7 : 4 0 : 2 6 . 6 1 7 6 9 0 4   [ I : o n n x r u n t i m e : D e f a u l t ,   b f c _ a r e n a . c c : 2 0 0   o n n x r u n t i m e : : B F C A r e n a : : E x t e n d ]   T o t a l   a l l o c a t e d   b y t e s :   4 2 9 6 0 1 5 8 7 2
 2 0 2 3 - 0 1 - 3 0   0 7 : 4 0 : 2 6 . 6 2 0 9 2 3 5   [ I : o n n x r u n t i m e : D e f a u l t ,   b f c _ a r e n a . c c : 2 0 3   o n n x r u n t i m e : : B F C A r e n a : : E x t e n d ]   A l l o c a t e d   m e m o r y   a t   0 0 0 0 0 2 8 B 3 1 D 5 2 0 6 0   t o   0 0 0 0 0 2 8 B B 1 D 5 2 0 6 0
 2 0 2 3 - 0 1 - 3 0   0 7 : 4 0 : 2 6 . 7 3 8 5 6 7 2   [ I : o n n x r u n t i m e : ,   s e q u e n t i a l _ e x e c u t o r . c c : 1 7 6   o n n x r u n t i m e : : S e q u e n t i a l E x e c u t o r : : E x e c u t e ]   B e g i n   e x e c u t i o n

**Screenshots**

**Additional context**

**Comment by fatcat-z** [comment]
Thanks for your detailed scripts for a repro.

I've checked the exported ONNX graph. No obvious think to improve there. I agree LOOP is not an efficient operation and for some models (like LSTM), ONNX has a dedicated OP for that to reduce LOOP ops. But for your case, there is no such think in ONNX.

My suggestion is to submit this issue in [onnxruntime repo](https://github.com/microsoft/onnxruntime) for a help.

**Comment by fischeruben** [comment]
Thank you for having a look at this. Guess I will follow your suggestion.
