### ISSUE TITLE
tf2onnx not outputting anything

### ISSUE THREAD

**Issue by noahcoolboy** [onnx/tensorflow-onnx#2110]
**Describe the bug**
Running tf2onnx on the model I am trying to convert makes tf2onnx freeze for a moment then stop.
No conversion takes place. This issue is specific to the model I am trying to convert as it converts other models fine.
Full Output log:
```
C:\Users\noahn\AppData\Local\Programs\Python\Python39\lib\runpy.py:127: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2023-01-30 15:27:25,319 - INFO - Using tensorflow=2.10.1, onnx=1.13.0, tf2onnx=1.13.0/434b4a
2023-01-30 15:27:25,319 - INFO - Using opset <onnx, 16>
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04*): Windows 10
- TensorFlow Version: 2.10.1
- Python version: 3.9.13
- ONNX version (if applicable, e.g. 1.11*): 1.13.0

**To Reproduce**
Download the following model: [pose_detection.tflite](https://storage.googleapis.com/mediapipe-assets/pose_detection.tflite)
Then run `python -m tf2onnx.convert --opset 16 --tflite pose_detection.tflite --output model.onnx`

**Additional context**
This model originates from mediapipe. It's the pose detection model (not the pose landmark one) which is used to find a person and create a bounding box for then feeding it into the pose landmark model.

**Comment by noahcoolboy** [comment]
I ended up using
https://github.com/PINTO0309/tflite2tensorflow
Issue fixed

**Comment by spoonbobo** [comment]
@noahcoolboy Hi, could you share how you process Detection output into landmark model? Thanks

**Comment by noahcoolboy** [comment]
@spoonbobo 
Hi! I'm guessing you are asking for how to turn the output tensors into landmark output?
If so, you can take a look at the code of the project I ended up using the model in.
https://github.com/noahcoolboy/toucan-track/blob/main/main.py#L141
https://github.com/noahcoolboy/toucan-track/blob/main/utils/inference.py#L247

**Comment by spoonbobo** [comment]
@noahcoolboy Thanks! Omg you spotted me added you. Sure, let me add you discord
