### ISSUE TITLE
tensorflow 2.11.x support?

### ISSUE THREAD

**Issue by andreped** [onnx/tensorflow-onnx#2146]
### Question
Am I safe to assume that `tf2onnx` is compatible with `tensorflow==2.11.x`? Also, what about `tf==2.12.x`?

I only found one person that have tried using ´2.11.x´ from the Issues, see https://github.com/onnx/tensorflow-onnx/issues/2102.

According to the documentations, only `<=2.10.x` is supported (see [here](https://github.com/onnx/tensorflow-onnx#tf2onnx---convert-tensorflow-keras-tensorflowjs-and-tflite-models-to-onnx)). However, the latest release is rather dated (see [here](https://github.com/onnx/tensorflow-onnx/releases/tag/v1.13.0)).

**Comment by fatcat-z** [comment]
TF2ONNX now supports tensorflow 2.11.x. But 2.12.x is not supported yet until the #2154 is fixed.
