### ISSUE TITLE
TensorFlow 2.12.0 breaks nightly tests.

### ISSUE THREAD

**Issue by fatcat-z** [onnx/tensorflow-onnx#2154]
self = <test_backend.BackendTests testMethod=test_Conv2DBackpropInput>
tflite_path = '/tmp/tmp9j283eve/test_Conv2DBackpropInput/test_Conv2DBackpropInput.tflite'

    def tflite_has_supported_types(self, tflite_path):
        try:
            with open(tflite_path, 'rb') as f:
                buf = f.read()
            buf = bytearray(buf)
            model = Model.GetRootAsModel(buf, 0)
            tensor_cnt = model.Subgraphs(0).TensorsLength()
            interpreter = tf.lite.Interpreter(tflite_path)
            for i in range(tensor_cnt):
>               dtype = interpreter._get_tensor_details(i)['dtype']   # pylint: disable=protected-access
E               TypeError: Interpreter._get_tensor_details() missing 1 required positional argument: 'subgraph_index'

**Comment by pranavladkat** [comment]
Is there an ETA for this issue?

**Comment by q-ycong-p** [comment]
+1 on this issue. Any update on a fix?

**Comment by q-ycong-p** [comment]
I put up a naive workaround #2204, just to start discussion towards a fix. Welcome more thoughtful fix of folks have deeper knowledge on tflite's change on subgraph at tf-2.12, and tf2onnx's corresponding path forward.

**Comment by q-ycong-p** [comment]
Hi @fatcat-z, all tests passed after re-opening #2204 - which aims to address this issue. Would appreciate a feedback/review from maintainers. Thank you!

**Comment by yan12125** [comment]
This issue can probably be closed as #2204 is merged?
