### ISSUE TITLE
convert tensorflow model to onnx in cuda 9.0, failed to load the onnx model in cuda 10.2

### ISSUE THREAD

**Issue by feng-1985** [onnx/tensorflow-onnx#2182]
experiments:
the model is trained with tensorflow gpu 1.12, and work well with python 3.6, cuda 9.0
1. in the python 3.6.8, cuda 9.0
tensorflow-gpu 1.12.0
tf2onnx-1.14
onnx-1.11
onnxruntime-gpu-1.6
run the command: tf2onnx.convert success.
But, load the onnx model raise the error "libcublas.so.10 cannot open shared object file"
replace the onnxruntime-gpu-1.6 to onnxruntime-1.10
It success load the onnx model, but can't use the gpu!
The onnxruntime-gpu-1.6 need the cuda 10, as the [requirements](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements) said.

2. in the python3.6.5, cuda 10.2
tensorflow-gpu 1.12.0
tf2onnx-1.14
onnx-1.11
onnxruntime-gpu-1.6
run the command: tf2onnx.convert, it raise the error "libcublas.so.9.0 cannot open shared object file" ...
or
I load the onnx model in experiment 1, it raise the error "unknown model file format version"

3. in the python3.8, cuda 10.2
tensorflow-gpu 2.12.0
tf2onnx-1.14
onnx-1.14
onnxruntime-gpu-1.6
run the command: tf2onnx.convert success.
But, load the onnx model raise the error "unknown model file format version."
or
I load the onnx model in experiment 1, it raise the error "unknown model file format version"

(onnxruntime.capi.onnxruntime_pybind11_state.Fail -- Unknown model file format version)

**Comment by fatcat-z** [comment]
The conversion itself has no relationship to cuda. The error of experiment 2 should be thrown by tensorflow functions when tf2onnx is going to get a frozen graph.

Is it possible that you convert the model by tf2onnx 1.14 with TensorFlow cpu version? And then check if the result could be loaded by onnxruntime.

**Comment by feng-1985** [comment]
So the conversion has no relation to the onnxruntime, they can use in different environments ?

The experiment 3 can convert success, but failed to load.

**Comment by fatcat-z** [comment]
> So the conversion has no relation to the onnxruntime, they can use in different environments ?
> 
> The experiment 3 can convert success, but failed to load.

Yes.

**Comment by fatcat-z** [comment]
> So the conversion has no relation to the onnxruntime, they can use in different environments ?
> 
> The experiment 3 can convert success, but failed to load.

Both python 3.6.x and tensorflow 1.12 is not in tf2onnx CI pipeline, so I suggest you focus on resolving the experiment 3 issue.

Please try to describe the problem in onnxruntime repo and see if any suggestions from there. And then probably we can see if tf2onnx could do anything to help.

**Comment by feng-1985** [comment]
Thanks. I figure it out.
The key for success load the onnx model, is keep the onnx version, opset number, onnxruntime version be compatibility, so just keep the convertion env and the load env too be same.
