### ISSUE TITLE
Bias term missing after conversion from tf.keras.layers.Dense to onnx

### ISSUE THREAD

**Issue by baijumeswani** [onnx/tensorflow-onnx#2213]
**Describe the bug**

After converting from a dense layer in tf, I would expect it to map to a `MatMul -> Add` where the `Add` adds the bias of the dense layer. However, after conversion, I don't see the `Add` node. Am I missing a step?

Here is a simple python script that can reproduce the problem:

```py
import tensorflow as tf
import numpy as np
import tf2onnx
import onnx

input_dim = 3
output_dim = 5
n_samples = 100

tf_input = tf.keras.Input(shape=(3,), dtype=tf.float32, name=f"input")
dense = tf.keras.layers.Dense(output_dim, input_shape=(input_dim,))(tf_input)

tf_model = tf.keras.Model(inputs=[tf_input], outputs=[dense], name="model")
tf_model.summary()
tf_model.predict(np.random.random((n_samples, input_dim,)))

onnx_model, _ = tf2onnx.convert.from_keras(tf_model)
onnx.save(onnx_model, "model.onnx")

```

ONNX model after conversion:

![image](https://github.com/onnx/tensorflow-onnx/assets/12852605/40e63890-442b-40b0-9870-89e61f401350)

**Urgency**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04*):
- TensorFlow Version: 2.12.0
- Python version: 3.10
- ONNX version: 1.13.1
- ONNXRuntime version: NA

**Comment by fatcat-z** [comment]
There is a parameter use_bias for Dense to decide if a bias is going to be added.

If use_bias is True, then the frozen tensorflow graph will have 2 inputs, one is for MatMul and the other is for BiasAdd. Afterwards, these 2 will be added up and set as the initializer of MatMul node in final onnx graph. So, we won't see the Add node in the onnx graph. 

If use_bias is False, then there is no BiasAdd input in the frozen tensorflow graph, hence the initializer will be different than the above one.

**Comment by baijumeswani** [comment]
We would like to use the exported model for training. If the bias term and the matmul weight are combined, the number of parameters between tf and onnx defers.
Any way to force having the `Add` node and maintaining the same weight values as in `Dense`?

**Comment by xadupre** [comment]
The convert function applies many optimizers. One of them folds constants: if a constant is multiplied to another constant, only the output is part of the graph. This optimizer is here: https://github.com/onnx/tensorflow-onnx/blob/main/tf2onnx/optimizer/const_fold_optimizer.py.

**Comment by xadupre** [comment]
If you try `dense = tf.keras.layers.Dense(output_dim, input_shape=(input_dim,), bias_initializer="ones")(tf_input)`, the bias do not disappear.
