### ISSUE TITLE
Conversion does not complete

### ISSUE THREAD

**Issue by pjjajal** [onnx/tensorflow-onnx#2235]
**Describe the bug**

When attempting to convert a model using the CLI the converter gets stuck at the "Optimizing ONNX model" stage and the model conversion does not complete. I attempted this multiple times and each time the conversion does not proceed any further. The longest period that I kept the converter running was >2h and the conversion still did not complete.

**Urgency**
None

**System information**
- OS Platform and Distribution: macOS Ventura 13.5.2
- TensorFlow Version: 2.13.0
- Python version: 3.10.9
- ONNX version: 1.14.1
- ONNXRuntime version: N/A
- tf2onnx version: 1.15.1

**To Reproduce**

1. Download the model [link](https://drive.google.com/file/d/1tM95SGiFXDmnzchIYEtTbqqAy2WkS1Qd/view?usp=drive_link).
2. Run the following command: `python -m tf2onnx.convert --saved-model <path where tfnet is saved>/tfnet --output ./model.onnx --opset 16`
3. Wait for completion.

**Screenshots**

The converter gets stuck at this stage of conversion.
<img width="719" alt="image" src="https://github.com/onnx/tensorflow-onnx/assets/61586397/8571e51f-a4fa-4253-82c7-5731ea5b50ed">

**Additional context**

- The model that is being converted was generated using the [nnsmith](https://github.com/ise-uiuc/nnsmith) fuzzing tool.  
- The converter was stuck at that stage for >2h, only then was the program manually interrupted.

**Comment by jiaojiaoYe** [comment]
excuse me, have you solved the problem? I hava met the same issue.

**Comment by pjjajal** [comment]
> excuse me, have you solved the problem? I hav[e] met the same issue.

It does not work with opset 16 but I think it works for a higher opset. I haven't tried it recently.
