### ISSUE TITLE
TF Incompatible tensor names (e.g. 'input.1') breaks ONNX-to-TF export

### ISSUE THREAD

**Issue by profPlum** [onnx/tensorflow-onnx#2237]
**Describe the bug**
The bug is exactly as is described here: https://stackoverflow.com/questions/76839366/tf-rep-export-graphtf-model-path-keyerror-input-1

**Urgency**
Yes there are important use cases blocked by this, the most basic functionality that is supposed to be supported by ONNX (that is converting an MLP from Pytorch to TF), is broken.

For more context, the person who posted this stack-overflow question experienced the same problem as me except he experienced it with ResNet-50 & I experienced it with a simple MLP (from pytorch-lightning).

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04*): Linux Ubuntu 18.04
- TensorFlow Version: 2.13.0
- Python version: 3.9
- ONNX version (if applicable, e.g. 1.11*): 1.14.1
- ONNXRuntime version (if applicable, e.g. 1.11*): ??
- onnx-tf version: 1.10.0

**Comment by CYuxian** [comment]
Seems that this is an issue of converting onnx to tf so it should be reported to https://github.com/onnx/onnx-tensorflow (not tensorflow-onnx)

**Comment by fatcat-z** [comment]
> Seems that this is an issue of converting onnx to tf so it should be reported to https://github.com/onnx/onnx-tensorflow (not tensorflow-onnx)

Yes, you are right. This tool aims to convert a TensorFlow model to onnx model while the issue is on the opposite.
