### ISSUE TITLE
tf2onnx support for tensorflow Resizing "area" method

### ISSUE THREAD

**Issue by ZachZhao96** [onnx/tensorflow-onnx#2239]
Hi,

I had an error message when I tried converting my TensorFlow.Keras model to ONNX format using tf2onnx and ONNX, I realized that the Resizing "area" method used in my model architecture is not supported by ONNX and tf2onnx. I have tried retraining the model using other resizing methods like 'Bilinear' and "Nearest". Neither of them gave me good validation and testing results compared to "Area". I wonder if there is a chance to have tf2onnx support the ResizeArea method for tensorflow.keras.layers.Resizing and tensorflow.image.resize in the future.

![image](https://github.com/onnx/tensorflow-onnx/assets/89313814/5ea6e438-4be0-4c78-b841-f63f6afb40e8)

Thank you,

Zachary Zhao

**Comment by fatcat-z** [comment]
https://github.com/microsoft/onnxruntime/issues/17564 has been filed since one mode doesn't work.
