### ISSUE TITLE
Error While converting tensorflow mobileNet model to ONNX

### ISSUE THREAD

**Issue by vinayak618** [onnx/tensorflow-onnx#224]
Hi I'm using the tensorflow-gpu 1.9.0 and latest tf2onnx converter to convert the mobile net model to onnx format, But ending up with below error.
_**/tf2onnx/optimizer/transpose_optimizer.py line 92, in post_optimize_action
    if is_nhwc_transpose(op) and (input_shape[1] == 1 or (input_shape[2] == 1 and input_shape[3] == 1)):
TypeError: 'NoneType' object is not subscriptable**_

can anyone help?
Below is the link for model:
[https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_0.75_192_frozen.tgz](url)

**Comment by pengwa** [comment]
there is a bug not covered by latest pypi package. you can sync from master to use latest change. or you can modify that code adding null check for input_shape referencing https://github.com/onnx/tensorflow-onnx/commit/b303ec6f10e69c1dc0131030d7a6985ddef714bf#diff-aec0b12f6093a46a56b676fa8a96b7d5R89. 

                if not input_shape: 
                    continue


@guschmue maybe we need update a newer version package now?

**Comment by guschmue** [comment]
yes, planning to push a new package early next week

**Comment by vinayak618** [comment]
Thanks @pengwa was able to solve the issue by setting the package from source.

**Comment by pengwa** [comment]
tf2onnx 0.3.2 on pypi  has the fix now. closed this.
