### ISSUE TITLE
Protobuf version conflict between tf2onnx and tensorflow

### ISSUE THREAD

**Issue by marqueurs404** [onnx/tensorflow-onnx#2243]
# Ask a Question

### Question
The release logs of version 1.15 of tf2onnx mentioned supporting TensorFlow 2.12/2.13. However, when I tried to pip install tf2onnx 1.15 and tensorflow 2.12 or 2.13, there is clearly a version conflict preventing the pip install.

### Further information
![image](https://github.com/onnx/tensorflow-onnx/assets/4110723/2959c134-6d37-4715-8a34-93fafe46e9cc)

**Comment by marqueurs404** [comment]
Closing as the conflict was happening with another related library not, not tf2onnx

**Comment by Zahlii** [comment]
I would like to re-open this issue, while the comment above is true (in the sense that you can manage to resolve tensorflow and tf2onnx in a clean virtualenv), it will lead to protobuf ~=3.20 to be installed.

This was only changed from tf2onnx 1.15 onwards (see https://github.com/onnx/tensorflow-onnx/pull/2171)

If I want to install this together with some GRPC dependencies, this will resolve to the following setup - note that this is using the most recent protobuf version, but "downgrade" tf2onnx. Will this lead to issues with tf2onnx 1.14? What was the original reason on why to include the protobuf pin?

        #7 2.483 protobuf==4.24.4
        #7 2.483 ├── grpcio-reflection==1.59.0 [requires: protobuf>=4.21.6]
        #7 2.483 ├── grpcio-tools==1.59.0 [requires: protobuf>=4.21.6,<5.0dev]
        #7 2.483 ├── onnx==1.14.1 [requires: protobuf>=3.20.2]
        #7 2.483 │   └── tf2onnx==1.14.0 [requires: onnx>=1.4.1]
        #7 2.483 ├── onnxruntime==1.16.1 [requires: protobuf]
        #7 2.483 ├── tensorboard==2.12.3 [requires: protobuf>=3.19.6]
        #7 2.483 │   └── tensorflow==2.12.1 [requires: tensorboard>=2.12,<2.13]
        #7 2.483 └── tensorflow==2.12.1 [requires: protobuf>=3.20.3, <5.0.0dev,!=4.21.5,!=4.21.4,!=4.21.3,!=4.21.2,!=4.21.1,!=4.21.0]
