### ISSUE TITLE
TensorRT only support "round_prefer_floor" nearest mode but tf2onnx uses "floor"

### ISSUE THREAD

**Issue by ShuaiShao93** [onnx/tensorflow-onnx#2248]
**Describe the bug**
When I convert a model that has Resize op, I got error `Assertion failed: (transformationMode != "tf_half_pixel_for_nn" || nearest_mode == "round_prefer_floor") && "This version of TensorRT only support round_prefer_floor nearest mode in tf_half_pixel_for_nn!"`

It turns out TRT8.6.1 only supports "round_prefer_floor" but tf2onnx uses "floor" [here](https://github.com/onnx/tensorflow-onnx/blob/b57fe915b3728fbf996b490170a374821dd8383a/tf2onnx/onnx_opset/nn.py#L1437C5-L1437C5)

**Comment by ShuaiShao93** [comment]
Sent PR https://github.com/onnx/tensorflow-onnx/pull/2249

**Comment by nchaly** [comment]
@ShuaiShao93 why PR https://github.com/onnx/tensorflow-onnx/pull/2249 was not merged?  
https://github.com/onnx/onnx-tensorrt/blob/0462dc31ae78f48744b6141ae376df1f96d3f459/builtin_op_importers.cpp#L3770-L3772  - that check is still there and I'm having a case where importing fails with message "[TRT] [E] ModelImporter.cpp:967: ERROR: onnxOpCheckers.cpp:613 In function checkResize:
[8] (transformationMode != "tf_half_pixel_for_nn" || nearest_mode == "round_prefer_floor") && "This version of TensorRT only support round_prefer_floor nearest mode in tf_half_pixel_for_nn!"

**Comment by swdn133** [comment]
I just stumbled across the exact same issue.
I guess it would be possible to workaround by modifying the resulting onnx with graphsurgeon or anything like that, but this is kind of messy. 
It would be great to have this issue resolved.

**Comment by nchaly** [comment]
@swdn133 Right, for me workaround is rather easy on model side - just try some interpolation which is not 'nearest' for `UpSampling2D` layer (bilinear in my case).

**Comment by swdn133** [comment]
@nchaly 
I need to keep the 'nearest' mode for some reasons. Therefore simply switching the interpolation mode doesn't work for me. I need to keep consistency between multiple different models. The workaround for me right now is to walk over the resulting onnx graph and afterwards changing the attribute from 'floor' to 'round_prefer_floor'.
It's certainly not the cleanest solution, but at least it works.

**Comment by nchaly** [comment]
Here is one more workaround, it upgrade is an option.
The original issue is easily reproducible in following environment:
```
tensorflow 2.15.1
keras 2.15.0
tf2onnx 1.16.1
onnx 1.17.0
tensorrt 10.9.0.34

Beginning ONNX file parsing
[03/12/2025-11:07:47] [TRT] [E] In node 17 with name: Resize__54 and operator: Resize (checkResize): UNSUPPORTED_NODE: (transformationMode != "tf_half_pixel_for_nn" || nearest_mode == "round_prefer_floor") && "This version of TensorRT only support round_prefer_floor nearest mode in tf_half_pixel_for_nn!"
ERROR: Failed to parse the ONNX file.
In node 11 with name: Resize__34 and operator: Resize (checkResize): UNSUPPORTED_NODE: (transformationMode != "tf_half_pixel_for_nn" || nearest_mode == "round_prefer_floor") && "This version of TensorRT only support round_prefer_floor nearest mode in tf_half_pixel_for_nn!"
``` 

But upgrade to tf 2.16 seems to be fixing this particular error.  (Most troubles probably will be brought by the need of migration to keras 3.9 from 2.15)

```
tensorflow 2.16.2
keras 3.9.0
tf2onnx 1.16.1
onnx 1.17.0
tensorrt 10.9.0.34

Loading ONNX file from path model_test_01.onnx...
Beginning ONNX file parsing
Completed parsing of ONNX file
Building an engine from file model_test_01.onnx; this may take a while...
Completed creating Engine
```

**Comment by swdn133** [comment]
I tried with tensorflow 2.18.0 and legacy Keras (keras 2.x) backend and the problem did not change.

If it works as @nchaly described above, then the upgrade to keras 3.9.0 seems to do the trick. Nice to know.
