### ISSUE TITLE
Keras weights (.h5) to ONNX-model

### ISSUE THREAD

**Issue by Egorundel** [onnx/tensorflow-onnx#2251]
### Question
Hello, I have the following task: I need to make an **ONNX** model from the **weights.h5** (obtained after training a neural network built on **keras** - **RetinaNet**), which is then translated into **TensorRT**. 

Now I plan to transfer weights (**weights.h5**) to **ONNX**. How do I do it correctly?

### Further information
**Model name**: *RetinaNet*

**Comment by Egorundel** [comment]
I'll write it myself, since I seem to have understood the algorithm. He's like this:

**.h5**
↓
**TensorFlow SavedModel (folder with weights.pb)**
A format containing a binary representation of the model
↓
**Freeze model (folder with weights.pb)**
This format includes freezing the model — converting all its variables into constants
↓
ONNX (with tf2onnx)
↓
TensorRT Engine (with trtexec command)

**Comment by benjmerales** [comment]
Hi @Egorundel . I am also trying to find a way to convert H5 > ONNX > TRT. have you resolved this issue on Tensorflow 2.x? Since freezing the model is already deprecated on TFv2+

**Comment by Egorundel** [comment]
@benjmerales Hello! Yes, I tried, look below:

**.h5 → SavedModel** script:
```python
# Import libraries
import tensorflow as tf
from tensorflow import keras
from keras_retinanet.models import load_model

print("\nTensorFlow version:", tf.__version__)
print("Keras version:", keras.__version__, "\n")

# Load the model
model = load_model("model.h5")

# Check its architecture
model.summary()

# Save the model in SavedModel format
model.save(filepath='model_tf', save_format='tf')
```

**SavedModel → FreezeModel** script:
```python
import tensorflow as tf
from tensorflow.python.framework.convert_to_constants import convert_variables_to_constants_v2
from keras_retinanet.models import load_model

# Load the model
loaded_model = load_model('model_tf')

# Check its architecture
loaded_model.summary()

print("loaded_model.inputs[0].shape: ", loaded_model.inputs[0].shape)

# Convert the model
full_model = tf.function(lambda x: loaded_model(x))
full_model = full_model.get_concrete_function(
    tf.TensorSpec(loaded_model.inputs[0].shape, loaded_model.inputs[0].dtype))

# Get frozen ConcreteFunction
frozen_func = convert_variables_to_constants_v2(full_model)
frozen_func.graph.as_graph_def()

# Save the frozen graph from the frozen ConcreteFunction to disk
tf.io.write_graph(graph_or_graph_def=frozen_func.graph,
                  logdir="./frozen_models",
                  name="frozen_graph.pb",
                  as_text=False)
```
for **SavedModel → ONNX** use: [tf2onnx](https://github.com/onnx/tensorflow-onnx)
```terminal
python -m tf2onnx.convert --saved-model model_tf --output model.onnx
```

for **ONNX → TensorRT Engine** use `trtexec`:
```terminal
trtexec --onnx=model.onnx --saveEngine=retinaNet.engine --minShapes=input_1:1x512x512x3 --optShapes=input_1:6x512x512x3 --maxShapes=input_1:12x512x512x --memPoolSize=workspace:3000 --noTF32 --fp16
```

**Comment by benjmerales** [comment]
What version of Tensorflow is this code compatible?

**Comment by Egorundel** [comment]
@benjmerales  tensorflow-gpu 2.4.0

You can also use the usual TensorFlow 2.4.0

**Comment by salanzewei** [comment]
@Egorundel hello,I'm new to the model deployment.why you put SavedModel to FreezeModel ,but still use SavedModel to onnx, what is the function  of FreezeModel?

**Comment by Egorundel** [comment]
@salanzewei Hi, I'm new to this myself, I still don't understand what's the matter. Do you understand?
