### ISSUE TITLE
Conversion to ONNX with dynamic batch_size

### ISSUE THREAD

**Issue by Egorundel** [onnx/tensorflow-onnx#2253]
### Question
What should I specify when **converting to ONNX** as an `input` if I want to make a **dynamic batch_size**. 
Should I specify `-1` or something like that? (for example: `-1, 640, 640, 3`)

**Comment by guker** [comment]
> Yes, more details can be found [here](https://github.com/onnx/tensorflow-onnx#--inputs---outputs).

its ok, ths very much

**Comment by fatcat-z** [comment]
This issue is resolved, so closing this. Feel free to open a new one if the issue still exists.
