### ISSUE TITLE
Please help validate release candidate for ONNX 1.15.0rc1

### ISSUE THREAD

**Issue by liqunfu** [onnx/tensorflow-onnx#2254]
Hi ONNX Converter team,
 
Please help validate ONNX 1.15.0 rc1, here is the [onnx · TestPyPI](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftest.pypi.org%2Fproject%2Fonnx%2F1.15.0rc1%2F&data=05%7C01%7CLiqun.Fu%40microsoft.com%7Cb727256d33b84ada77f908dbca92505d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638326502011191427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PWX1KaDvZSIGIWDU2gIByqMyL%2Bq39oI8%2Fn8aLdBUoDg%3D&reserved=0).
 
Thanks,
Liqun

**Comment by fatcat-z** [comment]
The change of [not allowing empty iterator](https://github.com/onnx/onnx/blob/c2e38cb97d2001c5563f2707c28ebca753f04e85/onnx/helper.py#L877C3-L877C3) causes some problem and I'm trying to figure out a solution.

Besides this, no issues were found.

**Comment by liqunfu** [comment]
> The change of [not allowing empty iterator](https://github.com/onnx/onnx/blob/c2e38cb97d2001c5563f2707c28ebca753f04e85/onnx/helper.py#L877C3-L877C3) causes some problem and I'm trying to figure out a solution.
> 
> Besides this, no issues were found.

Thank you @fatcat-z ! 
regarding issue, the attr_type argument was added so that if you can have the caller to passed a valid type that will work.

**Comment by liqunfu** [comment]
Please help validate ONNX 1.15.0 rc2, here is the [onnx · TestPyPI](https://test.pypi.org/project/onnx/1.15.0rc2/).
