### ISSUE TITLE
Is there any upgrades on tf2onnx

### ISSUE THREAD

**Issue by hanzigs** [onnx/tensorflow-onnx#2287]
tf2onnx 1.16.0 requires protobuf~=3.20.2
but
tensorflow-intel 2.15.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 3.20.2 which is incompatible.
Using python 3.11.7
Thanks in advance

**Comment by fatcat-z** [comment]
Yes, it should be fixed. A workaround is: after install tf2onnx 1.16, please feel free to upgrade protobuf to 3.20.3 and tf2onnx supports it as well.

**Comment by hanzigs** [comment]
and support for protobuf 4.x as well please. because some libraries using protobuf 4.24.3. many Thanks.

**Comment by fatcat-z** [comment]
> and support for protobuf 4.x as well please. because some libraries using protobuf 4.24.3. many Thanks.

Actually, for most of case, tf 2.x and protobuf 4.x works well. But tf2onnx still needs to support tf 1.15. version which is used by a lot of developers. So the official version of protobuf has to be limited.
