### ISSUE TITLE
Please help validate release candidate for ONNX 1.16.0rc2

### ISSUE THREAD

**Issue by liqunfu** [onnx/tensorflow-onnx#2318]
Hi ONNX Converter team,

Please help validate ONNX 1.16.0 rc2, here is the [onnx · TestPyPI]https://test.pypi.org/project/onnx/1.16.0rc2/

Thanks,
Liqun

**Comment by cjvolzka** [comment]
Is this a duplicate of https://github.com/onnx/tensorflow-onnx/issues/2310?
