### ISSUE TITLE
Running Onnx inference graph 

### ISSUE THREAD

**Issue by vinayak618** [onnx/tensorflow-onnx#241]
Hi @pengwa , The previous issue with tf2onnx was resolved in latest release, Thank you so much.
In the mean while, i was converting some of the custom models from pb to onnx and facing the assertion error at _**_create _transpose_pairs_after_node**_.
If you can help in this, it would be great.

Error: 
assert len(node.output) == 1  # just support node who has 1 output
AssertionError

**Comment by pengwa** [comment]
can you add "print(node)" to see what the node is before the assert error happens?

**Comment by vinayak618** [comment]
Yeah  sure @pengwa .
print(node) will give the below output.
**_input: mul:0
input: FusedBatchNorm__10:0
output: add:0
name: add
op_type: Add_**

**Comment by vinayak618** [comment]
Yeah that was it.
But anyway its strange.
I got it running in r0.2 branch and not in master branch.
How do i run the onnx model for inference? apart from onnx-tensorflow, mxnet and caffe2.

**Comment by vinayak618** [comment]
@pengwa.
running the style-transfer quantized model provided in [https://storage.googleapis.com/download.tensorflow.org/models/stylize_v1.zip](url) will throw the below error:
**KeyError: tf.quint8**

**Comment by nbcsm** [comment]
@vinayak618 
unfortunately we don't have to plan to support quantization for now, because onnx quantization support is not finalized yet.

**Comment by vinayak618** [comment]
@nbcsm.
are all models in [https://github.com/onnx/tensorflow-onnx/blob/master/tests/run_pretrained_models.yaml](url) are tested successfully?
it has one quantized model so

**Comment by vinayak618** [comment]
@nbcsm @pengwa 
is there a plan to support the Quantized models anytime sooner?
if not, is there any way to convert quantized tf models to onnx?

**Comment by nbcsm** [comment]
quantization support is on our backlog, but there is no plan yet.

there are 2 dependencies that block:
-  tf2onnx quantized model conversion has to depends on onnx quantization support first, in onnx 1.4 probably.
-  backend support is also required, so you can run an onnx model that contains quantized ops.

please stay tuned.

**Comment by nbcsm** [comment]
@vinayak618, btw, may I know your scenario please? so we can better understand the requriement.

**Comment by guschmue** [comment]
quantize_weights.py does weight packing only. I'd not expect it do have much different results than tensorflow quantization but it will pack all weights which might be the reason why accuracy suffers compared to tensorflow (for the model use used it for that wasn't the case).
There is a ```--verbose``` option what will tell how much error is introduced for each weight.

**Comment by guschmue** [comment]
The quantize_weights.py hack is obsolete, winmltools has now better support for quantization:
https://docs.microsoft.com/en-us/windows/ai/convert-model-winmltools#quantize-onnx-model
