### ISSUE TITLE
AttributeError on input nodes

### ISSUE THREAD

**Issue by NicolasHorMann** [onnx/tensorflow-onnx#268]
I tried on: [this model](https://github.com/argman/EAST).
I used this command: python -m tf2onnx.convert --input detection.pb --inputs "input_images" --outputs "feature_fusion/Conv_7/Sigmoid,feature_fusion/concat_3" --output ./detection.onnx --opset 8

tensorflow 1.8
onnx 1.3.0
onnxruntime  0.1.4
tf2onnx 0.3.2

Traceback:
using tensorflow=1.8.0, onnx=1.3.0, opset=8, tfonnx=0.3.2/aa1141
2019-01-08 18:21:21.137155: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_batch_norms
2019-01-08 18:21:21.212516: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_old_batch_norms
ERROR:tf2onnx:node <function rewrite_custom_rnn_cell at 0x7f77c6edc0d0>: exception 'NoneType' object has no attribute 'inputs'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/convert.py", line 118, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/convert.py", line 102, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 2435, in process_tf_graph
    raise ex
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 2426, in process_tf_graph
    ops = rewrite(g, ops)
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/rewriter/rnn.py", line 50, in rewrite_custom_rnn_cell
    return  CustomRnnRewriter(g).run()
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/rewriter/custom_rnn_rewriter.py", line 78, in run
    return self.run_internal()
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/rewriter/loop_rewriter_base.py", line 76, in run_internal
    self.g.delete_unused_nodes(all_output_name)
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/graph.py", line 852, in delete_unused_nodes
    related_nodes = self.extract_sub_graph_nodes(outputs_name)
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/graph.py", line 837, in extract_sub_graph_nodes
    res_set = res_set.union(self._extract_sub_graph_nodes(node))
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/graph.py", line 821, in _extract_sub_graph_nodes
    for node in top_node.inputs:
AttributeError: 'NoneType' object has no attribute 'inputs'

**Comment by pengwa** [comment]
hi @NicolasHorMann, can you try 

python -m tf2onnx.convert --input detection.pb --inputs "input_images**:0**" --outputs "feature_fusion/Conv_7/Sigmoid:0,feature_fusion/concat_3**:0**" --output ./detection.onnx --opset 8

**Comment by NicolasHorMann** [comment]
hi @pengwa , thank you!

ValueError & other errors; logs:
using tensorflow=1.8.0, onnx=1.3.0, opset=8, tfonnx=0.3.2/aa1141
2019-01-08 22:35:38.228651: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_batch_norms
2019-01-08 22:35:38.310312: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_old_batch_norms
ERROR:tf2onnx:node resnet_v1_50/pool1/MaxPool has unknown dim [-1, 64, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/pool1/MaxPool has unknown dim [-1, 64, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_1/bottleneck_v1/shortcut/Conv2D has unknown dim [-1, 64, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_1/bottleneck_v1/shortcut/Conv2D has unknown dim [-1, 64, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 64, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_1/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 64, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_1/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 64, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_1/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 64, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_1/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 64, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_1/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 64, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_2/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_2/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_2/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 64, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_2/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 64, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_2/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 64, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_2/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 64, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_3/bottleneck_v1/shortcut/MaxPool has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_3/bottleneck_v1/shortcut/MaxPool has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_3/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_3/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_3/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 64, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block1/unit_3/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 64, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_1/bottleneck_v1/shortcut/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_1/bottleneck_v1/shortcut/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_1/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_1/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_1/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 128, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_1/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 128, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_1/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 128, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_1/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 128, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_2/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_2/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_2/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 128, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_2/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 128, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_2/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 128, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_2/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 128, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_3/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_3/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_3/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 128, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_3/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 128, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_3/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 128, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_3/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 128, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_4/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_4/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_4/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 128, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_4/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 128, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_4/bottleneck_v1/shortcut/MaxPool has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block2/unit_4/bottleneck_v1/shortcut/MaxPool has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_1/bottleneck_v1/shortcut/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_1/bottleneck_v1/shortcut/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_1/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_1/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_1/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_1/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_1/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_1/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_2/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 1024, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_2/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 1024, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_2/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_2/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_2/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_2/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_3/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 1024, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_3/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 1024, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_3/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_3/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_3/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_3/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_4/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 1024, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_4/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 1024, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_4/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_4/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_4/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_4/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_5/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 1024, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_5/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 1024, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_5/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_5/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_5/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_5/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_6/bottleneck_v1/shortcut/MaxPool has unknown dim [-1, 1024, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_6/bottleneck_v1/shortcut/MaxPool has unknown dim [-1, 1024, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_6/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 1024, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_6/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 1024, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_6/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block3/unit_6/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 256, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_1/bottleneck_v1/shortcut/Conv2D has unknown dim [-1, 1024, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_1/bottleneck_v1/shortcut/Conv2D has unknown dim [-1, 1024, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_1/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 1024, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_1/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 1024, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_1/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_1/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_1/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_1/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_2/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 2048, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_2/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 2048, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_2/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_2/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_2/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_2/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_3/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 2048, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_3/bottleneck_v1/conv1/Conv2D has unknown dim [-1, 2048, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_3/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_3/bottleneck_v1/conv2/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_3/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node resnet_v1_50/block4/unit_3/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation
ERROR:tf2onnx:node feature_fusion/ResizeBilinear: exception get tensor value: feature_fusion/ResizeBilinear/size__233 must be Const
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/convert.py", line 118, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/convert.py", line 102, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 2441, in process_tf_graph
    mapped_op, unmapped_op = tensorflow_onnx_mapping(g, continue_on_error, custom_op_handlers)
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 2307, in tensorflow_onnx_mapping
    raise ex
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 2298, in tensorflow_onnx_mapping
    onnx_node = func(g, node, node.name, args)
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 1227, in upsample_op7
    target_shape = node.inputs[1].get_tensor_value()
  File "/usr/local/lib/python3.6/site-packages/tf2onnx/graph.py", line 180, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: feature_fusion/ResizeBilinear/size__233 must be Const

**Comment by pengwa** [comment]
For the error:
> ERROR:tf2onnx:node feature_fusion/ResizeBilinear: exception get tensor value: feature_fusion/ResizeBilinear/size__233 must be Const. https://github.com/onnx/tensorflow-onnx/issues/151 mentioned this. While we are going to support OPSET9 once the official release is published. 

This is limitation of ONNX OPSET8, in OPSET9, we can allow the non-constant value during convert ResizeBilinear

@guschmue  for the  error " ERROR:tf2onnx:node resnet_v1_50/block4/unit_3/bottleneck_v1/conv3/Conv2D has unknown dim [-1, 512, -1, -1] for pads calculation"

**Comment by pengwa** [comment]
BTW, https://github.com/onnx/tensorflow-onnx/issues/269 is used to track the issue when inputs/outputs not passed in correctly.

**Comment by nbcsm** [comment]
pending on user response, close this issue for now.
please re-open it if still needed.
