### ISSUE TITLE
NotImplementedError: StridedSlice version 1 is not implemented.

### ISSUE THREAD

**Issue by Rathna21** [onnx/tensorflow-onnx#273]
I am getting the above issue from both CLI conversion or through program conversion.

I installed onnx and onnx-tf from source. 

My python script:

from tensorflow.core.framework import graph_pb2

from onnx_tf.frontend import tensorflow_graph_to_onnx_model
from onnx_tf.pb_wrapper import TensorflowGraph

graph_def = graph_pb2.GraphDef()
with open("frozen.pb", "rb") as f:  # load tf graph def
  graph_def.ParseFromString(f.read())
output = TensorflowGraph.get_output_node_names(
    graph_def)  # get output node names

model = tensorflow_graph_to_onnx_model(graph_def=graph_def, output=output)  # convert tf graph to onnx model
with open("output.onnx", 'wb') as f:
  f.write(model.SerializeToString())

Could you please release a version that resolves StridedSlice error ?

**Comment by nbcsm** [comment]
rathna21, seems you are using https://github.com/onnx/onnx-tensorflow
while this repo is tensorflow-onnx.

you may want to create issue in that repo.
or you can have a try on tensorflow-onnx converter, we have partial support for StrideSlice.

**Comment by Rathna21** [comment]
@nbcsm,

I tried to use tensorflow-onnx converter, my model successfully converted to .onnx format.

But when I am trying to load my onnx model, I am getting the following error,

**Type Error : Type parameter (T) bound to different types (tensor(float) and tensor(int32) in node conv2d_transpose_4/mul).**

Could you please help me in this?

**Comment by pengwa** [comment]
which runtime (e.g.) backend are you using for running the onnx file? onnxruntime or caffe2 or whatever?

**Comment by iamshri8** [comment]
@pengwa 

I am using onnxruntime.

**Comment by Rathna21** [comment]
@pengwa 

I am using onnxruntime.

**Comment by pengwa** [comment]
@Rathna21  can you share you models somewhere? seems Mul is having inputs of different types.

**Comment by guschmue** [comment]
If you can't share the model ... just a couple of nodes that are the input to conv2d_transpose_4/mul would help.

**Comment by Rathna21** [comment]
@guschmue 

Sure. Please find the attached screenshot.
![screen shot 2019-01-23 at 8 02 34 pm](https://user-images.githubusercontent.com/34045027/51630218-e49bcc00-1f49-11e9-93e2-0fcf5a4a2a6f.png)

**Comment by pengwa** [comment]
still hard to know what happens in the graph. maybe provide some node information around conv2d_transpose_4/mul (including its all inputs nodes and consumer nodes)    in protobuf?

**Comment by nbcsm** [comment]
close this issue due to lack of information.
@Rathna21, please re-open it if there is update.
thanks.
