### ISSUE TITLE
How we handle Const and Placeholder Node

### ISSUE THREAD

**Issue by pengwa** [onnx/tensorflow-onnx#280]
Today, we are converting Const and Placeholder node during conversion, and make them be in initializer or graph inputs. 

And when we want to get the corresponding node, we Graph will make a "fake/dummpy" Const or GraphInput node for convenience. 

While it would be easier to do this way:

We do nothing for Const and Placeholder during conversion(e.g. op mapping), they remain to be the original node they are. We do some special handling for them when we are calling Graph.make_graph(). 

The benefit we get: 1). we can avoid creating dummy nodes just for code convenience and need take care of deletion when calling set_nodes(). 2). we don't need main initializer in the Graph object (they are represented as node in the Graph), initializer is created in make_graph() only. 3). If we need add new or update Const or Graph input, just create or update Const node or Placeholder instead of adding new initializers and graph inputs. 

@guschmue  how do you feel about this?

**Comment by guschmue** [comment]
I guess that would be ok.
