### ISSUE TITLE
tf.dynamic_decode not supported

### ISSUE THREAD

**Issue by pengwa** [onnx/tensorflow-onnx#287]
tf.while_loop is supported now, so we need enhance loop_rewriter to support two apis in title.

**Comment by pengwa** [comment]
map_fn is supported by PR https://github.com/onnx/tensorflow-onnx/pull/316. made by @zhijxu-MS .

**Comment by nbcsm** [comment]
https://github.com/onnx/tensorflow-onnx/issues/344

**Comment by nbcsm** [comment]
https://github.com/onnx/tensorflow-onnx/pull/360

**Comment by nbcsm** [comment]
dynamic_decode is supported via several PRs
the test is https://github.com/onnx/tensorflow-onnx/pull/360
