### ISSUE TITLE
Consider using the mainline ONNX optimizer for graph transformations

### ISSUE THREAD

**Issue by anderspapitto** [onnx/tensorflow-onnx#3]
Hello! We've just noticed that tensorflow-onnx contains a library for graph manipulations (graph_matcher.py) and a small suite of optimizations built on top of it.

ONNX itself contains a library for graph manipulations (https://github.com/onnx/onnx/tree/master/onnx/optimizer/passes) and a growing suite of optimizations built on top of it. The reason we built the ONNX optimizer is to share work - many frontends and backends will want to perform common optimizations, and they should only need to be written once.

Would you be open to using the ONNX optimizer to represent your passes? It is a slightly different interface, but we've taken a look through and all the optimizations currently implemented in tensorflow-onnx should be compatible.

**Comment by guschmue** [comment]
fair, let me see if I can switch this.

**Comment by guschmue** [comment]
ok, I can definitely remove the optimization code and use the one in onnx.
I still need graph_matcher.py for matching tensorflow subgraphs to be replaced with onnx ops (like transpose is a good example) but if there would be similar support in onnx we could switch that one too.

**Comment by guschmue** [comment]
have switched some time ago to the onnx optimizer ... works fine.
