### ISSUE TITLE
ConstantFill is removed from ONNX 1.4

### ISSUE THREAD

**Issue by chinhuang007** [onnx/tensorflow-onnx#303]
The experimental ConstantFill op is totally removed from ONNX 1.4, https://github.com/onnx/onnx/pull/1434. This causes issues in frontend and backend handlers. Since ConstantFill is gone from ONNX code base, we can't declare it as an ONNX op anymore. 

Shall we simply delete our backend handler for ConstantFill and rework our frontend handler for tf.fill?

I am not sure how to support backward compatibility when the op is completely removed from ONNX. Suggestions are welcome.

**Comment by guschmue** [comment]
tensorflow-onnx avoids experimental ops as they can't be versioned. 
Just checked the tensorflow-onnx master - we do not use ConstantFill.

**Comment by chinhuang007** [comment]
Thanks for the comments!!

**Comment by guschmue** [comment]
thanks for checking :)
