### ISSUE TITLE
Command line output says says “using tensorflow=1.5.0, onnx=1.1.2”

### ISSUE THREAD

**Issue by choef** [onnx/tensorflow-onnx#32]
Commit description in GitHub says the converter should be updated to TF 1.8 and ONNX 1.2.

**Comment by guschmue** [comment]
the 'using' message is reporting what was found on the system, not what we want to be installed.
I just added a dependency to onnx-1.2 (https://github.com/onnx/tensorflow-onnx/pull/40) so it will be installed for you when you install tensorflow-onnx.
For tensorflow: we don't know if the user wants cpu or gpu so we use whatever is installed on the system.
