### ISSUE TITLE
Need simple const folding after conversion.

### ISSUE THREAD

**Issue by tlepley-cadence** [onnx/tensorflow-onnx#322]
We detected that a `Cast` (from int32 to int64) operation was recently added to the `shape` parameter of the `Rescale` operation (Commit 30fa07aa19ab9dcb70bcfd1e40249457f5eb9c0d by pengwa : fix few issues found in real model). 

Since ONNX opset 5, this `shape` parameter should indeed be a `int64` array (https://github.com/onnx/onnx/blob/master/docs/Changelog.md).  

Nevertheless, I'm wondering why this cast appears now (we have been using Opset 7 for some time already). Shouldn't this Cast be optimized out by tf2onnx (what was maybe done until now?), by converting the `shape` constant tensor to int64 at ONNX conversion time ?

**Comment by pengwa** [comment]
yes, the commit you mentioned did remove such a logic: a const node being int32, then we used to get the tensor value from it, then create a new tensor with the same value, BUT using int64, and feed the tensor as output of the original const node.

normally this is okay. but when it comes to situation, where the const node is used by more than one node, in-place updating upon the const node will make the other node failed. This is the bug hidden for a long time.

yeah we have opportunities to optimize out the cast, (and as well as many transposes I observed in other places) with some common constant folding after the whole model is converted. It should be easy to do this. But we haven't get a chance doing that yet.

**Comment by tlepley-cadence** [comment]
@pengwa thanks for the explanation. IMO, converting a Cast of constant into a constant should be part of the existing _constant folding_ optimization. As soon as a constant has only one user, it is safe to combine it with its user.

**Comment by tlepley-cadence** [comment]
By the way, I see the code for constant folding (`rewrite_constant_fold`), but it seems it doesn't get called. Was the constant folding optim disabled ?
```
    rewriters = [rewrite_transpose, rewrite_flatten,
                 rewrite_random_uniform, rewrite_random_uniform_fold_const,
                 rewrite_random_normal, rewrite_dropout, rewrite_leakyrelu,
                 rewrite_single_direction_lstm, rewrite_bi_direction_lstm,
                 rewrite_single_direction_gru, rewrite_single_direction_grublock,
                 rewrite_bi_direction_gru, rewrite_logical_compare_with_equal,
                 rewrite_custom_rnn_cell, rewrite_generic_loop, rewrite_cond
                 ]
```

**Comment by pengwa** [comment]
rewrite_constant_fold is actually written for pre-conversion graph. we don't enable it since we just use tf's tool do the folding. constant folding after the conversion should be pretty similar with this.

**Comment by tlepley-cadence** [comment]
The conversion to ONNX brings new opportunities for constant folding. This Cast operator added by tf2onnx is a case, and there may be others. Couldn't we enable `rewrite_constant_fold`, at least as an opt-in ?

**Comment by pengwa** [comment]
rewrite_constant_fold is written for folding before the conversion, e.g. it is targeting tensorflow node/type/graph. So yes we can use similar logic to fold after the graph converted to onnx, while we need a similar function targetting onnx node/type/graph.

**Comment by tlepley-cadence** [comment]
OK, I got it now :) Some 'rewrite' function operate on the TF representation while some others operate on the ONNX representation.

**Comment by pengwa** [comment]
yes exactly.

**Comment by pengwa** [comment]
currently we have cases, Const + Cast, Const+transpose , I'll take a look at them shortly.

**Comment by guschmue** [comment]
If one badly needs some constant folding on the onnx graph, we have a tool
https://github.com/onnx/tensorflow-onnx/blob/master/tools/onnx-experiments.py
that implements simple constant folding on the onnx graph after the conversion.

**Comment by nbcsm** [comment]
@tlepley-cadence, now we have [const_fold_optimizer.py](https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/optimizer/const_fold_optimizer.py) to fold const after conversion.
contribution is welcomed. :-)

**Comment by nbcsm** [comment]
https://github.com/onnx/tensorflow-onnx/pull/428
