### ISSUE TITLE
OneHot conversion issue

### ISSUE THREAD

**Issue by choef** [onnx/tensorflow-onnx#33]
Attatched file with error info
[OneHotSpew.txt](https://github.com/onnx/tensorflow-onnx/files/2064199/OneHotSpew.txt)

**Comment by guschmue** [comment]
It actually has issues with tf.cast, not sure why (we have a unit test for it that is happy) ... maybe send me your basic.pb.
tf.one_hot() like here:
https://github.com/onnx/tensorflow-onnx/blob/master/tests/test_backend.py#L730
has no mapping to onnx and it not going to work.

**Comment by guschmue** [comment]
worked around this in the converter for now ... we still want a onehot op in onnx
