### ISSUE TITLE
Select node with no shape attribute cannot convert from tf model to onnx one

### ISSUE THREAD

**Issue by OnceJune** [onnx/tensorflow-onnx#344]
I'm trying to convert a tensorflow graph which got a gmm_attention_wrapper and hit this error:

```
ERROR:tf2onnx.rewriter.loop_rewriter:loop rewrite failed, due to exception: object of type 'NoneType' has no len(), details:Traceback (most recent call last):
  File "lib/python3.7/site-packages/tf2onnx-0.4.0-py3.7.egg/tf2onnx/rewriter/loop_rewriter.py", line 68, in rewrite
    out_tensor_value_info.shape = utils.create_vague_shape_like(out_tensor_value_info.shape)
  File "lib/python3.7/site-packages/tf2onnx-0.4.0-py3.7.egg/tf2onnx/utils.py", line 346, in create_vague_shape_like
    make_sure(len(shape) >= 0, "rank should be >= 0")
TypeError: object of type 'NoneType' has no len()
```

I found there's a Select node (prefix/gmm_attention_wrapper/Select:0) that got only "dtype" attribute but no "shape" and trigger that exception.
Can anyone help with this issue?

**Comment by nbcsm** [comment]
@OnceJune, is that possible to share your model pb file please?
so we can take a further look?
thanks.

**Comment by OnceJune** [comment]
> @OnceJune, is that possible to share your model pb file please?
> so we can take a further look?
> thanks.

It's a tacotron2 model with gmmattention. Sorry I cannot share my model due to business security issue. Seems loop_writer tries to ensure the shape of a loop cond node but there's no "shape" attribute in a Select node.

**Comment by nbcsm** [comment]
is dynamic_decode used in this model?
i saw a similar issue recently when dealing with a tacotron2 like model.
dynamic_decode is not well supported currently, we are working on it.

**Comment by nbcsm** [comment]
it will be very helpful if you can reproduce the error with some basic simple tf script.
then you can share the script and the pb generated by this simple script, instead of the real model.

**Comment by OnceJune** [comment]
@nbcsm yes, dynamic_decode is used. so dynamic_decode is not fully supported even if I use the latest master branch?

**Comment by nbcsm** [comment]
yes, it is not supported yet.
we are working on it, just stay tuned. :-)

**Comment by OnceJune** [comment]
thank you so much. i'll try a simple graph and see if i can reproduce the problem.

**Comment by Aryta** [comment]
No

**Comment by nbcsm** [comment]
@OnceJune, we have supported dynamic_decode, please have a try on latest master.

i will close this PR, just re-open it if it does not work.
thanks.
