### ISSUE TITLE
Folding transpose before Conv2D fails

### ISSUE THREAD

**Issue by lucienwang1009** [onnx/tensorflow-onnx#356]
@guschmue folding transpose nodes before conv2d into the constant kernel will fail if more than one conv2d consume the same kernel.

If there are several consumers of a kernel (assuming n conv2d use the same kernel), the converter will add transpose nodes between the kernel and the first n-1 conv2d nodes.
Since current graph isn't updated in real time, these transpose nodes aren't added to the graph, which cut off the connections between the kernel and conv2d.
Then when converting the last conv2d which is the only consumer of the kernel in that time, the kernel will be transposed into a wrong value.

@pengwa talk to me offline that his PR for updating nodes will fix this bug. Maybe we should add some unit tests for the fold const optimization.

**Comment by zhijxu-MS** [comment]
i am going to introduce a new graph optimization phase into tf2onnx which includes const-folding.
and i have enhanced the transpose optimizer which will merge duplicated transpose nodes.

with these two changes I think we can add a transpose node directly even when transpose's input is a const.

**Comment by pengwa** [comment]
this should be fixed with attached PR merged, pls have a try, let me know whether it works.
