### ISSUE TITLE
Does GreaterEqual op support comparison with float32?

### ISSUE THREAD

**Issue by jiafatom** [onnx/tensorflow-onnx#385]
When I run onnxruntime on a converted onnx model (converted from tf2onnx), I got an error like this:
INVALID_GRAPH : Load model from model_data/yolov3.onnx failed:Type Error: Type 'tensor(float)' of input parameter (TFNodes_yolo_evaluation_layer_1_concat_10_0) of operator (Equal) in node (TFNodes_yolo_evaluation_layer_1_GreaterEqual_Equal__1209) is invalid.

I think this is when I convert the GreaterEqual op. When it uses rewrite_logical_compare_with_equal to convert, Equal op has two inputs. One is a constant 0.6 which is initializer, float32. The other is a float type. Looks like these two types mismatch. Shall we do cast for this? Thanks!

**Comment by jiafatom** [comment]
Looks like Equal op only supports tensor(bool), tensor(int32), tensor(int64) in onnx spec. However, in rewrite_logical_compare_with_equal, it seems that it applies to float type, so it causes the error. For GreaterEqual, would it be converted by a NOT and a LESS?

**Comment by guschmue** [comment]
I'll rewrite this a little.

**Comment by guschmue** [comment]
https://github.com/onnx/tensorflow-onnx/pull/389
