### ISSUE TITLE
Custom op does not make effect for GreaterEqual op

### ISSUE THREAD

**Issue by jiafatom** [onnx/tensorflow-onnx#386]
I tried to use a Custom op for GreaterEqual, but it does not make effect. Seems that it is because tfonnx uses rewrite_logical_compare_with_equal for GreaterEqual. For such a rewrite, it causes the custom op does not make effect. When I comment this out from rewriters, it will go to my custom op...How could we fix this issue? Thank you!

**Comment by guschmue** [comment]
https://github.com/onnx/tensorflow-onnx/pull/389
