### ISSUE TITLE
ellipse_mask in stridedslice may not support complicated use cases

### ISSUE THREAD

**Issue by jiafatom** [onnx/tensorflow-onnx#400]
Suppose I have a 5-dim tensor vec, and now I am using vec[..., 0:1], currently the strided slice logic can only apply start=0, end=max for axis=0. But it should be for axis 0,1,2,3. We can add a unit test to verify this first.

**Comment by zhijxu-MS** [comment]
@lucienwang1009  could you enhancement on stridedslice  cover this case?

**Comment by lucienwang1009** [comment]
Yes, it's a bug. We will see if it can be fixed easily.

**Comment by lucienwang1009** [comment]
should have been fixed by #589. Close.
