### ISSUE TITLE
Can we support tf.round

### ISSUE THREAD

**Issue by jiafatom** [onnx/tensorflow-onnx#403]
We can convert it to onnx ceil: round(x) = ceil(x-0.5). Could you please help support this? Thanks!

**Comment by guschmue** [comment]
can do.

**Comment by nbcsm** [comment]
@jiafatom, yes, there is no TF round equivalent in onnx.
we may be able to construct a sub-graph for that, but it won't be performance efficient.

@linkerzhang for awareness, maybe we need a new onnx op for round support.

**Comment by nbcsm** [comment]
@jiafatom, there was an **abandoned** PR for **approximate** tf round implementation, https://github.com/onnx/tensorflow-onnx/pull/373

you can use it as an **offline** workaround.

**Comment by guschmue** [comment]
nothing efficient we can do - I think it would take 6 element wise ops to compose this.
@linkerzhang ... +1, we need an onnx op for it.

**Comment by jiafatom** [comment]
@nbcsm @guschmue There was discussions about the new onnx op for round support. As far as I am aware, it is not going to add round support, just use ceil. The philosophy is to use existing op as much as possible to support new ops. Round can be implemented by ceil, so it will not add ceil op.
add @linkerzhang for awareness.

**Comment by guschmue** [comment]
doesn't make sense since using 6 or so element wise ops to implement tf.round() is going to be really slow. This needs to be added to onnx.

**Comment by jeffsaremi** [comment]
I need this for a Customer of ours. their model is using tf.round.
I will create a PR for the new specification

**Comment by jeffsaremi** [comment]
Created the following PR for this:
https://github.com/onnx/onnx/pull/2053

**Comment by guschmue** [comment]
tf.round is now supported with opset-11
