### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by prasanthpul** [onnx/tensorflow-onnx#412]
Add CI to ensure tf2onnx works on Python 3.7

**Comment by nbcsm** [comment]
tf2onnx depends on tensorflow, and tensorflow starts to support python 3.7 since 1.13.
we are enabling tf 1.13 currently, there are some minor compatibility issues to fix.

will enable python3.7 in CI with tf 1.13.

**Comment by nbcsm** [comment]
https://github.com/onnx/tensorflow-onnx/pull/452

**Comment by nbcsm** [comment]
onnx does not have python3.7 wheel either

**Comment by prasanthpul** [comment]
With ONNX 1.5 it will

**Comment by prasanthpul** [comment]
ONNX 1.5 WHLs are now available in test PyPi: https://test.pypi.org/project/onnx/#files (will be on official pypi soon)

**Comment by nbcsm** [comment]
done, close it.
