### ISSUE TITLE
Restructure tfonnx.py which is very large.

### ISSUE THREAD

**Issue by prasanthpul** [onnx/tensorflow-onnx#413]
Consider breaking into several files, per domain and per class of op (follow the ONNX op def groupings)

**Comment by pengwa** [comment]
There is a pr for this https://github.com/onnx/tensorflow-onnx/pull/404#issuecomment-475870711. But closed, @guohua for any comment

**Comment by guschmue** [comment]
There is a plan, #404 comes after this. 
The majority of the code is not the mapping, its the methods itself so we want to fix them first.

**Comment by guschmue** [comment]
https://github.com/onnx/tensorflow-onnx/pull/443
