### ISSUE TITLE
refine tf const folding

### ISSUE THREAD

**Issue by nbcsm** [onnx/tensorflow-onnx#417]
tf sometimes fails to fold some simple constants, need to improve it.

**Comment by tjingrant** [comment]
Hi @nbcsm, I'm one of the author of onnx-tf. We briefly covered this issue with our meeting with @guschmue yesterday and I wonder if you see the need to use a backend to do the constant folding. 

We have a constant folding pass in onnx-tf frontend (https://github.com/onnx/onnx-tensorflow/pull/305) that uses onnx-tf backend to evaluate constant onnx nodes, do you see a need to port it here? It doesn't need to be tied with onnx-tf, any onnx backend should work.

**Comment by guschmue** [comment]
So far we tried to avoid having a hard dependency on a backend so we constant fold a few things via numpy here: https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/tfonnx.py#L2104
But there are some issues with it.
We saw the need mostly for older tensorflow versions.

**Comment by guschmue** [comment]
Master uses grappler which does a much better job on constant folding.
