### ISSUE TITLE
generate and publish a list of ops supported

### ISSUE THREAD

**Issue by prasanthpul** [onnx/tensorflow-onnx#420]

**Comment by tjingrant** [comment]
I'll take this issue.

**Comment by nbcsm** [comment]
@tjingrant, any update on this? thanks.

**Comment by guschmue** [comment]
I think @tjingrant is waiting for me - I need to make a change to move the ops that we marked as opset4 to opset1 else his output would be all iffy.

**Comment by tjingrant** [comment]
Hi, @nbcsm  @guschmue yes, the doc wouldn't be correct if I generate the doc right now. @guschmue please drop me an email when you're done. I have some free time towards the end of next week and can probably use it to work on this feature.

**Comment by guschmue** [comment]
Yes, will do. Sorry, have been dragging this out.

**Comment by guschmue** [comment]
Ok, done - @tjingrant, all yours. If you are busy with other things we can help out.

**Comment by guschmue** [comment]
https://github.com/onnx/tensorflow-onnx/pull/612
