### ISSUE TITLE
Add missing ops that were supported in onnx-tensorflow frontend

### ISSUE THREAD

**Issue by chinhuang007** [onnx/tensorflow-onnx#424]
We would like to add the following operators that were supported in onnx-tensorflow frontend

- BatchNorm (not needed; never appears in TF graphs)
- Ceil (done)
- Conv1D (done)
- GRU (already covered by rewriter)
- LogicalXor (not needed; never appears in TF graphs)
- LSTM (already covered by rewriter)
- MaxPoolwithArgmax (done)
- RNN (already covered by rewriter)
- RandomStandardNormal (already covered by rewriter)
- Selu (done)
- Softplus (done)
- Softsign (done)

**Comment by guschmue** [comment]
I was wrong when I said we never call  the onnx GRU and LSTM ops - after checking, we do in some cases. We can maybe look at your test case to make sure we cover that.
RandomStandardNormal we do.
The remaining ones - sure.

**Comment by pengwa** [comment]
@guschmue  I did not remember we called GRU or LSTM, which case do you mean?

**Comment by pengwa** [comment]
@chinhuang007  do you mean TF has GRU/LSTM node that we should map? Can you elaborate about the mapping onnx-tensorflow frontend did for them?

**Comment by guschmue** [comment]
@pengwa  - I thought the same but Nathan keeps telling me we do call it. Found this: 
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/rewriter/lstm_rewriter.py#L275

**Comment by pengwa** [comment]
@guschmue  Yeah, that's the place we map tf control flow based RNN into a single LSTM/GRU op, so using that one is expected.

**Comment by guschmue** [comment]
Yeh, I get it now.

**Comment by pengwa** [comment]
about RandomStadardNormal, @chinhuang007  please kindly check https://github.com/onnx/tensorflow-onnx/blob/b2d3f9771887da56490e009093a3a97701700e27/tf2onnx/tfonnx.py#L1955 because there we rewriter the graph before doing the mapping, and we callied it Pre-Rewriter which might can save you guys some time :) .

**Comment by chinhuang007** [comment]
@pengwa Thanks for your comments. We simply compared with the mapping of ops in tfonnx.py, and have not looked into the rewriters. So I guess the ops like GRU, LSTM, RandomStadardNormal will be handled by some rewriters during the graph pre-processing?

**Comment by pengwa** [comment]
@chinhuang007  yes, it is. :) we have bunches of testing for that.

**Comment by chinhuang007** [comment]
Got it. We will remove GRU, LSTM, RandomStandardNormal from the list.

**Comment by pengwa** [comment]
@chinhuang007  cool! thanks!

**Comment by fferroni** [comment]
Hello, I am trying to convert a model but I get this error
```
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx-1.5.0-py3.6.egg/tf2onnx/tfonnx.py", line 550, in tensorflow_onnx_mapping
ValueError: tensorflow op Selu is not supported
```
Is there a chance Selu will be added soon to converter? I think it is already present in ONNX

**Comment by chinhuang007** [comment]
@guschmue The list is completed. So we might be able to close the issue.

**Comment by guschmue** [comment]
cool, thanks!
