### ISSUE TITLE
tf2onnx conversion fails with ValueError: Value "None" is not valid attribute data type.

### ISSUE THREAD

**Issue by PreethaVeera** [onnx/tensorflow-onnx#425]
The tf2onnx conversion of models mentioned in run_pretrained_models.yaml fails. Below is the error stack trace from the basic functionality tests - (regression-graphdef). 

> regression-graphdef
> 	downloaded tests/models/regression/graphdef/frozen.pb
> 	tensorflow OK
> using tensorflow=1.10.0, onnx=1.3.0, opset=7, tfonnx=0.5.0/dc792f
> 	to_onnx FAIL Value "None" is not valid attribute data type. Traceback (most recent call last):
>   File "tests/run_pretrained_models.py", line 271, in run_test
>     input_names=inputs.keys())
>   File "tests/run_pretrained_models.py", line 162, in to_onnx
>     input_names=input_names, output_names=self.output_names)
>   File "/home/.conda/envs/py36/lib/python3.6/site-packages/tf2onnx-0.5.0-py3.6.egg/tf2onnx/tfonnx.py", line 2509, in process_tf_graph
>     g = Graph(onnx_nodes, output_shapes, dtypes, target, opset, extra_opset, output_names)
>   File "/home/.conda/envs/py36/lib/python3.6/site-packages/tf2onnx-0.5.0-py3.6.egg/tf2onnx/graph.py", line 380, in __init__
>     self.make_node("Identity", [new_output_name], outputs=[o], op_name_scope=n.name + "_" + "graph_outputs")
>   File "/home/.conda/envs/py36/lib/python3.6/site-packages/tf2onnx-0.5.0-py3.6.egg/tf2onnx/graph.py", line 450, in make_node
>     onnx_node = helper.make_node(op_type, inputs, outputs, name=name, domain=domain, **raw_attr)
>   File "/home/.conda/envs/py36/lib/python3.6/site-packages/onnx/helper.py", line 51, in make_node
>     for key, value in sorted(kwargs.items()))
>   File "/home/.conda/envs/py36/lib/python3.6/site-packages/onnx/helper.py", line 51, in <genexpr>
>     for key, value in sorted(kwargs.items()))
>   File "/home/.conda/envs/py36/lib/python3.6/site-packages/onnx/helper.py", line 250, in make_attribute
>     'Value "{}" is not valid attribute data type.'.format(value))
> ValueError: Value "None" is not valid attribute data type.
> 

Has anyone faced the same issue? Any help will be appreciated.

**Comment by guschmue** [comment]
the master requires onnx-1.4.1 and if you have a tree and update with 'git pull' nobody notices.
```pip install -U onnx````
should fix it.

**Comment by PreethaVeera** [comment]
Upgrading ONNX version to 1.4.1 solves the issue. Thanks for the reponse.
