### ISSUE TITLE
log tensorflow, onnx info using log level or in another place?

### ISSUE THREAD

**Issue by jiafatom** [onnx/tensorflow-onnx#430]
I see in process_tf_graph() in tf2onnx/tfonnx.py, there is a print out in recent change:
` print("using tensorflow={}, onnx={}, opset={}, tfonnx={}/{}".format(
        tf.__version__, utils.get_onnx_version(), opset,
        tf2onnx.__version__, tf2onnx.version.git_version[:6]))`
Since keras convertor will call this function a lot of times (each sub-layer we need use tf2onnx), it is a bit annoying we see this log printing a lot. Could we use log level (like log debug) for printing this? or print this in another place? Thanks!

**Comment by guschmue** [comment]
+1, it used to be in convert.py

**Comment by nbcsm** [comment]
https://github.com/onnx/tensorflow-onnx/issues/448

**Comment by nbcsm** [comment]
https://github.com/onnx/tensorflow-onnx/pull/453
https://github.com/onnx/tensorflow-onnx/pull/459

now, logging level is supported, and one can use [tf2onnx.logging.set_level](url) to set level explicitly.
