### ISSUE TITLE
Converter debug output usability

### ISSUE THREAD

**Issue by awoodsmsft** [onnx/tensorflow-onnx#437]
When running the converter, the current output ends with the details of the last node to be converted.  No summary is presented to the user.  I suggest the following:

•	If (--output specified) “Conversion from {source} to {output} successful”
•	Else “Conversion processing of {source} successful, to export model run with ‘—output’”

**Comment by nbcsm** [comment]
https://github.com/onnx/tensorflow-onnx/issues/448

**Comment by nbcsm** [comment]
https://github.com/onnx/tensorflow-onnx/pull/459
