### ISSUE TITLE
test_softplus and test_softsign fails for tf < v1.10

### ISSUE THREAD

**Issue by nbcsm** [onnx/tensorflow-onnx#438]
introduced by https://github.com/onnx/tensorflow-onnx/pull/435

@chinhuang007, could you help to get it fixed please?
please refer to the build here for detail logs: https://github.com/onnx/tensorflow-onnx/runs/91188007

we have azure pipelines running for PR and push.
[unit_test-matrix.yml](https://github.com/onnx/tensorflow-onnx/blob/master/ci_build/azure_pipelines/unit_test-matrix.yml) will run for each push, but it is not enabled for PR currently.

**Comment by guschmue** [comment]
tf-1.9. I think this is a little inconsistent in tensorflow:

tf.math.softplus, alias tf.nn.softplus

tf.nn.softsign, alias tf.math.softsign (but the alias is not supported in tf-1.9)

As far I can tell tf.nn should work for all tf versions.

I can send a pr.

**Comment by guschmue** [comment]
https://github.com/onnx/tensorflow-onnx/pull/439
