### ISSUE TITLE
None types in Graph._output_shapes 

### ISSUE THREAD

**Issue by LucidusC** [onnx/tensorflow-onnx#441]
I'm trying to convert a frozen .pb files into onnx, however, there are some layer (namely: map/while/Enter, map/while/Enter_1, etc.) are reported as None in _output_shapes and causing get_shape(name) returns None and caused Error.  

Any cue on which part of code actually write values to Graph._output_shapes?  And under what circumstances it is supposed to be None?

Many thanks.

**Comment by guschmue** [comment]
In most cases we use shape inference info that we get from tensorflow. But that is not always available and we have additional shape inference in tf2onnx/shape_inference.py that will fill in the gaps. But tf2onnx/shape_inference.py is not complete yet, for example we have some additions coming that we ran into while converting ssd.
If you can share the model or some info about it we can take a look,

**Comment by ernestcheung** [comment]
@guschmue It would be great if you can take a look in it.
The layers that I am encountering a problem are of names: 
'''map/while/truediv, 
map/TensorArrayStack/TensorArrayGatherV3'''

If this would take too much time to fix it, it would also be great if you guys can point me to where I can learn to edit shape_inference.py;  (for example viewing the.pb from tensorboard and extract info to fill in shape_inference.py).

Thanks you so much!

**Comment by nbcsm** [comment]
@ernestcheung, [shape_inference.py](https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/shape_inference.py) is the place that we add code to deal with shape that cannot be got from tf directly.
you can view the file history to get the idea how we add support more ops.


basically, you can [dump graph](https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/graph.py#L836) after ```infer_shape_for_graph``` is called.

you can also open a tensorboard to view the original tf graph. you may want to try
https://github.com/onnx/tensorflow-onnx/blob/master/tools/tf_graph_tool.py#L199-L206

then locate the node that does not have a shape, follow its inputs on the graph, try to find ancestors which has shape and can be used to infer the missing one.

**Comment by guschmue** [comment]
I think this has improved over time, hope this issue no longer exists.
