### ISSUE TITLE
Cannot convert  mobilenet_v2_1.4_224

### ISSUE THREAD

**Issue by snnn** [onnx/tensorflow-onnx#444]
model: https://storage.googleapis.com/mobilenet_v2/checkpoints/mobilenet_v2_1.4_224.tgz

Model name: mobilenet_v2_1.4_224
Input: input
Output: MobilenetV2/Predictions/Reshape_1

command: '/usr/bin/python3', '-m', 'tf2onnx.convert', '--input', '/data/tmp/frozen_graph.pb', '--inputs', 'input:0', '--outputs', 'MobilenetV2/Predictions/Reshape_1:0', '--opset=9', '--fold_const', '--verbose', '--output', 'opset_9/mobilenet_v2_1.4_224/model.onnx'

error:
ERROR:tf2onnx:node MobilenetV2/Conv/Conv2D input needs to be rank 4, is 0
ERROR:tf2onnx:node MobilenetV2/Conv/Conv2D: exception list index out of range

tensorflow=1.13.1, onnx=1.4.1, opset=9, tfonnx=0.5.0/dc792f

**Comment by snnn** [comment]
The input has sahpe of "1,224,224,3". Do I need to append "--inputs-as-nchw" arg?

**Comment by guschmue** [comment]
1,224,224,3 is nhwc - if you want to pass in the image as nchw use --inputs-as-nchw

**Comment by guschmue** [comment]
On master: this does the same,  works but the tolerance is too high. Need to look at it:
```
run_pretrained_models.py --tests mobilenet_v2_1.4_224
mobilenet_v2_1.4_224
        downloaded /tmp/pre-trained\mobilenet_v2_1.4_224\mobilenet_v2_1.4_224_frozen.pb
        tensorflow OK
using tensorflow=1.10.0, onnx=1.4.1, opset=7, tfonnx=1.5.0/82f805
tensorflow ops: Counter({'Const': 158, 'Conv2D': 36, 'BiasAdd': 36, 'Relu6': 35, 'DepthwiseConv2dNative': 17, 'FusedBatchNorm': 17, 'Add': 10, 'Reshape': 2, 'Placeholder': 1, 'AvgPool': 1, 'Squeeze': 1, 'Softmax': 1, 'Shape': 1})
tensorflow attr: Counter({'dtype': 159, 'value': 158, 'T': 157, 'data_format': 107, 'strides': 54, 'padding': 54, 'dilations': 53, 'use_cudnn_on_gpu': 36, 'is_training': 17, 'epsilon': 17, 'Tshape': 2, 'shape': 1, 'ksize': 1, 'squeeze_dims': 1, 'out_type': 1})
onnx mapped: Counter({'Const': 158, 'Conv2D': 36, 'BiasAdd': 36, 'Relu6': 35, 'DepthwiseConv2dNative': 17, 'FusedBatchNorm': 17, 'Add': 10, 'Reshape': 2, 'Placeholder': 1, 'AvgPool': 1, 'Squeeze': 1, 'Shape': 1, 'Softmax': 1})
        to_onnx OK
        run_onnx OK
        Results:
Not equal to tolerance rtol=0.05, atol=1e-06

(mismatch 92.10789210789211%)
 x: array([[0.000349, 0.000175, 0.000181, ..., 0.000214, 0.000494, 0.007882]],
      dtype=float32)
 y: array([[0.000424, 0.000155, 0.000225, ..., 0.000572, 0.000218, 0.008519]],
      dtype=float32)
=== RESULT: 1 failed of 1, backend=onnxruntime
```

**Comment by snnn** [comment]
OK, I found the reason.  This model has incomplete shape info. So I need to fill in that information while doing conversion. However, the command line doesn't have such an arg, but the python APIs has. That why your unitest passed, but I still can't convert this model.

**Comment by guschmue** [comment]
You can do something like --inputs X:0[1,256,256,3].
Its in the readme but easy to miss.

**Comment by snnn** [comment]
Another option is: as the checkpoint and graph def files are there,  I can freeze the graph by myself, then it will have correct shape info. 
Thanks.

**Comment by cong235** [comment]
@snnn Can you share your code? I meet the same problems

**Comment by TUT-jiayou** [comment]
@snnn  I also meet  the errors

**Comment by TUT-jiayou** [comment]
@snnn HI, I also try to convert the same module as your one, I solved the errors
```
ERROR:tf2onnx:node MobilenetV2/Conv/Conv2D input needs to be rank 4, is 0
ERROR:tf2onnx:node MobilenetV2/Conv/Conv2D: exception list index out of range
```
execute the command
```
python -m tf2onnx.convert --input /data1/tensorflow/model/mobilenet_v2_1.4_224_frozen.pb --output /data1/mobilenet_v2_tf.onnx --inputs input:0[1,224,224,3]   --outputs MobilenetV2/Predictions/Reshape_1:0 --opset 7
```
but now I have a new error, 

![Selection_137](https://user-images.githubusercontent.com/21277368/83374024-eb1f3b00-a3fc-11ea-89f0-dfab1b66d1db.png)

could you help me ? thank for your time.
