### ISSUE TITLE
Selu and ScatterNd operations not supported?

### ISSUE THREAD

**Issue by fferroni** [onnx/tensorflow-onnx#455]
Hello,

I tried to convert a Tensorflow model which contains the following operations:

tf.scatter_nd 
tf.nn.selu

Neither of them seem to be supported by this conversion tool; however, they are present in the ONNX standard. Is someone going to add them?

**Comment by fferroni** [comment]
Interestingly, there are some onnx backend tests for i.e. gather_nd, so why do I fail at converting a graph
```
    @check_target('rs6', 'GatherNd')
    def test_gathernd(self):
        x_val = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float32)
        indices = np.array([[[0, 1], [1, 1]], [[1, 2], [0, 2]]], dtype=np.int32)
        x = tf.placeholder(tf.float32, x_val.shape, name=_TFINPUT)
        x_ = tf.gather_nd(x, tf.constant(indices))
        _ = tf.identity(x_, name=_TFOUTPUT)
        self._run_test_case([_OUTPUT], {_INPUT: x_val})
        tf.reset_default_graph()

        x_val = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=np.float32)
        indices = np.array([[[0], [2]], [[4], [7]], [[6], [1]]], dtype=np.int32)
        x = tf.placeholder(tf.float32, x_val.shape, name=_TFINPUT)
        x_ = tf.gather_nd(x, tf.constant(indices))
        _ = tf.identity(x_, name=_TFOUTPUT)
self._run_test_case([_OUTPUT], {_INPUT: x_val})
```

**Comment by guschmue** [comment]
selu we can take care of. scatter_nd we don't have, but we can take a look if we can do it with onnx.

**Comment by fferroni** [comment]
Ok great.. how quickly can I expect this? Anyway I can help?

**Comment by guschmue** [comment]
for something like selu you'd use a handler and for selu you can just add it to this list:
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/math.py#L37

**Comment by Shivanshmundra** [comment]
@guschmue thanks for the info. Can you please tell should I add in ```DirectOp``` or in some other?
Also, what is difference between ```Selu``` and ```LeakyRelu``` because for ```LeakyRelu``` rewriter has been written?

**Comment by chinhuang007** [comment]
I have PR coming in shortly to handle selu as a directop, part of closing issue https://github.com/onnx/tensorflow-onnx/issues/424.

**Comment by guschmue** [comment]
@Shivanshmundra for the handler vs rewriter question:
we use handlers most of the time and those always deal with 1 tensorflow op.
But for some tensorflow constructs you need to deal with a pattern of multiple ops and we use rewriters for those. They make a pass over the entire graph and in many cases use a graph matcher to match the pattern. The simplest example is RandomUniform where tensorflow uses more than 1 op so we match the pattern and replace that subgraph with the onnx equivalent: https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/rewriter/random_uniform.py#L17
In general those things are pretty painful ... handlers are more fun.

**Comment by nbcsm** [comment]
https://github.com/onnx/tensorflow-onnx/pull/511

**Comment by fferroni** [comment]
@chinhuang007 hi, i tried the latest master to convert a graph containing selu, after your merge, but it still complains that tensorflow op Selu is not supported. Using ONNX 1.5.0 and latest ft2onnx

**Comment by chinhuang007** [comment]
I looked into tf.scatter_nd finding it is very different from onnx.scatter in terms of how updates and indices are applied to produce the expected output tensor. I could flatten the tf inputs and calculate/create the indices in python, based on the input values, and eventually use the new updates and indices to get the result. However, I have not found the corresponding onnx operators to implement the exact logic needed in a graph. What I am trying to figure out is whether any other tf operators might have similar situations that a complex programming logic can't be represented in a onnx graph... Any suggestions and comments are welcome!

**Comment by Max-K-cadence** [comment]
Hi @chinhuang007, I've been watching at ScatterNd for some time and came to the same conclusion. There is no node that would do the exact thing in ONNX. I think the closest analogue is how GatherNd is implemented: for it, we generate a set of nested loops with Gather operations inside. Hope it helps!

**Comment by guschmue** [comment]
+1 on gathernd, going to be a bit of pain

**Comment by guschmue** [comment]
We added support for both.
