### ISSUE TITLE
Split operator - 'num_splits' attribute not available in the ONNX output

### ISSUE THREAD

**Issue by rajh619** [onnx/tensorflow-onnx#48]
I tried converting alexnet tensorflow model  to onnx  ,Unfortunately  in 'Split' operator the 'num_splits' attribute is not available in the converted ONNX  output . 
While conversion ,only the axis attribute is stored ,missing the num_splits value as shown below : 

https://github.com/onnx/tensorflow-onnx/blob/1ed0964c9ca924784478e50bbc0673f0c71692a7/tf2onnx/tfonnx.py#L644-L650

**Comment by guschmue** [comment]
You are right, the spec wants it:
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Split
But since I know multiple runtimes are happy with it, I checked the schema source:
https://github.com/onnx/onnx/blob/master/onnx/defs/tensor/defs.cc#L277
says it is optional ... documentation bug.
