### ISSUE TITLE
yolov2-voc conversion and Transposes

### ISSUE THREAD

**Issue by ayermolo** [onnx/tensorflow-onnx#480]
When graph is converted Transpose is not inserted for MaxPool.
Output graph is:
Input --> Transpose --> Conv -->Transpose --> Add (constant folded fusedBatchNorm) --> LeakyRelu --> MaxPool --> Transpose -->Conv

**Comment by ayermolo** [comment]
So I looked in to it some more. Issue seems to be triggered by rewrite_conv2d_with_pad, and some assumptions in conv_convert_inputs. More precisely it looks like it assumes that none constant inputs are already converted. Which is not true when rewrite_conv2d_with_pad happens. The conv_convert_inputs generates transpose for that input in to Conv, and then blindly sets parent, MaxPool, to NCHW. This parent.data_format = "NCHW" looks suspicious. It makes sense for when input is constant in if case, line 373, but I am not sure I understand the logic for always setting it at the end.

```
        for idx in input_indices:
            parent = node.inputs[idx]
            if node.inputs[idx].is_const():
                # if input is a constant, transpose that one
                if not parent.data_format:
                    val = parent.get_tensor_value(as_list=False)
                    parent.set_tensor_value(val.transpose(NHWC_TO_NCHW))
            else:
                # if input comes from a op, insert transpose op
                input_name = node.input[idx]
                transpose = ctx.insert_new_node_on_input(node, "Transpose", input_name)
                transpose.set_attr("perm", NHWC_TO_NCHW)
                transpose.skip_conversion = True
                shape = ctx.get_shape(input_name)
                new_shape = spatial_map(shape, NHWC_TO_NCHW)
                ctx.set_shape(transpose.output[0], new_shape)
            **parent.data_format = "NCHW"**
```

**Comment by nbcsm** [comment]
@ayermolo, the bug is fixed, and your model is working fine on my devbox, please give another try.
i will close this issue.

**Comment by ayermolo** [comment]
@nbcsm  Can confirm it works in my environment also. Thanks for fixing this!
