### ISSUE TITLE
Inception V4 broken

### ISSUE THREAD

**Issue by vuzelac-cadence** [onnx/tensorflow-onnx#490]
I've took Inception V4 from a checkpoint here: https://github.com/tensorflow/models/tree/master/research/slim

Close to the end, there is Flattening layer implemented using `StridedSlice`. TF2ONNX 0.3.1 will properly recognize flattening and will insert `Flatten `layer.
Current TF2ONNX generates:
```
Shape->Gather->Cast->Slice->Squeeze->Cast->Unsqueeze->Concat->Cast
                                           Unsqueeze-^
```
I am not evaluating this complex translation for correctness, however, `Squeeze `above removes axis=0 from 1D data which breaks the model.

**Comment by guschmue** [comment]
This is the same model that we use in our CI pipeline:
https://github.com/onnx/tensorflow-onnx/blob/master/tests/run_pretrained_models.yaml#L169 
As far I can tell its fine. If I run it manual:
```
python tests/run_pretrained_models.py --tests googlenet_v4_slim --opset 8
TensorFlow OK
Using tensorflow=1.13.1, onnx=1.4.1, tf2onnx=1.5.0/82f805
Using opset <onnx, 8>
Optimizing ONNX model
After optimization: Identity -2 (2->0), Transpose -86 (336->250)
To_ONNX, OK
Run_ONNX OK
Results: OK
RESULT: 0 failed of 1, backend=onnxruntime
```
results look good. (the rtol in the yaml file is 0.1 but I changed it to 0.01 in my tree and will send a PR for that).
We can take a look at the graph.

**Comment by vuzelac-cadence** [comment]
Thanks for a quick response.
Maybe I am missing something, but your script is downloading officially non-existent model: 
`https://github.com/tensorflow/models/tree/master/research/slim` 

This README lists the checkpoint files only, right ?

When freezing from a checkpoint using provided instructions (using TF1.13.1) the frozen model looks very different. I assume the model you use was frozen 2 years back using Tensorfflow version < 1.0.0.

**Comment by guschmue** [comment]
Ah, we use the frozen.pb from tensorflow team which is pretty old. 
I can try tf-1.13, see how that works.

**Comment by vuzelac-cadence** [comment]
Hi @guschmue , please let me know if I can help with anything. We have some customers blocked on Inception V4, and would like to enable them ASAP.

**Comment by zhijxu-MS** [comment]
hi @vuzelac-cadence could you please share with me the frozen pb file in your env?

**Comment by vuzelac-cadence** [comment]
@zhijxu-MS, I can only share to a specific email address - could you send me any email address I could use for communication ?

**Comment by zhijxu-MS** [comment]
pls email the  pb file to zhijxu@microsoft.com   .
i will have a double confirm with you after receiving.

**Comment by vuzelac-cadence** [comment]
File sent. Obtained using these commands:
```
python export_inference_graph.py -
       --alsologtostderr 
       --model_name=inception_v4 
       --output_file=graph.pb  
        
python freeze_graph.py 
       --input_graph=graph.pb 
       --input_checkpoint=inception_v4.ckpt 
       --output_graph=inception_v4_frozen.pb
       --output_node_names=InceptionV4/Logits/Predictions  
       --input_binary=True
```

**Comment by zhijxu-MS** [comment]
@vuzelac-cadence got you pb file while it looks good in my env for opset 8/9/10.

do you forget to add option "--fold_const"? 

my commnd is "run_pretrained_models.py --config ../../inception_v4_issues.yaml --opset 10 --target rs6 --debug --fold_const"
content of the yaml file in this command is as follows:
[tmp.txt](https://github.com/onnx/tensorflow-onnx/files/3184954/tmp.txt)

**Comment by guschmue** [comment]
do we need ```--target rs6``` ?

**Comment by zhijxu-MS** [comment]
@guschmue/@vuzelac-cadence   just tried, the --target is not need now.

**Comment by vuzelac-cadence** [comment]
I have sent the ONNX model (inception_v4_op9.onnx) - can you please confirm if your model  has the same sub-network and the end (subnetwork given in my 1st post) ?
If the same, isn't it wrong that the Squeeze is removing the axis=0 from 1D data ?

I would assume ONNXRUNTIME is not throwing any error because of #503 and https://github.com/onnx/onnx/issues/1993.

Another side problem with this sub-network:
CNTK doesn't support Shape. Many frameworks don't support non constant Reshape shape argument, so would need to go through a great deal of work in order to fold all this sub-network into a Constant. I am wondering why all this network even exists when you actually had it all nicely replaced with a Flatten layer in TF2ONNX 0.3.1 (see inception_v4_tf2onnx0.3.1.onnx I've shared as well).

**Comment by lucienwang1009** [comment]
It's a bug related to flatten_rewriter #554

**Comment by lucienwang1009** [comment]
@vuzelac-cadence does the PR fix your issue?

**Comment by nbcsm** [comment]
close it, @vuzelac-cadence feel free to reopen if there is still issue.

**Comment by TUT-jiayou** [comment]
HI, all
@guschmue  @vuzelac-cadence  @zhijxu-MS @lucienwang1009 
#  I also try to convert the  https://storage.googleapis.com/download.tensorflow.org/models/inception_v4_2016_09_09_frozen.pb.tar.gz to onnx, I got the error
```
/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/runpy.py:125: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
WARNING:tensorflow:From /home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2021-07-30 16:41:47,830 - WARNING - From /home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tf2onnx/verbose_logging.py:76: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

Traceback (most recent call last):
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tf2onnx/convert.py", line 605, in <module>
    main()
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tf2onnx/convert.py", line 213, in main
    graph_def, inputs, outputs = tf_loader.from_graphdef(args.graphdef, args.inputs, args.outputs)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tf2onnx/tf_loader.py", line 315, in from_graphdef
    frozen_graph = freeze_session(sess, input_names=input_names, output_names=output_names)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tf2onnx/tf_loader.py", line 262, in freeze_session
    graph_def = convert_variables_to_constants(sess, graph_def, output_node_names)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py", line 277, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py", line 197, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "/home/yons/workspace/anaconda3/envs/nx_cross_compilers/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py", line 152, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: graph/InceptionV4/Logits/Predictions is not in graph
```
#  used command
```
python -m tf2onnx.convert \
    --input $MODEL_DIR/inception_v4_2016_09_09_frozen.pb  \
    --inputs graph/input:0 \
    --outputs"graph/InceptionV4/Logits/Predictions:0" \
    --fold_const
```
# Env 
* Ubuntu18.04
* python 3.7.10
* tensorflow-estimator 1.15.1
* tensorflow-gpu 1.15.5
* onnx 1.6.0
* onnxruntime 1.3.0
* tf2onnx 1.9.1
* tensorrt 7.1.3
Thanks for your time.
