### ISSUE TITLE
list supported TF ops for each opset

### ISSUE THREAD

**Issue by nbcsm** [onnx/tensorflow-onnx#494]
explicitly list which TF ops are supported in each opset so data scientists can avoid unsupported ones during model development.

**Comment by guschmue** [comment]
dupe of https://github.com/onnx/tensorflow-onnx/issues/420 ?

**Comment by nbcsm** [comment]
not quite sure whether #420 is for overall supported ops or for each opset.
@tjingrant, any update on #420 please?

**Comment by guschmue** [comment]
fixed under #420
