### ISSUE TITLE
Unable to convert from simple Tensorflow/Keras model

### ISSUE THREAD

**Issue by BigFatFlo** [onnx/tensorflow-onnx#497]
Hi,

I'm trying to use tf2onnx to convert the simplest model I can find (the model for MNIST provided in the [tensorflow tutorials](https://www.tensorflow.org/tutorials)) in order to test the conversion process.
Unfortunately it doesn't work:

This is the code to build, train and save the model:

```
import tensorflow as tf
from tensorflow import keras

mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

saved_model_path = "./saved_models/saved_mnist"
keras.experimental.export_saved_model(model, saved_model_path)

```
Then when I try to convert it using:
`python -m tf2onnx.convert --saved-model ./saved_models/saved_mnist/`

I get this error:

> Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/bigfatflo/.local/lib/python3.6/site-packages/tf2onnx/convert.py", line 135, in <module>
    main()
  File "/home/bigfatflo/.local/lib/python3.6/site-packages/tf2onnx/convert.py", line 99, in main
    graph_def, inputs, outputs = loader.from_saved_model(args.saved_model, args.inputs, args.outputs)
  File "/home/bigfatflo/.local/lib/python3.6/site-packages/tf2onnx/loader.py", line 94, in from_saved_model
    outputs[output_tensor.name] = sess.graph.get_tensor_by_name(output_tensor.name)
  File "/home/bigfatflo/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3654, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/home/bigfatflo/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3478, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/bigfatflo/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3552, in _as_graph_element_locked
    raise ValueError(err_msg)
ValueError: The name 'init_1' refers to an Operation, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".

Any idea what the problem is?
Am I not supposed to use the Keras API in Tensorflow to get a model compatible with tf2onnx? 
Should I use the lower level APIs?

Thank you

**Comment by guschmue** [comment]
Ah, this is tf-2.0. I briefly looked at it - one of the outputs in the saved model is not a tensor. If I ignore that output it does convert find. Let me find a real fix for it.

**Comment by BigFatFlo** [comment]
Thank you for the quick reply.
Did you plan on supporting TF 2.0 in the near future or is it going to take a long time?
Being able to convert to ONNX would be a good enough reason for me to stick with TF 1.

**Comment by guschmue** [comment]
Sorry for the delay. I looked at it and can fix this specific issue (let me try to get to this by end of week). 
For full tf-2.0 support we'll need to do some more testing but we plan to do this very soon and we will support tf-2.0 for sure.

**Comment by BigFatFlo** [comment]
Thank you, that's good to hear.
Just out of curiosity, what causes a problem with the conversion? Is it the keras API? The "saved model" export?

**Comment by guschmue** [comment]
Sorry for the delay, it should be fixed now.
