### ISSUE TITLE
ValueError: StridedSlice: only strides=1 is supported

### ISSUE THREAD

**Issue by dlml** [onnx/tensorflow-onnx#509]
using tensorflow=1.4.0, onnx=1.5.0, opset=7, tfonnx=1.4.1/1ccb27

**Comment by zhijxu-MS** [comment]
could you try --opset 8 or 9 or 10 to see if it works? and we have enhance the conversion logic of strideslice again.

**Comment by guschmue** [comment]
We assume that is no longer an issue.
