### ISSUE TITLE
Need for some communication channel 

### ISSUE THREAD

**Issue by Shivanshmundra** [onnx/tensorflow-onnx#510]
Hi @nbcsm and other collaborators, 
Can we have any communication channel(maybe slack or gitter) for this project as asking small things on issue doesn't work good?
Also that would include contribution guidelines too.

**Comment by Shivanshmundra** [comment]
@nbcsm ping.

**Comment by nbcsm** [comment]
thanks for the suggestion.

for contribution guide, here it is:
https://github.com/onnx/tensorflow-onnx/blob/master/CONTRIBUTING.md

for other communication channel, we will think about it.

**Comment by guschmue** [comment]
Lets use this for now:
https://gitter.im/onnx/converters
