### ISSUE TITLE
Question: Did the convertor compare TF and converted ONNX model

### ISSUE THREAD

**Issue by fanghuaqi** [onnx/tensorflow-onnx#518]
Hi, I have question about the converted ONNX model, I simply looked into the source code and want to find whether there are code related to comparing the TF and converted onnx model, but I didn't find any, so I have question here, how did the tool to ensure the converted model works as TF model.

Thanks
Huaqi

**Comment by nbcsm** [comment]
currently, converter itself does not compare the results.
it is in the test scripts, e.g.:
https://github.com/onnx/tensorflow-onnx/blob/master/tests/backend_test_base.py#L98-L135
https://github.com/onnx/tensorflow-onnx/blob/master/tests/run_pretrained_models.py#L191

we may also support compare in converter in the future.
for now, you can construct a yaml file (similar to https://github.com/onnx/tensorflow-onnx/blob/master/tests/run_pretrained_models.yaml) and execute run_pretrained_models.py to convert+compare/validate.

**Comment by fanghuaqi** [comment]
@nbcsm Thanks for your information, I think it could be awesome if in the converter itself has compare and validate function in future.

**Comment by guschmue** [comment]
It gets more complex to specific the input data, that is why run_pretrained_models.py uses a yaml file. Don't think we want to add this directly to tf2onnx.
