### ISSUE TITLE
Support for running ONNX model with TF backend 

### ISSUE THREAD

**Issue by nglee** [onnx/tensorflow-onnx#520]
Hi, thank you for devoting your time and effort to this project.

I've tried to use [`onnx-tensorflow`](https://github.com/onnx/onnx-tensorflow) to run ONNX v1.4.1 model and it seems that the feature in `onnx-tensorflow` is somewhat outdated. I've followed the instructions [here](https://github.com/onnx/onnx-tensorflow#onnx-model-inference-with-tensorflow-backend) and the `prepare` function emits error messages such as: `ValueError: 'z.PlusArgs[0]_reshape1' is not a valid scope name`.

I've opened an issue here since it seems that the [`onnx-tensorflow`](https://github.com/onnx/onnx-tensorflow) repository is going to be merged into this project.

Does this project support training and running ONNX graph with TF backend, as the `onnx-tensorflow` project does? If not, is there any future plans for this feature?

**Comment by guschmue** [comment]
running the onnx graph under tensorflow will stay in [onnx-tensorflow](https://github.com/onnx/onnx-tensorflow) and this project does only tensorflow->onnx.
Don't think onnx-tensorflow supports training since onnx itself does not support this yet. If you mean exporting to onnx from the training script, there is a python api in tensorflow-onnx that you can call from the trainng script.

**Comment by nglee** [comment]
> running the onnx graph under tensorflow will stay in onnx-tensorflow and this project does only tensorflow->onnx.

Thanks for your confirmation.

> What is your original issue you mentioned above?

I was hoping that I could convert a `CNTK` model to a `TF` model.

To do so, firstly I've converted a `CNTK` pre-trained model(ResNet50 for ImageNet 1K) downloaded from [here](https://github.com/Microsoft/CNTK/blob/master/PretrainedModels/Image.md#resnet50-for-imagenet-1k) to `ONNX` format. I've followed the steps described [here](https://github.com/onnx/tutorials/blob/master/tutorials/CntkOnnxExport.ipynb). It seemed successful. The `CNTK` version I've used is `2.7` which supports `ONNX` v1.4.1.

However, I wasn't able to convert the `ONNX` model to `TF` model using `onnx-tensorflow`. I've followed the steps described [here](https://github.com/onnx/onnx-tensorflow/blob/master/example/onnx_to_tf.py).

The error message is:
https://gist.github.com/nglee/be7091c1abe96c75c6012b60e0ac3823

**Comment by guschmue** [comment]
This question should go to https://github.com/onnx/onnx-tensorflow
