### ISSUE TITLE
Keyerror:tf.float32_ref 

### ISSUE THREAD

**Issue by ignvinay** [onnx/tensorflow-onnx#527]
Hi,
   I am trying to convert the .pb to onnx of ssd mobilenet.
I followed the steps :

1) We are using tf2onnx script from below location :
https://github.com/onnx/tensorflow-onnx 
2) We have taken ssd_mobile_v1 from following location :
http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz
3)  First checked via tensorboard and got the inputs and outputs names .
4) Feeded these above inputs to script by running as below :
python -m tf2onnx.convert --input ..\ssd_mobilenet_v1_coco_2018_01_28\frozen_inference_graph.pb --inputs image_tensor:0[1,300,300,3]   --checkpoint ..\ssd_mobilenet_v1_coco_2018_01_28\model.ckpt.meta  --output ..\ssd_mobilenet_v1_coco_2018_01_28\ --outputs num_detections:0,detection_boxes:0,detection_scores:0,detection_classes:0

I get the following errors:
Any ideas on how to fix this.

My machine 
Windows 10
Tensorflow-gpu 1.12
onnx 1.5.0

_(tyqi_tf) D:\tf2onnx\tensorflow-onnx>python -m tf2onnx.convert --input ..\ssd_mobilenet_v1_coco_2018_01_28\frozen_inference_graph.pb --inputs image_tensor:0[1,300,300,3]   --checkpoint ..\ssd_mobilenet_v1_coco_2018_01_28\model.ckpt.meta  --output ..\ssd_mobilenet_v1_coco_2018_01_28\ --outputs num_detections:0,detection_boxes:0,detection_scores:0,detection_classes:0
Check ..\ssd_mobilenet_v1_coco_2018_01_28\frozen_inference_graph.pb ['image_tensor:0'] ['num_detections:0', 'detection_boxes:0', 'detection_scores:0', 'detection_classes:0']
2019-05-17 17:25:48,902 - INFO - Using tensorflow=1.12.0, onnx=1.5.0, tf2onnx=1.5.0/64423c
2019-05-17 17:25:48,902 - INFO - Using opset <onnx, 7>
2019-05-17 17:25:48,902 - INFO - Apply shape override:
2019-05-17 17:25:48,902 - INFO -        Set image_tensor:0 shape to [1, 300, 300, 3]
2019-05-17 17:25:54,186 - WARNING - Cannot infer shape for Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/zeros: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/zeros:0
Traceback (most recent call last):
  File "C:\Users\GF63\AppData\Local\conda\conda\envs\tyqi_tf\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\GF63\AppData\Local\conda\conda\envs\tyqi_tf\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\tf2onnx\tensorflow-onnx\tf2onnx\convert.py", line 146, in <module>
    main()
  File "D:\tf2onnx\tensorflow-onnx\tf2onnx\convert.py", line 128, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "D:\tf2onnx\tensorflow-onnx\tf2onnx\tfonnx.py", line 708, in process_tf_graph
    onnx_nodes, op_cnt, attr_cnt, output_shapes, dtypes = tensorflow_to_onnx(tf_graph, shape_override)
  File "D:\tf2onnx\tensorflow-onnx\tf2onnx\tfonnx.py", line 123, in tensorflow_to_onnx
    return tflist_to_onnx(graph.get_operations(), shape_override)
  File "D:\tf2onnx\tensorflow-onnx\tf2onnx\tfonnx.py", line 67, in tflist_to_onnx
    dtypes[out.name] = utils.map_tf_dtype(out.dtype)
  File "D:\tf2onnx\tensorflow-onnx\tf2onnx\utils.py", line 190, in map_tf_dtype
    dtype = TF_TO_ONNX_DTYPE[dtype]
KeyError: tf.float32_ref_

**Comment by guschmue** [comment]
```python -m tf2onnx.convert --input ..\ssd_mobilenet_v1_coco_2018_01_28\frozen_inference_graph.pb --inputs image_tensor:0[1,300,300,3] --output ..\ssd_mobilenet_v1_coco_2018_01_28\ --outputs num_detections:0,detection_boxes:0,detection_scores:0,detection_classes:0 --opset 10```
should work.
It should have been happy with ```--checkpoint``` and just freeze it, will take a look why that did not work.
I think you don't need the ```[1,300,300,3]```.

**Comment by ignvinay** [comment]
Hi guschmue,
    Thanks for your reply. I got the ONNX model from your recommended setting (opset 10). But it fails parsing in tensorrt, as it throws error saying unsupported UINT8 format.
    How do i resolve this problem?
What does this opset 10 does?, is there document describing these oprations ?
Also it would be great help in guiding me towards solving parsing problem.

Regards
Vinay

**Comment by guschmue** [comment]
The uint8 type comes from tensorflow and tf2onnx just maps it to the onnx equivalent. Sounds like tensorrt doesn't support that type yet. I'd open a tensorrt issue.

**Comment by ignvinay** [comment]
Thanks guschmue.
Please share some information on opset. I am not getting what are these.

**Comment by guschmue** [comment]
onnx has versioned ops called opsets. For ssd you need opset 10 since it includes thing like nms.

**Comment by zhijxu-MS** [comment]
@ignvinay  is the issues fixed? if so, I am going to close the issue, thanks.

**Comment by ignvinay** [comment]
No, the NVidia guys are saying next version (jetpack 4.2.1)will have the fix. But not yet out there in public.
Having said that, since this related to tensorRT, you can close this issue.
Thanks for the support.
