### ISSUE TITLE
ShapeInferenceError after upgrading tf2onnx to the latest released version

### ISSUE THREAD

**Issue by snnn** [onnx/tensorflow-onnx#529]
After upgrading tf2onnx from 1.4.0 to 1.5.1, it doesn't work for me anymore.
```
2019-05-20 13:04:18,402 - INFO - tf2onnx.tfonnx: Using tensorflow=1.13.1, onnx=1.5.0, tf2onnx=1.5.0/64423c
```

```
Test inception_v2 failed:Load model from /home/chasun/src/onnxruntime/scripts/opset_9/inception_v2/model.onnx failed:Node:reshape__613 Output:InceptionV2/Logits/Conv2d_1c_1x1/Conv2D__342:0 [ShapeInferenceError] Mismatch between number of source and target dimensions. Source=0 Target=4
```
The following one works
```
using tensorflow=1.13.1, onnx=1.5.0, opset=9, tfonnx=1.4.1/1ccb27
```

**Comment by lucienwang1009** [comment]
Can you share the frozen pb file?

**Comment by snnn** [comment]
https://onnxruntimetestdata.blob.core.windows.net/models/graph.zip

**Comment by lucienwang1009** [comment]
works find on my windows/linux machine, I use onnxruntime 0.4.0 from binary.

**Comment by snnn** [comment]
Could you please also try the lastest  onnxruntime master?

**Comment by lucienwang1009** [comment]
work fine on onnxruntime master/b9e8a.

**Comment by snnn** [comment]
I found the reason. I splitted the weights into a separated file, by calling the onnx functions:
```python
onnx.external_data_helper.convert_model_to_external_data(onnx_model, True,  'raw_data')
onnx.save(onnx_model, model_without_raw_data)
```

If I don't do that, it will be fine.
In tf2onnx  1.4.0, it also works even the weights are in a separated file.
I don't know what get changed in tf2onnx, but it seems more like a ONNX issue, not a converter issue.

**Comment by lucienwang1009** [comment]
close the issue since it's not a converter issue.
