### ISSUE TITLE
Perm Can't be dynamic in ONNX

### ISSUE THREAD

**Issue by Ersho** [onnx/tensorflow-onnx#534]
I am trying to convert this model to onnx. 

https://github.com/eragonruan/text-detection-ctpn/releases/download/untagged-48d74c6337a71b6b5f87/ctpn.pb

I have installed TF2ONNX with pip, my tensorflow version is 1.13.0. 

With summarize graph, model looks like this

![image](https://user-images.githubusercontent.com/16139977/58166144-3f47f900-7c9a-11e9-9d11-603c64d7b68c.png)

Due to this image, I try to run 

` python -m tf2onnx.convert --input ctpn.pb --output transfered.onnx  --inputs "Placeholder:0" --outputs "rpn_bbox_pred/Reshape_1:0,Reshape_2:0"`

And I run with 
`
ValueError: make_sure failure: perm can't be dynamic in ONNX
`

This error, but beforhand it prints 

`
ERROR - Failed to convert node lstm_o/bidirectional_rnn/fw/transpose
OP=Transpose
`

So, are the given parameters wrong? or do I have any other error?

**Comment by lucienwang1009** [comment]
ONNX [Transpose](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Transpose) require a constant perm as its attribute while in TF this perm can be a tensor. In your model, the perm input is a tensor from a subgraph of Range and Concat:
![image](https://user-images.githubusercontent.com/28888626/58180934-77bcf680-7cdd-11e9-9471-623b615b4e20.png)
The subgraph is expected to be folded by TF const folding but obviously it doesn't work... A workaround for now is to fold these two ops manually in your script. We will see if it's necessary to implement our own const folding (actually there has been a rewriter "rewrite_constant_fold" in tfonnx.py to handle the issue, but it's not stable yet).

**Comment by Ersho** [comment]
Thank you for the quick reply.

**Comment by oohlala1204** [comment]
Hi, I have a similar problem, and the error is:
```
2019-07-16 11:11:17,534 - ERROR - Failed to convert node rnn/transpose
OP=Transpose
Name=rnn/transpose
Inputs:
        Slice_1:0=Slice, [-1, 35, 39], 1
        rnn/concat:0=Concat, [3], 6
Outpus:
        rnn/transpose:0=[35, -1, 39], 1

......

ValueError: make_sure failure: perm can't be dynamic in ONNX
```

How to use the rewriter "rewrite_constant_fold" in tfonnx.py to handle this issue? I am very new to this, thanks a lot.
