### ISSUE TITLE
Specifying :0 cause problems

### ISSUE THREAD

**Issue by mrgloom** [onnx/tensorflow-onnx#539]
The names should be padded with `:0` and these names become names in onnx graph like `id: image_tensor:0`

`
python -m tf2onnx.convert --input ./model.pb --output ./faceboxes_feature_extractor.onnx --inputs image_tensor:0 --outputs prediction_layers/box_encoding_predictor_0/BiasAdd:0,prediction_layers/class_predictor_0/BiasAdd:0,prediction_layers/box_encoding_predictor_1/BiasAdd:0,prediction_layers/class_predictor_1/BiasAdd:0,prediction_layers/box_encoding_predictor_2/BiasAdd:0,prediction_layers/class_predictor_2/BiasAdd:0`

But this can be a reson of problems like https://github.com/onnx/onnx-tensorflow/issues/426

**Comment by mrgloom** [comment]
Related
https://github.com/onnx/tensorflow-onnx/issues/107

**Comment by guschmue** [comment]
true, we intentionally kept the names/outputs as they are in tensorflow but if you pass this to onnx-tf tensorflow is going to be unhappy about the colon in the name.
We plan fixing this soon, maybe initially with a ```--cnames``` option.

**Comment by guschmue** [comment]
Another related issue: https://github.com/onnx/tensorflow-onnx/issues/520.

**Comment by xiaotiancd** [comment]
hi，
Is there anyone working on this, we want to use it for a small project. Many thanks!

**Comment by guschmue** [comment]
no plan to change this. We prefer to use the tensor name as output instead of the node name.
