### ISSUE TITLE
pip install onnx==1.2 failed, No matching distribution found for onnx==1.2

### ISSUE THREAD

**Issue by pengwa** [onnx/tensorflow-onnx#54]
Could not find a version that satisfies the requirement onnx==1.2 (from versions: 0.1, 0.2, 0.2.1, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.2.1, 1.2.2)
No matching distribution found for onnx==1.2

I think we might need update the README for a version, which exists in https://pypi.org/project/onnx/#history? :)

**Comment by guschmue** [comment]
yes, my bad. I'll change the readme. setup.py will actually install it anyway.
