### ISSUE TITLE
need support for NotEqual / fp32

### ISSUE THREAD

**Issue by guschmue** [onnx/tensorflow-onnx#542]
Need support for NotEqual on fp32 type ... basically add a Not behind Equal.
Equal support is there but only supports int types correctly. fp32 will cast to int32 which is maybe not the correct way to compare floats.

**Comment by awoodsmsft** [comment]
@guschmue, has this issue been resolved?  You mentioned in email on 6/19 that you had resolved the "RuntimeError" issue, but there were _two_ of them, and this is the second.

**Comment by guschmue** [comment]
the issue is that onnx does not support float types for Equal/NotEqual and will take time to add it to onnx.
We can work around this with something like 
```
abs(a - b) > 0
```
at the cost of 2 extra element wise ops which is not helping performance,
I can add this for now.

**Comment by guschmue** [comment]
talked to some people - we'll try to get it into onnx and onnxruntime.

**Comment by guschmue** [comment]
both onnxruntime-master and tf2onnx should support this now. It's a bit iffy since opset-11 is not released yet.
