### ISSUE TITLE
Is there a way to select a subgraph of TensorFlow Graphs and convert it to ONNX subgraph

### ISSUE THREAD

**Issue by fanghuaqi** [onnx/tensorflow-onnx#545]
Hi, I have a question, in current TF2ONNX tool, if I want to convert a subgraph of TensorFlow graph into ONNX subgraph, is it possible to do it? 

Why I am asking this?
* We can find out that if we show a graph in Tensorboard, and we can see some nodes are under the same name scope, for example, see screenshot below:

![image](https://user-images.githubusercontent.com/1538922/58448334-2926b680-813a-11e9-90e3-ddddfe1d573d.png)

If we are able to convert this subgraph called `Preprocessor` which consist a lot of tf operators into onnx operators which might be smaller. 

We can have steps like this:
* Find subgraph in TF by name scope matching, or convert it to NetworkX and using functions in NetworkX to find subgraph
* Create equivalent subgraph using ONNX API to replace the subgraph of TF
* Create compare function to compare the subgraph in TF and ONNX to make sure the conversion is correct

Thanks
Huaqi

**Comment by fanghuaqi** [comment]
If we are capable to do this in TF2ONNX, and expose this function to users, then it will enable user to convert subgraph in TF to subgraph in ONNX, if there are some subgraphs not supported current TF2ONNX, user can convert it using this flow.

BR
Huaqi

**Comment by lucienwang1009** [comment]
Thanks for reaching out. TF2ONNX only provides inputs and outputs name as a boundary to extract subgraph from TF. And the inputs node should be Placeholder (converter only treats Placeholder as ONNX inputs). AFAIK, TF's APIs, `tf.graph_util.extract_sub_graph` and `tf.graph_util.convert_variables_to_constants`, also only support outputs to extract subgraph.

It's feasible to convert part of the graph if one creates Placeholders manually as the model inputs in our built-in graph and remove all useless nodes by `graph.extract_sub_graph_nodes`. But I feel it's more reasonable to be done by user in TF side rather than in converter. In fact, inputs and outputs name is used as additional information to help convert the graph rather than the boundary of model. @guschmue for comments.

**Comment by guschmue** [comment]
I think should should mostly work today, not totally sure if we depend on the placeholders. We should be able to make this work.
The way keras-onnx converter is using tf2onnx works a little like this.

**Comment by lucienwang1009** [comment]
@guschmue Yes, keras-onnx extracts the subgraph in some typical layers and then converts it with tf2onnx. And it indeed creates placeholders for all inputs when performing cropping:
https://github.com/onnx/keras-onnx/blob/5a37ba8e6b788eb22241349fb1a6e0fbb0b496eb/keras2onnx/subgraph.py#L130
We should be able to do the same work before mapping tf graph to our internal graph.

**Comment by fanghuaqi** [comment]
Thank you all for detailed comment, I think it could be good if we have something like I asked, subgraph/operator replacement

**Comment by lucienwang1009** [comment]
@fanghuaqi refer to #555 that enhances the utility of extracting subgraph according to name scope.

**Comment by fanghuaqi** [comment]
thanks @lucienwang1009, this utility is good.

Here is what I mean:
1. Take the [ssd_mobilenet_v1_coco](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz) model for example
2. This TF graph contains preprocessing part, feature extraction part, post-processing part, but preprocessing and post processing part is not easy to convert it by operator to operator, if we can do conversion by subgraph to subgraph, then it could be nice, so if for preprocessing part, first the convertor can select that subgraph by name scope passed by some configuration file, then user implement coresponding subgraph in ONNX
3. If we are capable to do this, then we can convert the whole graph, not only part of it by extract the feature extraction part using this utility
4. And also similar cases for the LSTM or RNN etc nodes, we can find the subgraph and convert to ONNX subgraph

BR
Huaqi

**Comment by lucienwang1009** [comment]
@fanghuaqi I understand what you mean. What you're looking for is a graph rewriter that replaces a subgraph in TF into a subgraph in ONNX. We do have several such rewriters in our converter but we don't support the customized rewriter. We will see if it's a common feature.
For now, you can implement your own name scope rewriter that resembles predefined rewriters. I'd like to recommend you to start from those in tf2onnx/tfonnx.py.

**Comment by guschmue** [comment]
We made some change recently that honors inputs and outputs that you pass in via command line and api so I think this should work now in your case.
