### ISSUE TITLE
TF while_loop condition might also depend on input TensorArray

### ISSUE THREAD

**Issue by lucienwang1009** [onnx/tensorflow-onnx#558]
Current loop_rewriter only considers the case that condition graph of TF only depends on state variables and ignore the dependency on input TensorArray. The following graph shows the special case when the condition depends on a state variable that no op consumes outside while_loop:
![image](https://user-images.githubusercontent.com/28888626/58788445-7addae00-861e-11e9-8558-29a27e118328.png)

**Comment by lucienwang1009** [comment]
It's a so rare case and resolving it in current rewriter is so difficult that we decide to leave it out.

**Comment by wangqiaoshi** [comment]
+1
