### ISSUE TITLE
Support FakeQuantWithMinMaxVars

### ISSUE THREAD

**Issue by letmaik** [onnx/tensorflow-onnx#559]
With opset 10 ONNX now has a few quantization ops. Could these be used to support TF's [FakeQuantWithMinMaxVars](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/fake-quant-with-min-max-vars)?

**Comment by guschmue** [comment]
Fyi @linkerzhang  , lets talk about this one tomorrow.

**Comment by guschmue** [comment]
The plan is this:

We'll  add support in tf2onnx to convert fake/simulated quantitization models to onnx(fp32)
onnxruntime will come with a onnx(fp32) -> onnx(int8) quantitzation tool.

If you run both steps you should get a working end to end solution.

Need to figure some details first before we know when we have it.

**Comment by huanyuan54** [comment]
@guschmue  Looking forward to onnx（fp32） - > onnx（int8） quantitzation tool.

**Comment by guschmue** [comment]
we are waiting for the tool before we add this to the converter so we can test it.

**Comment by rmccorm4** [comment]
Hi @guschmue,

Any updates on support for this? Came up here: https://devtalk.nvidia.com/default/topic/1071486/tensorrt/fake_quant_with_min_max_args-support.

**Comment by guschmue** [comment]
The quantization tool is here:
https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/quantization
I think the plan was to have the tool remove FakeQuantWithMinMaxVars  but just checked and it is not doing this - need to check why.
We could remove the FakeQuantWithMinMaxVars ops in tf2onnx but I fear the quantization tool badly would want the min/max from the ops.

**Comment by guschmue** [comment]
Somebody is working on adding support for FakeQuantWithMinMaxVars  to :
https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/quantization
Longterm the plan is to define an onnx op similar to FakeQuantWithMinMaxVars so it works the same way for other converters.

**Comment by rmccorm4** [comment]
Thanks for the update @guschmue !

I think there was a similar effort here: https://github.com/jhalakpatel/tensorflow-onnx/tree/fake_quant_ops_rewriter/tf2onnx/rewriter which worked for one case I encountered, in case it helps at all.

CC @jhalakpatel

**Comment by guschmue** [comment]
attaching this to https://github.com/onnx/tensorflow-onnx/issues/965, somebody is working on it.
