### ISSUE TITLE
converted GRU op has activation "sigmoid"

### ISSUE THREAD

**Issue by fjfjfan** [onnx/tensorflow-onnx#566]
Hello, 
Seems models in https://github.com/onnx/tensorflow-onnx/blob/master/tests/test_gru.py converted by tf-onnx will have activations like  "**sigmoid**", "Tanh", "sigmoid", "Tanh", since
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/rewriter/gru_rewriter.py#L123

Just wondering why it's "sigmoid", not "Sigmoid" as showed in https://github.com/onnx/onnx/blob/master/docs/Operators.md#GRU

Thanks!

**Comment by lucienwang1009** [comment]
It should be Sigmoid rather than sigmoid according to onnx specification. 
Using sigmoid doesn't cause problems in onnxruntime, as it's not case sensitive.
We will fix it in later version. Thanks for calling attention to our mistake.

**Comment by lucienwang1009** [comment]
Fixed by #583
