### ISSUE TITLE
GraphDef preprocessing to prune / replace unexisting ops

### ISSUE THREAD

**Issue by vadimkantorov** [onnx/tensorflow-onnx#568]
OpenSeq2Seq's model checkpoints, such as [wav2letter](https://nvidia.github.io/OpenSeq2Seq/html/speech-recognition/wave2letter.html#training) contain a HorovodAllreduce ops. So [`saver = tf.train.import_meta_graph(model_path, clear_devices=True)`](https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/loader.py#L76) fails with the error below. Currently one has to import horovod prior to conversion (the problem is that horovod requires MPI infra to build and doesn't provide pre-built pypi module).

It would be very nice if tf2onnx allowed removing / replacing such ops with Identity.

```
  File ".../.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1435, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File ".../.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1457, in _import_meta_graph_with_return_elements
    **kwargs))
  File ".../.local/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 806, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File ".../.local/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File ".../.local/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 399, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File ".../.local/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 159, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: 'HorovodAllreduce'
```

This is mostly relevant for a CLI interface.

**Comment by guschmue** [comment]
Fair point, models trained on tpu have a similar issue. Need to think a little how to go about this.

**Comment by vadimkantorov** [comment]
There is a very little documented tf.tools.graph_transforms.TransformGraph https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/python/transform_graph_test.py#L76. Maybe you could provide an ability to configure it through a CLI front-end and provide some recipes for users (common scenarios: help identify an input node from the data iterator; strip training nodes and loss etc).

**Comment by vadimkantorov** [comment]
Maybe it is possible to add on the fly OpDefs (with attibutes actually present in the graph def) for unknown ops to TensorFlow prior to graph import (it should be more reliable than having to remove these graph nodes manually from the graph entirely, in that case potential unresolved dependencies are an issue).

**Comment by mrgloom** [comment]
I have the same error `KeyError: 'HorovodAllreduce'` for model trained under horovod.
How can I fix it?

`Currently one has to import horovod prior to conversion`
Do I need to modify `/usr/local/lib/python3.7/site-packages/tf2onnx/tf_loader.py` adding something like `import horovod.tensorflow as hvd` on top of it?

**Comment by guschmue** [comment]
We don't have a clean way of loading such modules.
Best I can come up with it to use the a short python file and call the converter via python api: 
https://github.com/onnx/tensorflow-onnx#from_keras-tf-20-and-newer
