### ISSUE TITLE
GraphUtil.optimize_model_proto has issues when dealing with initializers

### ISSUE THREAD

**Issue by jiafatom** [onnx/tensorflow-onnx#573]
Hi, I have a big model, see part of it:
![before_opt](https://user-images.githubusercontent.com/30608893/58983126-f0ff2380-878a-11e9-8cdb-68b488274e34.png)

Before optimization, one initializer is an Identity with type [12]. After tf2onnx graphutil optimization, it becomes a Transpose node, input type[12], perm [0,3,1,2]

See here

![after_opt](https://user-images.githubusercontent.com/30608893/58983301-594e0500-878b-11e9-91ed-77c85cfde52a.png)

Ideally after optimization, the input type should be a 4-d tensor (meaning a Reshape should happen here). What is the issue here? Thank you so much!

**Comment by zhijxu-MS** [comment]
#588 fixes this issue, thank for the issuing it.
