### ISSUE TITLE
When will the new version be released?

### ISSUE THREAD

**Issue by fjfjfan** [onnx/tensorflow-onnx#575]
Dear admins,
when trying the UTs, found that the code in master has a lot of improvement to convert the tf models, so just wondering when it will be released and could be installed from pip? Thanks a lot!

**Comment by guschmue** [comment]
yes, can do in the next few days.

**Comment by guschmue** [comment]
not forgotten, waiting for some regression to be fixed.

**Comment by guschmue** [comment]
We released tf2onnx-1.5.2
