### ISSUE TITLE
ERROR - pass1 convert failed for name: "superpoint/IteratorFromStringHandleV2"

### ISSUE THREAD

**Issue by moonjiaoer** [onnx/tensorflow-onnx#576]
2019-06-06 13:34:42,354 - INFO - Using tensorflow=1.13.1, onnx=1.5.0, tf2onnx=1.5.1/0c735a
2019-06-06 13:34:42,354 - INFO - Using opset <onnx, 7>
2019-06-06 13:34:42,354 - INFO - Apply shape override:
2019-06-06 13:34:42,354 - INFO - 	Set superpoint/Placeholder:0 shape to [240, 320, 1]

2019-06-06 13:34:44,395 - ERROR - pass1 convert failed for name: "superpoint/IteratorFromStringHandleV2"

Hi
I tried to convert the tensorflow pb file to the onnx.
but it seems like your onnx can't support the op:"IteratorFromStringHandleV2"
I really hope to know if this can be solved?
Thx

**Comment by lucienwang1009** [comment]
It looks like involved in `tf.dataset` module. I doubt if it's possible to be handled by the current converter, as there isn't the corresponding concept in onnx spec.
My suggestion will be to modify tf graph, removing those dataset related ops and put the calculation in python script.

**Comment by moonjiaoer** [comment]
Hi @lucienwang1009 
Thanks for your reply.
Other question: we use the quantification in our network so we will have the node(op) which named  "FakeQuantWithMinMaxVars"
could onnx support for this op?
cause we will use this op in our network for many times and I think it's impossible to remove it from the tf graph.
here is part of our pb.file
![2019-06-04 19-16-55 的屏幕截图](https://user-images.githubusercontent.com/25788679/59236388-8174b280-8c28-11e9-9290-5a804e64e3bf.png)
![2019-06-04 19-17-43 的屏幕截图](https://user-images.githubusercontent.com/25788679/59236391-83d70c80-8c28-11e9-818e-47054bbbd46a.png)
![2019-06-04 19-17-59 的屏幕截图](https://user-images.githubusercontent.com/25788679/59236394-85a0d000-8c28-11e9-9afa-d9bffd9bb5ec.png)

**Comment by zhijxu-MS** [comment]
#599 has same requirement with FakeQuantWithMinMaxVars. we will investigate it and contribution is welcom.

**Comment by guschmue** [comment]
I think for FakeQuantWithMinMaxVars we need to discuss first internally.

**Comment by guschmue** [comment]
I'll check with onnx folks on FakeQuantWithMinMaxVars tomorrow.

**Comment by moonjiaoer** [comment]
Hi @guschmue 

Thanks for your reply.
BTW could I skip "IteratorFromStringHandleV2" via specifying input names?

**Comment by moonjiaoer** [comment]
Hi @guschmue @lucienwang1009 

Do you have any update for this issue?

**Comment by lucienwang1009** [comment]
@moonjiaoer please use `tools/tf_graph_tool.py extract` to cut out the subgraph. You can specify both the source nodes and the destination node.

**Comment by zxp771** [comment]
Hi @lucienwang1009 
Thanks for your reply.
I have another question about how to deal with the FakeQuantWithMinMaxVars nodes?
As the model graph, I uploaded those nodes are needed by every layer.
it's hard to cut out and I think even we cut out those nodes it will bring some new issue.
Thanks

**Comment by zxp771** [comment]
Hi @guschmue 
Do you have any update for this issue?

**Comment by guschmue** [comment]
FakeQuantWithMinMaxVars  goes with https://github.com/onnx/tensorflow-onnx/issues/559 ... we are waiting for the tool so we can test it end to end.

**Comment by guschmue** [comment]
attaching to https://github.com/onnx/tensorflow-onnx/issues/965
