### ISSUE TITLE
Bad Min conversion?

### ISSUE THREAD

**Issue by vadimkantorov** [onnx/tensorflow-onnx#579]
I'm trying to convert the openseq2seq's wav2letter model. It has `tf.min(tf.relu(x), 20)` activation function. 
With default opset = 7 it looks like:
![image](https://user-images.githubusercontent.com/1041752/59153373-1d9b8f80-8a58-11e9-9ab4-403df1953ab2.png)

In the source it is explained that it does sth like: `min(x -x + 20, x)` in order to implement broadcasting. Note that value = 20 is present in the graph.

With opset = 10 it looks like:
![image](https://user-images.githubusercontent.com/1041752/59153417-3193c100-8a59-11e9-8b10-7ca912a79b27.png)

Note that `20` is no longer present in node properties. Instead it refers to some `ForwardPass/w2l_encoder/Minimum/y:0`. I inspected it and it also does not contain the related attributes:
```
OP=Const
Name=ForwardPass/w2l_encoder/Minimum_17/y
Outpus:
        ForwardPass/w2l_encoder/Minimum_17/y:0=[], 10

name: "value"
t {
  data_type: 10
  name: "ForwardPass/w2l_encoder/Minimum_17/y:0"
  raw_data: "\000M"
}
type: TENSOR
```

**Comment by zhijxu-MS** [comment]
@vadimkantorov  wav2letter seems to be a public model, would you mind share with me the link to download it?

**Comment by lucienwang1009** [comment]
@vadimkantorov [Min](https://github.com/onnx/onnx/blob/master/docs/Operators.md#min) of opset >= 8 supports broadcasting so we don't need to do something `min(x -x + 20, x)`. And `ForwardPass/w2l_encoder/Minimum/y` does contain the value `20` as its `raw_data`.

**Comment by vadimkantorov** [comment]
@zhijxu-MS here is the link: https://drive.google.com/file/d/10EYe040qVW6cfygSZz6HwGQDylahQNSa/view?usp=sharing

**Comment by vadimkantorov** [comment]
Here is the onnx file that I got using [my conversion script (using tf2onnx under the hood)](https://github.com/vadimkantorov/tfcheckpoint2pytorch/blob/master/tfcheckpoint2pytorch.py)
[w2l_plus_large_mp.zip](https://github.com/onnx/tensorflow-onnx/files/3271033/w2l_plus_large_mp.zip)

**Comment by lucienwang1009** [comment]
@vadimkantorov Thanks for the detailed info. 
If there is no running error or mismatched result, it should be two different conversions of `Minimum` on different onnx opsets as what I said above.

**Comment by vadimkantorov** [comment]
@lucienwang1009 I understand the different ways of conversion for opset7 and opset10. I was just worried that value = 20 was not visible in Netron visualizer (when converted for opset10). But if you say it's present in the onnx graph, then please feel free to close this issue.

Anyway currently I'm blocked with tf2onnx usage by: https://github.com/onnx/tensorflow-onnx/issues/572 and https://github.com/onnx/tensorflow-onnx/issues/571 (TensorFlow uses BatchToSpaceND for representing dilated convolutions).

Thanks!

**Comment by lucienwang1009** [comment]
@vadimkantorov Thanks for a deal of feedback :) We will deal with them soon. For optimization enhancement, please feel free to file an issue.
