### ISSUE TITLE
Problem with loading converted onnx model

### ISSUE THREAD

**Issue by antonfr** [onnx/tensorflow-onnx#591]
Hi, 
I have converted to onnx ssdlite_mobilenet_v2_coco model from tensorflow detection model zoo (could be found [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md)). To convert, I used the following script:
`
$ python3 -m tf2onnx.convert --input frozen_inference_graph.pb --inputs image_tensor:0 --outputs num_detections:0,detection_classes:0,detection_boxes:0,detection_scores:0 --output ssd_mobilenet.onnx --fold_const --opset 10
` 
Here is the output of this script:
`
//anaconda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-06-07 12:57:24,367 - INFO - Using tensorflow=1.13.1, onnx=1.5.0, tf2onnx=1.5.1/0c735a
2019-06-07 12:57:24,367 - INFO - Using opset <onnx, 10>
2019-06-07 12:57:26,867 - WARNING - Cannot infer shape for Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/zeros: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/zeros:0
2019-06-07 12:57:53,960 - INFO - 
2019-06-07 12:57:54,552 - INFO - Optimizing ONNX model
2019-06-07 12:58:35,835 - INFO - After optimization: Add -76 (370->294), Cast -1 (1265->1264), Const -48 (2154->2106), Gather +6 (554->560), Identity -162 (165->3), Mul -21 (301->280), Reshape -33 (327->294), Shape -1 (111->110), Transpose -187 (385->198), Unsqueeze -7 (429->422)
`
Now I'm trying to load the model using ML.NET. I'm using the following code:
`        public struct ImageSettings
        {
            public const int ImageWidth = 300;
            public const int ImageHeight = 300;
            public const bool ChannelLast = true;
        }

        public struct SSDSettings
        {
            public const string SSDInput = "image_tensor:0";
            public const string SSDDetectionsOutput = "num_detections:0";
            public const string SSDClassesOutput = "detection_classes:0";
            public const string SSDBoxesOutput = "detection_boxes:0";
            public const string SSDScoresOutput = "detection_scores:0";
        }

        public PredictionEngine<ImageData, ImagePredictions> LoadModel(string modelLocation,
                                                                       string imagesLocation,
                                                                       string tagsLocation)
        {
            IDataView data = mLContext.Data.LoadFromTextFile<ImageData>(path: tagsLocation,
                                                                        hasHeader: false);
            var pipeline = mLContext.Transforms.LoadImages(outputColumnName: "image_tensor:0",
                                                           imageFolder: imagesLocation,
                                                           inputColumnName: nameof(ImageData.ImagePath))
                   .Append(mLContext.Transforms.ResizeImages(outputColumnName: "image_tensor:0",
                                                             imageWidth: ImageSettings.ImageWidth,
                                                             imageHeight: ImageSettings.ImageHeight,
                                                             inputColumnName: "image_tensor:0"))
                   .Append(mLContext.Transforms.ExtractPixels(outputColumnName: "image_tensor:0",
                                                              interleavePixelColors: ImageSettings.ChannelLast))
                   .Append(mLContext.Transforms.ApplyOnnxModel(modelFile: modelLocation,
                                                               outputColumnNames: new[] { SSDSettings.SSDDetectionsOutput,
                                                                                          SSDSettings.SSDClassesOutput,
                                                                                          SSDSettings.SSDBoxesOutput,
                                                                                          SSDSettings.SSDScoresOutput },
                                                               inputColumnNames: new[] { SSDSettings.SSDInput }));

            var model = pipeline.Fit(data);

            var predictionEngine = mLContext.Model.CreatePredictionEngine<ImageData, ImagePredictions>(model);
            return predictionEngine;
        }`

I got the following error:
`Error initializing model :Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:InvalidGraph] Load model from /my/path/to/file/ssd_mobilenet.onnx failed:Node:Preprocessor/map/strided_slice Node (Preprocessor/map/strided_slice) has input size 4 not in range [min=1, max=1].
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath, SessionOptions options) in C:\agent\_work\6\s\csharp\src\Microsoft.ML.OnnxRuntime\InferenceSession.cs:line 83
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath) in C:\agent\_work\6\s\csharp\src\Microsoft.ML.OnnxRuntime\InferenceSession.cs:line 31
   at Microsoft.ML.Transforms.Onnx.OnnxModel..ctor(String modelFile, Nullable 1 gpuDeviceId, Boolean fallbackToCpu)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, Options options, Byte[] modelBytes)`

How could I fix this error?
MacOS 10.13.6
Tensorflow 1.13.1
Onnx 1.5.0
ML.NET 1.0
Visual Studio 2019 8.0.5

**Comment by zhijxu-MS** [comment]
the error msg "strided_slice Node (Preprocessor/map/strided_slice) has input size 4 not in range [min=1, max=1]" seems to me like you are using a wrong onnxruntime version.
tf2onnx will convert stridedslice into slice, and [slice](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Slice) support 3~5 input in opset10, while supports only one input [below opset10](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Slice-1).

**Comment by antonfr** [comment]
@zhijxu-MS Without OnnxRuntime, I got input size error, with OnnxRuntime I got Graph Input is not associated with a node error. I'm using OnnxRuntime 0.4.0 version. I also tried to convert with another opset, but this tensorflow model can be converted only with opset 10.

**Comment by lucienwang1009** [comment]
It seems `Onnx type not supported` cause onnxruntime down rather than the input not found.
@antonfr could you please provide the full error log?

**Comment by antonfr** [comment]
@lucienwang1009 full error log is provided above. By the way, I'm trying to convert other ssd mobilenet models, and I got the same error, only graph input nodes change. Tested also with:

- ssd_mobilenet_v1_coco_2017_11_17 graph input names: i__18, cond__20, i__41, cond__43, i
- ssd_mobilenet_v1_coco_2018_01_28 graph input names: i__53, cond__55, i__24, cond__26, i
- ssd_mobilenet_v2_coco_2018_03_29 graph input names: i__22, cond__24, i__45, cond__47, i
- ssdlite_mobilenet_v2_coco_2018_05_09 graph input names: i__19, cond__21, i__42, cond__44, i

**Comment by guschmue** [comment]
We run ssd_mobilenet_v1_coco_2017_11_17 as part of mlperf https://github.com/mlperf/inference/tree/master/cloud/image_classification and it works fine.
I just tried ssdlite_mobilenet_v2_coco_2018_05_09 and it looks good too, including accuracy pass.
That was with onnxruntime.

There are some warnings from onnxruntime about memory planning which is being worked on and a few images fail because of some onnxruntime  which is also being worked on.

Don't think there is a tf2onnx issue here.

**Comment by antonfr** [comment]
@guschmue I've just tried to use your model and I've got the same problem as described above:
`
2019-06-14 09:56:48.057457 [W:onnxruntime:InferenceSession, session_state_initializer.cc:502 SaveInputOutputNamesToNodeMapping] Graph input with name i__22 is not associated with a node. 
2019-06-14 09:56:48.057524 [W:onnxruntime:InferenceSession, session_state_initializer.cc:502 SaveInputOutputNamesToNodeMapping] Graph input with name cond__24 is not associated with a node. 
2019-06-14 09:56:48.253452 [W:onnxruntime:InferenceSession, session_state_initializer.cc:502 SaveInputOutputNamesToNodeMapping] Graph input with name i__45 is not associated with a node. 
2019-06-14 09:56:48.253481 [W:onnxruntime:InferenceSession, session_state_initializer.cc:502 SaveInputOutputNamesToNodeMapping] Graph input with name cond__47 is not associated with a node. 
2019-06-14 09:56:48.253716 [W:onnxruntime:InferenceSession, session_state_initializer.cc:502 SaveInputOutputNamesToNodeMapping] Graph input with name i is not associated with a node. 
Onnx type not supported
`
If I use earlier version of OnnxRuntime, so once again I got `input size 4 not in range [min=1, max=1].` error.

**Comment by guschmue** [comment]
sounds like a runtime issue. Not sure what onnxruntime version you are using but master builds from June definitely work for me.

**Comment by antonfr** [comment]
@guschmue I use 0.4.0 via NuGet. Could you specify your OS, Visual Studio, Microsoft.ML, Microsoft.ML.ImageAnalytics, Microsoft.ML.CpuMath and Microsoft.ML.OnnxTransformer versions?

**Comment by guschmue** [comment]
I use a master build from early June.

**Comment by lucienwang1009** [comment]
Close it as it seems a runtime related issue.
