### ISSUE TITLE
Feature request: option to fold Transpose + Conv + Transpose -> Conv

### ISSUE THREAD

**Issue by vadimkantorov** [onnx/tensorflow-onnx#593]
This is original exported ONNX by tf-onnx:
[w2l_plus_large_mp.zip](https://github.com/onnx/tensorflow-onnx/files/3284920/w2l_plus_large_mp.zip)

**Comment by zhijxu-MS** [comment]
we have transpose optimizer to remove transpose if possible. it looks like you don't use the optimizer.
could you please tell me how do invoke tf2onnx. ideally, the following transpose can be removed.
![image](https://user-images.githubusercontent.com/43435212/59418899-68245f80-8dfc-11e9-9e49-ae8ee5d2026c.png)

**Comment by zhijxu-MS** [comment]
we have transpose optimizer to remove transpose optimizer if possible, have you enabled it.
and the snapshot from your model looks like you don't freeze the tf graph since it contains a lot of variable.
![image](https://user-images.githubusercontent.com/43435212/59419162-e84ac500-8dfc-11e9-9397-f0a898ce1f63.png)

**Comment by zhijxu-MS** [comment]
graph_def = meta_graph.read_meta_graph_file(meta_graph_file).graph_def
could you freeze your checkpoint instead of using meta_graph which doesn't contain weight?

**Comment by vadimkantorov** [comment]
I had to modify graph_def first before freezing (otherwise not installed horovod is breaking loading). I think I succeeded once freezing the graph when passing modified `meta_graph_def` to `import_meta_graph` - so this was possible, you are right.

**Comment by zhijxu-MS** [comment]
BatchToSpaceND is going to support 3D data now(#590). if you have another request on BatchToSpaceND, feel free to issue an feature request.

**Comment by zhijxu-MS** [comment]
BTW, is ur problem in this issue fixed? if so, I am going to close it, thanks.

**Comment by vadimkantorov** [comment]
This issue was a minor feature request that could make the output graph simpler to inspect :) This issue was not a blocking issue (e.g. https://github.com/onnx/tensorflow-onnx/issues/578, https://github.com/onnx/tensorflow-onnx/issues/568, https://github.com/onnx/tensorflow-onnx/issues/571 were more serious issues for practical converter usage)
