### ISSUE TITLE
Missing op InvertPermutation

### ISSUE THREAD

**Issue by fuzzyBatman** [onnx/tensorflow-onnx#595]
Hi. I would like to add the [InvertPermutation](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/invert-permutation) op to this project.
How do I get started?

**Comment by lucienwang1009** [comment]
@fuzzyBatman It seems too complex to compose this op into onnx subgraph. We may need onnx's support to convert this op.

**Comment by fuzzyBatman** [comment]
Oh. Do you have an idea about the process?
Should this op be added to **onnx**, or to **tf-onnx** with some feature support from onnx?

**Comment by lucienwang1009** [comment]
I believe it should be added to onnx. @guschmue for comments.

**Comment by guschmue** [comment]
If we need a new op to onnx the process is sometime like this:
-submit a pr to onnx and get it accepted
-wait for the implementation in onnxruntime (we need that only so we can add unit tests in tf2onnx)
-add support for the new op to tf2onnx

**Comment by fuzzyBatman** [comment]
Thank you. Should I open an issue on onnx?

Btw , I've been reading some PRs in the ONNX repo to understand how to add operators, I am unable to find the code that defines the op logic. Can you help me understand how this works? Consider the [EyeLike](https://github.com/onnx/onnx/pull/1428/files) op example.

**Comment by fuzzyBatman** [comment]
@lucienwang1009 @guschmue I do not understand how ONNX works. I read the _adding a new operator_ section but I am little confused.

Say I want to add the invert_permutation op to ONNX. I should submit a PR to ONNX which contains the Op schema, definition in docs and some test cases, as done in the EyeLike op example PR, and that is it? The implementation is done elsewhere?

**Comment by zhijxu-MS** [comment]
**ONNX** defines opetation schema.
**ONNX backend**, for example ONNXRunTime, implements ONNX opetaion.

**Comment by fuzzyBatman** [comment]
@zhijxu-MS Thanks!
