### ISSUE TITLE
Missing op CropAndResize

### ISSUE THREAD

**Issue by fuzzyBatman** [onnx/tensorflow-onnx#596]
Hi. I would like to add the [CropAndResize](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/crop-and-resize) op to this project.

**Comment by lucienwang1009** [comment]
Thanks very much for your contribution. This is a related issue: https://github.com/onnx/onnx/issues/2100

**Comment by lucienwang1009** [comment]
here is the changing for RoiAlign in order to support CropAndResize: https://github.com/onnx/onnx/pull/2102/files

**Comment by guschmue** [comment]
CropAndResize seems to be in opset-11: https://github.com/onnx/onnx/pull/2142. In this case we'll automatically add it to the converter when opset-11 releases.

**Comment by guschmue** [comment]
This is now supported in master.
