### ISSUE TITLE
Issues when you are using Python2

### ISSUE THREAD

**Issue by pengwa** [onnx/tensorflow-onnx#60]
Though it is clearly stated that tensorflow-onnx is tested on Python3 only, I think it's necessary to list some issues in case you have (actually I have experienced) when using Python2 accidentally (and got here after searching with error messages) , if you turn to Python3, all of them are gone. 

- Failed case 1 when run example command. This is caused by some circular import as I understand. https://stackoverflow.com/questions/17845366/importerror-cannot-import-name/17845428. 
basically, tensorflow-onnx/tf2onnx/__init__.py is importing tfonnx, utils, graph, etc; while graph.py/tfonnx.py is importing tf2onnx. 

> **/usr/bin/python: cannot import name tfonnx**

- Failed case 2 when run example command, this seems to be caused by Python2 & Python3 are treating the unicode differently. The former requires an explicit convert with str() for unicode. [[a similar issue at stackoverflow](https://stackoverflow.com/questions/20905702/typeerror-argument-of-type-char-const)]

> python -m tf2onnx.convert --input tests/models/fc-layers/frozen.pb --inputs X:0 --outputs output:0 --output tests/models/fc-layers/model.onnx --verboseusing tensorflow=1.8.0, onnx=1.2.2
> 2018-06-28 16:08:50.136707: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_batch_norms
> 2018-06-28 16:08:50.137558: I tensorflow/tools/graph_transforms/transform_graph.cc:264] Applying fold_old_batch_norms
> 2018-06-28 16:08:50.150945: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2018-06-28 16:08:50.241093: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
> name: Quadro K620 major: 5 minor: 0 memoryClockRate(GHz): 1.124
> pciBusID: 0000:03:00.0
> totalMemory: 1.95GiB freeMemory: 1.57GiB
> 2018-06-28 16:08:50.241123: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
> 2018-06-28 16:11:11.227140: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2018-06-28 16:11:11.227167: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
> 2018-06-28 16:11:11.227173: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
> 2018-06-28 16:11:11.227317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1314 MB memory) -> physical GPU (device: 0, name: Quadro K620, pci bus id: 0000:03:00.0, compute capability: 5.0)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/home//community/tensorflow-onnx/tf2onnx/convert.py", line 97, in <module>
>     main()
>   File "/home//community/tensorflow-onnx/tf2onnx/convert.py", line 85, in main
>     extra_opset=extra_opset)
>   File "tf2onnx/tfonnx.py", line 1182, in process_tf_graph
>     onnx_nodes, op_cnt, attr_cnt, output_shapes, dtypes = tensorflow_to_onnx(tf_graph)
>   File "tf2onnx/tfonnx.py", line 85, in tensorflow_to_onnx
>     onnx_tensor = utils.tf_to_onnx_tensor(node.get_attr(a), name=node.name + ":0")
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2327, in get_attr
>     c_api.TF_OperationGetAttrValueProto(self._c_op, name, buf)
> TypeError: in method 'TF_OperationGetAttrValueProto', argument 2 of type 'char const *'

**Comment by guschmue** [comment]
Yes, sorry ... we're python3 shop and have not been testing with python2 at all. Let me see if we can fix it.

**Comment by guschmue** [comment]
with numpy abandoning python2.7 with 1.17 it doesn't make sense for us to support it.
