### ISSUE TITLE
_concat_handler in transpose_optimizer has issues

### ISSUE THREAD

**Issue by jiafatom** [onnx/tensorflow-onnx#600]
The current logic is to set axis to 1 for any cases. But for the case ROIAlign->Transpose[0,2,3,1]->Concat, this still needs be 0, because it concats based on the num_roi axes which is 0.

**Comment by zhijxu-MS** [comment]
will fix this in the near future.

**Comment by zhijxu-MS** [comment]
fix in https://github.com/onnx/tensorflow-onnx/pull/607
