### ISSUE TITLE
The op output dtype "tf.resource" is not supported

### ISSUE THREAD

**Issue by JerryShih** [onnx/tensorflow-onnx#61]
I try to use convert the trained [ssd_mobilenet_v1_coco model](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2017_11_17.tar.gz)(frozen_inference_graph.pb) in [tensorflow model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md), but the "types_pb2.DT_RESOURCE" type is not supported in "TF_TO_ONNX_DTYPE".

Here is the def for that type:
https://www.tensorflow.org/api_docs/python/tf/DType

tf.resource: Handle to a mutable resource.

I'm a beginner for tensorflow, so I don't know the actual meaning for that op output type.

The error message:
  File "/usr/local/lib/python3.6/site-packages/tf2onnx-0.0.2.0-py3.6.egg/tf2onnx/convert.py", line 85, in main
  File "/usr/local/lib/python3.6/site-packages/tf2onnx-0.0.2.0-py3.6.egg/tf2onnx/tfonnx.py", line 1183, in process_tf_graph
  File "/usr/local/lib/python3.6/site-packages/tf2onnx-0.0.2.0-py3.6.egg/tf2onnx/tfonnx.py", line 60, in tensorflow_to_onnx
  File "/usr/local/lib/python3.6/site-packages/tf2onnx-0.0.2.0-py3.6.egg/tf2onnx/utils.py", line 154, in map_tf_dtype
KeyError: tf.resource

**Comment by guschmue** [comment]
There is no equivalent to tf.resource in onnx. I'll take a look at the model if there is something we can do deal with it.

**Comment by pengwa** [comment]
I checked ssd_mobilenet_v2_coco model, all DT_RESOURCE type (e.g. tf.resource) are in Enter operator node, it looks like below:

`
node {
  name: "Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArray_9"
  op: "TensorArrayV3"
  input: "Postprocessor/BatchMultiClassNonMaxSuppression/map/strided_slice"
  attr {
    key: "clear_after_read"
    value {
      b: true
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "dynamic_size"
    value {
      b: false
    }
  }
  attr {
    key: "element_shape"
    value {
      shape {
        unknown_rank: true
      }
    }
  }
  attr {
    key: "identical_element_shapes"
    value {
      b: true
    }
  }
  attr {
    key: "tensor_array_name"
    value {
      s: ""
    }
  }
}


node {
  name: "Postprocessor/BatchMultiClassNonMaxSuppression/map/while/TensorArrayWrite_4/TensorArrayWriteV3/Enter"
  op: "Enter"
  input: "Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArray_9"
  attr {
    key: "T"
    value {
      type: DT_RESOURCE
    }
  }
  attr {
    key: "frame_name"
    value {
      s: "Postprocessor/BatchMultiClassNonMaxSuppression/map/while/while_context"
    }
  }
  attr {
    key: "is_constant"
    value {
      b: true
    }
  }
  attr {
    key: "parallel_iterations"
    value {
      i: 32
    }
  }
}

`

So I think/assume if we later solve the control-flow map, this issue will get resolved.

**Comment by guschmue** [comment]
Ah. The TensorArray comes in many cases together with control flow, aka when looping one might also need a more flexible way of to manipulate tensors. Onnx control flow would not cover TensorArray and I'm not sure yet if it is good enough to map things in the converter. We need to walk over some concrete example.

**Comment by laobadao** [comment]
The same question, is there any wonderful solution? Still can only wait for onnx to make changes?

**Comment by guschmue** [comment]
The Enter belongs to control flow and the TensorArray is a side effect of the control flow in tensorflow. Control flow is suppose to come with onnx 1.3. If there we'd need to rewrite the graph to the onnx control flow which is maybe ok but I'm concerned that we'll run into issues mapping the TensorArray to onnx but have not given it much thought.
But until onnx 1.3 there is no way to get this to work.

**Comment by thlinh** [comment]
@guschmue : I have similar problems. In the announcement (https://github.com/onnx/onnx/wiki/ONNX-version-1.3-Released ) it's said that Control Flow is introduced already. Did you have a chance to check that? Thanks!

**Comment by guschmue** [comment]
Yes, opset 8 has it. We looked at it and think we can map tensorflow control flow to it.
Waiting for a runtime that supports the control flow before we start on it ... best guess is that in oct we start supporting some of the opset 8 control flow.

**Comment by zcc720** [comment]
ValueError: Graph has cycles.
when i convert my Object Detection Models(ssd_mobilenet_v2) to onnx, I encountered this mistake.
Is this situation related to this?

**Comment by guschmue** [comment]
I think this is fixed.
