### ISSUE TITLE
pool_op()  add_padding() [p_y0, p_x0, p_y1, p_x1] implement subsample  has a [-1,-1,,0,0] result 

### ISSUE THREAD

**Issue by laobadao** [onnx/tensorflow-onnx#64]
tensorflow code:

layers.max_pool2d(inputs, [1, 1], stride=[2,2], padding="SAME") to implement subsample in resnetv1_50,

tf-onnx:
pool_op () ksize =[1,1] stride=[2,2], padding="SAME"

  [p_y0, p_x0, p_y1, p_x1]=  [-1,-1,0,0] 

run_caffe2 :
still  this problem 
[enforce fail at conv_pool_op_base.h:154] pads_[dim] >= 0. -1 vs 0

**Comment by guschmue** [comment]
yes, kernel size = 1 is broken. I'll fix it tomorrow.

**Comment by guschmue** [comment]
I have a fix, still adding more unit test to have some better coverage in that area.

**Comment by guschmue** [comment]
Should be fixed:
https://github.com/onnx/tensorflow-onnx/pull/67

**Comment by laobadao** [comment]
@guschmue Great!
