### ISSUE TITLE
Could you provde a guide for how to convert LSTM model

### ISSUE THREAD

**Issue by fanghuaqi** [onnx/tensorflow-onnx#640]
Hi, according to this link https://github.com/onnx/tensorflow-onnx/blob/master/examples/rnn_tips.md, rnn and lstm cells are supported, but I tried to convert some frozen lstm model, I can't convert it correctly, the converter is just doing operator to operator conversion, but I am expecting the tensorflow lstm graph nodes can be converted to onnx lstm node, not like this.

I tried to convert the model located in `tests/models/lstm/frozen.pb`, here is my command:

```
python tf2onnx/convert.py --input tests/models/lstm/frozen.pb --output test.onnx --inputs X:0,keep_prop:0 --outputs output:0 -v --opset 8  --fold_const
```

here is the converted graph
![image](https://user-images.githubusercontent.com/1538922/60655878-0eee9f80-9e81-11e9-9eac-287ef84db8e9.png)

I thought the converted graph should use LSTM operator of ONNX, but actually not, could you give me some hints on it.

Thanks
Huaqi

**Comment by lucienwang1009** [comment]
It seems you used an unrolled LSTM, since there are no `while_loop` operators. 
The current converter cannot handle this form of LSTM in the sense of rewriting it into a single LSTM op.

**Comment by fanghuaqi** [comment]
Hi @lucienwang1009 ,  thanks for your explaination, this `tests/models/lstm/frozen.pb` are the one located in this repo, I thought it could be converted, could you point out 1 pb file with LSTM node in it that TF2ONNX could convert, I would like to take a try.

**Comment by lucienwang1009** [comment]
We have plenty of unit tests for LSTM in `tests/test_lstm.py`. You can easily create a sample TF LSTM model and convert it to ONNX by `python tests/test_lstm.py --debug`. The frozen TF graph and converted ONNX model are under $TF2ONNX_TEMP_DIRECTORY.

**Comment by fanghuaqi** [comment]
OK, it looks good to me, but why there is no support for static rnn(the unroll one), any plan to support it in future?

**Comment by lucienwang1009** [comment]
It's doable, but not of high priority. The current converter is able to convert static rnn and achieve comparable performance with TF. Your request seems more like an optimization than a required feature. We will see if it's easy to do in our rewrite process and contribution is also welcomed.

**Comment by lucienwang1009** [comment]
duplicate #537 close.
