### ISSUE TITLE
ValueError: make_sure failure: perm can't be dynamic in ONNX

### ISSUE THREAD

**Issue by oohlala1204** [onnx/tensorflow-onnx#650]
When I am trying to convert the tf model to onnx with the tool tf2onnx, an error occurs:
```
2019-07-16 11:11:17,534 - ERROR - Failed to convert node rnn/transpose
OP=Transpose
Name=rnn/transpose
Inputs:
        Slice_1:0=Slice, [-1, 35, 39], 1
        rnn/concat:0=Concat, [3], 6
Outpus:
        rnn/transpose:0=[35, -1, 39], 1

......

ValueError: make_sure failure: perm can't be dynamic in ONNX
```
How to use the rewriter "rewrite_constant_fold" in tfonnx.py to handle this issue? I am very new to this, thanks a lot.

**Comment by zhijxu-MS** [comment]
have you used **--fold_const** to use tf graph optimizer to fold some nodes that can be a const?

**Comment by oohlala1204** [comment]
No, I  use tf.estimator to save tensorflow model, and use "python -m tf2onnx.convert --saved-model $LAST_SAVED_MODEL --output $OUT/bert.onnx --opset 8" to convert model.

**Comment by oohlala1204** [comment]
> have you used --fold_const to use tf graph optimizer to fold some nodes that can be a const?
No, I use tf.estimator to save tensorflow model, and use "python -m tf2onnx.convert --saved-model $LAST_SAVED_MODEL --output $OUT/bert.onnx --opset 8" to convert model.

**Comment by oohlala1204** [comment]
> have you used --fold_const to use tf graph optimizer to fold some nodes that can be a const?

Thank you so much. When I add "--fold_const" , the conversion is sucessful.
