### ISSUE TITLE
Questions about changes in node types

### ISSUE THREAD

**Issue by lalalalao** [onnx/tensorflow-onnx#653]
I have a simple network for mnist. First,for input：   
 with tf.name_scope('reshape1'):x_image=tf.reshape(x,[-1,28,28,1])
I use tf2onnx to convert the model to onnx，it is different from pb.The kind of this node has changed, causing problems with the subsequent conversion of tensorrt
ps:I try to convert ckpt/pb to onnx,I get the same result.

**Comment by lucienwang1009** [comment]
Do you mind posting the different part that you thought is converted incorrectly?

**Comment by lalalalao** [comment]
I use netron to visual network. The first one is my pb.It's right.
![pb-image](https://github.com/lalalalao/photo/blob/master/2019-07-17%2017-13-06.png)
But when convert to onnx.My model has changed.
![onnx-image](https://github.com/lalalalao/photo/blob/master/2019-07-17%2017-13-31.png)
You can see  'Cast'. It's shape input of reshape.I don't know why a module was added

**Comment by zhijxu-MS** [comment]
what is the command used to convert? and I couldn't access the shared link by you

**Comment by lalalalao** [comment]
> what is the command used to convert? and I couldn't access the shared link by you

I use python3 -m tf2onnx.convert
pb is 
![2019-07-17 17-13-06](https://user-images.githubusercontent.com/42710977/61421947-eca65880-a93b-11e9-83ed-a94ab6e2f3b3.png)
onnx is 
![2019-07-17 17-13-31](https://user-images.githubusercontent.com/42710977/61421958-f7f98400-a93b-11e9-9947-756f18f4e7b1.png)

**Comment by lucienwang1009** [comment]
@lalalalao The shape input of Reshape is required to be "int64" while the origin shape is of "int32" so the Cast node is introduced.

**Comment by lucienwang1009** [comment]
What's the error of tensorrt?

**Comment by lalalalao** [comment]
> What's the error of tensorrt?

cast is not supported.But why the model.pb don't have 'cast'. And I find the kind of reshape has chaged from 'Constant' to 'Intializer'.Is it  irrelevant?

**Comment by lucienwang1009** [comment]
uh, Constant replacing by Initializer is due to 1) onnx's Constant only supports "float" in opset < 9. 2) In onnxruntime, Constant will be transformed to Initializer, putting an additional burden on performance.
For tensor's error, I suggest you use const_fold_optimizer.py to fold these Casts. @zhijxu-MS please comment.
