### ISSUE TITLE
ShapeInferenceError on converted NAS models

### ISSUE THREAD

**Issue by snnn** [onnx/tensorflow-onnx#665]
Source models are from: https://github.com/tensorflow/models/tree/master/research/slim/datasets
The converted nasnet_large/nasnet_mobile/pnasnet_large onnx opset 10 models have shape inference error like:
[ShapeInferenceError] Can't merge shape info. Both source and target dimension have values but they differ. Source=22 Target=21 Dimension=3

Only opset 10 has this problem. If I change opset to 7/8/9, it's fine.

Version info:
 tensorflow=1.14.0, onnx=1.5.0, tf2onnx=1.6.0/7b9f05

**Comment by guschmue** [comment]
thanks for catching!

**Comment by lucienwang1009** [comment]
should be fixed by #667
