### ISSUE TITLE
 g = process_tf_graph? why do this work?

### ISSUE THREAD

**Issue by sy-swjtu** [onnx/tensorflow-onnx#666]
g = process_tf_graph(tf_graph,
                             continue_on_error=args.continue_on_error,
                             target=args.target,
                             opset=args.opset,
                             custom_op_handlers=custom_ops,
                             extra_opset=extra_opset,
                             shape_override=args.shape_override,
                             input_names=inputs,
                             output_names=outputs,
                             inputs_as_nchw=args.inputs_as_nchw)
hi,
I have a question, trace-based means that it operates by executing your model once. 
If the model is dynamic, the export won’t be accurate. 
Why did you do this?
Can you give a detailed explanation, or reference?
Very thankful！！！

**Comment by guschmue** [comment]
not sure if I understand the question correctly - the input to process_tf_graph is graphdef, aka the tensorflow graph which is static. No execution or tracing is done in tfonnx.
