### ISSUE TITLE
Error in Bert Tutorial tf2onnx in optimize graph

### ISSUE THREAD

**Issue by chikubee** [onnx/tensorflow-onnx#668]
On running the tf2onnx.convert file, getting an error with optimize_graph.
<img width="1007" alt="Screenshot 2019-07-31 at 4 08 19 PM" src="https://user-images.githubusercontent.com/25073753/62205639-80047280-b3ad-11e9-83fe-64b0acdd7c82.png">

Any leads so as to why this is happening?

**Comment by lucienwang1009** [comment]
fixed by #657. please try the latest converter.

**Comment by guschmue** [comment]
I think that fix might not be in pypi yet - I can push a new release today.

**Comment by guschmue** [comment]
done, ```pip install -U tf2onnx``` should fix it.

**Comment by chikubee** [comment]
Thanks, works just fine.
