### ISSUE TITLE
Tensorflow op LinSpace is not support

### ISSUE THREAD

**Issue by yashpatel5400** [onnx/tensorflow-onnx#670]
Hey! I'm trying to convert a TF model that uses LinSpace to ONNX but it doesn't seem to be supported with the ONNX version 1.5.0. Are there steps to go about enabling support of this operation?

I'm specifically using ONNX to ingest a TF model into Caffe2, so if there is a more straightforward approach to circumventing this issue, I'd also be willing to try that alternative!

**Comment by guschmue** [comment]
I wonder if we can use tf.range() could be used.  But Range() itself might be a problem on caffe2 ... it uses [control flow](https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/controlflow.py#L249) which I belief caffe2 does not support unless all inputs are constant.
Are the inputs for LinSpace in your case all constants?

**Comment by danperazzo** [comment]
Hello, has this issue been solved?

**Comment by chiragsamal** [comment]
Hello, I also had the same problem. Just add this in your command line like this:
--custom-ops LinSpace:ai.onnx.cont 
Example: python -m tf2onnx.convert --saved-model "saved model" --output " onnx file .onnx" --custom-ops LinSpace:ai.onnx.cont

Hope this helps :)
