### ISSUE TITLE
Tensorflow op Cumsum is not supported

### ISSUE THREAD

**Issue by JiayiFeng** [onnx/tensorflow-onnx#671]
Hi, I'm trying to convert my tensorflow pb model to onnx by `tf2onnx.convert` with `opset=10`. But an error occurs that `Cumsum` op is not supported. However, in this page https://github.com/onnx/onnx/blob/master/docs/Operators.md I notice that `Cumsum` has been supported since version 11. So I'm wondering how can I make my converting tool supporting version 11 opset? 

Many thanks!

**Comment by guschmue** [comment]
opset-11 is not out yet. Maybe end of august we think. Once opset-11 is released it takes about 2 weeks to add support to tf2onnx.

**Comment by JiayiFeng** [comment]
ok, thanks!
