### ISSUE TITLE
:num issue converting frozen StyleGAN model

### ISSUE THREAD

**Issue by albusdemens** [onnx/tensorflow-onnx#672]
Hi, hats off for your work! I have a frozen [StyleGAN](https://github.com/NVlabs/stylegan) graph saved as a `.pb` file, which I would like to convert into an `.onnx` using something like `python -m tf2onnx.convert --input ./frozen_models/model.pb --inputs input:num --outputs output --output tf_mobilenet.onnx`. 

If I do so, I get the errors `output_names = [i.split(':')[:-1][0] for i in output_names]` and similar, already reported [here](https://github.com/onnx/tensorflow-onnx/issues/651). In my particular case, the id of the input is `Gs/latents_in`, which is a tensor 512 elements long, and the output is an image. How should I edit the command? In case it might help, here is a snippet of the graph with the input region:
![image](https://user-images.githubusercontent.com/276459/62977272-d8f8ef80-be1e-11e9-911a-06263e3131d5.png)

**Comment by lucienwang1009** [comment]
the error arises from the missing index. if your output node name is `output` and desired tensor is the `0`-th output of this node, the correct argument is `--outputs output:0`. Similarly, the inputs argument is `--inputs Gs/latents_in:0` according to the provided snippet. You can also set the input shape explicitly by `--inputs Gs/latents_in:0[512]` in case it's missing during freezing the graph.

**Comment by albusdemens** [comment]
Thanks for your reply! With both the commands you suggested, I get the error `assert d in name_to_node, "%s is not in graph" % d
AssertionError: output is not in graph`. 

Do you have any suggestion on how to fix this?

**Comment by albusdemens** [comment]
Thanks @lucienwang1009! Following your suggestions, I am now giving the command `python -m tf2onnx.convert --input ./frozen_models/model.pb --inputs Gs/G_mapping/latents_in:0[512] --outputs Gs/images_out:0 --output tf_mobilenet.onnx`, which results in the error `ValueError: Invalid reduction dimension 1 for input with 1 dimensions. for 'Gs/G_mapping/PixelNorm/Mean' (op: 'Mean') with input shapes: [512], [] and with computed input tensors: input[1] = <1>.`

I guess that some variables size got lost when freezing the graph... I'll check if things go better if I save the graph instead. Let me know if you have other suggestions on how to proceed. Cheers

**Comment by lucienwang1009** [comment]
@albusdemens, are you sure the input is of shape `[512]`? The `Mean` op in your model reduct the tensor by axis 1, which will fail on the input of 512 elements.

**Comment by albusdemens** [comment]
Yes, the input is a tensor with 512 elements so my command should be correct. Still, I don't understand how the mean of a tensor can have dimension 0, as my error says... I guess something went wrong with freezing the graph, so I am re-implementing the network from scratch. Thank for the help though!

**Comment by fatcat-z** [comment]
It's been over 2 months, so closing this. Feel free to open a new one if the issue still exists.
