### ISSUE TITLE
Shape inference broken

### ISSUE THREAD

**Issue by letmaik** [onnx/tensorflow-onnx#674]
After https://github.com/onnx/tensorflow-onnx/pull/557 got merged, doing shape inference via `onnx.shape_inference.infer_shapes(m)` doesn't work anymore. I'm using the latest onnx 1.5.0 release.

**Comment by guschmue** [comment]
Ah, you mean for opset9 or better. 
That change basically removed constants from inputs since inputs are not constants. In older onnx versions constants had to be part of the inputs, in opset9 that changed.
Possible a onnx issue.
@linkerzhang thought on this ?

**Comment by guschmue** [comment]
I think this is a onnx issue, can you open a bug there?

**Comment by guschmue** [comment]
closing since it moved to onnx.
