### ISSUE TITLE
Is TF2.0 supported yet?

### ISSUE THREAD

**Issue by srkm009** [onnx/tensorflow-onnx#684]
Is anyone able to test TF2.0 saved models & tensorflow-onnx? to convert .pb to .onnx formats?

**Comment by guschmue** [comment]
should be, at least we tried a few that worked.

**Comment by chudegao** [comment]
Try convert tf2.0 saved model to onnx failed.  
The saved model is from https://tensorflow.google.cn/beta/tutorials/keras/save_and_restore_models

(dlipy3) [root@bjosm01 onnx]# ls ./saved_models/1567491440/
assets  saved_model.pb  variables
(dlipy3) [root@bjosm01 onnx]# python -m tf2onnx.convert --saved-model ./saved_models/1567491440/ --output ./onnx/mnist.onnx --opset 7
2019-09-03 14:33:04.988096: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/opt/anaconda3/envs/dlipy3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/anaconda3/envs/dlipy3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/opt/anaconda3/envs/dlipy3/lib/python3.6/site-packages/tf2onnx/__init__.py", line 13, in <module>
    from tf2onnx import tfonnx, utils, graph, graph_builder, graph_matcher, shape_inference, schemas  # pylint: disable=wrong-import-order
  File "/opt/anaconda3/envs/dlipy3/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 20, in <module>
    from tensorflow.tools.graph_transforms import TransformGraph
ModuleNotFoundError: No module named 'tensorflow.tools.graph_transforms'
(dlipy3) [root@bjosm01 onnx]# vi /opt/anaconda3/envs/dlipy3/lib/python3.6/site-packages/tf2onnx/tfonnx.py
(dlipy3) [root@bjosm01 onnx]# pip show tensorflow
Name: tensorflow
Version: 2.0.0b1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /opt/anaconda3/envs/dlipy3/lib/python3.6/site-packages
Requires: keras-applications, keras-preprocessing, termcolor, google-pasta, tb-nightly, grpcio, absl-py, astor, tf-estimator-nightly, wrapt, wheel, six, gast, protobuf, numpy
Required-by: tensorflow-serving-api
(dlipy3) [root@bjosm01 onnx]#

**Comment by guschmue** [comment]
There are 2 different things:

converting a tf-2.0 graph - that one should work (but has not received much testing)

running tf2onnx when tf-2.0 is installed. That one doesn't work yet but we hope we get this to work soon.

**Comment by srkm009** [comment]
I am able to convert TF2.0 models(Trained in TF2.0 - Beta1) to onnx. But the tf2onnx itself is installed from source on TF1.14+Py3.6 as recommend.  

Unfortunately, networks with Batch-norm layers + trained on TF2.0-rc0 is going through with warning and ERROR for FusedBatchNormV3. This is eventually failing completely while running onnx2trt, if you want to deploy using TensorRT.

**Comment by DeepBlender** [comment]
@guschmue could you explain how a tf-2.0 graph can be converted? I tried several approaches, but none of them worked.

**Comment by guschmue** [comment]
It requires a good amount of changes. I'm working on a PR for that and hope I will have it work this week.

**Comment by mohitranawat** [comment]
@guschmue , can you tell how to convert onnx to .pb . Initially I was able to convert in 1.14.0 version but in 2.0.0 I am not able to do it. Can you help?. Thanks!

**Comment by guschmue** [comment]
see my comment above.
