### ISSUE TITLE
Unable to convert quantized tensorflow model

### ISSUE THREAD

**Issue by legitmaxwu** [onnx/tensorflow-onnx#686]
I first quantized the official Resnet v2 50 model using TensorFlow's GraphTransforms tool using this command.

```
~/......./tensorflow/tools/graph_transforms/transform_graph \
--in_graph=/........./models/research/tensorrt/models/resnetv1_imagenet_frozen_graph.pb --out_graph=/........./models/research/tensorrt/models/resnetv1_imagenet_frozen_graph_quant.pb --inputs=input_tensor:0 --outputs=softmax_tensor:0 \
--transforms='add_default_attributes
strip_unused_nodes(type=float, shape="50,224,224,3")
fold_constants(ignore_errors=true)
fold_batch_norms
fold_old_batch_norms
quantize_weights
quantize_nodes
strip_unused_nodes'
```

Then I tried to convert to ONNX using the tf2onnx tool.

```
python -m tf2onnx.convert --graphdef frozen_resnet_quant.pb --output frozen_resnet_fromtf.onnx \
    --fold_const --opset 10 \
    --inputs input_tensor:0  \
    --outputs softmax_tensor:0
```

I was met with this error:

`RuntimeError: Numpy data type not understood yet: [('quint8', 'u1')]`

Is converting quantized models to ONNX format supported in TensorFlow yet? It seems that the quantized data types aren't supported in the conversion tool yet.

Thanks,
Max

**Comment by guschmue** [comment]
There is no plan to support conversion of quantitized models in tf2onnx. 

Instead the plan is to take the fp32 or the fp32 with fake quantitization version of the model, convert it to onnx and use [this tool](https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/quantization) to quantitize the onnx graph.

**Comment by legitmaxwu** [comment]
Thanks for the response. I tried converting a few models (VGG, alexnet, official ResNet) and keep running into this type of error:

`ValueError: invalid weight name <weight_name> found in the graph`

Do you know of any models that might work?

Thanks,
Max

**Comment by guschmue** [comment]
Hm, I have not seen this message before and it does not come from tf2onnx code.
Maybe comes from tensorflow when we call it.
Can you capture a stack trace ?

**Comment by legitmaxwu** [comment]
Hi, sorry, I should have clarified that I ran into the ValueError while trying the tool you linked to (not tf2onnx). I was trying to quantize onnx-formatted models.

Perhaps I should take this issue to the onnxruntime repository. Thanks!

**Comment by zcin** [comment]
LMAO WTF is .......

**Comment by guschmue** [comment]
Fyi @askhade

**Comment by jediblu** [comment]
Is it possible to support conversion of quantized TF models in tf2onnx? Some developers are going to use TF to quantize models. Building better support for converting TF to onnx will improve the prospect of onnx as an open interoperable format. Thanks!

**Comment by guschmue** [comment]
We have not been planning for adding direct support for quantitizatized tensorflow models for a couple of reasons:
1. we expect them to be rare - more likely there is a quantitizatized  tflite model in the future
2. we think for most quantitizatized  models there will be the original tensorflow model and one with fake quanitzation as well (if it was retraining). Those we will convert those to onnx.

We want to use the onnx quantitization tool. But we will make the changes to tf2onnx needed to create what the onnx quantitization tool needs.

**Comment by jediblu** [comment]
In that case, is there any plan to add support in tf2onnx to convert tflite models to onnx? Thanks.

**Comment by guschmue** [comment]
Most of the code in tf2onnx is specific to tensorflow and would look very different for tflite. We think that would be a different converter. 
tflite format is generated by toco and toco takes a tensorflow model as input. For tf2onnx we want exactly that input you'd give to toco.
Than tf2onnx converts this to onnx and the onnx quantitization tool and does the quantitization.

**Comment by jediblu** [comment]
Got it. Is there any plan to build a tflite to onnx converter? Thanks.

**Comment by guschmue** [comment]
I'm not aware of any.
