### ISSUE TITLE
rnn layer conversion errors

### ISSUE THREAD

**Issue by mxdilln** [onnx/tensorflow-onnx#693]
Hi,

I am trying to convert a model with RNN layers from tf to onnx. I have tried a number of different methods, but have been running into some errors, which don't seem to be addressed in the tips [documentation](https://github.com/onnx/tensorflow-onnx/blob/master/examples/rnn_tips.md):

```
    def define_model(self, multi_gpu=False):
        """ """

        embedding_layer = tf.keras.layers.Embedding(self.embedding_matrix.shape[0],
                                                    self.embedding_matrix.shape[1],
                                                    weights=[self.embedding_matrix],
                                                    input_length=None,
                                                    trainable=False)
         
        lstm_layer = tf.keras.layers.LSTM(64, return_sequences=True)
        maxpool_layer = tf.keras.layers.GlobalMaxPool1D()
        linear_layer = tf.layers.Dense(units=self.y_train.shape[1], activation='softmax')

        y_pred = embedding_layer(self.batchX_placeholder)
        y_pred = lstm_layer(y_pred)
        y_pred = maxpool_layer(y_pred)
        y_pred = linear_layer(y_pred)
        y_pred = tf.identity(y_pred, name="output")
```

This model will train OK, but when using ```loader.freeze_session(sess, output_names=["output:0"])``` to freeze the graph, I get the following:

ValueError: Cannot find the variable that is an input to the ReadVariableOp.

This model will freeze and convert to onnx fine when the lstm layer only is omitted. I get the same error with GRU, RNN and Bidirectional layers, so am guessing it is something to do with RNNs. 

From searching through previous issues, I rewrote the rnn layer in the dynamic form (as in the lstm tests suggested in issue https://github.com/onnx/tensorflow-onnx/issues/640. 

```
    def define_model(self, multi_gpu=False):
        """ """

        embedding_layer = tf.keras.layers.Embedding(self.embedding_matrix.shape[0],
                                                    self.embedding_matrix.shape[1],
                                                    weights=[self.embedding_matrix],
                                                    input_length=None,
                                                    trainable=False)

        lstm_cell = rnn.LSTMCell(num_units=64)

        maxpool_layer = tf.keras.layers.GlobalMaxPool1D()
        linear_layer = tf.layers.Dense(units=self.y_train.shape[1], activation='softmax')

        y_pred = embedding_layer(self.batchX_placeholder)
        y_pred, _ = tf.nn.dynamic_rnn(lstm_cell, y_pred, dtype=tf.float32)
        y_pred = maxpool_layer(y_pred)
        y_pred = linear_layer(y_pred)
        y_pred = tf.identity(y_pred, name="output")
```

This now freezes the graph, but get the following error with ```tf2onnx.tfonnx.process_tf_graph(tf_graph, input_names=["input:0"], output_names=["output:0"])```  :

ValueError: make_sure failure: perm can't be dynamic in ONNX

Issue https://github.com/onnx/tensorflow-onnx/issues/650 suggests ```fold_constant``` but I am unsure how to incorporate this in a script rather than command line, and am confused as this comes after the graph has been frozen.

Is this the correct way to be approaching LSTM conversion?

**Comment by guschmue** [comment]
Above the ValueError must be a error message with the node name and the op that triggered this.
The python api assumes that this graph is already frozen and optimized. To get to there you can follow this code:
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/convert.py#L131

Much easier would be to use the command line with a ```--fold_const``` option.

**Comment by mxdilln** [comment]
Thanks, using the command line has worked! 

For info, the error message was very similar to https://github.com/onnx/tensorflow-onnx/issues/650 (ie to do with the rnn/transpose)
