### ISSUE TITLE
Nodes in Loop subgraph are not topologically sorted

### ISSUE THREAD

**Issue by jiafatom** [onnx/tensorflow-onnx#716]
**Describe the bug**
When we convert a keras model, we are using tf2onnx for custom layers, the model can be converted. But onnxruntime crashes because nodes in the subgraph of Loop node are not topologically sorted. Can we fix this? Thanks.

**Urgency**
This is a critical bug.

**Comment by jignparm** [comment]
@jiafatom, what's the onnxruntime error message? Also, is the model small enough to attach to this issue?
