### ISSUE TITLE
No attribute split in Split operator after conversion

### ISSUE THREAD

**Issue by OuHangKresnik** [onnx/tensorflow-onnx#718]
**Describe the bug**

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS
- Tensorflow Version: 1.14.1
- Python version: 2.7

**To Reproduce**

@tf_op("Split")
class Split:
    @classmethod
    def version_1(cls, ctx, node, **kwargs):
        # T output = Split(int32 split_dim, T value, @int num_split)
        # T outputs = Split(T input, @INT axis, @INTS split)
        split_dims = node.inputs[0].get_tensor_value()
        ctx.remove_input(node, node.input[0])
        node.set_attr("axis", split_dims)

    @classmethod
    def version_2(cls, ctx, node, **kwargs):
        cls.version_1(ctx, node, **kwargs)

    @classmethod
    def version_11(cls, ctx, node, **kwargs):
        # no change
        cls.version_1(ctx, node, **kwargs)

The code doesn't take care of the "split" attribute

**Expected behavior**

converted node should contain the "split" attribute

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by OuHangKresnik** [comment]
The split value should be store in node.inputs[1]

**Comment by OuHangKresnik** [comment]
By the way, the "split" sometimes comes from another op instead of const. 

I think make it an attribute may not be suitable.

**Comment by jignparm** [comment]
It's needed as an attribute for the ONNX operator. 

https://github.com/onnx/onnx/blob/master/docs/Operators.md#Split

In the  TensorFlow 'frozen' model however, I believe this value may not always be constant (but usually is).

@guschmue , in cases where the split dims are non-constant (i.e. not known at conversion time), would this code be valid?

**Comment by guschmue** [comment]
Common issue that onnx as an attribute where tensorflow has a dynamic input. We try as good as we can to get the tf input const so we can set the attribute but sometimes that doesn't work and you get the 'get tensor value: ... must be Const' error. If that happens we need to go back to onnx and propose a change in the onnx spec to make the input dynamic in onnx.

**Comment by jignparm** [comment]
Thanks for the update. It looks like the most sustainable solution is to update  Onnx spec  to take 'dims' as an input instead of an attribute, and for now continue with the best-effort algorithm in tf2onnx.

**Comment by guschmue** [comment]
If you have not tried this: add a ```--fold_const``` in the command line to enable all constant folding.

**Comment by OuHangKresnik** [comment]
> Thanks for the update. It looks like the most sustainable solution is to update Onnx spec to take 'dims' as an input instead of an attribute, and for now continue with the best-effort algorithm in tf2onnx.

Yap, I agree with that.

**Comment by OuHangKresnik** [comment]
> If you have not tried this: add a `--fold_const` in the command line to enable all constant folding.

No, it doesn't work in my case

**Comment by guschmue** [comment]
this should be support since opset-13 where the attribute became an input.
