### ISSUE TITLE
bug:StridedSlice: attribute new_axis_mask not supported

### ISSUE THREAD

**Issue by emelife** [onnx/tensorflow-onnx#729]
**Describe the bug**
I want to convert yolov3 pb file to onnx model with
g = process_tf_graph(sess.graph,continue_on_error=True, opset=11,input_names=input, output_names=output)  function.
report  strideslice bug : new_axis_mask not support

system information:
os:linux ubuntu 16.04
tensorflow 1.14.0
python 3.6

bug content:
OP=StridedSlice
Name=pred_lbbox/strided_slice_10
Inputs:
	pred_lbbox/concat:0=Concat, [13, 13, 2], 6
	pred_lbbox/strided_slice_10/stack:0=Const, [5], 6
	pred_lbbox/strided_slice_10/stack_1:0=Const, [5], 6
	pred_lbbox/strided_slice_10/stack_2:0=Const, [5], 6
Outpus:
	pred_lbbox/strided_slice_10:0=[1, 13, 13, 1, 2], 6
Traceback (most recent call last):
  File "/home/liuxy/workspace/venv/lib/python3.6/site-packages/tf2onnx-1.6.0-py3.6.egg/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/liuxy/workspace/venv/lib/python3.6/site-packages/tf2onnx-1.6.0-py3.6.egg/tf2onnx/onnx_opset/tensor.py", line 755, in version_10
    cls.version_1(ctx, node, **kwargs)
  File "/home/liuxy/workspace/venv/lib/python3.6/site-packages/tf2onnx-1.6.0-py3.6.egg/tf2onnx/onnx_opset/tensor.py", line 638, in version_1
    raise ValueError("StridedSlice: attribute " + attr_name + " not supported")
ValueError: StridedSlice: attribute new_axis_mask not supported

**Comment by jignparm** [comment]
Thanks for raising this issue. What's the source of the model you are using (link?)

The error message is coming from https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/tensor.py#L634. Currently `new_axis_mask` is not supported -- but it likely should be supportable.

**Comment by emelife** [comment]
> Thanks for raising this issue. What's the source of the model you are using (link?)
> 
> The error message is coming from https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/tensor.py#L634. Currently `new_axis_mask` is not supported -- but it likely should be supportable.

thanks for you reply, yolov3 model source link [](https://github.com/YunYang1994/tensorflow-yolov3)

**Comment by jignparm** [comment]
@emelife , 

I did not encounter any `new_axis_mask` errors in the conversion, at least for the yolov3_coco model in the link provided (wrong link ?)


### Method 1
I was able to convert the yolov3_coco model successfully using the command below (on Windows, using TF 1.14 and the master branch of tensorflow-onnx)

``` sh
python -m tf2onnx.convert \
    --input yolov3_coco.pb \
    --inputs input/input_data:0 \
    --outputs pred_sbbox/concat_2:0,pred_mbbox/concat_2:0,pred_lbbox/concat_2:0 \
    --output yolov3_coco.onnx \
    --verbose \
    --fold_const \
    --opset 11 \                                                                                                                                                                        
```

However,  the original TF model is missing the shape of the input.  When you run the  `freeze_graph.py` script here https://github.com/YunYang1994/tensorflow-yolov3/blob/master/freeze_graph.py#L23

Update this line
```python
input_data = tf.placeholder(dtype=tf.float32, name='input_data')
```

to this line below. This will save the model with the right shape information.
```python
input_data = tf.placeholder(dtype=tf.float32, name='input_data', shape=(1,416,416,3))
```

###  Method 2

Another way to convert the model, and also test that output of Tensorflow and the output of converted ONNX model match, is to run the script below (make sure you do `pip install onnxruntime` first):

```sh
python tests/run_pretrained_models.py --backend onnxruntime --opset 11 --config mypretrained.yaml --onnx-file /d/tmp/pre-trained --fold_const -v
```
...using this sample **mypretrained.yaml** file

```
yolov3:
  disabled: false
  model_type: frozen
  model: D:\modelsyolov3\tensorflow-yolov3\yolov3_coco.pb
  input_get: get_ramp
  inputs:
    "input/input_data:0":  [1,416, 416, 3]
  outputs:
    - pred_sbbox/concat_2:0
    - pred_mbbox/concat_2:0
    - pred_lbbox/concat_2:0
```
This scored outputs are very close, but not exact. There is a 0.001% difference in the output of the ONNX model, which should be acceptable for most use cases.


```
Not equal to tolerance rtol=0.01, atol=1e-06

Mismatch: 0.00116%
Max absolute difference: 1.6213251e+34
Max relative difference: 0.15384616
 x: array([[[[[0.000000e+00, 0.000000e+00, 0.000000e+00, ...,
           0.000000e+00, 0.000000e+00, 0.000000e+00],
          [0.000000e+00, 0.000000e+00,          inf, ...,...
 y: array([[[[[0.000000e+00, 0.000000e+00, 0.000000e+00, ...,
           0.000000e+00, 0.000000e+00, 0.000000e+00],
          [0.000000e+00, 0.000000e+00,          inf, ...,...
2019-11-09 02:12:54,973 - INFO 
===================================

```

**Comment by guschmue** [comment]
Method3:
You can override the shape in the input list, ie.
```
--inputs input/input_data:0[1,416, 416, 3]
```

**Comment by emelife** [comment]
@jignparm 
thanks for your reply. yes,
first, if do follow method 1 ,there is no error comes out,but when I delete --fold_const option ,It also report same error.I don't really understand what fold_const mean . ?
second,my purpose is that  I want to get the input and output tensor shape of inner op in yolov3. so after i convert to yolov3.onnx ,I call shape_inference.infer_shapes(g) function , in this step ,it needs to change all const-op to input-op,but if opset >=9, it won't support change any more [https://github.com/onnx/tensorflow-onnx/blob/c2227eafe287a5971286a2a8d71dc473f7cf0c04/tf2onnx/graph.py#L952](url)   do you have other medthod to get inner op tensor shape? thanks

**Comment by jignparm** [comment]
The "fold_const" option allows constant node attributes/inputs to be propagated down the graph -- if some values are known to be constant, a subset of nodes can be replaced/reduced at compile time. It really should not be an optional flag -- it should be specified at every model conversion to get the fastest possible model. However, for now it's an optional flag.

>do you have other method to get inner op tensor shape?

Is the shape required to convert/run the model, or the question is primarily for debugging purposes? The internal shapes and types are stored at each node in the graph object at compile/conversion time -- they are usually not needed after the model is converted (i.e. at inference time), so causing internal const nodes to show up as model inputs is probably not correct (i.e. the ONNX model should look similar to the TF model after conversion, not have extra inputs).

**Comment by emelife** [comment]
@jignparm 
thanks. I understand the meaning of  fold_const option.so if I add fold_const option,strided_slice attribute problem doesn't come up because onnx optimizes this node.
second,I want to know the internal shapes because I need to do model perfermance analysis ,not for run .I don't want to calc internal shapes one by one,so I use shape inference tools.

**Comment by jignparm** [comment]
The shape inference tools seems like the best option to know the internal shapes -- TF2ONNX keeps track of the shapes, but does not print out explicitly. If you load up the model, you'll be able to see the shapes and types of the nodes in debug mode (e.g. below).


![image](https://user-images.githubusercontent.com/13698702/68819201-3a0daa80-063c-11ea-815f-a83278b58639.png)

**Comment by emelife** [comment]
> The shape inference tools seems like the best option to know the internal shapes -- TF2ONNX keeps track of the shapes, but does not print out explicitly. If you load up the model, you'll be able to see the shapes and types of the nodes in debug mode (e.g. below).
> 
> ![image](https://user-images.githubusercontent.com/13698702/68819201-3a0daa80-063c-11ea-815f-a83278b58639.png)

what is the software tool of this picture?

**Comment by jignparm** [comment]
That's PyCharm execution TF2ONNX in debug mode, in the middle of a model conversion.

**Comment by jignparm** [comment]
Closing issue. Reopen if any further questions.

**Comment by emelife** [comment]
> Closing issue. Reopen if any further questions.

Thanks a lot!

**Comment by xiaoga501** [comment]
I have tried to use the tf2onnx convert yolov3.pb -> yolov3.onnx. (https://github.com/onnx/tensorflow-onnx)The yolov3 tensorflow model comes from https://github.com/YunYang1994/tensorflow-yolov3/blob/master/freeze_graph.py#L23.
It seems to generate yolov3.onnx follows jignparm's method 2:
2019-12-12 10:14:15,616 - INFO - run_pretrained: To_ONNX, OK
2019-12-12 10:14:15,914 - INFO - run_pretrained: Created /home/xiaoga/pre-trained/yolov3.onnx
2019-12-12 10:14:16,184 - INFO - run_pretrained: Model saved to /tmp/tmphwporkg5/run_pretrained/yolov3.onnx
2019-12-12 10:14:16,674 - INFO - run_pretrained: Run_ONNX OK
2019-12-12 10:14:16,687 - ERROR - run_pretrained: Results
Traceback (most recent call last):
  File "tests/run_pretrained_models.py", line 283, in run_test
    np.testing.assert_allclose(tf_res, onnx_res, rtol=self.rtol, atol=self.atol)
  File "/home/xiaoga/anaconda3/envs/mypy35/lib/python3.5/site-packages/numpy/testing/_private/utils.py", line 1515, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/xiaoga/anaconda3/envs/mypy35/lib/python3.5/site-packages/numpy/testing/_private/utils.py", line 841, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.01, atol=1e-06

Mismatch: 0.00704%
Max absolute difference: 1.0280139e+36
Max relative difference: 1.
 x: array([[[[[8.000000e+00, 8.000000e+00, 1.566263e-36, ...,
           1.000000e+00, 9.869913e-01, 1.000000e+00],
          [8.000000e+00, 8.000000e+00, 0.000000e+00, ...,...
 y: array([[[[[8.000000e+00, 8.000000e+00, 1.566263e-36, ...,
           1.000000e+00, 9.869853e-01, 1.000000e+00],
          [8.000000e+00, 8.000000e+00, 0.000000e+00, ...,...
2019-12-12 10:14:16,714 - INFO - run_pretrained: ===================================
2019-12-12 10:14:16,714 - INFO - run_pretrained: RESULT: 1 failed of 1, backend=onnxruntime

But when I modified the tensorrt mnist_onnx_sample to parse the yolov3.onnx, encounter the problem below:
(mypy35) xiaoga@xiaoga-Lenovo:~/到 TensorRT-5.1.5.0 的链接/bin$ ./sample_onnx_mnist
&&&& RUNNING TensorRT.sample_onnx_mnist # ./sample_onnx_mnist
----------------------------------------------------------------
Input filename: ../../../data/mnist/yolov3.onnx
ONNX IR version: 0.0.4
Opset version: 7
Producer name: tf2onnx
Producer version: 1.5.3
Domain:
Model version: 0
Doc string:
----------------------------------------------------------------
WARNING: ONNX model has a newer ir_version (0.0.4) than this parser was built against (0.0.3).
While parsing node number 151 [Slice]:
ERROR: builtin_op_importers.cpp:2041 In function importSlice:
[8] Assertion failed: std::find(axes.begin(), axes.end(), BATCH_DIM) == axes.end()
[E] Failure while parsing ONNX file
&&&& FAILED TensorRT.sample_onnx_mnist # ./sample_onnx_mnist
sample_onnx_mnist: sampleOnnxMNIST.cpp:212: int main(int, char**): Assertion `trtModelStream != nullptr' failed.
已放弃 (核心已转储)



Please give some advice and thanns a lot!

**Comment by GuardSkill** [comment]
> @emelife ,
> 
> I did not encounter any `new_axis_mask` errors in the conversion, at least for the yolov3_coco model in the link provided (wrong link ?)
> 
> ### Method 1
> I was able to convert the yolov3_coco model successfully using the command below (on Windows, using TF 1.14 and the master branch of tensorflow-onnx)
> 
> ```shell
> python -m tf2onnx.convert \
>     --input yolov3_coco.pb \
>     --inputs input/input_data:0 \
>     --outputs pred_sbbox/concat_2:0,pred_mbbox/concat_2:0,pred_lbbox/concat_2:0 \
>     --output yolov3_coco.onnx \
>     --verbose \
>     --fold_const \
>     --opset 11 \                                                                                                                                                                        
> ```
> 
> However, the original TF model is missing the shape of the input. When you run the `freeze_graph.py` script here https://github.com/YunYang1994/tensorflow-yolov3/blob/master/freeze_graph.py#L23
> 
> Update this line
> 
> ```python
> input_data = tf.placeholder(dtype=tf.float32, name='input_data')
> ```
> 
> to this line below. This will save the model with the right shape information.
> 
> ```python
> input_data = tf.placeholder(dtype=tf.float32, name='input_data', shape=(1,416,416,3))
> ```
> 
> ### Method 2
> Another way to convert the model, and also test that output of Tensorflow and the output of converted ONNX model match, is to run the script below (make sure you do `pip install onnxruntime` first):
> 
> ```shell
> python tests/run_pretrained_models.py --backend onnxruntime --opset 11 --config mypretrained.yaml --onnx-file /d/tmp/pre-trained --fold_const -v
> ```
> 
> ...using this sample **mypretrained.yaml** file
> 
> ```
> yolov3:
>   disabled: false
>   model_type: frozen
>   model: D:\modelsyolov3\tensorflow-yolov3\yolov3_coco.pb
>   input_get: get_ramp
>   inputs:
>     "input/input_data:0":  [1,416, 416, 3]
>   outputs:
>     - pred_sbbox/concat_2:0
>     - pred_mbbox/concat_2:0
>     - pred_lbbox/concat_2:0
> ```
> 
> This scored outputs are very close, but not exact. There is a 0.001% difference in the output of the ONNX model, which should be acceptable for most use cases.
> 
> ```
> Not equal to tolerance rtol=0.01, atol=1e-06
> 
> Mismatch: 0.00116%
> Max absolute difference: 1.6213251e+34
> Max relative difference: 0.15384616
>  x: array([[[[[0.000000e+00, 0.000000e+00, 0.000000e+00, ...,
>            0.000000e+00, 0.000000e+00, 0.000000e+00],
>           [0.000000e+00, 0.000000e+00,          inf, ...,...
>  y: array([[[[[0.000000e+00, 0.000000e+00, 0.000000e+00, ...,
>            0.000000e+00, 0.000000e+00, 0.000000e+00],
>           [0.000000e+00, 0.000000e+00,          inf, ...,...
> 2019-11-09 02:12:54,973 - INFO 
> ===================================
> ```

Thank you very much, even not the same source model, the provided command is useful for me to overcome this issue.
