### ISSUE TITLE
ImportError: libprotobuf.so.20: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by I-CANT-CODE** [onnx/tensorflow-onnx#733]
**Describe the bug**
Im getting this error:
ImportError: libprotobuf.so.20: cannot open shared object file: No such file or directory

**Urgency**
low

**System information**
- OS Platform and Distribution (linux/ubuntu)

**To Reproduce**
python -m tf2onnx.convert --input /tmp/tmp/my_model.pb --inputs x --outputs summaries/up_convolution_out/activations --output tmp/tmp/model.onnx --verbose

**Expected behavior**
getting the .onnx file in tmp/tmp/

**Comment by jignparm** [comment]
Did you install the prerequisites? Installing Tensorflow should install protobuf automatically.

**Comment by I-CANT-CODE** [comment]
Yes tensor flow is installed in the Conda environment that I am running
this I also installed the tf onnx tool using condo install While the
environment was activated

**Comment by jignparm** [comment]
Can you paste the full stack trace of the error?

Also what's the output of this command on your host...

```
 pip show libprotobuf
```

It should print something similar to below.

```
Name: protobuf
Version: 3.10.0
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: None
Author-email: None
License: 3-Clause BSD License
Location: d:\anaconda37\lib\site-packages
Requires: six, setuptools
Required-by: tensorflow, tensorboard, onnx

```

**Comment by I-CANT-CODE** [comment]
python -m tf2onnx.convert --input /tmp/tmp/my_model.pb --inputs x --outputs summaries/up_convolution_out/activations --output tmp/tmp/model.onnx --verbose
/home/users/user/anaconda3/envs/tf-gpu-cuda8/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/users/user/anaconda3/envs/tf-gpu-cuda8/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/users/user/anaconda3/envs/tf-gpu-cuda8/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/users/user/anaconda3/envs/tf-gpu-cuda8/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/users/user/anaconda3/envs/tf-gpu-cuda8/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/users/user/anaconda3/envs/tf-gpu-cuda8/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/home/users/user/anaconda3/envs/tf-gpu-cuda8/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/users/user/anaconda3/envs/tf-gpu-cuda8/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/users/user/anaconda3/envs/tf-gpu-cuda8/lib/python3.6/site-packages/tf2onnx/__init__.py", line 12, in <module>
    from . import verbose_logging as logging
  File "/home/users/user/anaconda3/envs/tf-gpu-cuda8/lib/python3.6/site-packages/tf2onnx/verbose_logging.py", line 16, in <module>
    from . import constants
  File "/home/users/user/anaconda3/envs/tf-gpu-cuda8/lib/python3.6/site-packages/tf2onnx/constants.py", line 8, in <module>
    from onnx import helper
  File "/home/users/user/anaconda3/envs/tf-gpu-cuda8/lib/python3.6/site-packages/onnx/__init__.py", line 8, in <module>
    from .onnx_cpp2py_export import ONNX_ML
ImportError: libprotobuf.so.20: cannot open shared object file: No such file or directory

when i do pip show protobuf there is no output.

**Comment by jignparm** [comment]
>when i do pip show protobuf there is no output.

The package is probably not installed. Have you tried installing the package separately using  `pip install protobuf`?  https://pypi.org/project/protobuf/

**Comment by I-CANT-CODE** [comment]
It says that it is already installed when I do pip install protobuf

**Comment by I-CANT-CODE** [comment]
ok I was able to fix that issue by doing conda install protobuf

however now I am getting the following error:

'tensorflow.python._pywrap_transform_graph'
