### ISSUE TITLE
Slow Inference onnx runtime?

### ISSUE THREAD

**Issue by kunalgoyal9** [onnx/tensorflow-onnx#750]
**Describe the bug**
Inference Speed for a sample image of "ssd_mobilenet_v1_coco_2018_01_28" on Tensorflow took around only 0.034 secs(29.4 FPS) while after conversion to onnx through the mentioned [notebook](https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/ConvertingSSDMobilenetToONNX.ipynb) took 0.19 secs(5 FPS)

**Urgency**
High

**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- Tensorflow Version: 2.0.0
- Python version: 3.6

**To Reproduce**
Describe steps/code to reproduce the behavior: 
1) ran [notebook](https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/ConvertingSSDMobilenetToONNX.ipynb)
2) Through time.time() calculated sess.run() time.
![image](https://user-images.githubusercontent.com/21281457/69574641-b0bc8780-0fee-11ea-8186-a514d138587b.png)

**Expected behavior**
I expected similar to Tensorflow API results i.e. (29.4 FPS)

**Screenshots**
Tensorflow API Screenshot
![image](https://user-images.githubusercontent.com/21281457/69575276-eca41c80-0fef-11ea-98f9-066f8de6f659.png)

**Comment by guschmue** [comment]
this should be filed under https://github.com/microsoft/onnxruntime

On my box I see numbers similar to tensorflow. I belief the default settings for onnxruntime
are not optimal and I usual do something like this:
```
opt = rt.SessionOptions()
opt.intra_op_num_threads = vcpu - 1
opt.graph_optimization_level = rt.GraphOptimizationLevel.ORT_ENABLE_ALL
sess = rt.InferenceSession(model_path, opt)
```
but even with default settings I'd not expect 150ms.

**Comment by jignparm** [comment]
Closing this out for now. Please re-open if needed.
