### ISSUE TITLE
“custom_op_via_python.py”  Is it useful?

### ISSUE THREAD

**Issue by sicccs** [onnx/tensorflow-onnx#751]
import tensorflow as tf
import tf2onnx
from onnx import helper

_TENSORFLOW_DOMAIN = "ai.onnx.converters.tensorflow"

def print_handler(ctx, node, name, args):
    node.type = "Identity"
    node.domain = _TENSORFLOW_DOMAIN
    del node.input[1:]
    return node

with tf.Session() as sess:
    x = tf.placeholder(tf.float32, [2, 3], name="input")
    x_ = tf.add(x, x)
    # x__ = tf.Print(x, [x], "hello")
    _ = tf.identity(x_, name="output")
    onnx_graph = tf2onnx.tfonnx.process_tf_graph(sess.graph,
                                                 # custom_op_handlers={"Print": (print_handler, [])},
                                                 # extra_opset=[helper.make_opsetid(_TENSORFLOW_DOMAIN, 1)],
                                                 input_names=["input:0"],
                                                 output_names=["output:0"])
    model_proto = onnx_graph.make_model("test")
    with open("/tmp/model.onnx", "wb") as f:
        f.write(model_proto.SerializeToString())

--------------------------------------------------------------------
As shown above,I annotate the code，There's no difference

Ubuntu16.04
Python3.7
tensorflow1.14.0
tfonnx1.6.0
onnx1.6.0
onnxruntime1.0.0

**Comment by guschmue** [comment]
There is some example [here](https://github.com/onnx/tensorflow-onnx/blob/master/examples/custom_op_via_python.py):
```
python examples/custom_op_via_python.py
```
If I run this I get:
```
python tools/dump-onnx.py --input /tmp/model.onnx

graph tf2onnx (
  %input:0[FLOAT, 2x3]
) {
  %Print:0 = Identity[first_n = -1, message = 'hello', summarize = 3](%input:0)
  %output_raw_output___3:0 = Identity(%Print:0)
  %output:0 = Identity(%output_raw_output___3:0)
  return %output:0
}
```

Looks ok to me. 
The tf.add  is not in the graph because we use ```x``` as input into print where we should have used ```x_```, else the tf.add is optimized away since nobody is consuming its output.

**Comment by sicccs** [comment]
> There is some example [here](https://github.com/onnx/tensorflow-onnx/blob/master/examples/custom_op_via_python.py):
> 
> ```
> python examples/custom_op_via_python.py
> ```
> 
> If I run this I get:
> 
> ```
> python tools/dump-onnx.py --input /tmp/model.onnx
> 
> graph tf2onnx (
>   %input:0[FLOAT, 2x3]
> ) {
>   %Print:0 = Identity[first_n = -1, message = 'hello', summarize = 3](%input:0)
>   %output_raw_output___3:0 = Identity(%Print:0)
>   %output:0 = Identity(%output_raw_output___3:0)
>   return %output:0
> }
> ```
> 
> Looks ok to me.
> The tf.add is not in the graph because we use `x` as input into print where we should have used `x_`, else the tf.add is optimized away since nobody is consuming its output.

I understand. I made a mistake.Thank you
