### ISSUE TITLE
ONNX model size is just 69 bytes

### ISSUE THREAD

**Issue by pragnakalpdev6** [onnx/tensorflow-onnx#758]
I have generated '.onnx' model from saved model of the pretrained gpt2 model which is 6gb large.
the file generated by the onnx is just 69 bytes. How can i assure that onnx generated is valid or not???

below is the content of onnx file generated
tf2onnx1.5.3:-tf2onnxR"converted from ./1558_saved_model/Beds

**Comment by guschmue** [comment]
69 bytes for sure will be broken. Any error message during conversion ?
