### ISSUE TITLE
HFNet convert: StridedSlice: attribute new_axis_mask not supported, and other unsupported Ops

### ISSUE THREAD

**Issue by Irwin-Liu** [onnx/tensorflow-onnx#763]
When I use tf2onnx to convert tf saved models of hfnet, I got StridedSlice and MaxPool Op are not supported errors.

My hfnet convert work please see https://github.com/Irwin-Liu/hfnet-tf2onnx, it includes hfnet saved models, tf to frozen model code, converted frozen models, and frozen model to onnx code. My environment is also introduced in README.md.

Whatever command line or api I used, like
python -m tf2onnx.convert --opset 11 --fold_const --saved-model ./models/hfnet --output ./models/savedmodel.onnx
python frozen2onnx.py
I got below errors

E0103 11:26:22.870321 139943249016576 tfonnx.py:357] Failed to convert node pred/simple_nms/strided_slice
OP=StridedSlice
Name=pred/simple_nms/strided_slice
Inputs:
	pred/local_head/detector/Squeeze:0=Squeeze, [1, 224, 224], 1
	pred/simple_nms/strided_slice/stack:0=Const, [2], 6
	pred/simple_nms/strided_slice/stack_1:0=Const, [2], 6
	pred/simple_nms/strided_slice/stack_2:0=Const, [2], 6
Outpus:
	pred/simple_nms/strided_slice:0=[1, 224, 224, 1], 1
Traceback (most recent call last):
  File "/home/liushiwen/.conda/envs/tf2onnx/lib/python3.7/site-packages/tf2onnx-1.6.0-py3.7.egg/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/liushiwen/.conda/envs/tf2onnx/lib/python3.7/site-packages/tf2onnx-1.6.0-py3.7.egg/tf2onnx/onnx_opset/tensor.py", line 746, in version_10
    cls.version_1(ctx, node, **kwargs)
  File "/home/liushiwen/.conda/envs/tf2onnx/lib/python3.7/site-packages/tf2onnx-1.6.0-py3.7.egg/tf2onnx/onnx_opset/tensor.py", line 628, in version_1
    raise ValueError("StridedSlice: attribute " + attr_name + " not supported")
ValueError: StridedSlice: attribute new_axis_mask not supported
E0103 11:26:22.872146 139943249016576 tfonnx.py:357] Failed to convert node pred/simple_nms/MaxPoolV2
OP=MaxPool
Name=pred/simple_nms/MaxPoolV2
Inputs:
	pred/simple_nms/strided_slice:0=StridedSlice, [1, 224, 224, 1], 1
	pred/simple_nms/MaxPoolV2/ksize_Concat__35:0=Concat, [4], 6
	pred/simple_nms/MaxPoolV2/strides:0=Const, [4], 6
Outpus:
	pred/simple_nms/MaxPoolV2:0=[1, 224, 224, 1], 1
Traceback (most recent call last):
  File "/home/liushiwen/.conda/envs/tf2onnx/lib/python3.7/site-packages/tf2onnx-1.6.0-py3.7.egg/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/home/liushiwen/.conda/envs/tf2onnx/lib/python3.7/site-packages/tf2onnx-1.6.0-py3.7.egg/tf2onnx/onnx_opset/nn.py", line 343, in version_11
    cls._convert(ctx, node, **kwargs)
  File "/home/liushiwen/.conda/envs/tf2onnx/lib/python3.7/site-packages/tf2onnx-1.6.0-py3.7.egg/tf2onnx/onnx_opset/nn.py", line 356, in _convert
    kernel_shape_tf = node.inputs[1].get_tensor_value()
  File "/home/liushiwen/.conda/envs/tf2onnx/lib/python3.7/site-packages/tf2onnx-1.6.0-py3.7.egg/tf2onnx/graph.py", line 260, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: pred/simple_nms/MaxPoolV2/ksize_Concat__35 must be Const

In fact, I can see several nearly same errors at same time.

After read issue #729 , I tried to give a const input [1, 224, 224, 1] when convert frozen model, and it works for first several layers. Then I still got above errors. This attempt can also be seen in https://github.com/Irwin-Liu/hfnet-tf2onnx/blob/master/export_frozen.py.

I want to know how to fix these errors, so that I can know what custom ops I should write for hfnet as next work.

**Comment by jignparm** [comment]
Not sure if this is still an ongoing issue,  but looks like the model does not load in Tensorflow 1.14, due to the 'Resampler' op not being registered. Which version of TF are you using?

###log
```
$ python -m tf2onnx.convert --opset 11 --fold_const --input hf_frozen_const.pb --output frozen_const.onnx

Traceback (most recent call last):
  File "D:\anaconda37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\anaconda37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\jignparmtf2onnx\tf2onnx\convert.py", line 161, in <module>
    main()
  File "D:\jignparmtf2onnx\tf2onnx\convert.py", line 116, in main
    graph_def, inputs, outputs = loader.from_graphdef(args.graphdef, args.inputs, args.outputs)
  File "D:\jignparmtf2onnx\tf2onnx\loader.py", line 63, in from_graphdef
    tf.import_graph_def(graph_def, name='')
  File "D:\anaconda37\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\anaconda37\lib\site-packages\tensorflow\python\framework\importer.py", line 427, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'Resampler' in binary running on JRP-VM1-WIN-GPU. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
```

**Comment by Irwin-Liu** [comment]
Hi, I use TensorFlow 1.14 too. 'Resampler' is registered by "tf.contrib.resampler", like third line of https://github.com/Irwin-Liu/hfnet-tf2onnx/blob/master/export_frozen.py.
I repeat your command and get same problem on my environment, but I don't remember whether I solved it 3 month ago. But I also used Python API and wrote frozen2onnx.py(https://github.com/Irwin-Liu/hfnet-tf2onnx/blob/master/frozen2onnx.py) to convert, in which 'Resampler' can be registered. Then I got same above errors.
I run frozen2onnx.py right now, and can get same result.

**Comment by jignparm** [comment]
Shouldn't the resampler only be present during training time? Based on 29 of export_frozen.py, it seems like this op should have been dropped. Any idea if there's an actual use case for this operator in the inference graph, or if it can be stripped out?

**Comment by Irwin-Liu** [comment]
HFNet is used to re-localization and published at https://arxiv.org/abs/1812.03506.
Resampler is used to get descriptors from feature graph by the location of key points, which can be saw at https://github.com/ethz-asl/hfnet/blob/8fd6080252d48814bf9facfb07400d3aef91972b/hfnet/models/hf_net.py#L234 . So I'm sure it is used in inference graph and can't be stripped out.

But according to error log, the unsupported ops are StridedSlice and MaxPool, is Resampler the reason why failed to convert?

**Comment by jignparm** [comment]
The ReSampler was just the first error  running tf2onnx out-of-the-box (there was no link to the custom  frozen2onnx.py converter script).

Using frozen2onnx.py, and latest tf2onnx code, there are no StridedSlice errors anymore.

The only remaining error is for the MaxPoolV2 ops -- the code expects input[1] of MaxPoolV2 is always a compile-time constant, and doesn't handle run-time dynamic values.  Will investigate if this assumption can be waived shortly.

**Comment by Irwin-Liu** [comment]
I update tf2onnx by current master, though they are both shown as tf2onnx 1.6.0 by pip list, and successfully reproduce what you said. Thanks very much!

Hope the MaxPoolV2 errors can be fixed in the near future.

**Comment by guschmue** [comment]
MaxPoolV2 is supported since some time.
