### ISSUE TITLE
ssd_mobilenet_v3_small_coco_2019_08_14

### ISSUE THREAD

**Issue by PythonImageDeveloper** [onnx/tensorflow-onnx#775]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 16.04
- Tensorflow Version:1.14 binary installed
- Python version:3.5
- onnx 1.6.0
- onnxruntime 1.1.0
- tf2onnx - 1.5.4

when I run below code on **ssd_mobilenet_v3_small_coco_2019_08_14**:
```
python3 -m tf2onnx.convert --graphdef ssd_mobilenet_v3_small_coco_2019_08_14/frozen_inference_graph.pb --output ssd_mobilenet_v3_small_coco_2019_08_14.onnx \
    --fold_const --opset 10 --verbose\
    --inputs image_tensor:0 \
    --outputs num_detections:0,detection_boxes:0,detection_scores:0,detection_classes:0   
```
I get this error:

>     graph._c_graph, serialized, options)  # pylint: disable=protected-access
> tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'explicit_paddings' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]; attr=dilations:list(int),default=[1, 1, 1, 1]>; NodeDef: {{node FeatureExtractor/MobilenetV3/Conv/Conv2D}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/mm/.local/lib/python3.5/site-packages/tf2onnx/convert.py", line 161, in <module>
>     main()
>   File "/home/mm/.local/lib/python3.5/site-packages/tf2onnx/convert.py", line 116, in main
>     graph_def, inputs, outputs = loader.from_graphdef(args.graphdef, args.inputs, args.outputs)
>   File "/home/mm/.local/lib/python3.5/site-packages/tf2onnx/loader.py", line 63, in from_graphdef
>     tf.import_graph_def(graph_def, name='')
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 430, in import_graph_def
>     raise ValueError(str(e))
> ValueError: NodeDef mentions attr 'explicit_paddings' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]; attr=dilations:list(int),default=[1, 1, 1, 1]>; NodeDef: {{node FeatureExtractor/MobilenetV3/Conv/Conv2D}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

**Comment by jignparm** [comment]
What's the source of your model (link)?

The SSD model here --> http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v3_small_coco_2019_08_14.tar.gz converts to ONNX fine using the command line below.

### Convert to ONNX
```
python -m tf2onnx.convert --graphdef ssd_mobilenet_v3_small_coco_2019_08_14/frozen_inference_graph.pb --output ssd_mobilenet_v3_small_coco_2019_08_14.onnx \
    --fold_const --opset 10 --verbose\
    --inputs normalized_input_image_tensor:0 \
    --outputs raw_outputs/box_encodings:0,raw_outputs/class_predictions:0


```

**Comment by PythonImageDeveloper** [comment]
Thanks,
Your command is correctly working and converted, but I don't know why this network has such input and outputs, As most of Tensorflow object detection model zoo have **image_tensor:0** input and  **num_detections:0,detection_boxes:0,detection_scores:0,detection_classes:0** outputs.

**Comment by jignparm** [comment]
>In the TensorRT, I must set the input and outputs to image_tensor:0 input

I'm not sure why TensorRT should be not use those inputs/outputs....the input/output names are part of the model (independent of TensorRT of any other inference engine).  

> As most of Tensorflow object detection model zoo have...

Please inspect  every model carefully to verify the input and output names, instead of assuming a common pattern. There is no  pattern regarding placeholder naming convention.

**Comment by PythonImageDeveloper** [comment]
Did you work with ssd_mobilenet_v3_small? Did you run the converted model(TensoRT) on jetson nano?

**Comment by jignparm** [comment]
>Did you work with ssd_mobilenet_v3_small? Did you run the converted model(TensoRT) on jetson nano?

I verified the results between Tensorflow 1.14 and latest OnnxRuntime  -- the output results of the original TF model and converted ONNX model match up. 

What's the issue you are facing on TensorRT + Jetson nano? Are the outputs not matching, or the model is failing to run? Most likely it's an issue with the runtime inference engine,, since the model is converted successfully, and runs fine under OnnxRuntime.

**Comment by PythonImageDeveloper** [comment]
I converted the .pb file to .onnx file using [tensorflow-onnx](https://github.com/onnx/tensorflow-onnx), with this command:
```
python3 -m tf2onnx.convert --graphdef ssd_mobilenet_v3_small_coco.pb --output ssd_mobilenet_v3_small_coco.onnx \
    --fold_const --opset 10 \
    --inputs normalized_input_image_tensor:0 \
    --outputs raw_outputs/box_encodings:0,raw_outputs/class_predictions:0
```
Then I using this model :
```
import onnx
import onnx_tensorrt.backend as backend
import numpy as np
from time import time
from PIL import Image
import numpy as np

input_data = np.array(Image.open('cat.jpg').resize((320,320)))
input_data = np.expand_dims(input_data, axis=0).astype('float32')
input_data = input_data/255.

model = onnx.load("ssd_mobilenet_v3_small_coco.onnx")
engine = backend.prepare(model, device='CUDA:0')

while True:
    output_data = engine.run(input_data)[0]
```

I installed :
**tf2onnx : 1.5.4
onnx : 1.4.1**

**Comment by jignparm** [comment]
Based on your example above, even the TensorFlow original model is predicting class score values as 0.5. 

It looks like the original model has some issues, or else the data preparation steps are not quite correct (see https://github.com/tensorflow/models/issues/7727).

Could you try to get correct scores in TensorFlow first, and then compare with the converted ONNX model? 

### TensorFlow
```python
import tensorflow as tf
from PIL import Image
import numpy as np

image_path = r'cats.jpg'
model_path = r'frozen_inference_graph.pb'
output_names = ['raw_outputs/box_encodings:0', 'raw_outputs/class_predictions:0']
input_names = ['normalized_input_image_tensor:0']

input_data = np.array(Image.open(image_path).resize((320, 320)))
input_data = np.expand_dims(input_data, axis=0).astype('float32')
input_data = input_data / 255.

feed_dict = {input_names[0]: input_data}

with tf.Session() as sess:
    with tf.gfile.GFile(model_path, 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
        tf.import_graph_def(graph_def, name='')
        res = sess.run(output_names, feed_dict=feed_dict)
        print('Results:', res)
        print('Unique Class scores', np.unique(res[1]))
```
### Results
```
Results: [array([[[-1.5177027e-19, -1.3691601e-18,  8.3486214e-18,  1.8013723e-18],
        [-7.2626491e-18,  5.8560479e-18, -9.0981711e-18,  9.1619815e-18],
        [-2.0315618e-18, -8.0482321e-19, -1.6122743e-18, -1.4601467e-18],
        ...,
        [ 5.7505814e-31,  1.3925701e-30, -8.9931355e-31,  2.4463876e-31],
        [-3.3578927e-30, -4.3663738e-33, -1.4428099e-30,  9.2840516e-31],
        [-9.4014834e-31, -3.2971338e-31, -7.9477421e-31, -4.3221366e-31]]],
      dtype=float32), array([[[0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
        ...,
        [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
        [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5]]], dtype=float32)]
Unique Class scores [0.5]
```

**Comment by PythonImageDeveloper** [comment]
The model_path = r'frozen_inference_graph.pb' is for ssd_mobilenent_v3_small?
If you tested this model and got same result with onnx and orginal model, Please share your code for testing.

**Comment by jignparm** [comment]
### 1
>The model_path = r'frozen_inference_graph.pb' is for ssd_mobilenent_v3_small?

That's correct...for ssd_mobilenet_v3_small_coco (see the model location link above). 

Please verify the exact location of the model you are using. The input names (e.g. image_tensor:0) you listed do not match the input names in the model above.

```
$ /d/bin/summarize_graph.exe --in_graph=frozen_inference_graph.pb
Found 1 possible inputs: (name=normalized_input_image_tensor, type=float(1), shape=[1,320,320,3])
No variables spotted.
Found 2 possible outputs: (name=raw_outputs/box_encodings, op=Identity) (name=raw_outputs/class_predictions, op=Identity)

```

### 2
>If you tested this model and got same result with onnx and orginal model, Please share your code for testing.

See `Method 2` outlined here https://github.com/onnx/tensorflow-onnx/issues/729 for how to convert the TF model to ONNX, and compare the output results.

**Comment by AsmaAP** [comment]
I have the same issue. Any updates ?
