### ISSUE TITLE
stridedslice_op: begin_mask =9,and  begin: [0 2 2 0]  Need to deal with it?

### ISSUE THREAD

**Issue by laobadao** [onnx/tensorflow-onnx#78]
stridedslice_op:
 input: "detector/yolo-v3/ResizeBilinear_1:0"
input: "detector/yolo-v3/strided_slice_1/stack:0"
input: "detector/yolo-v3/strided_slice_1/stack_1:0"
input: "detector/yolo-v3/strided_slice_1/stack_2:0"
output: "detector/yolo-v3/strided_slice_1:0"
name: "detector/yolo-v3/strided_slice_1"
op_type: "StridedSlice"
attribute {
  name: "begin_mask"
  i: 9
  type: INT
}
attribute {
  name: "ellipsis_mask"
  i: 0
  type: INT
}
attribute {
  name: "end_mask"
  i: 9
  type: INT
}
attribute {
  name: "new_axis_mask"
  i: 0
  type: INT
}
attribute {
  name: "shrink_axis_mask"
  i: 0
  type: INT
}

begin: [0 2 2 0]
end: [ 0 -2 -2  0]
strides: [1 1 1 1]
mask: 1
mask: 0
mask: 0
mask: 1
new_begin: [0, 2, 2, 0]
new_end: [9223372036854775807, -2, -2, 9223372036854775807]

**Comment by guschmue** [comment]
yes we should. If you have a fix send a pr.  if not I can look at it :)

**Comment by laobadao** [comment]
@guschmue thanks, (*^▽^*) In fact, I want to solve the problem that the slice multi-dimensional can not run on caffe2, although it violates the tensorflow and onnx specifications, but in order to run on caffe2, I still split into a one-dimensional operation, the begin_mask , seems to have no effect in my model, thank you,

**Comment by guschmue** [comment]
there is this command line option ```--target caffe2``` that I used to runtime specific workarounds. caffe2 and winml needed some of those. Its should be ok to add some hack for caffe2
```
if ctx.is_target(TARGET_CAFFE2):
    some hack
```
The current default is to have target_caffe2 set but we are going to change that soon.

**Comment by pengwa** [comment]
begin_mask is supported now, @laobadao feel free to have a try and let us know whether this solved your issue.
