### ISSUE TITLE
Failed to convert convolutional autoencoder with skip connections

### ISSUE THREAD

**Issue by achernigin1987** [onnx/tensorflow-onnx#780]
**Describe the bug**
We use ordinary "autoencoder with skip connections" trained by tensorflow 1.4 and saved as a frozen model.
![tf_frozen_model](https://user-images.githubusercontent.com/22882667/73442634-3ef21880-4366-11ea-82a8-dfdbe17892ab.png).

 Conversion to ONNX model with using of opset 8 is failed with error "h and w need to be known" for ResizeNearestNeighbor operation. But we have reviewed convertor source code and found that size of input and target only required to calculate scales. This requirement is very strange, because almost every convolutional network assumes that only input channels count are fixed, but spatial sizes can be different and usually not specified.
We have hardcoded scales into tensorflow-onnx code locally in the following way:

```
@tf_op(["ResizeBilinear", "ResizeNearestNeighbor"])
class Resize:
    @classmethod
    def version_7(cls, ctx, node, **kwargs):
        mode = "linear" if node.type == "ResizeBilinear" else "nearest"
        node.type = "Upsample"
        shape = ctx.get_shape(node.input[0])
        #target_shape = node.inputs[1].get_tensor_value()
        # https://www.tensorflow.org/api_docs/python/tf/image/resize_nearest_neighbor
        # wants the input to be NHWC - adjust target_shape to this.
        n, h, w, c = shape
        #nh, nw = target_shape
        #utils.make_sure(all(i != -1 for i in [nh, nw]), "h and w need to be known")
        # scaler is nchw
        scaler = [1., 1., 2. , 2.]
        node.set_attr("scales", scaler)
        node.set_attr("mode", mode)
        ctx.remove_input(node, node.input[1])
        node.data_format = "NHWC"
        conv_convert_inputs(ctx, node, with_kernel=False)
```
and ran tf2oonx. After that we successfully got the resulted model.
![onnx_op8_model](https://user-images.githubusercontent.com/22882667/73443274-6eedeb80-4367-11ea-8d4e-be1d5753fe24.png)

Unfortunately, this model has invalid node names in comparision with the original tensorflow model. For example, all convolutions have completely new names and the first Transpose node has name "Encoder/Stage1/conv2D/Conv2D_8" that is actually name of the one of convolution in the original tensorflow model, etc. 
![onnx_op10_model_names](https://user-images.githubusercontent.com/22882667/73443512-dc018100-4367-11ea-8546-5d4c67842a24.png)

Correct naming you can see in the following image:
![tf_frozen_model_names](https://user-images.githubusercontent.com/22882667/73443800-66e27b80-4368-11ea-86bb-d0ad19475c4c.png)

Moreover, we have tried to convert TF frozen model using opset 10 and it has successfully finished without errors. But result model looks very strange and incorrect:
![onnx_op10_model](https://user-images.githubusercontent.com/22882667/73444125-ff78fb80-4368-11ea-8a56-ef062f860217.png)

**Urgency**.
We have temp workaround to convert our model (patch provided above) but it's not applicable for production, and we plan to release our product very soon we ONNX support. But currently tensorflow-onnx convertor doesn't work for widely-used autoencoder architecture and we need to fix it urgent.

**System information**
- OS Platform and Distribution:  Windows 10 and Ubuntu 18.04
- Tensorflow Version:  1.14-1.15
- Python version :  3.6

**To Reproduce**
1) Create autoencoder with symmetric skip-connections in TF
2) freeze model
3) try to convert

**Expected behavior**
We need to get result model as we have taken after local patch or the as original TF model

**Comment by guschmue** [comment]
For the Upsample() op the scales are an attribute that the converter needs to calculate and it can only do this if it known input and output shapes so if H or W are not known it doesn't work.
But In opset-10 there is now a Resize() op where scales can be passed in at runtime. So if you use ```--opset 10``` it should work.

**Comment by achernigin1987** [comment]
I have attached image with opset 10. It looks very awful:
![onnx_op10_model](https://user-images.githubusercontent.com/22882667/73546338-1c3b2f00-444e-11ea-9dda-cbf42fb0154d.png)

**Comment by guschmue** [comment]
You mean this shape/gather/slice/div/concat sequence ? Since we need to calculate the scales at runtime I don't see how we can avoid this. We can take a look if the gather is really needed.
If the Resize() op would take the desired output shape as argument things would be much simpler.

For names: we don't try to preserve names other than the inputs and outputs.

**Comment by achernigin1987** [comment]
> For names: we don't try to preserve names other than the inputs and outputs.
Is it possible to add such functionality to tensorflow-onnx? Sometimes we need access to intermediate nodes and it is a little bit complicated to use different node names for the same model in different formats (we support the both onnx and tensorflow formats). 

Except that, tf2onnx converter sets node names that don't correspond to actual node type. For example, in our converted onnx model _Transpose_ node got name "Graph/Encoder/Stage1/conv2d/Conv2D__8" from the original graph convolution, _Reshape_ node got name new name "Transpose_298". It is very inconvenient to debug and log such nodes.

> You mean this shape/gather/slice/div/concat sequence ?
Yes, I think we don't need _gather_, _div_ _concat_ and _cast_. Original tensorflow graph specifies output size as a shape of one of previous LeakyRelu layer. As I can see, opset10 allows to specify "sizes" attribute in the similar way. So, we don't need to calculate scales at all.

**Comment by guschmue** [comment]
This should be fixed in https://github.com/onnx/tensorflow-onnx/pull/874
