### ISSUE TITLE
Error while converting Frozen model (.pb)

### ISSUE THREAD

**Issue by AsharFatmi** [onnx/tensorflow-onnx#783]
Hi
I am converting a Keras model to onnx to eventually implement TensorRT for inference.
I converted the keras to a tensorflow model (.pb file).

I am running the following code to convert it to onnx.

```
import tf2onnx
import tensorflow as tf

def load_graph_def(model_path) -> tf.GraphDef:
    """
    Helper function to read model protobuf and return graph definition
    Args:
        model_path: Path to frozen model .pb file

    Returns:
        graph_def: graph definition

    """
    graph_def = tf.GraphDef()
    with open(model_path, "rb") as f:
        graph_def.ParseFromString(f.read())

    return graph_def


tf_graph = load_graph_def('tf_model.pb')


onnx = tf2onnx.tfonnx.process_tf_graph(tf_graph, 
            continue_on_error=False, verbose=False, target=None,
            opset=None, custom_op_handlers=None,
            custom_rewriter=None, extra_opset=None,
            shape_override=None, inputs_as_nchw=None,
            input_names=None, output_names=None)


print('Done')
```

Unfortunately i am getting the following error:

```
kingashar@kingashar:~/YOLOV3-LP$ python3 tfTonnx.py 
WARNING:tensorflow:From tfTonnx.py:4: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

Traceback (most recent call last):
  File "tfTonnx.py", line 29, in <module>
    input_names=None, output_names=None)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 486, in process_tf_graph
    tf_graph = infer_shape(tf_graph, shape_override)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/shape_inference.py", line 33, in infer_shape
    tf_graph = infer_shape_for_graph(tf_graph)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/shape_inference.py", line 91, in infer_shape_for_graph
    for o in tf_graph.get_operations():
AttributeError: 'GraphDef' object has no attribute 'get_operations'
```

_Can anyone pleasehelp with this issue?_

Thanks in Advance

**Comment by jignparm** [comment]
The arguments to the process_tf_graph() function seem to be missing several values (e.g. input_names, output_names etc.)

An easy alternative is to save the graphdef as a frozen TF model file, and then use TF2ONNX from the command line interface.

**Comment by AsharFatmi** [comment]
Thanks for the expeditious response...
I tried your method and got the onnx model.

But now when I am trying to run inference on the model to check if the output is stable I am getting the following error:-

```
InvalidArgument                           Traceback (most recent call last)
<ipython-input-7-88e50fa7826c> in <module>
----> 1 result = sess.run(outputs, {"input:0": T})
      2 result

/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py in run(self, output_names, input_feed, run_options)
    140             output_names = [output.name for output in self._outputs_meta]
    141         try:
--> 142             return self._sess.run(output_names, input_feed, run_options)
    143         except C.EPFail as err:
    144             if self._enable_fallback:

InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (N11onnxruntime17PrimitiveDataTypeIhEE) , expected: (N11onnxruntime17PrimitiveDataTypeIfEE)
```

I am feeding the image in the exact same format as I was before converting it to the onnx format.

**Can you help me out with this?**

The code is here:- 

```
import onnxruntime as rt
import os
sess = rt.InferenceSession("model.onnx")

# we want the outputs in this order
outputs = ["concatenate_1/concat:0"]

result = sess.run(outputs, {"input:0": T})
print(result)
```

**Comment by jignparm** [comment]
Most likely the type of T does not match the input expected by the model. You can use Netron to visualize the model and inspect the input types the model expects.

Also, have a look at this link. It's describing a similar  error message as above http://www.xavierdupre.fr/app/onnxruntime/helpsphinx/auto_examples/plot_common_errors.html

**Comment by AsharFatmi** [comment]
I am feeding the exact same input as I was before converting to onnx.
Also, neutron is not giving a definite shape all it says is it should 3 channel image.
![Screenshot from 2020-02-09 11-19-34](https://user-images.githubusercontent.com/36506102/74098167-554e6000-4b2e-11ea-8859-7ef3d1854905.png)

**Comment by AsharFatmi** [comment]
I converted the model directly from Keras to onnx. Thanks
