### ISSUE TITLE
dynamic shape

### ISSUE THREAD

**Issue by lxl910915** [onnx/tensorflow-onnx#784]
**Describe the bug**
We use [tf2onnx ](https://github.com/onnx/tensorflow-onnx)to convert tensorflow saved_model to onnx. If we do not fix the input shape when generating tensorflow saved_model and convert tensorflow saved_model to onnx, we use onnxruntime.InferenceSession to run this model, getting the following errorwe get this error :
_2020-02-03 09:12:55.136772385 [E:onnxruntime:, sequential_executor.cc:183 Execute] Non-zero status code returned while running Concat node. Name:'feature_fusion/concat_3' Status Message: /onnxruntime/onnxruntime/core/providers/cpu/tensor/concat.cc:64 onnxruntime::common::Status onnxruntime::ConcatBase::PrepareForCompute(onnxruntime::OpKernelContext*, const std::vector<const onnxruntime::Tensor*>&, onnxruntime::Prepare&) const inputs_n_rank == inputs_0_rank was false. Ranks of input data are different, cannot concatenate them. expected rank: 4 got: 0_

https://github.com/microsoft/onnxruntime/issues/2872#issuecomment-581297603

https://github.com/onnx/onnx-tensorflow/issues/464

**Urgency**
none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 16.04
- Tensorflow Version: TF-1.14.0

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by jignparm** [comment]
It seem that you already have a workaround now, which is to fix the model shape (based on this comment https://github.com/microsoft/onnxruntime/issues/2872#issuecomment-581297603).

Please share the model if you can, to debug why the shape requires to be set explicitly.

**Comment by lxl910915** [comment]
> It seem that you already have a workaround now, which is to fix the model shape (based on this comment [microsoft/onnxruntime#2872 (comment)](https://github.com/microsoft/onnxruntime/issues/2872#issuecomment-581297603)).
> 
> Please share the model if you can, to debug why the shape requires to be set explicitly.

We train [EAST](https://github.com/argman/EAST#train), and get it saved_model. 
`saved_model_cli show --all --dir /tmp/1/` get the following result:
```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_images'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1, -1, 3)
        name: input_images:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['geometry'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1, -1, 5)
        name: feature_fusion/concat_3:0
    outputs['score'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1, -1, 1)
        name: feature_fusion/Conv_7/Sigmoid:0
  Method name is: tensorflow/serving/predict
```

Then, we convert saved_model to onnx using `python -m tf2onnx.convert --saved-model /tmp/1/ --output east_model.onnx --outputs feature_fusion/concat_3,feature_fusion/Conv_7/Sigmoid  --opset 10 --verbose `.

Next, we

**Comment by lxl910915** [comment]
Any body help?

**Comment by jignparm** [comment]
Sorry for the delay -- is this the model that you are using can you confirm this is the model you are using ? --> http://download.tensorflow.org/models/resnet_v1_50_2016_08_28.tar.gz

Will reply back shortly on this.

**Comment by jignparm** [comment]
@lxl910915 , Can you try this  command line instead. The --fold_const is usually required.

#Command line
```
python -m tf2onnx.convert 
--saved-model /tmp/1/ 
--output east_model.onnx 
--inputs input_images:0
--outputs feature_fusion/concat_3:0,feature_fusion/Conv_7/Sigmoid:0 
--opset 10
--fold_const 
--verbose
```

Unfortunately, I'm stuck at the login prompt below for the YunDetectService.exe applicaiton. Any way you can upload to a the east model to a location that is easy to download from (from the US)?



![image](https://user-images.githubusercontent.com/13698702/74298230-075d7600-4d41-11ea-9447-769befd2f8e2.png)

**Comment by lxl910915** [comment]
@jignparm @guschmue  
Can you tell us that does tensorflow-onnx support dynamic shape of input ?
If it supports, can you provide a demo? Otherwise, this issue become a feature request.

**Comment by lxl910915** [comment]
https://github.com/onnx/onnx/issues/654#issuecomment-410538671

**Comment by lxl910915** [comment]
> @lxl910915 , Can you try this command line instead. The --fold_const is usually required.
> 
> #Command line
> 
> ```
> python -m tf2onnx.convert 
> --saved-model /tmp/1/ 
> --output east_model.onnx 
> --inputs input_images:0
> --outputs feature_fusion/concat_3:0,feature_fusion/Conv_7/Sigmoid:0 
> --opset 10
> --fold_const 
> --verbose
> ```
> 
> Unfortunately, I'm stuck at the login prompt below for the YunDetectService.exe applicaiton. Any way you can upload to a the east model to a location that is easy to download from (from the US)?
> 
> ![image](https://user-images.githubusercontent.com/13698702/74298230-075d7600-4d41-11ea-9447-769befd2f8e2.png)

We have upload to [here](https://github.com/lxl910915/Test/blob/master/east_model.onnx).

**Comment by lxl910915** [comment]
Setting --cmake_extra_defines onnxruntime_DEBUG_NODE_INPUTS_OUTPUTS=2 when building onnxruntime. We get node inputs as follows:
```
------DumpNodeInputs-----
Concat node: feature_fusion/concat_3
Input 0 Name: feature_fusion/mul_6:0 Shape: {1,64,64,4}
Input 1 Name: feature_fusion/truediv:0 Shape: {}
```
We can see the shape of input0 and input1 is diff. Input0's shape is empty. Finding feature_fusion/mul_6's parent nodes, some TRTKernel nodes' output shape is empty.
```
------DumpNodeInputs-----
TRTKernel_17 node: TensorrtExecutionProvider_TRTKernel_17_17
Input 0 Name: feature_fusion/Conv_7/Conv2D__647:0_TensorrtExecutionProvider_65 Shape: {1,64,64,1}
------DumpNodeOutputs-----
Output 0 Name: feature_fusion/Conv_7/Sigmoid:0 Shape: {}
OrtMemoryInfo: [ name:Tensorrt id:0 mem_type:0 alloc_type:1]
------DumpTensor-----

1.63163e-06
```

**Comment by jignparm** [comment]
Thanks for uploading the model, and for the great debugging.

The bug/difference is clearly due to `ort_session.set_providers(['TensorrtExecutionProvider', '...'])`, since the CPU and GPU execution providers can run  the model with dynamic inputs just fine.

Also, can you also try the following way to set dynamic shape (using dim_value instead of dim_param)? It's possible that the TensorrtExecutionProvider will recognize that correctly.

```
model.graph.input[0].type.tensor_type.shape.dim[1].dim_value = -1
model.graph.input[0].type.tensor_type.shape.dim[2].dim_value = -1
```

Regardless whether the above works or not, the  CPU, GPU and TRT execution providers all need to process a working graph in the same way. I'll open up a issue with OnnxRuntime.

**Comment by jignparm** [comment]
Created https://github.com/microsoft/onnxruntime/issues/3034 to resolve this discrepancy.

**Comment by lxl910915** [comment]
> Thanks for uploading the model, and for the great debugging.
> 
> The bug/difference is clearly due to `ort_session.set_providers(['TensorrtExecutionProvider', '...'])`, since the CPU and GPU execution providers can run the model with dynamic inputs just fine.
> 
> Also, can you also try the following way to set dynamic shape (using dim_value instead of dim_param)? It's possible that the TensorrtExecutionProvider will recognize that correctly.
> 
> ```
> model.graph.input[0].type.tensor_type.shape.dim[1].dim_value = -1
> model.graph.input[0].type.tensor_type.shape.dim[2].dim_value = -1
> ```
> 
> Regardless whether the above works or not, the CPU, GPU and TRT execution providers all need to process a working graph in the same way. I'll open up a issue with OnnxRuntime.

dim_value does't work.
