### ISSUE TITLE
feature request posenet on mobilenet

### ISSUE THREAD

**Issue by rush86999** [onnx/tensorflow-onnx#785]
It would be great to use onnx js with tensorflow posenet model from tensorflow js. any help on getting this working would be appreciated.

**Comment by guschmue** [comment]
We'd need to have the tensorflow model checkpoint that goes with it. google has a tflite model for it but I can't find the tensorflow checkpoint that goes with it.

**Comment by rush86999** [comment]
is this the link https://storage.googleapis.com/tfjs-models/savedmodel/ssd_mobilenet_v1/weights_manifest.json ?

**Comment by guschmue** [comment]
that is ssd-mobilenet and the format is tensorflow.js. We need a checkpoint from tensorflow which must be there since there is a tflite model that would need it as input.
