### ISSUE TITLE
Custom ops

### ISSUE THREAD

**Issue by danperazzo** [onnx/tensorflow-onnx#788]
Hi, just a question: can I use tf2onnx with Tensorflow custom ops in C++? Or this is not supported currently with the converter? Thanks!

**Comment by guschmue** [comment]
This should be supported. There are 2 options:
1. by default if we find a tensorflow op that is not supported we just leave it as is in the onnx graph.
If your c++ custom op has the same inputs/outputs as the tensorflow op you don't need to do anything.
2. If you use the python api you can register a custom op. There is some example here:
https://github.com/onnx/tensorflow-onnx/blob/master/examples/custom_op_via_python.py
This is using a older api. We have a newer api for the registration that is a little easier, for example:
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/custom_opsets/ms.py#L46.
If you don't want to use the python api you could copy your implementation to custom_opsets similar to ms.py (which is basically contains custom ops). If your custom op is not in the onnx domain, you might need ```--extra_opset```, ie. for ms.py ```--extra_opsetcom.microsoft:1```.

**Comment by danperazzo** [comment]
Ok, i will try it, thnaks @guschmue !
