### ISSUE TITLE
SpaceToBatchND error: only support same blocksize at different dims

### ISSUE THREAD

**Issue by carlosgalvezp** [onnx/tensorflow-onnx#790]
Hi,

We are trying to convert our frozen network (as protobuf) into ONNX. The `tf2onnx` tool is called like this:

`python -m tf2onnx.convert --input model.pb --inputs image:0 --outputs output1:0,output2:0 --opset 11 --verbose`

However the tool complains with the following message:
```
2020-02-06 11:47:47,438 - INFO - tf2onnx.tfonnx: Using tensorflow=1.14.0, onnx=1.6.0, tf2onnx=1.5.4/ee756a
2020-02-06 11:47:47,438 - INFO - tf2onnx.tfonnx: Using opset <onnx, 11>
2020-02-06 11:47:47,994 - VERBOSE - tf2onnx.tfonnx: Mapping TF node to ONNX node(s)
2020-02-06 11:47:48,127 - ERROR - tf2onnx.tfonnx: Failed to convert node Main_conv_dilated/SpaceToBatchND
OP=SpaceToDepth
Name=Main_conv_dilated/SpaceToBatchND
Inputs:
	pad:0=Pad, [1, 32, 80, 124], 1
	Main_conv_dilated/SpaceToBatchND/block_shape:0=Const, [3], 6
	Main_conv_dilated/SpaceToBatchND/paddings:0=Const, [3, 2], 6
Outpus:
	Main_conv_dilated/SpaceToBatchND:0=[4, 32, 40, 62], 1
Traceback (most recent call last):
  File "venv/lib/python3.6/site-packages/tf2onnx/tfonnx.py", line 354, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "venv/lib/python3.6/site-packages/tf2onnx/onnx_opset/tensor.py", line 1285, in version_1
    "only support same blocksize at different dims")
  File "venv/lib/python3.6/site-packages/tf2onnx/utils.py", line 291, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: only support same blocksize at different dims
```

This stems from creating a `Conv2D` layer as follows:

```
        self._conv = tf.compat.v2.keras.layers.Conv2D(
            filters=32,
            kernel_size=3,
            dilation_rate=(2, 2),
            use_bias=True,
            padding='valid',
            name='Main_conv_dilated',
            data_format='channels_first')
```
Is this expected?
Thanks!

**Comment by jignparm** [comment]
This operator is being updated, so the error message should disappear very shortly. 

ONNX does not support SpacetoBatchND directly, so it has be composed using a combination of other primitive operators. The current implementation only supports [n, n] block_shape, but  will be updated to support arbitrary sized block_shapes and >4D tensors.

**Comment by jignparm** [comment]
This should be fixed by https://github.com/onnx/tensorflow-onnx/pull/797.

Can you check if you're still seeing a conversion failure?

**Comment by carlosgalvezp** [comment]
Hi @jignparm ! Thanks a lot for the fix. It seems to work, since I now get a different error in further layers. I can open up a different bug for those.

**Comment by jignparm** [comment]
Thanks for the verification. I'll close this out after merging.

For the remaining errors, one option would be to share the model (assuming privacy is not a concern), otherwise another bug works as well.

**Comment by carlosgalvezp** [comment]
Great! Unfortunately I'm not able to share the model so I'll put up another ticket for the other issue. Thanks a lot for the quick help :)
