### ISSUE TITLE
Slice/Strided Slice possible discrepancy.

### ISSUE THREAD

**Issue by chrisjhebert1973** [onnx/tensorflow-onnx#791]
**Describe the bug**

Converting a superresolution model from TensorFlow to ONNX with tf2onnx, appears to work but attempting to load the model in the onnx runtime (using WinML Dashboard) throws an error pertaining to the input count of the Slide operation.

Loading model (path = D:\Documents\Development\xxxxxx\ISVs\xxxxx\xxxxxx\onnx_test\model6.onnx)...
Load Model: D:\Documents\Development\xxxxxx\ISVs\xxxxx\xxxxxx\onnx_test\model6.onnx [FAILED]
Node:Slice__506 Node (Slice__506) has input size 4 not in range [min=1, max=1].
000001C3AB982E3C

I believe this should in fact be a strided_slice rather than a slice and both should be supported in this opset.

**Urgency**
Need to get a workaround or fix for this pretty urgently.

**System information**
- Windows 10
- Tensorflow 1.15.0
- Python 3.7.5

**To Reproduce**
Unfortunately I am unable to share the model.

**Screenshots**
![winmldashboard_issue](https://user-images.githubusercontent.com/810219/73987179-614edd80-48f4-11ea-9a5f-23e8c2ddf656.png)

**Comment by jignparm** [comment]
What opset is the model? It looks like the "Slice" op is generated assuming opset 10+ (which allows "Slice" to have 3+ inputs) but from the error message, the model is probably stamped with an opset less than 10 (where "Slice" had exactly 1 input).

Does the model run successfully if you convert using "--opset 11" on the command line?

**Comment by chrisjhebert1973** [comment]
Hi, thanks for getting back to me...

This is the code snippet used to perform the conversion, Using opset==10 for this conversion. The actual conversion works correctly however I'm unable to run the model (in WinMLDashboard), though perhaps winmldashboard iteslf doesn't have access to opset==10?

                 in_names = [key for key in in_dict];
                    out_names = [outp for outp in out_list]

                    print("ONNX Input Names : {}".format(in_names))
                    print("ONNX Output Names : {}".format(out_names))

                    graph_def = freeze_graph(sess,sess.graph_def,[out_names[0][:-2]])

                    with tf.Graph().as_default() as graph:
                        tf.import_graph_def(graph_def,name='')

                        onnx_graph = tf2onnx.tfonnx.process_tf_graph(graph, input_names=in_names,
                                                                 output_names=out_names,opset=10,inputs_as_nchw=[True,True,True,True,True])
                        model_proto = onnx_graph.make_model("topaz_sr")
                        with open("./onnx_test/model6.onnx", "wb") as f:
                            f.write(model_proto.SerializeToString())

**Comment by chrisjhebert1973** [comment]
I think actually tf2onnx is working as it should and it’s likely my WinML runtime is not the right version?

**Comment by chrisjhebert1973** [comment]
Let me verify this, then I’ll close this issue.

**Comment by jignparm** [comment]
It would be good to know  the latest ONNX opset version that WinMLDashboard supports.

**Comment by guschmue** [comment]
as far I know winml is currently on opset-8:
https://docs.microsoft.com/en-us/windows/ai/windows-ml/onnx-versions

**Comment by jignparm** [comment]
Assuming there are no further issues, due to non-response. Closing.
