### ISSUE TITLE
RandomNormalLike seed is not set

### ISSUE THREAD

**Issue by AlexRibard** [onnx/tensorflow-onnx#793]
Hi,
I am converting a model with a RandomStandardNormal node.
I noticed that the seed specified in .pb model is not carried over to the .onnx model

Thanks!

Here are the .pb and corresponding .onnx models
[models.zip](https://github.com/onnx/tensorflow-onnx/files/4182853/models.zip)

**Comment by jignparm** [comment]
#800 should address this issue. The rewriter for RandomStandardNormal was skipping the seed value.

**Comment by AlexRibard** [comment]
Thanks! :)
