### ISSUE TITLE
Conv framed by Transposes

### ISSUE THREAD

**Issue by AlexRibard** [onnx/tensorflow-onnx#794]
Hi!
I am exporting a model .pb to .onnx and have noticed that the Conv opperator is framed by two Transposes.
If I manually set the data_format in Tensorflow to match NCHW, the tf2onnx optimizer removes the transposes.
However in the base case the Transpose are not optimized away.

![image](https://user-images.githubusercontent.com/12990800/74187690-18ac6280-4c1b-11ea-9d56-4b2e60a59224.png) 
vs 
![image](https://user-images.githubusercontent.com/12990800/74187726-28c44200-4c1b-11ea-9987-13e7ee07ec4e.png)

Thanks!

Here are the .pb and corresponding .onnx models
[example.zip](https://github.com/onnx/tensorflow-onnx/files/4182918/example.zip)

**Comment by guschmue** [comment]
Took a quick look. I think the first 2 transposes we can get rid of by because the optimizer is not aware how to move the transpose over Elu. If we can we'd 2 back to back transposes that nuke each other. Should be easy to add. The third transpose I'm not sure if we can find a way to remove it.

**Comment by guschmue** [comment]
with the fix and 
```python tf2onnx\convert.py --input example.pb --output t.onnx --inputs visual_observation_0:0,action_masks:0 --outputs action:0 --opset 11 --inputs-as-nchw visual_observation_0:0```
as command line all transposes are gone.

**Comment by AlexRibard** [comment]
Without --inputs-as-nchw there is a transpose before the first Conv.

**Comment by AlexRibard** [comment]
@guschmue thanks! :)

**Comment by guschmue** [comment]
yeah, no way to remove it unless the input nchw.
We merged the fix to master.
