### ISSUE TITLE
Merge MatMul followed by a Add as GEMM

### ISSUE THREAD

**Issue by AlexRibard** [onnx/tensorflow-onnx#795]
Hi!
I am trying to export a .pb model to a .onnx
In the original model, there is a MatMul followed by a Add.
Would it be possible for the tf2onnx optimizer to merge those two layers into a GEMM?

![image](https://user-images.githubusercontent.com/12990800/74188103-cae42a00-4c1b-11ea-8f45-fab10da261bf.png)

Thanks!

Here is the example
[example.zip](https://github.com/onnx/tensorflow-onnx/files/4182938/example.zip)

**Comment by jignparm** [comment]
Usually the optimizations are either for speed or for clarify.

Is this faster in some scenarios (or just more legible)?

**Comment by AlexRibard** [comment]
It's slightly faster in my case. Similar to how CCN + BiasAdd in TensorFlow is merged into one CNN call in onnx.

**Comment by AlexRibard** [comment]
maybe add this as an option to the optimizer?

**Comment by jignparm** [comment]
It can probably just be added as an enhancement (auto-optimize). Extra options for the optimizer is probably not required -- users would generally want all optimizations possible.

**Comment by guschmue** [comment]
This was added some time ago, forgot to update this issue:
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/rewriter/gemm_rewriter.py
