### ISSUE TITLE
Cannot find the tensorflow-onnx folder after running pip install -U tf2onnx, can't finish installation

### ISSUE THREAD

**Issue by bara495** [onnx/tensorflow-onnx#799]
**Describe the bug**
Cannot find the tensorflow-onnx folder after running pip install -U tf2onnx
In that folder python setup.py install or python setup.py develop should be ran.

**Urgency**
Well if you cannot easily install the repo I guess it is urgent

**System information**
- Linux Ubuntu 16.04, also on Mac Mojave
- Tensorflow Version: 1.14
- Python version: 3.5

**To Reproduce**
Just do the first step of installation (pip install -U tf2onnx)
**Expected behavior**
A folder named tensorflow-onnx in which there is a setup.py file to continue installation as prescribed
**Screenshots**
![onnx q github](https://user-images.githubusercontent.com/16253032/74247410-490d0300-4ce6-11ea-9aaa-a341cac9c737.png)
(a particular part of packages installed, I searched for that setup.py in everything onnx related, but no luck)

**Comment by bara495** [comment]
Just now realized that we are talking about the repo's folder :man_facepalming: 

**maybe add a heads up, to make the instructions a bit more clear, since there is no instruction that says you need to clone the repo**

**Comment by jignparm** [comment]
Yes, cloning the repo is a prerequisite, if you want to use the latest master branch. Otherwise, you can simply 'pip install tf2onnx' to install the released packages.
