### ISSUE TITLE
tf2.0 - Branch gs/tf2

### ISSUE THREAD

**Issue by MI-LA01** [onnx/tensorflow-onnx#808]
Hello, 
Just wanted to know if this branch can be tested ? I tried to convert a tf2.0 .pb to onnx but ended with this : 

```
 File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 1 of node batch_normalization/cond was passed float from batch_normalization/gamma:0 incompatible with expected resource.
```

(I compiled tensorflow-onnx from source w/ a python3 setup.py install) ; had onnx-1.5.0 installed and tensorrt6. Tensorflow is at 2.0. pls note i run this on a jetson tx2 (aarch64)

**Comment by guschmue** [comment]
hm, hard to tell from the error msg. Is this a public model or can you give us the few lines how batchnorm is called ?

**Comment by guschmue** [comment]
I have added some more unit tests around batchnorm - works for me.

**Comment by guschmue** [comment]
I assume this is fixed.
