### ISSUE TITLE
Possible conversion bug for StridedSlice with negative stride and implicit bounds

### ISSUE THREAD

**Issue by tazr** [onnx/tensorflow-onnx#810]
**Describe the bug**
When a tensorflow model contains a slicing operation with a negative stride and an implicit bound, `onnxruntime` fails on the onnx model produced by `tf2onnx`.

**Urgency**
None.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 1903
- Tensorflow Version: 1.14.0
- Python version: 3.7.6

**To Reproduce**
1. Create a TF model
```python
import tensorflow as tf
ph = tf.placeholder(tf.float32, (1, 16, 32, 1), name='ph')
x = tf.concat([ph[:, :, :10], ph[:, :, 9::-1]], axis=0)
y = tf.add(x, 1, name='y')
g = tf.get_default_graph().as_graph_def()
tf.train.write_graph(g, '.', 'flip.pb', as_text=False)
```
2. Convert to ONNX
```bash
python -m tf2onnx.convert --input flip.pb --output flip.onnx --inputs ph:0 --outputs y:0 --opset 11
```

3. Run inference
```python
import onnxruntime as rt
sess = rt.InferenceSession('flip.onnx')
# onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (concat) Op (Concat) [ShapeInferenceError] Can't merge shape info. Both source and target dimension have values but they differ. Source=0 Target=10 Dimension=2
```

**Expected behavior**
I would expect no error

**Screenshots**

**Additional context**
The same problem occurs if the begin value is missing:
```python
x = tf.concat([ph[:, :, :10], ph[:, :, :21:-1]], axis=0)
```

However, if both begin *and* end values are provided, the model works fine:
```python
x = tf.concat([ph[:, :, :10], ph[:, :, 10:0:-1]], axis=0)  # works fine
```

It seems that the problem comes from the fact that default value of `0` and `1e9` are set for begin/end implicit bounds in [`StrideSlice.version_10`](https://github.com/onnx/tensorflow-onnx/blob/v1.5.5/tf2onnx/onnx_opset/tensor.py#L738), not taking into account the sign of the stride. A fix could perhaps be to switch those values when the stride is negative, or maybe use the actual shape values of the input, `ctx.get_shape(input_x.output[0])`?

**Comment by jignparm** [comment]
Thanks for posting the detailed description of the issue. 

Indeed the sign of the stride needs to be taken into account. Will upload a fix shortly.
