### ISSUE TITLE
If i have 2 outputs,how can i get 'network.mark_output'.

### ISSUE THREAD

**Issue by suntianqi123** [onnx/tensorflow-onnx#811]
--------
python -m tf2onnx.convert --input ocr_recognize.pb --output ocr_recognize.onnx --inputs input_node/images:0 --outputs mobilenetv2/output/num:0,mobilenetv2/output/cls:0 --verbose --fold_const --opset 7
--------
then i got the onnx file success, but 
when i want to mark_output, i print all the network layer,i can't find correct shape ,i just  find one correct outputs ,it's cls:0,the shape is (64,128,38),   how can i get another outputs.

**Comment by jignparm** [comment]
Using the model posted here https://github.com/XiaoMi/mace/issues/422, the command above produces this model.

The shapes of the two outputs are dynamic, as you can see below.

What source model are you using, and what shapes are you looking for?

![image](https://user-images.githubusercontent.com/13698702/75294552-a180ec00-5820-11ea-9277-bb0337141e3a.png)

**Comment by suntianqi123** [comment]
![Screenshot from 2020-02-26 10-31-10](https://user-images.githubusercontent.com/34191481/75306264-82677600-5883-11ea-9974-9a66138693e1.png)
Here is my onnx,and i it has two outputs. I use python to convert the onnx2trt. Here is the code:
`cls_layer = network.get_layer(network.num_layers - 1)
network.mark_output(cls_layer.get_output(0))`
then i can get the outputs:cls,how can i get the outputs:num?

**Comment by jignparm** [comment]
What error are you seeing when using the TensorRT API

Can you try using OnnxRuntime instead? See below for an example. There should be no issue in getting both output values.

###Code
```python
import onnxruntime as rt                                                                                                                                                                                 
import numpy as np                                                                                                                                                                                       
sess = rt.InferenceSession('ocr_recognize.onnx')                                                                                                                                                                                                                                                                                                                                                                  

res = sess.run(['mobilenetv2/output/num:0', 'mobilenetv2/output/cls:0'], {'input_node/images:0': np.ones((1,100,100,3), dtype=np.float32)})

print (res[0])                                                                                                                                                                                           
print (res[1])
```

###Output Log
```
[[[[1.00000000e+00 2.33751928e-12]
   [1.00000000e+00 3.21165317e-12]
   [1.00000000e+00 4.64438763e-08]
   [9.99997139e-01 2.86650834e-06]
   [9.99832511e-01 1.67508784e-04]
   [9.99009609e-01 9.90315340e-04]
   [9.98235703e-01 1.76430924e-03]
   [9.99424815e-01 5.75215905e-04]
   [9.99423862e-01 5.76218939e-04]
   [9.99810994e-01 1.89017737e-04]
   [9.99944210e-01 5.57981766e-05]
   [9.99903083e-01 9.69536632e-05]
   [9.99582946e-01 4.17051691e-04]]
```

**Comment by suntianqi123** [comment]
![Screenshot from 2020-02-26 15-38-38](https://user-images.githubusercontent.com/34191481/75322666-34b43300-58ae-11ea-93aa-25a4d032fc5c.png)
![Screenshot from 2020-02-26 15-38-53](https://user-images.githubusercontent.com/34191481/75322670-35e56000-58ae-11ea-8c29-27eca1235628.png)

my problem is :
There should be two outputs in onnx,but only one output CLS can be found when building TRT engine,and num can not be found when printing the names of all layers,What may the reason?

**Comment by jignparm** [comment]
>but only one output CLS can be found when building TRT

This repository deals mostly with  TF2ONNX issues (converting Tensorflow models to Onnx). The above sounds like TRT engines issue (correct if assuming is wrong). Maybe another repository can help with running TRT engine?

**Comment by suntianqi123** [comment]
OK,Thank you
