### ISSUE TITLE
InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:GridAnchorGenerator/range : Unrecognized attribute: Tidx for operator Range

### ISSUE THREAD

**Issue by Dhanashri-Dhanashri** [onnx/tensorflow-onnx#820]
Hi
Getting InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:GridAnchorGenerator/range : Unrecognized attribute: Tidx for operator Range error.
Model : Resnet 
The given SavedModel SignatureDef contains the following input(s):
  **inputs['image_bytes'] tensor_info:
      dtype: DT_STRING
      shape: (-1)
      name: input_tensor:0**
The given SavedModel SignatureDef contains the following output(s):
  outputs['classes'] tensor_info:
      dtype: DT_INT64
      shape: (-1)
      name: ArgMax:0
  outputs['probabilities'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 1001)
      name: softmax_tensor:0
Method name is: tensorflow/serving/predict

By updating 
tf2onnx : 1.5.5 , --op=11
Solved the opt round error and got the model resized.
Able to load the model, but the above issue arises while loading the onnx model in onnxruntime.

**Comment by jignparm** [comment]
Can you add `--extra_opset com.microsoft:1` to the command line? Range has a historical implementation as an operator (versus a function, as op opset=11).

**Comment by Dhanashri-Dhanashri** [comment]
Not working.

**Comment by jignparm** [comment]
Can you provide a link to download the model?

**Comment by Dhanashri-Dhanashri** [comment]
https://github.com/tensorflow/serving/tree/master/tensorflow_serving/servables/tensorflow/testdata/saved_model_half_plus_two_2_versions

**Comment by jignparm** [comment]
The 2 models in that directory have inputs x:0, x2:0, tf_example:0, which don't match the error log pasted above. Additionally, they contain the TF operators "ParseExample", which is not supported currently in Onnx or TF2onnx.

Please attach a link to the exact model generating the error log.

**Comment by guschmue** [comment]
I assume this is fixed.
