### ISSUE TITLE
DecodeJpeg op not supported

### ISSUE THREAD

**Issue by Dhanashri-Dhanashri** [onnx/tensorflow-onnx#822]
Saved model successfully got converted to onnx model with opset 11, but  the above error is displayed while loading the onnx model.
tf version = 1.2.0
onnx = 1.5
tf2onnx = 1.5.1
onnx = 1.2.1

**Comment by jignparm** [comment]
The TF DecodeJpeg operator is  not implemented in either TF2ONNX or ONNX. 

Is this a community pre-trained model, or a custom model?

If it's a custom model, can you retrain the model using PlaceHolder instead of DecodeJpeg, as I/O types of operators are usually not supported?

**Comment by guschmue** [comment]
unlikely that we have a decode jpeg op in onnx anytime soon.

**Comment by guschmue** [comment]
closing because this is a onnx issue.

**Comment by vilmara** [comment]
Hi @guschmue, any update on implementing TF `DecodeJpeg` operator in TF2ONNX or ONNX?.

**Comment by guschmue** [comment]
no change - there is no DecodeJpeg in onnx so tf2onnx can not map it.

**Comment by guschmue** [comment]
Only 2 options are replace DecodeJpeg with a Placeholder or implement DecodeJpeg (ie as custom op).
