### ISSUE TITLE
Convert saved_model successfully, but onnx file is zero size

### ISSUE THREAD

**Issue by THULiusj** [onnx/tensorflow-onnx#823]
**Describe the bug**
I use tf2onnx to convert a saved model to onnx file. It reports convertion is successful and onnx file is generated. But when I open the onnx file, it's only 60KB, and nothing in it.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Unbuntu 18.04
- Tensorflow Version: 1.15
- Python version: 3.6

**To Reproduce**
Saved model in Google drive: https://drive.google.com/open?id=1m3GjDPjv94WKw8ecCeIvTD8TFj6b_EyV
convert command: python -m tf2onnx --saved-model saved_model --output aocr.onnx --opset 11

**Additional context**
Anyone knows why tf2onnx reports successful but onnx file is wrong? Without error message, I don't know how to debug it.

**Comment by RandySheriffH** [comment]
@THULiusj: Tried with the link but pending on access.

**Comment by THULiusj** [comment]
@RandySheriffH,  checkpoint: https://drive.google.com/open?id=1-MKY0jeWg8LdDnNVdJ5xyTyRlpahamPs,  saved model: https://drive.google.com/open?id=1em3vdIZIaI_y67Qxz3XUTvRTnc8tjNB9

**Comment by RandySheriffH** [comment]
With:
python -m tf2onnx.convert --saved-model ~/ISSUE823/saved_model --output ~/ISSUE823/aocr.onnx --opset 11
I got:
![image](https://user-images.githubusercontent.com/48490400/75911927-34172180-5e05-11ea-8fd2-2d8e0f9e7aff.png)

**Comment by THULiusj** [comment]
@Randy, It's very strange that when I convert saved model, the onnx file is only 61b. What's your tf2onnx version? Also, can you send your converted onnx file to me?

**Comment by THULiusj** [comment]
@RandySheriffH  It's very strange that when I convert saved model, the onnx file is only 61b. What's your tf2onnx version? Also, can you send your converted onnx file to me?

**Comment by RandySheriffH** [comment]
I am with latest master branch.

**Comment by RandySheriffH** [comment]
Closing the issue but please feel free to reopen it if further assistance expected.
