### ISSUE TITLE
DepthwiseConv2DNative model -- converts successfully, but error at run-time

### ISSUE THREAD

**Issue by jignparm** [onnx/tensorflow-onnx#824]
**Describe the bug**
A TF model using DepthwiseConv2DNative  operator converts successfully, but ORT throws error at runtime.

**Urgency**
Not sure

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- Tensorflow Version: TF 1.15
- Python version: Any

**To Reproduce**
Convert the model here -> https://drive.google.com/file/d/1SU-pEb93eLQoRMxaK5z80jyjemZ0YuIn/view?usp=sharing.

** Error Message **
```
2020-03-03 18:45:35.1126365 [E:onnxruntime:, sequential_executor.cc:184 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Conv node. Name:'FeatureExtractor/MobilenetV2/expanded_conv/depthwise/depthwise' Status Message: Input channels C is not equal to kernel channels * group. C: 34 kernel channels: 1 group: 32
2020-03-03 18:45:35,113 - ERROR - run_pretrained: Run_ONNX FAIL
Traceback (most recent call last):
  File "D:/jignparmtf2onnx/tests/run_pretrained_models.py", line 302, in run_test
    onnx_results = self.run_onnxruntime(name, model_proto, inputs)
  File "D:/jignparmtf2onnx/tests/run_pretrained_models.py", line 189, in run_onnxruntime
    results = m.run(self.output_names, inputs)
  File "d:\onnxruntime5\build\Windows\Debug\Debug\onnxruntime\capi\session.py", line 142, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Conv node. Name:'FeatureExtractor/MobilenetV2/expanded_conv/depthwise/depthwise' Status Message: Input channels C is not equal to kernel channels * group. C: 34 kernel channels: 1 group: 32

```

**More Information**
https://github.com/microsoft/onnxruntime/issues/3114

**Comment by guschmue** [comment]
What is different with this model ?
This (aka the standard mobilenet-v2)
```
python tests\run_pretrained_models.py --tests mobilenet_v2_1.4_224 --opset 11
```
works for me on ort 1.1.

**Comment by qraleq** [comment]
@guschmue This model is SSD model with MobilenetV2_FPN backbone.

**Comment by guschmue** [comment]
ah, got it.

**Comment by qraleq** [comment]
Any update from the team on this issue?

**Comment by RandySheriffH** [comment]
@qraleq : would u mind share your tf pb file with public accessibility and paste your command for conversion? In tf2onnx we do DepthwiseConv2DNative by Conv with adjusted parameters like tranposed input and recalcuated group/pads, it is possible there are some loose ends escaping the unit test.

**Comment by qraleq** [comment]
@RandySheriffH You can download the .pb file on this link: https://drive.google.com/file/d/1SU-pEb93eLQoRMxaK5z80jyjemZ0YuIn/view?usp=sharing

Also, I use this command to convert the model to .onnx:
`!python3 -m tf2onnx.convert --graphdef frozen_inference_graph.pb --output model.onnx \
    --fold_const --opset 11 \
    --inputs image_tensor:0 \
    --outputs num_detections:0,detection_boxes:0,detection_scores:0,detection_classes:0`

**Comment by qraleq** [comment]
As I mentioned in the microsoft/onnxruntime#3114, we're using SSD with mobilenet_v2_fpn backbone. We set the parameter `use_explicit_padding: true` in the pipeline.config and it's a prerequisite for our model to work as we want.

If I set `use_explicit_padding: false` when exporting the tf graph, the model runs with .onnx runtime, but the results aren't good. So, there is some problem in handling the padding operation in the graph.

**Comment by RandySheriffH** [comment]
@qraleq : are we looking at the same model? By the linked pb I got two issue:
1. tf.broadcast_to not support - https://github.com/onnx/tensorflow-onnx/pull/839
2. During inferencing, caught exception - _[E:onnxruntime:, sequential_executor.cc:183 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running ReorderInput node. Name:'ReorderInput_217' Status Message: D:\4\s\onnxruntime\contrib_ops\cpu\nchwc_ops.cc:74 onnxruntime::contrib::ReorderInput::Compute (X_shape[1] % MlasNchwcGetBlockSize()) == 0 was false._

**Comment by qraleq** [comment]
@RandySheriffH Sorry, I might mixed the two models I shared in the previous thread. Can you try this one: https://drive.google.com/file/d/1drUHKCZm_gIHheIQDB4kJEwILLJv0r9C/view?

This model was frozen using tensorflow 1.14, and the previously shared was frozen using tf 1.15.

**Comment by RandySheriffH** [comment]
@qraleq : thanks but met with issue 2 as before.

**Comment by qraleq** [comment]
@RandySheriffH I figured what is missing to reproduce the error mentioned in the related thread. According to @jignparm proposal, we included `sess_options.graph_optimization_level = rt.GraphOptimizationLevel.ORT_ENABLE_EXTENDED` as a flag.

After including this, you should get the same error as we do!

P.S. I'll try  #839.

**Comment by RandySheriffH** [comment]
@qraleq : indeed now I could see the conv exception. Let's see ...

**Comment by qraleq** [comment]
@RandySheriffH Do you have any updates on this?

**Comment by RandySheriffH** [comment]
@qraleq: yes I do - comment the _pad_optimizer in transpose_optimizer.py then you will get everything right. I am still composing a decent fix on this which required more thorough understanding of the graph optimization. Please try it out and let me know if I am wrong.

**Comment by qraleq** [comment]
@RandySheriffH Thank you very much! Everything works as supposed now!
