### ISSUE TITLE
ValueError: Shape must be rank 1 but is rank 0 for 'ParseExample/ParseExample' (op: 'ParseExample') with input shapes: [], [0], [], [], [0], [1].

### ISSUE THREAD

**Issue by Siri-KA** [onnx/tensorflow-onnx#825]
I am trying to convert saved_model half_plus_two to onnx file :  [saved_model_link](https://github.com/Siri-KA/half_plus_two_saved_model).
Tried using opset value as 10 and 11. But the issue is same as above.
tensorflow==1.4.
onnx==1.5.0
onnxruntime==1.2.1
tf2version==1.5.5

**Comment by jignparm** [comment]
ParseExample() is an I/O operator -- generally there are no equivalent ONNX operators, and hence TF2ONNX doesn't support it.

**Comment by guschmue** [comment]
and onnx would not know the tf.example records proto. I belief most models would not use those for inference and instead add an interface with placeholders to the saved-model.
To make this would you could write a little tool that creates a graph, adds a placeholder with the same name as the ParseExample and the same outputs/dtypes/shapes than load the saved-model into the same graph OR maybe cleaner load the saved model and add a new interface to the saved-model that uses placeholders (for that you'd need the model source code I think).
Maybe not 100% what you need but similar there is an example for 1. here:
https://github.com/mlperf/training/pull/349/files
and for 2 here:
https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/BertTutorial.ipynb

**Comment by guschmue** [comment]
Don't think we can support ParseExample in onnx.
