### ISSUE TITLE
tf.cumsum and tf.cumprod not supported

### ISSUE THREAD

**Issue by danperazzo** [onnx/tensorflow-onnx#826]
Hello. When trying to convert the models to onnx, I got the following errors that tf.math.cumprod and tf.math.cumsum were not supported. What can I do?

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): WIndows 10
- Tensorflow Version: 1.15
- Python version: 3.6

**Comment by guschmue** [comment]
cumsum should be support if you use ```--opset 11```.
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/math.py#L503

cumprod is not because there is no onnx equivalent and it would take some time to get this op added to onnx.

**Comment by danperazzo** [comment]
Ok, thanks @guschmue !!

**Comment by savvaki** [comment]
Will there simply never be support for `tf.math.cumprod`?

**Comment by andife** [comment]
For the sake of interest, I would like to know which popular models (papers?) contain cumprod operators?
