### ISSUE TITLE
tf.linalg.inv conversion not supported 

### ISSUE THREAD

**Issue by danperazzo** [onnx/tensorflow-onnx#827]
Hello. When trying to convert the models to onnx, I got the error that tf.linalg.inv is not supported. I tried to change to tf.matrix_inverse to no avail. What can I do?

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): WIndows 10
Tensorflow Version: 1.15
Python version: 3.6

**Comment by danperazzo** [comment]
Ok, thanks @RandySheriffH !

**Comment by RandySheriffH** [comment]
Let's wait for next release of onnx which contains the op -https://github.com/onnx/onnx/blob/master/docs/Operators.md#inverse
Will add support thereby.

**Comment by RandySheriffH** [comment]
now we have it in https://github.com/onnx/tensorflow-onnx/pull/903

**Comment by ahyangyi** [comment]
Well, inverse did not actually make it.

https://github.com/onnx/onnx/pull/2747

I think this issue should be reopened as well.
