### ISSUE TITLE
Tensorflow 1.4 trained model conversion onnx error

### ISSUE THREAD

**Issue by GreenShadeZhang** [onnx/tensorflow-onnx#829]
My environment is python3.5 win10, using the branch tensorflow-onnx branch is 1.4, when I use freeze_ Graph freezes meta files to .pb files, and then uses the command line for model conversion when the following error slots, but I use the official example is no problem, is there a problem with my model transformation parameters, or is the tool has environmental requirements, I am a .net developer, so I am very confused about these issues.
Official command line:
python -m tf2onnx.convert --input tests/models/fc-layers/frozen.pb --inputs X:0 --outputs output:0 --output tests/models/fc-layers/model.onnx --verbose
My own command line:
python -m tf2onnx.convert --input tests/models/fc-layers/cpm_hand_frozen.pb --inputs input_placeholer:0 --outputs stage_3/mid_conv7/BiasAdd:0 --output tests/models/fc-layers/model.onnx --verbose
References to the project
https://github.com/timctho/convolutional-pose-machines-tensorflow
is the pb file generated by this project.

My environment is python3.5 win10 tensorflow1.4

Error message
  File "C:\Users\Gil_Z\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\core3.0\tensorflow-python\tensorflow-onnx\tf2onnx\convert.py", line 135, in <module>
    main()
  File "D:\core3.0\tensorflow-python\tensorflow-onnx\tf2onnx\convert.py", line 103, in main
    graph_def = tf_optimize(inputs, outputs, graph_def, args.fold_const)
  File "D:\core3.0\tensorflow-python\tensorflow-onnx\tf2onnx\tfonnx.py", line 2440, in tf_optimize
    graph_def = TransformGraph(graph_def, inputs, outputs, transforms)
  File "C:\Users\Gil_Z\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\tools\graph_transforms\__init__.py", line 51, in TransformGraph
    transforms_string, status)
  File "C:\Users\Gil_Z\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Couldn't interpret input as a GraphDef

**Comment by guschmue** [comment]
Could you try with a newer tensorflow version (tf-1.14 is pretty old) ?
```
python -m tf2onnx.convert --checkpoint cpm/cpm_hand.meta --inputs input_placeholer:0 --outputs stage_3/mid_conv7/BiasAdd:0 --output /tmp/cpm.onnx --opset 11
```
works for me on tensorflow-1.14 and ```pip install tf2onnx -U```

**Comment by GreenShadeZhang** [comment]
> Could you try with a newer tensorflow version (tf-1.4 is pretty old) ?
> 
> ```
> python -m tf2onnx.convert --checkpoint cpm/cpm_hand.meta --inputs input_placeholer:0 --outputs stage_3/mid_conv7/BiasAdd:0 --output /tmp/cpm.onnx --opset 11
> ```
> 
> works for me on tf-1.14 and `pip install tf2onnx -U`

Thank you for your help.

Model conversion is successful when I do what you say, but when I load the model in the uwp project, it will be reported Failed to load model with error: Unknown model file format version.

When I used WinML Dashboard to view the model, I didn't know if it was a problem with the model version or if the model conversion itself failed, and when I used the WinML Code Generator tool provided by [Windows-Machine-Learning](https://github.com/microsoft/Windows-Machine-Learning), Loading the model will report the above error.

So is Windows-Machine-Learning demanding a version of onnx? Or the conversion process causes the model's data corruption. Maybe I shouldn't ask this question here, but I hope you all give me some advice.

**Comment by guschmue** [comment]
I think window is currently supports onnx opset 8 (or maybe 9) so if you convert the model with ```--opset 8``` it should work (hoping that the model does not need ops that came in after opset 8).

**Comment by GreenShadeZhang** [comment]
When I look at the differences in the model with the WinML Dashboard tool, the format version of the onnx in the uwp example is ONNX v3, and when I build it in your method, I set the opset to 7 and the format version of the example is the SAME, but the format version of the generated onnx is ONNX v6, Maybe the problem is in this format version.

**Comment by guschmue** [comment]
Hm, this might be the IR version of onnx that is written into the protobuf based on the onnx version install. You could try ```pip install onnx==1.3``` before converting the model.

**Comment by GreenShadeZhang** [comment]
Thank you for your help I installed the model after the onnx 1.4 conversion load is OK, but putting it in the uwp project creates a new problem, the problem is that the code input type generated by mlgen seems to be Tensor, But most of the input types of c seem to be ImageFeatureValue types, so maybe the python project I'm referring to isn't right, I'm not very good at machine vision, so I'm going to give up the way to use the conversion model to do hand object recognition, it's hard, thank you for your help.
## [How to convert SoftwareBitmap to TensorFloat ](https://github.com/microsoft/Windows-Machine-Learning/issues/257)
