### ISSUE TITLE
ValueError: NodeDef mentions attr 'half_pixel_centers' not in Op<name=ResizeBilinear; signature=images:T, size:int32 -> resized_images:float; attr=T:type,allowed=[DT_INT8, DT_UINT8, DT_INT16, DT_UINT16, DT_INT32, DT_INT64, DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE]; attr=align_corners:bool,default=false>; NodeDef: {{node Preprocessor/map/while/ResizeToRange/cond/resize/ResizeBilinear}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

### ISSUE THREAD

**Issue by Dhanashri-Dhanashri** [onnx/tensorflow-onnx#833]
I have used Faster RCNN inception v2 model and obtained the frozen graph along with checkpoints and meta files.
When trying to convert it to .onnx file got this error! 
The metadata is similar to that of ssd-mobilenet as given in this repository..

**Comment by RandySheriffH** [comment]
@Dhanashri-Dhanashri: would u mind share your frozen pb with a link like it is in:
https://github.com/onnx/tensorflow-onnx/issues/812
Further please paste the command you used for conversion and full stack of exceptions reported.

**Comment by jignparm** [comment]
Closing out due to lack of details. Please reopen if needed.
