### ISSUE TITLE
source distribution (sdist) in PyPI

### ISSUE THREAD

**Issue by vshobha** [onnx/tensorflow-onnx#841]
Hi. We would like to use tf2onnx in our project CrypTen. Would it be possible to provide the source distribution in PyPI? Currently, it looks like only the binary wheel is provided in PyPI. Having the source available in PyPI would be of great help to us. Thank you very much!

**Comment by guschmue** [comment]
yes, I think we can do.

**Comment by vshobha** [comment]
@guschmue thank you very much! It looks also like the version in PyPI is 1.5.5, would it be possible to update that to 1.6.0? Using the version of 1.5.5 in PyPI leads to an error when importing the package.

**Comment by guschmue** [comment]
Sorry, there is some resistance internally since all of our packages are wheels. 
If the wheel doesn't work for you, maybe we can do something to make it work for you.

**Comment by guschmue** [comment]
I assume this is no longer an issue.
