### ISSUE TITLE
SSDMobilenet2ONNX Tutorial 

### ISSUE THREAD

**Issue by rmccorm4** [onnx/tensorflow-onnx#842]
Hi @guschmue ,

Was just glancing at https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/ConvertingSSDMobilenetToONNX.ipynb, and had a quick question.

I noticed these lines in the first cell:
```python
# force tf2onnx to cpu
os.environ['CUDA_VISIBLE_DEVICES'] = "0"
```

This line `os.environ['CUDA_VISIBLE_DEVICES'] = "0"` is actually specifying that CUDA applications will see/use only the first (zero-indexed) GPU on the system if any.

So the comment above that line is a bit misleading, and actually incorrect if you're expecting the CPU vs. GPU conversion to have different results, such as in this issue: https://github.com/onnx/tensorflow-onnx/issues/801#issuecomment-597939177

Just wanted to point it out to avoid misleading people, unless I'm mistaken. 🙂

**Comment by guschmue** [comment]
oh, good catch! I wanted it to be "" and will fix it  shortly.
For this specific tutorial it should not break something I think.

**Comment by guschmue** [comment]
should be fixed in master.

**Comment by rmccorm4** [comment]
Hi @guschmue , 

I see it's fixed in the efficientnet-lite tutorial, but still seems the same for the SSDMobilenet tutorial on master, that I originally brought up. 

Looks like the latest commit for that tutorial was a no-op (just removed a new-line).

**Comment by guschmue** [comment]
Oh, sorry - I messed up. Let me try again.
