### ISSUE TITLE
Onnx model does not inference

### ISSUE THREAD

**Issue by solarflarefx** [onnx/tensorflow-onnx#846]
**Describe the bug**
I have created an ONNX model from a frozen graph in TensorFlow. As a test I have run inference on this model by loading the pb file in python and tensorflow. This works fine but when I try to feed the same input to the onnx model, I get an error:

Message=run(): incompatible function arguments. The following argument types are supported:
1. (self: onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession, arg0: List[str], arg1: Dict[str, object], arg2: onnxruntime.capi.onnxruntime_pybind11_state.RunOptions) -> List[object]

Invoked with: <onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession object

**System information**
- OS Platform: Windows 10
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version: 1.2.0
- Python version: 3.7
- Visual Studio version (if applicable): 2019
- CUDA/cuDNN version: 10.1
- Tool to convert pb to onnx: tf2onnx 1.5.5
- Version of onnx: 1.6.0
- Version of TensorFlow: 1.14.0, gpu version

**To Reproduce**
I converted the model by using this link as a reference for converting my own model: https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/ConvertingSSDMobilenetToONNX.ipynb

I was able to generate an onnx model for my own pb file, but when I run the sess.run command, I get the error that I have written above.

**Additional context**
Note that I was successfully able to run the following examples: https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/ConvertingSSDMobilenetToONNX.ipynb , https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/efficientnet-edge.ipynb

As an additional point of reference, I tried running the SSDMobileNet using both the .pb file as well as the .onnx and it looks like both versions run fine and detect properly.

However I could not get my model to inference properly using the onnx model file.

I am wondering if this has anything to do with versions of everything matching properly: tensorflow, onnx, tf2onnx, onnxruntime.

I also used opset 11 for my export command.  Is there a guideline for which opset should be used?  My understanding is that you can use the latest opset if the runtime environment supports it.  Onnx Runtime 1.2.0 supports opset 11.

I tried experimenting by exporting using opsets 7 - 11, but this does not work.

**Additional Questions**
- Is there a good way to determine whether the issue is related to how I am exporting the onnx versus something related to my runtime environment?
- What is the fundamental difference between a frozen graph .pb file and .onnx model?

**Comment by jignparm** [comment]
This issue seems a duplicate of https://github.com/microsoft/onnxruntime/issues/3229.

* Can you share your model file (e.g. attach to this issue)?

* Can you share your python inference script? From the error message, the suspicion is that the arguments are not passed correctly into the session.run() method.

**Comment by solarflarefx** [comment]
Hello,

Attached are both the frozen graph model (.pb) as well as the onnx model.

[Mnist_model.zip](https://github.com/onnx/tensorflow-onnx/files/4341285/Mnist_model.zip)

Here is the code for the pb file inferencing:
`
	import numpy as np
	import math
	from MnistImageLoader import load_images,ReShapeData
	import tensorflow as tf

	#The following variables should be set to the folder where MNIST images have been extracted 
	mnist_test_path="E:\\MNISTpng-master\\datasets\\testing\\*\\*.png"
	nb_classes = 10 #we have these many digits in our training

	#Load test images
	print("Loading testing images")
	(test_data, test_target)=load_images(mnist_test_path)
	(test_data1,test_target1)=ReShapeData(test_data,test_target,nb_classes)
	print('Shape:', test_data1.shape)
	print(test_data1.shape[0], ' test images were loaded')
	print("Load complete")

	serialized_model = "E:/DLModels/Mnist_model.pb"

	graph_def = tf.compat.v1.GraphDef()

	# Import the TF graph
	with tf.io.gfile.GFile(serialized_model, 'rb') as f:
		graph_def.ParseFromString(f.read())
		tf.import_graph_def(graph_def, name='')
		graph_def = tf.GraphDef()
		graph_def.ParseFromString(f.read())

	# map input and output layers
	input_node = 'conv1_input:0'
	output_node = 'activation_4/Softmax:0'

	#Perform inference
	with tf.compat.v1.Session() as sess:
		for i in range(0,len(test_data1)):
			input_tensor = test_data[i]
			input_tensor = np.expand_dims(input_tensor, axis=0)
			input_tensor = np.expand_dims(input_tensor, axis=3)
			predictions, = sess.run(output_node, {input_node: input_tensor })
			print(predictions)

	print('Done!')
`

Here is the equivalent code for the onnx inferencing:
`
	import numpy as np
	import math
	from MnistImageLoader import load_images,ReShapeData
	import onnxruntime as rt

	#The following variables should be set to the folder where MNIST images have been extracted 
	mnist_test_path="E:\\MNISTpng-master\\datasets\\testing\\*\\*.png"
	nb_classes = 10 #we have these many digits in our training

	#Load test images
	print("Loading testing images")
	(test_data, test_target)=load_images(mnist_test_path)
	(test_data1,test_target1)=ReShapeData(test_data,test_target,nb_classes)
	print('Shape:', test_data1.shape)
	print(test_data1.shape[0], ' test images were loaded')
	print("Load complete")

	# load model
	serialized_model = "E:/DLModels/Mnist_model.onnx"
	sess = rt.InferenceSession(serialized_model)

	# map input and output layers
	input_node = 'conv1_input:0'
	output_node = 'activation_4/Softmax:0'

	#Perform inference
	for i in range(0,len(test_data1)):
		input_tensor = test_data[i]
		input_tensor = np.expand_dims(input_tensor, axis=0)
		input_tensor = np.expand_dims(input_tensor, axis=3)
		predictions, = sess.run(output_node, {input_node: input_tensor})
		print(predictions)

	print('Done!')

`

Both refer to functions in MNistLoader.py:
`
	import numpy as np
	import glob
	import cv2
	from keras.utils import np_utils
	import os.path

	#
	#Load an image using the specified path. opencv needed
	#Do not resize
	#
	def get_im(path):
		# Load as grayscale
		img = cv2.imread(path, 0)
		return img;
		# Reduce size
		#resized = cv2.resize(img, (128, 96))
		#return resized
	#
	#Load images and labels. Returns a tuple of image data,label
	#
	def load_images(path_in):
			filenames = glob.glob(path_in)
			images=[] 
			labels=[] #labels for each training file
			filenames = glob.glob(path_in)
			for filename in filenames:
					#get the parent folder from the full path of the file /mnist/blah/training/3/34348.png
					fulldir=os.path.dirname(filename)
					parentfolder=os.path.basename(fulldir)
					imagelabel=int(parentfolder)
					labels.append(imagelabel)
					img = get_im(filename)
					images.append(img)
					# if ("\\2\\" in filename):
					#         labels.append(0)			
					#         img = get_im(filename)
					#         images.append(img)          
					# elif ("\\3\\" in filename):
					#         labels.append(1)
					#         img = get_im(filename)
					#         images.append(img)
			return images,labels

	#
	#The output from load_images() is further refined
	#
	def ReShapeData(data,target,numclasses):
			data_out = np.array(data, dtype=np.uint8)
			target_out = np.array(target, dtype=np.uint8)
			data_out = data_out.reshape(data_out.shape[0],  28,28)
			data_out = data_out[:, :, :, np.newaxis]
			data_out = data_out.astype('float32')
			data_out /= 255
			target_out = np_utils.to_categorical(target_out, numclasses)
			return data_out,target_out
`

Note that I have adapted this from an example I have found online for better understanding of frozen graph inferencing.

The code for the pb inferencing works fine but the onnx equivalent inferencing code does not work properly.

**Comment by jignparm** [comment]
@solarflarefx , please see the code example below, which works fine to load your model and produce probabilities of 10 classes.

Feel free to close this issue.

###log
```
$ cat ort_load_model.py
import sys
import onnx
import onnxruntime as rt
import numpy as np
myfile = sys.argv[1]

sess = rt.InferenceSession(myfile)
input_name = sess.get_inputs()[0].name
output_name = sess.get_outputs()[0].name
scores = sess.run([output_name], {input_name: np.random.random((1,28,28,1)).astype(np.float32)})[0]
print (scores[0])


$ python ort_load_model.py Mnist_model.onnx
[4.25312319e-05 3.26818408e-04 4.42015764e-04 2.62277611e-02
 3.19961682e-02 2.90869642e-03 7.56456575e-06 1.19115185e-07
 9.37749505e-01 2.98845756e-04]
```

**Comment by solarflarefx** [comment]
Thank you very much!

**Comment by tm-topnet** [comment]
Hi, i need to make an inference on 2 inputs image.
something like that:
val = sess.run(["output"], [{"image_input": image_},{"template_input": template_}],)[0]

but i receive this error:

TypeError: run(): incompatible function arguments. The following argument types are supported:
    1. (self: onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession, arg0: List[str], arg1: Dict[str, object], arg2: onnxruntime.capi.onnxruntime_pybind11_state.RunOptions) -> List[object]

**Comment by yechong316** [comment]
> Hi, i need to make an inference on 2 inputs image. something like that: val = sess.run(["output"], [{"image_input": image_},{"template_input": template_}],)[0]
> 
> but i receive this error:
> 
> TypeError: run(): incompatible function arguments. The following argument types are supported: 1. (self: onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession, arg0: List[str], arg1: Dict[str, object], arg2: onnxruntime.capi.onnxruntime_pybind11_state.RunOptions) -> List[object]

well, I also receive this error, is anything can helpe me ?
