### ISSUE TITLE
Onehot operator in opset 9 version supports datatypes other than int

### ISSUE THREAD

**Issue by Dev1158** [onnx/tensorflow-onnx#852]
From the onnx documentation, it is observed that the onehot operator in opset version 9 supports datatypes other than int.
https://github.com/onnx/onnx/blob/master/docs/Changelog.md#onehot-9
But the handler is checking for the constraint whether output dtype is int, If not it rolls back to opset version 1.
https://github.com/onnx/tensorflow-onnx/blob/fdabeea6600f5c793a439ae54d138e7d325b5bf2/tf2onnx/onnx_opset/tensor.py#L1110

**Comment by guschmue** [comment]
yes, we miss the added type support easily because we forget that we worked around it in the past.
Same for the Slice op for opset > 10.

**Comment by RandySheriffH** [comment]
@Dev1158: would u mind share me your model via a google drive public link and command used for conversion please?

**Comment by guschmue** [comment]
I looked a little at the code:
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/onnx_opset/tensor.py#L1109
```
if ctx.is_target(constants.TARGET_RS6) \
                and output_dtype not in [onnx_pb.TensorProto.INT64, onnx_pb.TensorProto.INT32]:
            logger.warning("unsupported dtype in onnxruntime, onehot-9 can't be used directly")
            cls.version_1(ctx, node, **kwargs)
            return
```
Basically this gets executed only when you call the converter with ```--target rs6``` which worked around issues for the very early onnx support in windows because the runtime did not support those types.

I don't think this is a real issue. Or are you hitting this ?

**Comment by Dev1158** [comment]
I am hitting this case.

**Comment by guschmue** [comment]
but you'd need to pass ```--target rs6``` to get there which is a very old thing.
It should not be needed anymore, unless you use a 2 year old windows release.

**Comment by Dev1158** [comment]
I didn't mention any target specifically for conversion. Is there something
that is set by default?

**Comment by guschmue** [comment]
you'd need to explicitly set ```--target rs6``` in the command line which was only needed in very rare cases. Do you see this warning message that we print for this case ?

**Comment by Dev1158** [comment]
I didn't mention the target in the command line but I see the warning message that it is being rolled back to opset 1.

**Comment by guschmue** [comment]
Hm, don't know how we could get there. Our unit tests of course would trigger that path but not the normal model conversion.

**Comment by Dev1158** [comment]
I was using older version and was hitting the issue. Thanks.
