### ISSUE TITLE
Request for NonMaxSuppressionV5 support

### ISSUE THREAD

**Issue by jf99** [onnx/tensorflow-onnx#859]
While trying to convert a tensorflow frozen graph to ONNX, I got an error message that NMS V5 is not supported by tf2onnx:
> 2020-03-23 11:13:41,012 - ERROR - Tensorflow op [Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/non_max_suppression_with_scores/NonMaxSuppressionV5: NonMaxSuppressionV5] is not supported
2020-03-23 11:13:41,058 - ERROR - Unsupported ops: Counter({'NonMaxSuppressionV5': 1})

According to [Troubleshooting](https://github.com/onnx/tensorflow-onnx/blob/master/Troubleshooting.md) one should create an issue or PR in such a case. Since I lack of resources and python skill to do a PR, I chose to open this issue. Would be nice if you implemented NMS V5 conversion :-).

**Comment by guschmue** [comment]
Yes, we need to add  V5. Looking briefly at it - looks like soft_nms_sigma soft_nms_sigma have been added. soft_nms_sigma might need an onnx change.
How do you call tf.image.non_max_suppression*() ?

**Comment by hashishoya** [comment]
Hi @guschmue, I'm a colleague of @jf99 and we used Tensorflow Object Detection API for the training of the network. In our case, we just tried first to convert the pretrained [ssd_inception_v2_coco](http://download.tensorflow.org/models/object_detection/ssd_inception_v2_coco_2018_01_28.tar.gz) model to ONNX so we can use it later with TensorRT .. 

So I'm not sure how tf.image.non_max_suppression was used in their pre-trained model ..

**Comment by guschmue** [comment]
no worry, @RandySheriffH has a PR to support V4 and V5 as long soft_nms is not used. Hope with get away with it for now.

**Comment by RandySheriffH** [comment]
Fix merged to master, feel free to come to us for further assistance.
