### ISSUE TITLE
tf2onnx not support pad (opset 11) ？

### ISSUE THREAD

**Issue by zjd1988** [onnx/tensorflow-onnx#875]

**Comment by jignparm** [comment]
Pad is implemented below. What's the original issue? Is a particularly model failing?

https://github.com/onnx/tensorflow-onnx/blob/d91315c452d6cee71edc2a125d368717b8ccd85a/tf2onnx/onnx_opset/nn.py#L454

**Comment by zjd1988** [comment]
@jignparm appreciate it.It's my fault, I checked my command and find that --opset was set 10.
