### ISSUE TITLE
non-4D tensor or non-const pads require opset 11

### ISSUE THREAD

**Issue by carlosgalvezp** [onnx/tensorflow-onnx#887]
Hi!

I'm getting the following error trying to convert my Tensorflow model using opset 10:

```
2020-04-16 13:44:19,193 - ERROR - Failed to convert node node/conv/SpaceToBatchND
OP=SpaceToDepth
Name=node/conv/SpaceToBatchND
Inputs:
	node/ReLU/Relu:0=Relu, [1, 32, 76, 120], 1
	node/conv/SpaceToBatchND/block_shape:0=Const, [3], 6
	node/conv/SpaceToBatchND/paddings:0=Const, [3, 2], 6
Outpus:
	node/conv/SpaceToBatchND:0=[256, 32, 7, 10], 1
Traceback (most recent call last):
  File "/opt/tensorflow-onnx/tf2onnx/tfonnx.py", line 266, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/opt/tensorflow-onnx/tf2onnx/onnx_opset/tensor.py", line 1370, in version_1
    utils.make_sure(ctx.opset >= 11, 'non-4D tensor or non-const pads require opset 11')
  File "/opt/tensorflow-onnx/tf2onnx/utils.py", line 193, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: non-4D tensor or non-const pads require opset 11
```
The error happens in a Conv2D layer.

Using opset 11 fixes the issue, but other libraries that depend on ONNX (TRT) don't fully support it in the latest official releases, so I'd gladly use opset 10 if I can.

From the message, I can see that the input and output tensors are 4D, and the block_shape and paddings are Const. So what is the problem?

Thanks!

**Comment by jignparm** [comment]
@carlosgalvezp , how about the block_shape? Is it square N x N or rectangular  N x M? 

The error message lists the common  conditions for requiring opset 11, but there are other conditions as well -- i.e. if the block_shape is not a square, it requires opset 11.

**Comment by carlosgalvezp** [comment]
@jignparm That was it! The block_shape seems to be: [1, 16, 16]. 

When we call `Conv2D` in TensorFlow we pass `dilation_rate=(16,16)`, so I guess that's where it comes from. 

Now I wonder if the problem is in TensorFlow (it should produce a 2D block_shape instead of 3D) or if this is a standard thing and TF-ONNX should be able to deal with it. If it weren't for the first "1" the block shape would be just fine.

Anyway, I think the current error is a bit confusing so it could be good to add the information about the extra condition that is being tested (len(block_shape) == 2 and (block_shape[0] == block_shape[1]).

**Comment by jignparm** [comment]
> Now I wonder if the problem is in TensorFlow (it should produce a 2D block_shape instead of 3D) or if this is a standard thing and TF-ONNX should be able to deal with 

BTW, the block_shape is allowed to be greater than 2D.  So the 3D block_shape above is acceptable and tf2onnx will handle it, but it simply requires opset 11 to do so.

I  mentioned rectangular N x M above as a extra condition for requiring opset 11 -- so a 2D block_shape will work for lower opsets (< 11), provided it's square, but a non-square 2D block_shape (or higher dimensional block_shape) requires opset 11.

There are quite a few conditions to check, and the error message could be updated to outline all of them. Another option is to remove the details in the error message and simply throw  the message "Require opset 11" -- this gives minimal detail for debugging,  but may save user time in long run.

**Comment by carlosgalvezp** [comment]
Sounds good, thanks a lot for the explanation and the patience!

I'll continue investigating on the TRT side to see how to get things to work.
