### ISSUE TITLE
NonMaxSuppression with opset 11

### ISSUE THREAD

**Issue by rgc183** [onnx/tensorflow-onnx#889]
**System information**
- Ubuntu 18.04
- Tensorflow Version: 1.13
- Python version: 3.6
- Onnx converter: latest

I am trying to convert Tensorflow model to onnx. But I am getting error:

`
 ERROR - Tensorflow op [BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/NonMaxSuppression: NonMaxSuppression] is not supported
ERROR - Tensorflow op [SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/NonMaxSuppression_2: NonMaxSuppression] is not supported
 ERROR - Tensorflow op [SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/NonMaxSuppression_1: NonMaxSuppression] is not supported
ERROR - Tensorflow op [SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/NonMaxSuppression: NonMaxSuppression] is not supported
ERROR - Unsupported ops: Counter({'NonMaxSuppression': 4})
`
I am using opset 11.

**Comment by guschmue** [comment]
We are supporting NonMaxSuppressionV2 and newer. Not seen NonMaxSuppression but this must be generated by a really old tensorflow version.
is this a public model ?

**Comment by rgc183** [comment]
I think I can just upgrade my model to use NonMaxSuppressionV2 in the case. Thanks.
