### ISSUE TITLE
about input dtype

### ISSUE THREAD

**Issue by sezarxray** [onnx/tensorflow-onnx#893]
dear sir,
I tried to convert my model  tensorflow->onnx->tensorrt
but tensorrt said your input has default type uint8 (no support)!
(model is sth like input-0(uint8) >>> cast(float32) )
is there a way to change model input from uint8 to int32 in onnx model?
regards.

**Comment by jignparm** [comment]
You can edit the Onnx model manually to alter the input type.

See the code at link below for a similar example -- it's altering the shape of the input, but you can extend the logic to alter the type as well.

https://github.com/microsoft/onnxruntime/issues/2264
