### ISSUE TITLE
UnboundLocalError: local variable 'concrete_func' referenced before assignment

### ISSUE THREAD

**Issue by aksenventwo** [onnx/tensorflow-onnx#896]
Hello,

**Describe the bug**
I use this model https://tfhub.dev/google/imagenet/mobilenet_v1_050_160/classification/4

```
python -m tf2onnx.convert --saved-model Z:\model_tf2\4 --output Z:\model_tf2\4\model.onnx
```

Error:

```
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\admin\appdata\local\programs\python\python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "Z:\admin\tensorflow-onnx\tf2onnx\convert.py", line 169, in <module>
    main()
  File "Z:\admin\tensorflow-onnx\tf2onnx\convert.py", line 130, in main
    args.saved_model, args.inputs, args.outputs, args.signature_def)
  File "Z:\admin\tensorflow-onnx\tf2onnx\tf_loader.py", line 240, in from_saved_model
    _from_saved_model_v2(model_path, input_names, output_names, signatures)
  File "Z:\admin\tensorflow-onnx\tf2onnx\tf_loader.py", line 229, in _from_saved_model_v2
    frozen_graph = from_function(concrete_func, input_names, output_names)
UnboundLocalError: local variable 'concrete_func' referenced before assignment
```

**System information**
- WIN10:
- Tensorflow 2.1.0:
- Python version 3.6:

**Comment by aksenventwo** [comment]
I tried many of the models in [tfhub](https://tfhub.dev/s?module-type=image-augmentation,image-classification,image-feature-vector,image-generator,image-object-detection,image-others,image-style-transfer,image-rnn-agent&tf-version=tf2), and they reported the same problem

**Comment by aksenventwo** [comment]
Hi @jignparm , I tried it, but still reported this error, I further determined that it was because imported.signatures.keys () returned empty `KeysView(_SignatureMap({}))`, Is this because of tfhub's model preservation or other issues?

**Comment by jignparm** [comment]
TFHub seems to be formatting these saved_models in an unusual way -- need to figure out how to load these models in TF and extract the inputs/outputs successfully (even though SignatureMap is empty).

**Comment by guschmue** [comment]
This model does not have an interface exported so you need to do something like:
```
import tensorflow as tf
import tensorflow_hub as hub

m = tf.keras.Sequential([
        hub.KerasLayer("https://tfhub.dev/google/imagenet/mobilenet_v1_050_160/classification/4")
])
m.build([None, 160, 160, 3])  # Batch input shape.
x = tf.random.normal((1, 160, 160, 3))
y = m.predict(x)
m.save("/tmp/test")
```
With that it still has issues I gave that a try but there are still issues and documentation around this is a little sparse.

**Comment by guschmue** [comment]
This is a sub-classed model and according to this: 
https://colab.research.google.com/drive/172D4jishSgE3N7AO6U2OKAA_0wNnrMOq#scrollTo=xXgtNRCSyuIW
it is a bit tricky to save those.
Knowing that you can't save those you can create a graph from the model, save that and pass it to tf2onnx.
Or you can create a graph in memory and use the tf2onnx python api to covert it with the code below.
```
import tensorflow as tf
import tensorflow.keras as keras
import tensorflow_hub as hub
from tensorflow.python.keras.saving import saving_utils as _saving_utils
import tf2onnx

m = tf.keras.Sequential([
    keras.layers.Input(shape=[160, 160, 3]),
    hub.KerasLayer("https://tfhub.dev/google/imagenet/mobilenet_v1_050_160/classification/4")
])
m.build([None, 160, 160, 3])  # Batch input shape.
x = tf.random.normal((1, 160, 160, 3))
y = m.predict(x)
print(y.shape)
print(m.summary())

function = _saving_utils.trace_model_call(m)
concrete_func = function.get_concrete_function()
input_names = [input_tensor.name for input_tensor in concrete_func.inputs
               if input_tensor.dtype != tf.dtypes.resource]
output_names = [output_tensor.name for output_tensor in concrete_func.outputs
                if output_tensor.dtype != tf.dtypes.resource]

frozen_graph = tf2onnx.tf_loader.from_function(concrete_func, input_names, output_names)
with tf.Graph().as_default() as tf_graph:
    tf.import_graph_def(frozen_graph, name='')

g = tf2onnx.tfonnx.process_tf_graph(tf_graph, opset=11, input_names=input_names, output_names=output_names)
onnx_graph = tf2onnx.optimizer.optimize_graph(g)
model_proto = onnx_graph.make_model("converted from {}".format("/tmp/test.onnx"))
```
Pretty painful. We can see if we can simplify this my adding a new method to tf2onnx that does this for you.

**Comment by aksenventwo** [comment]
Thank you very much for trying! This solves my current problem. For me, if tf2onnx can directly parse similar tfhub models, it is really good. If not, it is also acceptable to perform a model conversion by the method you give. I think you or i can close this issue?

**Comment by guschmue** [comment]
Ok, assuming more people will run into this we can add a method convert_to_onnx(model) where model can be any model and do the things above internally. 
I will close the issue one we have this.

**Comment by jignparm** [comment]
@aksenventwo, @guschmue 

Using PR #984. I was able to convert the sub-classed TF2.x model (mobilenet_v1_050_160)  successfully, using the new `--concrete_function` parameter below.

The model contains 4 different concrete functions, so it requires the user to know which of the 4 should be converted for inference purposes, but it should be a good alternative to writing custom scripts.

As a caveat, the `--concrete_function` parameter should be considered experimental at this time.

```python
$ python -m tf2onnx.convert --saved-model .  --tag serve --concrete_function 3 --output converted.onnx
...
2020-06-24 12:35:48,508 - INFO - Using tensorflow=2.2.0, onnx=1.7.0, tf2onnx=1.7.0/aafc83
2020-06-24 12:35:48,508 - INFO - Using opset <onnx, 11>
2020-06-24 12:35:50,514 - INFO - Optimizing ONNX model
2020-06-24 12:35:51,839 - INFO - After optimization: BatchNormalization -27 (27->0), Const -147 (207->60), Identity -51 (51->0), Reshape -13 (13->0), Transpose -122 (123->1)
2020-06-24 12:35:51,855 - INFO -
2020-06-24 12:35:51,855 - INFO - Successfully converted TensorFlow model . to ONNX
2020-06-24 12:35:51,861 - INFO - ONNX model is saved at converted.onnx
```

![image](https://user-images.githubusercontent.com/13698702/85557782-a2335e80-b617-11ea-812d-22d0aea1234c.png)

**Comment by guschmue** [comment]
this should be fixed. You can also use our new python api which will make this a little easier.
https://github.com/onnx/tensorflow-onnx#from_keras-tf-20-and-newer
