### ISSUE TITLE
inference：YoloV3 into the onnx model, will the confidence go down? 

### ISSUE THREAD

**Issue by chuqnzhao** [onnx/tensorflow-onnx#901]
I compared the inference between the pb model and the onnx model and tested it by the sheet pictures.Pb model table box effect is better than onnx model:
1、Will onnx model transformation reduce model detection accuracy?
2、If so, what can be done to fix it？

Looking forward to your reply，thanks！

**Comment by jignparm** [comment]
The precision or the model should be comparable to original  TF model -- since the model conversion should be faithful conversion of operators and weights.

If the precision/accuracy of the model does not match TF (within reasonable tolerance) -- that's a bug. Would need to debug to fix it.

**Comment by chuqnzhao** [comment]
> The precision or the model should be comparable to original TF model -- since the model conversion should be faithful conversion of operators and weights.
> 
> If the precision/accuracy of the model does not match TF (within reasonable tolerance) -- that's a bug. Would need to debug to fix it.

thanks for your reply！
