### ISSUE TITLE
Gemm whose C is not unidirectional broadcastable to A * B is generated

### ISSUE THREAD

**Issue by milkpot** [onnx/tensorflow-onnx#902]
**Describe the bug**
The ONNX speficiation states that the input tensor C of the operator Gemm should be unidirectional broadcastable to  A * B. But tf2onnx generates a Gemm whose C is not unidirectional broadcastable to A * B.

**Urgency**
None.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.4 LTS
- Tensorflow Version: 1.15.0
- Python version: 3.6.9

**To Reproduce**
Run the following code:
```
import numpy as np
import tensorflow as tf
import tf2onnx

with tf.Session().as_default() as sess:
    x = tf.placeholder(name='input', shape=(None, 3), dtype=tf.float32)
    w = tf.constant(np.arange(3).reshape(3, 1).astype(np.float32))
    b = tf.constant(np.arange(4).reshape(1, 4).astype(np.float32))
    y = tf.matmul(x, w) + b
    y = tf.identity(y, name='output')

    onnx_graph = tf2onnx.tfonnx.process_tf_graph(sess.graph, input_names=['input:0'], output_names=['output:0'])
    model_proto = onnx_graph.make_model('test')
    with open('model.onnx', 'wb') as f:
        f.write(model_proto.SerializeToString())
```

The generated ONNX model contains a Gemm whose A is N x 3, B is 3 x 1, and C is 1 x 4 (see the screenshot), which violates the specification since the C (1 x 4) is not unidirectional broadcastable to A * B (N x 1).

**Expected behavior**
It should generate a MatMul operator followed by an Add operator.

**Screenshots**
The generated model, visualized by netron:
![a](https://user-images.githubusercontent.com/1009827/80465062-a889bf00-8975-11ea-8b18-139a758acc90.jpg)

**Additional context**
None.

**Comment by jignparm** [comment]
The onnx spec mentions this:

> The shape of A should be (M, K)
> The shape of B should be (K, N) 
>  The shape of C should be unidirectional broadcastable to (M, N).

In your example,  the shapes of A = (M, 3), B = (3, 1), C= (1, 4)

If M is 3, then N = 1.  So the shape (M, N) = (3,1), which is unidirectionally-broadcastable from the shape of C = (1, 4).

The model seems OK -- if the shapes were not compatible, the model would not run. You can verify the GEMM  operator is working by running the model using OnnxRuntime.

**Comment by milkpot** [comment]
> So the shape (M, N) = (3,1), which is unidirectionally-broadcastable from the shape of C = (1, 4).

I think 4 is not broadcastable to 1.

I verified that OnnxRuntime cannot run this model.

Code:
```
import numpy as np
import onnxruntime

model = onnxruntime.InferenceSession('model.onnx')
output = model.run(['output:0'], {'input:0': np.arange(3).reshape(1, 3).astype(np.float32)})
print(output)
```

Result:
```
2020-04-28 20:56:43.948892899 [W:onnxruntime:, graph.cc:73 MergeShapeInfo] Error merging shape info for output. 'output:0' source:{unk__7,1} target:{unk__8,4}. Falling back to lenient merge.
2020-04-28 20:56:43.950490605 [E:onnxruntime:, sequential_executor.cc:183 Execute] Non-zero status code returned while running Gemm node. Name:'Gemm__6' Status Message: Gemm: Invalid bias shape for broadcast
Traceback (most recent call last):
  File "a.py", line 5, in <module>
    output = model.run(['output:0'], {'input:0': np.arange(3).reshape(1, 3).astype(np.float32)})
  File "/home/yuno/study/tf2onnxbug/venv/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 142, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Gemm node. Name:'Gemm__6' Status Message: Gemm: Invalid bias shape for broadcast
```

**Comment by jignparm** [comment]
Sorry, I think you're right.  Uni-directional is stricter than multi-directional --  the source tensor must have same shape value as target, or else 1. 

So C's value of 4 does not work here. Looks like we'll need to split it into 2 operators, like you mentioned above.

> ...tensor B is unidirectional broadcastable to tensor A if one of the following is true:
> *   Tensor A and B all have the same number of dimensions and the length of each dimensions is either a common length or B's length is 1.

**Comment by jignparm** [comment]
Fixed in https://github.com/onnx/tensorflow-onnx/pull/906.

**Comment by jignparm** [comment]
Seems like OnnxRuntime may require a patch as well (to prevent generating a Gemm op dynamically from more basic ops).

Opening related issue: https://github.com/microsoft/onnxruntime/issues/3764

**Comment by jignparm** [comment]
Fixed in onnxruntime as well at https://github.com/microsoft/onnxruntime/pull/3780
