### ISSUE TITLE
OnnxRuntimeError This is an invalid model. Error in Node:dnn/input_from_feature_columns/input_layer/clk_bucketized_embedding/Bucketize : No Op registered for Bucketize with domain_version of 8

### ISSUE THREAD

**Issue by woaixiaojiaa** [onnx/tensorflow-onnx#904]
i have convert tensorlfow model to onnx model, while the option contains --custom_ops, to convert some ops, like bucketized that onnx can deal with it.
but when i load onnx model, that occured the problem.
how do i solve it??

**Comment by woaixiaojiaa** [comment]
when is build with opset 11, that does not work.

**Comment by jignparm** [comment]
Tf2onnx will generate the Onnx model with a default Bucketize op, but to run the model successfully,  each operator has to exist in OnnxRuntime as well.  The error is because the operator does not exist in OnnxRuntime.

You can create a custom Bucketize operator in ORT using this doc   --> https://github.com/microsoft/onnxruntime/blob/master/docs/AddingCustomOp.md

**Comment by woaixiaojiaa** [comment]
ok.thank you, but i have also another question, when i have convert onnx graph successful, the nodes that custom ops have domain "ai.onnx.converters.tensorflow" , that is confused, the domain how to work?

**Comment by jignparm** [comment]
The domain is like a group-id -- when you write the operator in C++, you can compile it to in under any domain (make up your own name, or use an one of the existing domains). As long as the domain of the op in Onnx model matches the domain in the runtime, the runtime will be able to find it and run the operator. 

Feel free to add your custom op to "ai.onnx.converters.tensorflow" or the default domain of the official ops ("ai.onnx"). It should not matter -- as long as the op in the Onnx model you create matches the domain that is hard-coded/compiled in your operator.

There is a bit more documentation here as well : https://github.com/onnx/onnx/blob/master/docs/Versioning.md.

**Comment by woaixiaojiaa** [comment]
ok，thank you！！！

**Comment by jignparm** [comment]
Assume issue is resolved. Reopen if needed.

**Comment by zhaohb** [comment]
@woaixiaojiaa Hello, now I want to implement the Bucketize Op. Have you implemented it already? If so, could you share the code?

thank you very much!
