### ISSUE TITLE
RuntimeError: MetaGraphDef associated with tag-set  could not be found in SavedModel

### ISSUE THREAD

**Issue by WhaSukGO** [onnx/tensorflow-onnx#911]
**Describe the bug**
I'm trying to convert my ```.pb``` file to ```.onnx```, but the command fails with an error, 
```"RuntimeError: MetaGraphDef associated with tag-set  could not be found in SavedModel"```

**How to reproduce**
Create new Colap notebook

```%tensorflow_version 1.x```

```!pip3 install -U tf2onnx```

```!python -m tf2onnx.convert --saved-model "./" --output model.onnx  ```

(I downloaded ssd_mobilenet_v2_coco from [supported TensorFlow models)](https://github.com/onnx/tensorflow-onnx/blob/master/tests/run_pretrained_models.yaml)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- Tensorflow Version: 1.15.2
- Python version: 3.6

**Comment by guschmue** [comment]
ssd_mobilenet_v2_coco.pb is a graphddef format, not a saved-model.
You need to convert it with
```
python -m tf2onnx.convert  --input ssd_mobilenet_v2_coco.pb --output model.onnx --inputs image_tensor:0  --outputs detection_boxes:0,detection_scores:0,num_detections:0,detection_classes:0 --opset 11
```

**Comment by Guneetkaur03** [comment]
@guschmue Earlier I was getting the same error, but on trying the way you mentioned, error got resolved but encountered another error. Can you please help.

ValueError: Node 'cond/ExpandDims' has an _output_shapes attribute inconsistent with the GraphDef for output #0: Shapes must be equal rank, but are 1 and 0
