### ISSUE TITLE
Unsupported ONNX data type: UINT8 (2)

### ISSUE THREAD

**Issue by WhaSukGO** [onnx/tensorflow-onnx#912]
```"Unsupported ONNX data type: UINT8 (2)"```

**Describe the bug**
Is there any way to convert my model to FP16 (or int8) ?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- Tensorflow Version: 1.15.2
- Python version: 3.6

Appreciate any help!

**Comment by guschmue** [comment]
tf2onnx should support both:
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/tf_utils.py#L40
but not all ops in onnx do support those types.
Which model is this ? Can you post the full stack trace ?

**Comment by WhaSukGO** [comment]
Oh, I'm trying to use my converted model (.pb -> .onnx) in TensorRT. However, it doesn't support UINT8.

(Nvidia Jetpack 4.3 is on which my TensorRT 6 is installed)

**Comment by guschmue** [comment]
tf2onnx just maps the tensorflow type to the equivalent onnx type.
Sounds like trt-6 doesn't implement uint8. How about trt-7 ?
Not sure if tf2onnx can do something on it.
Let me check with some trt folk.

**Comment by turowicz** [comment]
@guschmue I'm having a similar issue:

savedmodel -> onnx -> trt

The model is ssd_mobilenet_v2_coco and I get the UINT8 error from trt.

**Comment by guschmue** [comment]
Fyi @kevinch-nv

**Comment by svetlanadataper** [comment]
> @guschmue I'm having a similar issue:
> 
> savedmodel -> onnx -> trt
> 
> The model is ssd_mobilenet_v2_coco and I get the UINT8 error from trt.
> 
> JP44 TensorRT 7.x

Hi!

I am having the same problem...did anyone manage to figure this out?

Thank you

Svetlana

**Comment by NinaAI** [comment]
I'm having same problem: unsupported ONNX data type: UINT8

Anyone knows how to solve the error?

Thanks,
Nina

**Comment by svetlanadataper** [comment]
> I'm having same problem: unsupported ONNX data type: UINT8
> (TensorRT 7.0)
> Anyone knows how to solve the error?
> 
> Thanks,
> Nina

Hi Nina,

It seems like TensorRT supports only certain data types; UNIT8 is not one of them:

https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-700/tensorrt-api/python_api/infer/FoundationalTypes/DataType.html

For our case, we would have to retrain the model with input being a valid data type or convert the model with quantization, but I did not have success with that.

Svetlana

**Comment by NinaAI** [comment]
Hi Svetlana, 

did you try training model with INT8 as input data type?

**Comment by turowicz** [comment]
Good luck training MS COCO on your own.

**Comment by svetlanadataper** [comment]
> Good luck training MS COCO on your own.

I did not train the model as it is a pre-trained model of course... do you have any suggestions around it?

**Comment by turowicz** [comment]
It was a joke, it's impossible without a very big computer.

**Comment by svetlanadataper** [comment]
> It was a joke, it's impossible without a very big computer. People suggesting we retrain the models are having a laugh at us.

No kidding...I understand it was a joke, I meant in performing a conversion post training...anyways thanks

**Comment by Sgomes14843** [comment]
Hi, I am having the same problem, did anyone manage to figure this out?

**Comment by turowicz** [comment]
@svetlanadataper I don't believe this is possible but if you do solve it then please post a solution here.

**Comment by hyperfraise** [comment]
Also very interested. I'm just trying to not have to convert my data to float before passing it  to my tensorrt model by putting a type casting layer in the model (in order to save CPU ressources).

**Comment by alankongfq** [comment]
I also encountered this issue when trying to convert deeplab v3+ model from the tensorflow model zoo to tensorrt.
savedmodel -> onnx has no issued but onnx -> tensorrt raise this error. I tried to put in a custom plugin with input float as dtype following the instructions [here](https://forums.developer.nvidia.com/t/problem-converting-onnx-model-to-tensorrt-engine-for-ssd-mobilenet-v2/139337/16) to circumvent the error but hit another error after adding the plugin where the next node requires uint8 input so I guess the whole graph was built with dtype and not much can be done about it other then doing a round fine tuning from the pretrained weights to get the dtype I need.

After adding custom plugin in .pb and trying to convert using tf2onnx, error encounter:

`Traceback (most recent call last):
  File "/home/alankong/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 497, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node Shape was passed float from ImageTensor:0 incompatible with expected uint8.
`

Not sure if I did something wrong when trying to add the custom plugin.

**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 18.04): Ubuntu 18.04
- Tensorflow Version: 2.3.1
- Python version: 3.6
- CUDA version: 10.2 (symlink cuda 10.1 library to cuda 10.2 as workaround to use tensorflow installed via pip)
- cudnn version: 7.6.5
- TensorRT: 7.1.3.4

**Comment by hoangmt** [comment]
In case uint8 is in the input, you can use the following code to fix the model:
```python
import onnx_graphsurgeon as gs
import onnx
import numpy as np

graph = gs.import_onnx(onnx.load(model+".onnx"))
for inp in graph.inputs:
    inp.dtype = np.float32

onnx.save(gs.export_onnx(graph), "updated_"+model+".onnx")
```
You can do similarly for other nodes, by looping through all nodes in graph.nodes and change dtype to supported type. However, not sure if it will work, just something to try.

**Comment by guschmue** [comment]
I'll close this one since it is not a tf2onnx issue.
