### ISSUE TITLE
ResizeBilinear coordinate_transformation_mode half_pixel

### ISSUE THREAD

**Issue by jeffpyke** [onnx/tensorflow-onnx#914]
**Describe the bug**
ResizeBilinear coordinate transformation mode is not read from the TensorFlow graph. Therefore the ONNX model does not match TensorFlow when v2 ResizeBilinear op is used (half_pixel_centers=True).

https://github.com/onnx/tensorflow-onnx/blob/17e5c398f599d34b01896fad82032773874176b0/tf2onnx/onnx_opset/nn.py#L741

https://github.com/onnx/onnx/blob/master/docs/Operators.md#attributes-66

**Urgency**
medium

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Tensorflow Version: 1.15+
- Python version: 3

**To Reproduce**
Convert a graph with compat.v1 and compat.v2. Only one works (compat.v1).

**Expected behavior**
compat.v1.resize and compat.v2.resize are both supported.

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by jignparm** [comment]
Fixed via https://github.com/onnx/tensorflow-onnx/pull/932.
