### ISSUE TITLE
Cannot add custom attribute to the Onnx nodes

### ISSUE THREAD

**Issue by MaenMallah** [onnx/tensorflow-onnx#915]
Hello,

I am trying to add custom attribute to the ONNX node when converted from tensorflow (or any other actually) 

The problem is that I create a custom implementation of separableConv1D and onnx translates that to 2 conv2d operations with reshape and squeeze operations which is equivalent. However, our goal is to use the ONNX to create a conversion to the HW design which we are writing from scratch. It would be very useful to indicate that this is a separableConv1D operation so certain optimizations can be done. 

Each node has attribute which I guess you can add any name/type/value to them. It would be great to be able to add that this is a conv is in fact separableConv1D and others such as depth multiplier. As far as I can tell, there is no way to do this with the current implementation. I don't know if there is a way around this that allows the use to add extra info the ONNX model. I also could not fine a way to add info to the model level. As a last solution, we can add the topology information to the whole ONNX model that our conversion tool reads and parses it to optimize certain layers. 

Thanks.

**Comment by guschmue** [comment]
Some time there was some talk about the need to annotate nodes with hints but I think this never came to a conclusion. If we'd add a free-style attribute to a node the onnxchecker would not be happy and the checker is used by some runtimes before loading the model. 
Technical it would be easy to add of course.
@ebarsoum, @spandantiwari - any suggestions ?

**Comment by guschmue** [comment]
I wonder - if you know input and out shapes you could see with
```
groups == in_channels and out_channels = K * in_channels
```

**Comment by ebarsoum** [comment]
Can't you wrap it in a Function? Function was designed to address  this issue.

**Comment by MaenMallah** [comment]
@guschmue I saw that functionality of groups in the conversion code. However, my the two generated convolutions (depthwise and pointwise) have groups =1. I am using the backend function: tf.nn.separable_conv2d in TF2.0 to calculate the custom separableConv. I am doing something wrong and can get the conversion to store the info in groups?

**Comment by MaenMallah** [comment]
@ebarsoum You mean TF Functions? I am using tf.nn.separable_conv2d inside the custom layer to calculate the conv.

**Comment by guschmue** [comment]
The function @ebarsoum talks about is an onnx function. I guess it would need to be defined in onnx (say SeparableConv) and the converter would call that function instead of Conv. SeparableConv  would than do what needs to be done to map the separable_conv  to the onnx Conv operator. If your hardware knows how to implement that function directly you'd take over the implementation. Possible I guess but it would need to be in the onnx spec (for example like https://github.com/onnx/onnx/blob/master/docs/Operators.md#Celu), aka it would need to be in the next opset.

For the calc: if you see the Conv in your code and both conditions below are met
groups == in_channels and out_channels = K * in_channels
than this should be a separable_conv and you could call your handling of it. All the variables used should be static I think.

**Comment by MaenMallah** [comment]
@guschmue Thanks for the detailed reply. I think using the attributes fits better here. I have generated another model and checked groups and output_channels (first dimension of the weights) and it works fine.

**Comment by ebarsoum** [comment]
@MaenMallah  why attribute fit better? The problem of custom attributes which has been discussed in the past is standardization and the meaning of those attributes will depends on the runtime.

**Comment by MaenMallah** [comment]
@ebarsoum I meant for what we are planning to do. Our HW team can read the already existing groups attr and synthesis the optimized implementation. However, I also think having the ability to add custom attributes that are ignored by the runtime can be useful. We are using ONNX as a bridge between the NN libraries and HW design so we are not dependent on the SW choices. 

On that note: I also did not find info on how to add graph/model meta information the ONNX. Same logic so that the HW conversion tools can parse these (e.g. key/value pairs) and use them in constructing the network. Those all can be ignored by the onnx runtime and only custom designs use them to help the tool. The only thing I could think of was to store any additional info in a json file but it would make it uglier than being able to do that using one .onnx file.
