### ISSUE TITLE
Export weights to int8 datatype 

### ISSUE THREAD

**Issue by holoLens8** [onnx/tensorflow-onnx#917]
Hello, 
Is there a way to export 32float weights to int8 datatype?
Thanks.

**Comment by jignparm** [comment]
Can you try casting it to float32 and setting the cast operator as an output of the model. That should generate float32 when you run the model. Or did you mean something else?

**Comment by holoLens8** [comment]
Thanks for your answer. In fact I got the weights as a float32. What I'm looking for is to get weights as int8.

**Comment by jignparm** [comment]
Sorry, should have said cast to int8 instead. https://github.com/onnx/onnx/blob/master/docs/Operators.md#Cast

**Comment by guschmue** [comment]
float32 -> int8 would be quantization. 
You can use tf2onnx to get the float32 model and than run this tool to quantize to int8.

**Comment by sayakpaul** [comment]
Possible to apply dynamic-range quantization on TF model with ONNX? If so, could you provide an example?

**Comment by guschmue** [comment]
Yes, you'd convert the tf fp32 model with tf2onnx, than use the onnxruntime quantization tool (https://onnxruntime.ai/docs/performance/quantization.html).
If the model came as Qat model (aka it has FakeQuantitize* ops in it) tf2onnx should be able to convert it as well.
Maybe the easiest: if there is a quantized tflite model you can convert that one with tf2onnx.

**Comment by sayakpaul** [comment]
> If the model came as Qat model (aka it has FakeQuantitize* ops in it) tf2onnx should be able to convert it as well.

Could you expand a bit more?
