### ISSUE TITLE
UnicodeDecodeError when converting Resnet_v1_101

### ISSUE THREAD

**Issue by yutkin** [onnx/tensorflow-onnx#920]
**Describe the bug**
I'm trying to convert [ResNet v1 (101) trained on OpenImages dataset](https://storage.googleapis.com/openimages/web/extras.html). During conversion I got:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)`. 

Full log:
```
python3 -m tf2onnx.convert --checkpoint /out/oidv2-resnet_v1_101.ckpt.meta --output model.onnx --inputs input_values:0 --outputs multi_predictions:0
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tf2onnx/verbose_logging.py:72: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2020-05-12 13:21:57,966 - WARNING - From /usr/local/lib/python3.6/dist-packages/tf2onnx/verbose_logging.py:72: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

2020-05-12 13:22:03,666 - INFO - Using tensorflow=1.15.2, onnx=1.7.0, tf2onnx=1.5.6/80edd7
2020-05-12 13:22:03,666 - INFO - Using opset <onnx, 8>
2020-05-12 13:22:03,668 - WARNING - Shapes of Merge map/while/decoded_image/cond_jpeg/cond_png/cond_gif/Merge have different ranks: 3, 4
2020-05-12 13:22:05,049 - WARNING - Cannot infer shape for map/while/Squeeze: map/while/Squeeze:0
2020-05-12 13:22:05,050 - WARNING - Cannot infer shape for map/while/ExpandDims: map/while/ExpandDims:0
2020-05-12 13:22:05,050 - WARNING - Cannot infer shape for SpatialSqueeze: SpatialSqueeze:0
2020-05-12 13:22:05,050 - WARNING - Cannot infer shape for multi_predictions: multi_predictions:0
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/utils.py", line 139, in tf_to_onnx_tensor
    np_data = np_data.astype(np.str).astype(np.object)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 161, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 145, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 497, in process_tf_graph
    onnx_nodes, op_cnt, attr_cnt, output_shapes, dtypes = tensorflow_to_onnx(tf_graph, shape_override)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 124, in tensorflow_to_onnx
    return tflist_to_onnx(graph.get_operations(), shape_override)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 96, in tflist_to_onnx
    onnx_tensor = utils.tf_to_onnx_tensor(utils.get_tf_node_attr(node, a), name=port_name(node.name))
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/utils.py", line 141, in tf_to_onnx_tensor
    raise RuntimeError("Not support type: {}".format(type(np_data.flat[0])))
RuntimeError: Not support type: <class 'bytes'>
```

**Urgency**
none

**System information**
- OS Platform and Distribution: Ubuntu 18.04 (base Docker image)
- Tensorflow Version: 1.15.2
- Python version: 3.6

**Additional context**
[Model Checkpoint](https://storage.googleapis.com/openimages/2017_07/oidv2-resnet_v1_101.ckpt.tar.gzhttps://storage.googleapis.com/openimages/2017_07/oidv2-resnet_v1_101.ckpt.tar.gz)

**Comment by jignparm** [comment]
PR #922 fixes the UnicodeDecodeError message.

However, the model fails downstream due to the DecodeBmp operator. This operator is not implemented in Onnx (and also unlikely to be proposed in future opsets).

There are quite a few ResNet flavors available for download from the Onnx model zoo -> https://github.com/onnx/models/tree/master/vision/classification/resnet. Can these be used in your scenario?


![image](https://user-images.githubusercontent.com/13698702/81774440-15569a80-94da-11ea-8054-11901f332fc1.png)

**Comment by yutkin** [comment]
Unfortunately, right now I'm looking for models pretrained on OpenImages, but nevertheless thank you for the fix!

**Comment by jignparm** [comment]
Closing since original issue is resolved. Reopen if needed.

**Comment by Etty-Cohen** [comment]
Hi @yutkin @jignparm !
I am here in 2022...
something been updated?
I run that code (after updating tf_utils.py):
`python3 -m tf2onnx.convert --checkpoint oidv2-resnet_v1_101.ckpt.meta --output model.onnx --inputs input_values:0 --outputs multi_predictions:0`
and got that error:
```
/usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
INFO:tensorflow:Restoring parameters from oidv2-resnet_v1_101.ckpt
2022-07-11 10:56:25,501 - INFO - Restoring parameters from oidv2-resnet_v1_101.ckpt
WARNING:tensorflow:From /home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_loader.py:305: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
2022-07-11 10:56:26,661 - WARNING - From /home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_loader.py:305: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py:925: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2022-07-11 10:56:26,661 - WARNING - From /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py:925: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
2022-07-11 10:56:29,223 - INFO - Using tensorflow=2.8.0, onnx=1.6.0, tf2onnx=1.11.1/1915fb
2022-07-11 10:56:29,223 - INFO - Using opset <onnx, 11>
2022-07-11 10:56:35,207 - WARNING - Shapes of Merge map/while/decoded_image/cond_jpeg/cond_png/cond_gif/Merge have different ranks: 3, 4
2022-07-11 10:56:37,424 - WARNING - Cannot infer shape for map/while/Squeeze: map/while/Squeeze:0
2022-07-11 10:56:37,424 - WARNING - Cannot infer shape for map/while/ExpandDims: map/while/ExpandDims:0
2022-07-11 10:56:37,424 - WARNING - Cannot infer shape for map/while/Squeeze_1: map/while/Squeeze_1:0
2022-07-11 10:56:37,424 - WARNING - Cannot infer shape for SpatialSqueeze: SpatialSqueeze:0
2022-07-11 10:56:37,424 - WARNING - Cannot infer shape for multi_predictions: multi_predictions:0
2022-07-11 10:56:41,531 - INFO - Computed 0 values for constant folding
2022-07-11 10:56:47,556 - ERROR - rewriter <function rewrite_cond at 0x7f7187a915e0>: exception the rank of outputs map/while/decoded_image/cond_jpeg/cond_png/cond_gif/DecodeGif:0 and map/while/decoded_image/cond_jpeg/cond_png/cond_gif/DecodeBmp:0 mismatch: 4, 3
2022-07-11 10:56:47,557 - INFO - ['Traceback (most recent call last):\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 352, in run_rewriters\n    ops = func(g, g.get_nodes())\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/rewriter/cond_rewriter.py", line 332, in rewrite_cond\n    return CondRewriter(g).rewrite()\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/rewriter/cond_rewriter.py", line 54, in rewrite\n    return self.run()\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/rewriter/cond_rewriter.py", line 92, in run\n    if_node = self._create_if_node(cond_context)\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/rewriter/cond_rewriter.py", line 139, in _create_if_node\n    output_shapes, output_dtypes = self._get_output_shape_dtype(cond_context)\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/rewriter/cond_rewriter.py", line 117, in _get_output_shape_dtype\n    raise RuntimeError(\n', 'RuntimeError: the rank of outputs map/while/decoded_image/cond_jpeg/cond_png/cond_gif/DecodeGif:0 and map/while/decoded_image/cond_jpeg/cond_png/cond_gif/DecodeBmp:0 mismatch: 4, 3\n']
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 696, in <module>
    main()
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 266, in main
    model_proto, _ = _convert_common(
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 161, in _convert_common
    g = process_tf_graph(tf_graph, const_node_values=const_node_values,
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 439, in process_tf_graph
    g = process_graphs(main_g, subgraphs, custom_op_handlers, inputs_as_nchw, continue_on_error, custom_rewriter,
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 491, in process_graphs
    g = process_parsed_graph(main_g, custom_op_handlers, inputs_as_nchw, continue_on_error, custom_rewriter,
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 594, in process_parsed_graph
    topological_sort(g, continue_on_error)
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 336, in topological_sort
    g.topological_sort(ops)
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/graph.py", line 1055, in topological_sort
    utils.make_sure(j is not None, "Cannot find node with output %r in graph %r", inp, self.graph_name)
  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/utils.py", line 264, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: Cannot find node with output 'map/while/decoded_image/cond_jpeg/cond_png/cond_gif/Merge:0' in graph 'tf2onnx__3'

```

**Comment by fatcat-z** [comment]
> Hi @yutkin @jignparm ! I am here in 2022... something been updated? I run that code (after updating tf_utils.py): `python3 -m tf2onnx.convert --checkpoint oidv2-resnet_v1_101.ckpt.meta --output model.onnx --inputs input_values:0 --outputs multi_predictions:0` and got that error:
> 
> ```
> /usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
>   warn(RuntimeWarning(msg))
> INFO:tensorflow:Restoring parameters from oidv2-resnet_v1_101.ckpt
> 2022-07-11 10:56:25,501 - INFO - Restoring parameters from oidv2-resnet_v1_101.ckpt
> WARNING:tensorflow:From /home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_loader.py:305: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `tf.compat.v1.graph_util.convert_variables_to_constants`
> 2022-07-11 10:56:26,661 - WARNING - From /home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_loader.py:305: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `tf.compat.v1.graph_util.convert_variables_to_constants`
> WARNING:tensorflow:From /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py:925: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `tf.compat.v1.graph_util.extract_sub_graph`
> 2022-07-11 10:56:26,661 - WARNING - From /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py:925: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use `tf.compat.v1.graph_util.extract_sub_graph`
> 2022-07-11 10:56:29,223 - INFO - Using tensorflow=2.8.0, onnx=1.6.0, tf2onnx=1.11.1/1915fb
> 2022-07-11 10:56:29,223 - INFO - Using opset <onnx, 11>
> 2022-07-11 10:56:35,207 - WARNING - Shapes of Merge map/while/decoded_image/cond_jpeg/cond_png/cond_gif/Merge have different ranks: 3, 4
> 2022-07-11 10:56:37,424 - WARNING - Cannot infer shape for map/while/Squeeze: map/while/Squeeze:0
> 2022-07-11 10:56:37,424 - WARNING - Cannot infer shape for map/while/ExpandDims: map/while/ExpandDims:0
> 2022-07-11 10:56:37,424 - WARNING - Cannot infer shape for map/while/Squeeze_1: map/while/Squeeze_1:0
> 2022-07-11 10:56:37,424 - WARNING - Cannot infer shape for SpatialSqueeze: SpatialSqueeze:0
> 2022-07-11 10:56:37,424 - WARNING - Cannot infer shape for multi_predictions: multi_predictions:0
> 2022-07-11 10:56:41,531 - INFO - Computed 0 values for constant folding
> 2022-07-11 10:56:47,556 - ERROR - rewriter <function rewrite_cond at 0x7f7187a915e0>: exception the rank of outputs map/while/decoded_image/cond_jpeg/cond_png/cond_gif/DecodeGif:0 and map/while/decoded_image/cond_jpeg/cond_png/cond_gif/DecodeBmp:0 mismatch: 4, 3
> 2022-07-11 10:56:47,557 - INFO - ['Traceback (most recent call last):\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 352, in run_rewriters\n    ops = func(g, g.get_nodes())\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/rewriter/cond_rewriter.py", line 332, in rewrite_cond\n    return CondRewriter(g).rewrite()\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/rewriter/cond_rewriter.py", line 54, in rewrite\n    return self.run()\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/rewriter/cond_rewriter.py", line 92, in run\n    if_node = self._create_if_node(cond_context)\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/rewriter/cond_rewriter.py", line 139, in _create_if_node\n    output_shapes, output_dtypes = self._get_output_shape_dtype(cond_context)\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/rewriter/cond_rewriter.py", line 117, in _get_output_shape_dtype\n    raise RuntimeError(\n', 'RuntimeError: the rank of outputs map/while/decoded_image/cond_jpeg/cond_png/cond_gif/DecodeGif:0 and map/while/decoded_image/cond_jpeg/cond_png/cond_gif/DecodeBmp:0 mismatch: 4, 3\n']
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 696, in <module>
>     main()
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 266, in main
>     model_proto, _ = _convert_common(
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 161, in _convert_common
>     g = process_tf_graph(tf_graph, const_node_values=const_node_values,
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 439, in process_tf_graph
>     g = process_graphs(main_g, subgraphs, custom_op_handlers, inputs_as_nchw, continue_on_error, custom_rewriter,
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 491, in process_graphs
>     g = process_parsed_graph(main_g, custom_op_handlers, inputs_as_nchw, continue_on_error, custom_rewriter,
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 594, in process_parsed_graph
>     topological_sort(g, continue_on_error)
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 336, in topological_sort
>     g.topological_sort(ops)
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/graph.py", line 1055, in topological_sort
>     utils.make_sure(j is not None, "Cannot find node with output %r in graph %r", inp, self.graph_name)
>   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/utils.py", line 264, in make_sure
>     raise ValueError("make_sure failure: " + error_msg % args)
> ValueError: make_sure failure: Cannot find node with output 'map/while/decoded_image/cond_jpeg/cond_png/cond_gif/Merge:0' in graph 'tf2onnx__3'
> ```

Could you please reopen an issue with above details and the downloading url of the ck used in the example code so we can process it accordingly?

I've seen you updated 2 closed issues but seems like that brought a little confusion that we don't know the real problem you met.

Thanks.

**Comment by yutkin** [comment]
Hi! It is no longer relevant. 

The issue is due to decode jpeg node in the graph that ONNX does not support. For those who want to convert this model to ONNX, it is better to remove this node manually from prototxt first.

**Comment by Etty-Cohen** [comment]
> Hi! It is no longer relevant.
> 
> The issue is due to decode jpeg node in the graph that ONNX does not support. For those who want to convert this model to ONNX, it is better to remove this node manually from prototxt first.

Hi @yutkin you did it?

**Comment by Etty-Cohen** [comment]
> Hi! It is no longer relevant.
> 
> The issue is due to decode jpeg node in the graph that ONNX does not support. For those who want to convert this model to ONNX, it is better to remove this node manually from prototxt first.

@yutkin 

> > Hi @yutkin @jignparm ! I am here in 2022... something been updated? I run that code (after updating tf_utils.py): `python3 -m tf2onnx.convert --checkpoint oidv2-resnet_v1_101.ckpt.meta --output model.onnx --inputs input_values:0 --outputs multi_predictions:0` and got that error:
> > ```
> > /usr/lib/python3.8/runpy.py:127: RuntimeWarning: 'tf2onnx.convert' found in sys.modules after import of package 'tf2onnx', but prior to execution of 'tf2onnx.convert'; this may result in unpredictable behaviour
> >   warn(RuntimeWarning(msg))
> > INFO:tensorflow:Restoring parameters from oidv2-resnet_v1_101.ckpt
> > 2022-07-11 10:56:25,501 - INFO - Restoring parameters from oidv2-resnet_v1_101.ckpt
> > WARNING:tensorflow:From /home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_loader.py:305: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
> > Instructions for updating:
> > Use `tf.compat.v1.graph_util.convert_variables_to_constants`
> > 2022-07-11 10:56:26,661 - WARNING - From /home/etty/.local/lib/python3.8/site-packages/tf2onnx/tf_loader.py:305: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
> > Instructions for updating:
> > Use `tf.compat.v1.graph_util.convert_variables_to_constants`
> > WARNING:tensorflow:From /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py:925: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
> > Instructions for updating:
> > Use `tf.compat.v1.graph_util.extract_sub_graph`
> > 2022-07-11 10:56:26,661 - WARNING - From /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py:925: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
> > Instructions for updating:
> > Use `tf.compat.v1.graph_util.extract_sub_graph`
> > 2022-07-11 10:56:29,223 - INFO - Using tensorflow=2.8.0, onnx=1.6.0, tf2onnx=1.11.1/1915fb
> > 2022-07-11 10:56:29,223 - INFO - Using opset <onnx, 11>
> > 2022-07-11 10:56:35,207 - WARNING - Shapes of Merge map/while/decoded_image/cond_jpeg/cond_png/cond_gif/Merge have different ranks: 3, 4
> > 2022-07-11 10:56:37,424 - WARNING - Cannot infer shape for map/while/Squeeze: map/while/Squeeze:0
> > 2022-07-11 10:56:37,424 - WARNING - Cannot infer shape for map/while/ExpandDims: map/while/ExpandDims:0
> > 2022-07-11 10:56:37,424 - WARNING - Cannot infer shape for map/while/Squeeze_1: map/while/Squeeze_1:0
> > 2022-07-11 10:56:37,424 - WARNING - Cannot infer shape for SpatialSqueeze: SpatialSqueeze:0
> > 2022-07-11 10:56:37,424 - WARNING - Cannot infer shape for multi_predictions: multi_predictions:0
> > 2022-07-11 10:56:41,531 - INFO - Computed 0 values for constant folding
> > 2022-07-11 10:56:47,556 - ERROR - rewriter <function rewrite_cond at 0x7f7187a915e0>: exception the rank of outputs map/while/decoded_image/cond_jpeg/cond_png/cond_gif/DecodeGif:0 and map/while/decoded_image/cond_jpeg/cond_png/cond_gif/DecodeBmp:0 mismatch: 4, 3
> > 2022-07-11 10:56:47,557 - INFO - ['Traceback (most recent call last):\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 352, in run_rewriters\n    ops = func(g, g.get_nodes())\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/rewriter/cond_rewriter.py", line 332, in rewrite_cond\n    return CondRewriter(g).rewrite()\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/rewriter/cond_rewriter.py", line 54, in rewrite\n    return self.run()\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/rewriter/cond_rewriter.py", line 92, in run\n    if_node = self._create_if_node(cond_context)\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/rewriter/cond_rewriter.py", line 139, in _create_if_node\n    output_shapes, output_dtypes = self._get_output_shape_dtype(cond_context)\n', '  File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/rewriter/cond_rewriter.py", line 117, in _get_output_shape_dtype\n    raise RuntimeError(\n', 'RuntimeError: the rank of outputs map/while/decoded_image/cond_jpeg/cond_png/cond_gif/DecodeGif:0 and map/while/decoded_image/cond_jpeg/cond_png/cond_gif/DecodeBmp:0 mismatch: 4, 3\n']
> > Traceback (most recent call last):
> >   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
> >     exec(code, run_globals)
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 696, in <module>
> >     main()
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 266, in main
> >     model_proto, _ = _convert_common(
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/convert.py", line 161, in _convert_common
> >     g = process_tf_graph(tf_graph, const_node_values=const_node_values,
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 439, in process_tf_graph
> >     g = process_graphs(main_g, subgraphs, custom_op_handlers, inputs_as_nchw, continue_on_error, custom_rewriter,
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 491, in process_graphs
> >     g = process_parsed_graph(main_g, custom_op_handlers, inputs_as_nchw, continue_on_error, custom_rewriter,
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 594, in process_parsed_graph
> >     topological_sort(g, continue_on_error)
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/tfonnx.py", line 336, in topological_sort
> >     g.topological_sort(ops)
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/graph.py", line 1055, in topological_sort
> >     utils.make_sure(j is not None, "Cannot find node with output %r in graph %r", inp, self.graph_name)
> >   File "/home/etty/.local/lib/python3.8/site-packages/tf2onnx/utils.py", line 264, in make_sure
> >     raise ValueError("make_sure failure: " + error_msg % args)
> > ValueError: make_sure failure: Cannot find node with output 'map/while/decoded_image/cond_jpeg/cond_png/cond_gif/Merge:0' in graph 'tf2onnx__3'
> > ```
> 
> Could you please reopen an issue with above details and the downloading url of the ck used in the example code so we can process it accordingly?
> 
> I've seen you updated 2 closed issues but seems like that brought a little confusion that we don't know the real problem you met.
> 
> Thanks.

https://github.com/onnx/tensorflow-onnx/issues/1995
