### ISSUE TITLE
Feature request: Keep the order of inputs when converting graph

### ISSUE THREAD

**Issue by EFanZh** [onnx/tensorflow-onnx#926]
I am using `process_tf_graph` to convert TensorFlow frozen graphs to ONNX model, and I have found that the order of the inputs in the converted ONNX model might not be the same as the inputs specified as the `input_names` argument to `process_tf_graph`.

I understand that I can identify the correspondence of inputs by their names, or I can also sort the inputs in the ONNX model afterwards, but I think keeping the order might be less surprising.

Also, what about outputs? Is the outputs order guaranteed to be the same as the inputs specified in `output_names` argument?

I was using the master version (3383ff9bfa50e49bf69863983c965e49b94c073b) tf2onnx.

**Comment by guschmue** [comment]
We don't spend explicit attention to the order but we keep them in lists so their order might be preserved. Let me check on it.

**Comment by guschmue** [comment]
This should be fixed in the latest release.

**Comment by zakajd** [comment]
Hi @guschmue 
Does the output order preserved as well?

I tried to convert a multi-output model from SavedModel format to ONNX, but it changed the order of outputs.
For example, I have ['output_1', 'output_2', 'output_3'] in TF2 model, but after converting it's changed to ['output_3', 'output_1', 'output_2'].

**Comment by guschmue** [comment]
We are trying to preserve them now.

I also should have mentioned that we have a new api (process_tf_graph) to make this a little easier for users:
https://github.com/onnx/tensorflow-onnx#python-api-reference
