### ISSUE TITLE
Unable to import tf2onnx (python 3.7.5) on OSX 10.15.4

### ISSUE THREAD

**Issue by MKaptein** [onnx/tensorflow-onnx#927]
**Describe the bug**
After clean installation of TensorFlow and `tf2onnx` the import of `tf2onnx` fails:

```
Python 3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tf2onnx
[libprotobuf ERROR google/protobuf/descriptor_database.cc:394] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL google/protobuf/descriptor.cc:1356] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
```

**Urgency**
Would be nice if this did work.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
OSX Catalina, 10.15.4

- Tensorflow Version:
```
$ pip3 show tensorflow
Name: tensorflow
Version: 2.2.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib/python3.7/site-packages
Requires: tensorflow-estimator, six, wrapt, opt-einsum, keras-preprocessing, absl-py, wheel, scipy, astunparse, gast, h5py, tensorboard, numpy, termcolor, grpcio, google-pasta, protobuf
```

- Python version: 3.7.5

**To Reproduce**
Clean install of Tensorflow using pip; subsequently trying to import `tf2onnx`.

**Expected behavior**
No error on import

**Comment by guschmue** [comment]
hm, tf2onnx does not fiddle with protobuf and uses the installed tensorflow. We do install onnx if not found which does have a dependency on protobuf. Maybe there is some conflict.
What version of onnx is installed on your system? 
And tensorflow itself is happy ?

**Comment by prabhat00155** [comment]
Even I got this error on Python 3.6. I can import tensorflow.

(onnxrt_env) prroy-Mac:tf prroy$ pip freeze | grep onnx
onnx==1.7.0
onnxconverter-common==1.6.1
onnxmltools==1.6.1
onnxruntime==1.3.0
skl2onnx==1.6.9
tf2onnx==1.5.6

**Comment by MKaptein** [comment]
Tensorflow seems happy (but I am unsure how to be certain.. :S). My onnx version is

```
Name: onnx
Version: 1.7.0
Summary: Open Neural Network Exchange
Home-page: https://github.com/onnx/onnx
Author: bddppq
Author-email: jbai@fb.com
License: UNKNOWN
Location: /usr/local/lib/python3.7/site-packages
Requires: six, numpy, protobuf, typing-extensions
Required-by: tf2onnx, onnxconverter-common, keras2onnx
```

Does that help at all? (note, this is not really urgent for me at the moment as for the specific model  I was trying to do this for I found a workaround --- another machine really --- but if I can help solving the issue by trying stuff out / sharing information I am happy to help!

**Comment by prabhat00155** [comment]
Try downgrading onnx to 1.6.0. Also, I saw some import errors with TF2.2(not sure if it's supported), TF1.4 worked for me.

**Comment by guschmue** [comment]
tf-2.x is supported on master but not on 1.5.6.
One thing that changed with onnx-1.7 - it switched to using protobuf lite. But it has not been an issue for linux and windows.

**Comment by prabhat00155** [comment]
When I install tf2onnx from master, it works fine with latest onnx(1.7.0).

**Comment by MKaptein** [comment]
Not sure if this helps at all, but I just gave it another try, now with:

```
MC-Kaptein-Pro:~ mauritskate$ pip3 show protobuf
Name: protobuf
Version: 3.12.2
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: None
Author-email: None
License: 3-Clause BSD License
Location: /usr/local/lib/python3.7/site-packages
Requires: six, setuptools
Required-by: tensorflow, tensorboard, onnxconverter-common, onnx, keras2onnx

MC-Kaptein-Pro:~ mauritskate$ pip3 show tensorflow
Name: tensorflow
Version: 2.2.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib/python3.7/site-packages
Requires: keras-preprocessing, astunparse, six, scipy, google-pasta, protobuf, wrapt, tensorboard, gast, opt-einsum, grpcio, tensorflow-estimator, h5py, termcolor, wheel, absl-py, numpy
Required-by: 

MC-Kaptein-Pro:~ mauritskate$ pip3 show tf2onnx
Name: tf2onnx
Version: 1.5.6
Summary: Tensorflow to ONNX converter
Home-page: https://github.com/onnx/tensorflow-onnx
Author: onnx@microsoft.com
Author-email: onnx@microsoft.com
License: UNKNOWN
Location: /usr/local/lib/python3.7/site-packages
Requires: requests, numpy, onnx, six
Required-by: 

MC-Kaptein-Pro:~ mauritskate$ pip3 show onnx
Name: onnx
Version: 1.7.0
Summary: Open Neural Network Exchange
Home-page: https://github.com/onnx/onnx
Author: bddppq
Author-email: jbai@fb.com
License: UNKNOWN
Location: /usr/local/lib/python3.7/site-packages
Requires: numpy, six, protobuf, typing-extensions
Required-by: tf2onnx, onnxconverter-common, keras2onnx
```

Tensorflow itself seems happy (i.e., I can import it and run some basic examples, I don't know if there is anything specific I should try). 

Here I get:

```
MC-Kaptein-Pro:~ mauritskate$ python3
Python 3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import tf2onnx
[libprotobuf ERROR google/protobuf/descriptor_database.cc:394] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL google/protobuf/descriptor.cc:1356] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
Abort trap: 6
```

(that's the same as before). Now, downgrading to onnx 1.6.0:

```
MC-Kaptein-Pro:~ mauritskate$ pip3 install --upgrade onnx==1.6.0
Collecting onnx==1.6.0
  Downloading onnx-1.6.0-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (5.8 MB)
     |████████████████████████████████| 5.8 MB 2.8 MB/s 
Requirement already satisfied, skipping upgrade: typing-extensions>=3.6.2.1 in /usr/local/lib/python3.7/site-packages (from onnx==1.6.0) (3.7.4.2)
Requirement already satisfied, skipping upgrade: protobuf in /usr/local/lib/python3.7/site-packages (from onnx==1.6.0) (3.12.2)
Requirement already satisfied, skipping upgrade: numpy in /usr/local/lib/python3.7/site-packages (from onnx==1.6.0) (1.18.2)
Requirement already satisfied, skipping upgrade: six in /usr/local/lib/python3.7/site-packages (from onnx==1.6.0) (1.14.0)
Requirement already satisfied, skipping upgrade: setuptools in ./Library/Python/3.7/lib/python/site-packages (from protobuf->onnx==1.6.0) (46.1.1)
Installing collected packages: onnx
  Attempting uninstall: onnx
    Found existing installation: onnx 1.7.0
    Uninstalling onnx-1.7.0:
      Successfully uninstalled onnx-1.7.0
Successfully installed onnx-1.6.0
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/local/opt/python/bin/python3.7 -m pip install --upgrade pip' command.
MC-Kaptein-Pro:~ mauritskate$ python3
Python 3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tf2onnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/tf2onnx/__init__.py", line 13, in <module>
    from tf2onnx import tfonnx, utils, graph, graph_builder, graph_matcher, shape_inference, schemas  # pylint: disable=wrong-import-order
  File "/usr/local/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 20, in <module>
    from tensorflow.tools.graph_transforms import TransformGraph
ModuleNotFoundError: No module named 'tensorflow.tools.graph_transforms'
```

I might be missing something else locally?

**Comment by guschmue** [comment]
This must be tf-2.x. The tf2onnx release 1.5.6 on pypi does not support tf-2.x.
But our master does:
```pip install git+https://github.com/onnx/tensorflow-onnx```
We are doing to push a new release to pypi in the next few days.

**Comment by xavriley** [comment]
I was still getting this error on master today.

Downgrading to `tensorflow=1.14.0` and `onnx=1.6.0` with `tf2onnx` from pypy made it work for me with Python 3.6.

**Comment by ethanyanjiali** [comment]
Still running into the same issue with tf 2.2 and tf2onnx 1.6.1 or master (1.7.0). @guschmue do we expect a fix soon? thanks.

**Comment by guschmue** [comment]
There are 2 issues in this issue. You mean the protobuf issue?  @TomWildenhain-Microsoft  made some fix for this but we have not pushed that to pypi yet.

**Comment by TomWildenhain-Microsoft** [comment]
@ethanyanjiali Try importing `onnx` before `tf2onnx` or install the latest version of `tf2onnx` from git:
`pip install git+https://github.com/onnx/tensorflow-onnx`
Let us know if that does not work.

**Comment by ethanyanjiali** [comment]
thanks for the prompt feedback. I tried to import `onnx` before `tf2onnx` but it doesn't work. 
```
[libprotobuf ERROR google/protobuf/descriptor_database.cc:394] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL google/protobuf/descriptor.cc:1356] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
[1]    89023 abort      python main.py
```

my versions are:
```
tensorflow==2.2.0
onnx==1.7.0
tf2onnx @ git+https://github.com/onnx/tensorflow-onnx@85bca924068bf3c5f16fef86567458a5ef60a220
```

However, if I place `import tf2onnx` before `import tensorflow as tf`, the error went away. It aligns with previous suspicion that tf's protobuf has some conflict with tf2onnx's.

**Comment by guschmue** [comment]
fyi @TomWildenhain-Microsoft

**Comment by guschmue** [comment]
I think this was fixed.

**Comment by caio1985** [comment]
> thanks for the prompt feedback. I tried to import `onnx` before `tf2onnx` but it doesn't work.
> 
> ```
> [libprotobuf ERROR google/protobuf/descriptor_database.cc:394] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
> [libprotobuf FATAL google/protobuf/descriptor.cc:1356] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
> libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
> [1]    89023 abort      python main.py
> ```
> 
> my versions are:
> 
> ```
> tensorflow==2.2.0
> onnx==1.7.0
> tf2onnx @ git+https://github.com/onnx/tensorflow-onnx@85bca924068bf3c5f16fef86567458a5ef60a220
> ```
> 
> However, if I place `import tf2onnx` before `import tensorflow as tf`, the error went away. It aligns with previous suspicion that tf's protobuf has some conflict with tf2onnx's.

I had the same issue and simply changing the order of libraries worked.

In my case:

import onnx
import keras2onnx

from tensorflow.python.keras import backend as K
from tensorflow.python.keras.models import load_model

Also running on MacOS.
