### ISSUE TITLE
Converting dynamic input tensor to static

### ISSUE THREAD

**Issue by solarflarefx** [onnx/tensorflow-onnx#931]
Sometimes I get models from others on my team which I need to convert to onnx and then run inference on to measure some performance metrics.  I notice that sometimes the models have an dynamic shape on the input tensor but I run my metrics on fixed shapes.  For example, I've received models with tensor shape (?, C, H, W)

In those cases, C, H, and W are fixed but the first dimension has a dynamic value on the onnx model (though I know what value I want to use for inference).  I've noticed that if I want to use these with an enhanced optimization engine like TensorRT, this can cause a problem where in order to use the model I have to perform some intermediary steps where I have both a preprocessor an prediction engine in order to reshape and run inference. 

My question is that if I get a TensorFlow model that happens to be like this and then convert to onnx, is there a way to make the tensor input shape fixed in the conversion process?

**Comment by jignparm** [comment]
You can set the shape of the inputs explicitly. See the example syntax  `--inputs X:0[1,28,28,3]` on the  README.md.

**Comment by feiyuhuahuo** [comment]
@solarflarefx   Do you mean that if the batch size dimension is unknow, TensorRT would fail to load the onnx model ?

**Comment by Egorundel** [comment]
@feiyuhuahuo Did you manage to overcome the problem?
