### ISSUE TITLE
Cannot covert Keras dropout layer

### ISSUE THREAD

**Issue by EFanZh** [onnx/tensorflow-onnx#933]
**Describe the bug**

The master version of tf2onnx doesn’t handle Keras dropout layers well.

**System information**

- Arch Linux
- Tensorflow Version: 2.2.0
- Python version: 3.6.0
- tf2onnx version: `tf2onnx@git+https://github.com/onnx/tensorflow-onnx.git@43c01e5cab1ee789b45d1f8e6833bfdb13327942`

**To Reproduce**

1. Install the following packages:
   1. `keras`
   2. `tensorflow`
   3. `tf2onnx@git+https://github.com/onnx/tensorflow-onnx.git@43c01e5cab1ee789b45d1f8e6833bfdb13327942`
2. Run the following code:
```python
   import keras
   import tensorflow as tf
   from tf2onnx import tfonnx


   def main():
       for k in [keras, tf.keras]:
           with tf.Graph().as_default() as graph:
               model = k.Sequential(layers=[k.layers.Dropout(rate=0.5, input_shape=[4, 4])])

           tfonnx.process_tf_graph(tf_graph=graph,
                                   input_names=[model.input.name],
                                   output_names=[model.output.name])


   if __name__ == '__main__':
       main()
```

**Expected behavior**

The program exits successfully.

**Actual behavior**

The program fails with the following message:

```
ValueError: graph output dropout/Mul_1:0 not exist
```

**Comment by guschmue** [comment]
we most likely remove the dropout since we only support inference which makes the output disappear.
But its low priority for us since it is not common scenario to find dropout as model output.

**Comment by EFanZh** [comment]
The conversion fails even if dropout is not model output:

```python
import keras
import tensorflow as tf
from tf2onnx import tfonnx


def main():
    for k in [keras, tf.keras]:
        with tf.compat.v1.Session(graph=tf.Graph()) as session:
            model = k.Sequential(layers=[
                k.layers.Dense(units=4, input_shape=[4]),
                k.layers.Dropout(rate=0.5),
                k.layers.Dense(units=2)
            ])

            session.run([v.initializer for v in model.weights])

            graph_def = tf.compat.v1.graph_util.convert_variables_to_constants(sess=session,
                                                                               input_graph_def=session.graph_def,
                                                                               output_node_names=[model.output.op.name])

        with tf.Graph().as_default() as graph:
            tf.import_graph_def(graph_def=graph_def, name='')

        tfonnx.process_tf_graph(tf_graph=graph,
                                input_names=[model.input.name],
                                output_names=[model.output.name])


if __name__ == '__main__':
    main()
```

**Comment by guschmue** [comment]
I think this fails because we use the tensor names and not the model output names in the api.
We have since revised our python api and the new api should make this work much easier:
https://github.com/onnx/tensorflow-onnx#from_keras-tf-20-and-newer
