### ISSUE TITLE
Tensorflow Fill operator conversion 

### ISSUE THREAD

**Issue by pengwa** [onnx/tensorflow-onnx#94]
I got a GAN (style2paints) model, which are using Fill operator, which require a dynamic shape according to PlaceHolder_3 input's size. 

![image](https://user-images.githubusercontent.com/10530022/43334630-57760218-9200-11e8-840c-a962a6c9be0a.png)

**Comment by pengwa** [comment]
(experimental)ConstantFill in ONNX should support dynamic shape, so we can consider to add support after the op goes to stable opset.

**Comment by guschmue** [comment]
dupe of https://github.com/onnx/tensorflow-onnx/issues/79
