### ISSUE TITLE
If  some node output shape contains -1  like [1, -1, -1, 3] in  Relu6 and  add_padding () report  errors

### ISSUE THREAD

**Issue by laobadao** [onnx/tensorflow-onnx#95]
tensorflow  object detection  model [ssd_mobilenet_v1_quantized](http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18.tar.gz)

when I convert this  model,  
1. use tf_optimize() extract_sub_graph() pass new outputs names , some nodes before Postprocessor part , To some extent, delete the latter part of the model

2. tensorflow_to_onnx ()  delete Preprocessor part nodes ,and delete  some Assert nodes
```
ops = graph.get_operations()
    print("middle_inputs:", middle_inputs)
    new_input = None
    if middle_inputs:
        new_input = middle_inputs[0]
        print("new_input:", new_input)
        i = 0
        while i < len(ops):
            if "Preprocessor" in ops[i].name:
                ops.pop(i)
                i -= 1
            elif "Assert" in ops[i].name:
                print("Assert", ops[i].name)
                ops.pop(i)
                i -= 1
            elif ops[i].name == "ToFloat":
                ops.pop(i)
                i -= 1
            i += 1

    print("1 final len(ops):", len(ops))
```

3. just convert middle part , and repalce  palceholder node which what  I need 

```
 if node.type == "Placeholder":
                    output_names = [new_input]
                    attr["dtype"] = utils.map_tf_dtype(types_pb2.DT_FLOAT)
                    attr["shape"] = utils.middle_node_shape(node.name)
                    new_name = new_input[:-2]
                    print("new_name:", new_name)
                    onnx_node = helper.make_node(node.type, input_names, output_names, name=new_name, **attr)
```

4. final , this model's  nodes don't have  specific  shape ,only  have [1, -1, -1, 3], or some thing else  , and  there are some ops  such as  relu6  need  specific  shape to creat numpy array , or  add_padding () need  specific  shape  to caculate pads , Now  my stupid solution is run each node to get output shape and write these in a  dict,  

```
SSD_MIBILE_NODE_SHAPE = {
    'image_tensor': [1, 300, 300, 3],
    'FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_2_depthwise/depthwise': [1, 75, 75, 64],
    'FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_2_depthwise/BatchNorm/FusedBatchNorm': [1, 75, 75, 64],
    'FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/Conv2D': [1, 150, 150, 32],
    'FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/BatchNorm/FusedBatchNorm': [1, 150, 150, 32],

```

5. Although I finally converted successfully，and  run caffe2 OK, but as you can see, this is stupid. Do  you have any good advice？

**Comment by pengwa** [comment]
I think, to make the converted onnx file meaningful, we should feed those placeholder having dimension being -1, before call tf-onnx converter to do the conversion. 

Actually the test https://github.com/onnx/tensorflow-onnx/blob/9940b5bfed73b489dcfb5919899da4223ed056d8/tests/run_pretrained_models.py#L160 is doing this way I believe.

let me know if this does not answer your question.

**Comment by pengwa** [comment]
@laobadao  you can specify "placeholders with unknown ranks" when converting by passing input like this (https://github.com/onnx/tensorflow-onnx#usage):

--inputs X:0[1,28,28,3]


Then, there will be no more -1 in the graph. Does this fit your scenario?

**Comment by pengwa** [comment]
我看得懂中文，不过 collaborator 会看不懂， 我们尽量用英文吧。：）

**Comment by pengwa** [comment]
please cherry-pick https://github.com/onnx/tensorflow-onnx/pull/97/commits if current master branch does not change the placeholder shape override.

**Comment by laobadao** [comment]
@pengwa  I have already pass inputs x=:0[1,300,300,3], but tf2onnx.py   output_shapes = {} 

```
    output_shapes = {}
    dtypes = {}

    # find outputs
    ops = graph.get_operations()

    # create dict with output to shape mappings
    for node in ops:
        for out in node.outputs:
            shape = shape_override.get(out.name)
            if shape is None:
                try:
                    shape = out.get_shape().as_list()
                except Exception as ex:
                    shape = []
            dtypes[out.name] = utils.map_tf_dtype(out.dtype)
            output_shapes[out.name] = shape
```

as you can see, output_shapes dict just save out.name and shape from  tensorflow  frozen pb , Does not dynamically calculate shapes，placeholder was  ok ,  What bothers me is that conv or relu6 op requires shape calculation, but the shape of the other nodes in frozen pb has -1, only modifying the shape of an op can not change the shape behind.

Now, my  solution is before convert pb, I dynamically set a new shape for each Tensor with output shape , using set_shape().So far, this solution can meet my requirements.

**Comment by pengwa** [comment]
should placeholder be the only source of "-1"? so, you mean we have other operators that can have shape including -1? what's that?

**Comment by pengwa** [comment]
@laobadao i just fixed a shape override issue, maybe you can cherry-pick this change and try again? 
https://github.com/onnx/tensorflow-onnx/pull/97/commits/f7082e4869e74ea8e52e589b429508d6c1dcaf5d

**Comment by pengwa** [comment]
Maybe I am wrong,there should be -1 for nodes’s Output_shapes. i’ll Check it ...

**Comment by zhijxu-MS** [comment]
@laobadao ssd_mobilenet is convertible now, you could try it again now.

**Comment by guschmue** [comment]
We assume that is no longer an issue.
