### ISSUE TITLE
Tensorflow op [ MatrixDiag] is not supported

### ISSUE THREAD

**Issue by ZhengtianXu** [onnx/tensorflow-onnx#950]
When I am trying to convert the tf cpkt to onnx model, it causes the errors.
```
2020-06-03 17:09:10,860 - ERROR - Tensorflow op [Flamenetnormal_2/eye_2/MatrixDiag: MatrixDiag] is not supported
2020-06-03 17:09:10,860 - ERROR - Tensorflow op [Flamenetnormal_2/eye_1/MatrixDiag: MatrixDiag] is not supported
2020-06-03 17:09:10,860 - ERROR - Tensorflow op [Flamenetnormal_2/eye/MatrixDiag: MatrixDiag] is not supported
2020-06-03 17:09:11,978 - ERROR - Unsupported ops: Counter({'MatrixDiag': 3})
```
How to solve them? Thanks!

**Comment by guschmue** [comment]
We should support it. Did you try with ```--opset 11``` ? If that doesn't work, which tensorflow version are you using ?

**Comment by ZhengtianXu** [comment]
> We should support it. Did you try with `--opset 11` ? If that doesn't work, which tensorflow version are you using ?

Yes, I have tried with --opset 11 , the tensorflow version is 1.5.1

**Comment by RandySheriffH** [comment]
We have MatrixDiagV3 in code review which might be help.

**Comment by ZhengtianXu** [comment]
> We have MatrixDiagV3 in code review, MatrixDiag is just a simplified version.

How can I use this？

**Comment by RandySheriffH** [comment]
https://github.com/onnx/tensorflow-onnx/pull/935

**Comment by ZhengtianXu** [comment]
> #935 Just added MatrixDiag, feel free to try it out but be with opset12 please.

Thanks, I have tried with your branch ``RandySheriffH:rashuai/FixMatrixDiagV3`` with opset 8, it works. Also, I want to know whether this onnx model support tensorrt 6.0? When I try to convert, it causes some errors.

**Comment by RandySheriffH** [comment]
@guschmue for confirmation
