### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation

### ISSUE THREAD

**Issue by alex96295** [onnx/tensorflow-onnx#957]
**Describe the bug**

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Tensorflow Version:
- Python version:

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by guschmue** [comment]
We'd need to have a little more information, like the log when running tf2onnx.
Does tensorflow itself work?
I'm guessing tensorflow has some issue accessing gpu.
You could call tf2onnx and the take the gpu away which should prevent tensorflow from trying to access a gpu:
```
CUDA_VISIBLE_DEVICES="" python -m tf2onnx.convert ...
````

**Comment by alex96295** [comment]
@guschmue I am sorry I think I opened it twice, the complete explanation is at #958 

Sorry again

**Comment by alex96295** [comment]
I'll close this
