### ISSUE TITLE
Quantization won't work 

### ISSUE THREAD

**Issue by andrewhong5297** [onnx/tensorflow-onnx#959]
**Describe the bug**
I've tried using the pip install quantize pypi but it doesn't install on my computer so I can't quantize. Is there any other way to do quantize an onnx model? I've read that you can't convert a tflite model to onnx directly.

**Urgency**
No hard deadlines

**System information**
- OS Platform and Distribution: Windows 10
- Tensorflow Version: 2.0
- Python version: 3.6

**To Reproduce**
pip install quantize 

**Expected behavior**
Can't install quantize so can't quantize the onnx model. Thanks!

**Comment by guschmue** [comment]
the quantize package is unrelated to tf2onnx.
If you want to convert a tensorflow model to onnx and than quantitize the onnx model you'd:
- run tf2onnx on the fp32 tensorflow model
- take the onnx model that comes out of this and use this tool https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/quantization to quantitize it.
