### ISSUE TITLE
add support for FakeQuantWithMinMaxVars 

### ISSUE THREAD

**Issue by guschmue** [onnx/tensorflow-onnx#965]
replace FakeQuantWithMinMaxVars with a sequence of QuantizeLinear/DequantizeLinear to support Qat.

**Comment by nhphuong91** [comment]
@guschmue 
excuse me, could you explain more about "replace FakeQuantWithMinMaxVars with a sequence of QuantizeLinear/DequantizeLinear to support Qat"? 
Does user have to modify their network op or tf2onnx supports convert network with FakeQuantWithMinMaxVars op now?
Thanks!

**Comment by guschmue** [comment]
Yes, we replace FakeQuantWithMinMaxVars with QuantizeLinear/DequantizeLinear so we don't lose the info from FakeQuantWithMinMaxVars.
The runtime specific quantitization tool like https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/quantization will take the onnx graph and rewrites the graph with the real quantization ops.
tensorrt should also be aware of the QuantizeLinear/DequantizeLinear ops.

This is the way onnx wants to handle Qat. Pytorch onnx exporter will do the same.

**Comment by nhphuong91** [comment]
@guschmue When I try to convert a network re-train from SSD MobileNet v2, I got a bunch of ERROR log like below

> 2020-11-26 15:57:54,187 - ERROR - Tensorflow op [FeatureExtractor/MobilenetV2/Conv/act_quant/FakeQuantWithMinMaxVars: FakeQuantWithMinMaxVars] is not supported
> 2020-11-26 15:57:54,188 - ERROR - Tensorflow op [FeatureExtractor/MobilenetV2/expanded_conv/depthwise/act_quant/FakeQuantWithMinMaxVars: FakeQuantWithMinMaxVars] is not supported
> 2020-11-26 15:57:54,189 - ERROR - Tensorflow op [FeatureExtractor/MobilenetV2/expanded_conv/project/act_quant/FakeQuantWithMinMaxVars: FakeQuantWithMinMaxVars] is not supported
> 2020-11-26 15:57:54,190 - ERROR - Tensorflow op [FeatureExtractor/MobilenetV2/expanded_conv_1/expand/act_quant/FakeQuantWithMinMaxVars: FakeQuantWithMinMaxVars] is not supported
> 2020-11-26 15:57:54,190 - ERROR - Tensorflow op [FeatureExtractor/MobilenetV2/expanded_conv_1/depthwise/act_quant/FakeQuantWithMinMaxVars: FakeQuantWithMinMaxVars] is not supported
> 2020-11-26 15:57:54,191 - ERROR - Tensorflow op [FeatureExtractor/MobilenetV2/expanded_conv_1/project/act_quant/FakeQuantWithMinMaxVars: FakeQuantWithMinMaxVars] is not supported

But at the end, I got this log:

> 2020-11-26 15:57:54,316 - WARNING - ONNX Failed to infer shapes and dtypes for [Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/unstack__1165, type: Squeeze]
> Traceback (most recent call last):
>   File "/home/nhphuong/venv_hub/tensorrt713/lib/python3.6/site-packages/tf2onnx/schemas.py", line 157, in infer_onnx_shape_dtype
>     inferred_model = shape_inference.infer_shapes(model_proto)
>   File "/home/nhphuong/venv_hub/tensorrt713/lib/python3.6/site-packages/onnx/shape_inference.py", line 35, in infer_shapes
>     inferred_model_str = C.infer_shapes(model_str, check_type)
> RuntimeError: Shape inference error(s): (op_type:Squeeze, node name: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/unstack__1165): [ShapeInferenceError] Dimension of input 1 must be 1 instead of 4
> 
> 2020-11-26 15:57:54,391 - ERROR - Unsupported ops: Counter({'FakeQuantWithMinMaxVars': 86})
> 2020-11-26 15:57:54,458 - INFO - Optimizing ONNX model
> 2020-11-26 15:57:58,543 - INFO - After optimization: Add -64 (105->41), Cast -32 (133->101), Const -475 (877->402), Div -2 (13->11), Identity -114 (115->1), Less -2 (10->8), Reshape +6 (30->36), Shape -8 (35->27), Slice -7 (50->43), Squeeze -17 (66->49), Transpose -19 (162->143), Unsqueeze -61 (103->42)
> 2020-11-26 15:57:58,621 - INFO - 
> 2020-11-26 15:57:58,621 - INFO - Successfully converted TensorFlow model saved_model to ONNX
> 2020-11-26 15:57:58,713 - INFO - ONNX model is saved at model12.onnx

Does this mean the converting process finished successfully or fail?? I can see there exist a new file "model12.onnx" but cannot not convert it to tensorrt engine.

**Comment by guschmue** [comment]
Hm, the model has FakeQuantWithMinMaxVars and we support  FakeQuantWithMinMaxArgs. Let me see if we can add support for FakeQuantWithMinMaxVars.
