### ISSUE TITLE
Inputs_as_NCHW adds Transposes

### ISSUE THREAD

**Issue by AlexRibard** [onnx/tensorflow-onnx#977]
Hello,
I am converting a model from TF with the --inputs-as-nchw option
And the resulting model still contains a good amount of Transposes.

Here is the model
https://drive.google.com/file/d/17qLexicRukvDqrw3SjFh-0BSjj_ABxjR/view?usp=sharing

For examples
![image](https://user-images.githubusercontent.com/12990800/85056816-dddcad00-b16d-11ea-9a47-c4e9bc8b7279.png)
becomes
![image](https://user-images.githubusercontent.com/12990800/85056831-e503bb00-b16d-11ea-8898-87b0246fc71b.png)
But there are similar issues downstream in the model.

I am calling as follows:
```
python -m tf2onnx.convert --graphdef .\UnityProject\Assets\Resources\yolov2-tiny-arcityv3.pb --output output.onnx --inputs input:0 --outputs output:0 --inputs-as-nchw input:0
```

and I am on 1.5.6

Thanks!

**Comment by jignparm** [comment]
From the diagram above, some of the Transposes can probably be reduced further. Will have a look at it.

**Comment by jignparm** [comment]
With the enhancement in #978, there is only 1 transpose left in the graph.



![image](https://user-images.githubusercontent.com/13698702/85083451-56208e00-b1c1-11ea-82c9-fd504f72b8fd.png)
