### ISSUE TITLE
Installation on Jetson Nano fails

### ISSUE THREAD

**Issue by svetlanadataper** [onnx/tensorflow-onnx#979]
**Describe the bug**
There is no bug, the instructions need to be updated to install protobus-compiler package if not already installed or add it as a dependency.

**Urgency**
Installation is fixed after installing protobus:

`sudo apt-get install protobuf-compiler libprotoc-dev`

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux  4.9.140-tegra #1 SMP PREEMPT Wed Apr 8 18:10:49 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux
- Tensorflow Version: 1.15.20
- Python version: 3.6

**To Reproduce**
Describe steps/code to reproduce the behavior:

pip install -U tf2onnx  

Above command fails on Jetson Nano Jetpack 4.4.

**Expected behavior**
Instructions need to add protobuf as a prereq.

**Comment by guschmue** [comment]
tf2onnx has a dependency to onnx and onnx itself depends on protobuf.
But as far I know there is no arm package for onnx yet.
There is a issue for this under onnx https://github.com/onnx/onnx/issues/2791.
