### ISSUE TITLE
OSError: Cannot parse file b

### ISSUE THREAD

**Issue by IAMAl** [onnx/tensorflow-onnx#990]
**HELP: Error for Parsing**
OSError: Cannot parse file b'saved_model/saved_model.pb': Error parsing message.

**System information**
- OS: Linux Ubuntu 18.04
- Tensorflow Version:1.15
- Python version: 3.7.6

**To Reproduce**
saved_model.pb file is here;
https://github.com/IAMAl/onnx

**Comment by guschmue** [comment]
The parsing error is because your saved_model.pb is actually a saved_model.pbtxt.

**Comment by IAMAl** [comment]
Ah,...
I forgot to use of '''as_text=False''', many thanks for your pointing out.
