### ISSUE TITLE
tags 'serve' could not be found

### ISSUE THREAD

**Issue by IAMAl** [onnx/tensorflow-onnx#991]
**HELP: Error of MetaGraphDef**
RuntimeError: MetaGraphDef associated with tags 'serve' could not be found in SavedModel. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
available_tags: []

The '''serve''' and or other tag is seemed not in the pb file, what I made wrong ?

**System information**
- OS: Linux Ubuntu 18.04:
- Tensorflow Version: 1.15
- Python version: 3.7.6

**To Reproduce**
pb file is here (as_text=False);
https://github.com/IAMAl/onnx

tf2pb.py in same dir is conversion script.

**Comment by guschmue** [comment]
your file is in the graphdef format which is different than a saved-model format.
Use --graphdef in the tf2onnx command line. But for graphdef formats you need to also specify --inputs and --outputs for the model.
More details here:
https://github.com/onnx/tensorflow-onnx#getting-started

**Comment by IAMAl** [comment]
Hi, I tried to generate protobuff file, but meet an error of;
python3.7/site-packages/tf2onnx/tf_utils.py", line 116, in map_tf_dtype
dtype = TF_TO_ONNX_DTYPE[dtype]
KeyError: tf.float32_ref

I made is here;
https://github.com/IAMAl/onnx/tf2pb.py

**Comment by jignparm** [comment]
See this comment on a similar issue, and how to freeze a graph prior to calling 'process_tf_graph': https://github.com/onnx/tensorflow-onnx/issues/987#issuecomment-651038133

**Comment by IAMAl** [comment]
I tried to add freezing the model, then I meet error of;
ValueError: Input 0 of node depth_prediction/depth_net/cnv1/weights/Assign was passed float from depth_prediction/depth_net/cnv1/weights:0 incompatible with expected float_ref.

Updated script is here;
https://github.com/IAMAl/onnx

**Comment by jignparm** [comment]
I see a slightly different error when trying to freeze the model (see below).  Any chance you can remove the variables from the model, or at least get them to be freeze-able to constants? The model won't convert otherwise.
 
```
python -m tf2onnx.convert --graphdef saved_model.pb --outputs depth_prediction/depth_prediction/truediv:0 --inputs depth_prediction/depth_prediction/raw_input:0 --output converted.onnx --fold_const --opset 11

tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value depth_prediction/depth_net/cnv2b/BatchNorm/beta
         [[{{node _retval_depth_prediction/depth_net/cnv2b/BatchNorm/beta_0_6}}]]
```

**Comment by IAMAl** [comment]
model is here, but which not include pb file (so I need the conversion);
https://sites.google.com/view/vid2depth

I use my own script to convert;
https://github.com/IAMAl/onnx
I use common defined function, freeze_create().

**Comment by IAMAl** [comment]
Now, tf2pd.py works for freezing graph, but type error is occurred;

Use `tf.compat.v1.graph_util.extract_sub_graph`
INFO:tensorflow:Froze 150 variables.
I0703 04:07:44.116324 140298940589888 graph_util_impl.py:334] Froze 150 variables.
INFO:tensorflow:Converted 150 variables to const ops.
I0703 04:07:44.561610 140298940589888 graph_util_impl.py:394] Converted 150 variables to const ops.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/tf_env1/lib/python3.7/site-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node depth_prediction/depth_net/cnv1/weights/Assign was passed float from depth_prediction/depth_net/cnv1/weights:0 incompatible with expected float_ref.

**Comment by guschmue** [comment]
I think this comes from tensorflow itself. Looks like after freezing there is some assign that wants to update one of those now constants. Try calling ```tf.compat.v1.graph_util.extract_sub_graph()``` before freezing, maybe that gets rid of the assign.

Of course this model uses custom ops that onnx does not support. tf2onnx will just copy those unchanged into the onnx graph but you'd need to move them over to onnxruntime somehow.

**Comment by IAMAl** [comment]
Hi, I added the function (see my source code), but still meet same error, something is wrong.

**Comment by IAMAl** [comment]
I fixed the error of '''tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node''', see my code. But now I meet optimization error. Even if removing the optimization, some error is occurred.

**Comment by jignparm** [comment]
Can you try running `tf2onnx.optimizer.optimize_graph()` immediately after `tf2onnx.tfonnx.process_tf_graph()` in your script,  before `make_model()`?

The model.py file seems to be missing for your repo, and I don't see the frozen TF model either (so cannot follow your steps offline).

**Comment by guschmue** [comment]
so optimize_graph() should be used but is not really related to your error is you still see
```tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node depth_prediction/depth_net/cnv1/weights/Assign was passed float from depth_prediction/depth_net/cnv1/weights:0 incompatible with expected float_ref.
```
Maybe take a look at the model outputs your script calculates - if this would pickup the assign node it would explain why the node can't be removed and lingers around.

The Assign node assigns a value to a variable but when you freeze the graph all variables need to become const so there can't be a variable. float32_ref is a variable. There is either something in the model that prevents the variable to be const (which sometimes is the case) or using the variable as output would prevent it from being removed.

**Comment by IAMAl** [comment]
Hi, 
after '''tf.compat.v1.graph_util.convert_variables_to_constants''', at '''process_tf_graph''' error is;
'''
onnx_graph = tf2onnx.tfonnx.process_tf_graph(frozen_graph, input_names=inputs, output_names=outputs)
File "/home/ubuntu/miniconda3/envs/tf_env1/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 370, in process_tf_graph
tf_graph = infer_shape(tf_graph, shape_override)
File "/home/ubuntu/miniconda3/envs/tf_env1/lib/python3.7/site-packages/tf2onnx/shape_inference.py", line 34, in infer_shape
tf_graph = infer_shape_for_graph(tf_graph)
File "/home/ubuntu/miniconda3/envs/tf_env1/lib/python3.7/site-packages/tf2onnx/shape_inference.py", line 80, in infer_shape_for_graph
for o in tf_graph.get_operations():
AttributeError: get_operations
'''
model.py is this;
https://github.com/tensorflow/models/tree/master/research/vid2depth

**Comment by guschmue** [comment]
Sorry, should have explained this better - optimize_graph runs on the onnx graph. So your code
```
    opt_graph = tf2onnx.optimizer.optimize_graph(frozen_graph)
    onnx_graph = tf2onnx.tfonnx.process_tf_graph(opt_graph, input_names=inputs, output_names=outputs)
```
should be
```
    onnx_graph = tf2onnx.tfonnx.process_tf_graph(frozen_graph, input_names=inputs, output_names=outputs)
    opt_graph = tf2onnx.optimizer.optimize_graph(onnx_graph )
```
Some sample code is here:
https://github.com/onnx/tensorflow-onnx/blob/master/tf2onnx/convert.py#L143

**Comment by IAMAl** [comment]
@guschmue , sorry I forgot to commit.
I did the committing, and that error can be reproduced.

**Comment by guschmue** [comment]
not sure if I understand. process_tf_graph fails with AttributeError: get_operations ?  
frozen_graph needs to be the  in-memory flavor of graphdef.

**Comment by IAMAl** [comment]
>not sure if I understand. process_tf_graph fails with AttributeError: get_operations ?
yes,

--
File "tf2pb.py", line 98, in _run_pb_gen
onnx_graph = tf2onnx.tfonnx.process_tf_graph(frozen_graph, input_names=inputs, output_names=outputs)
File "/home/ubuntu/miniconda3/envs/tf_env1/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 370, in process_tf_graph
tf_graph = infer_shape(tf_graph, shape_override)
File "/home/ubuntu/miniconda3/envs/tf_env1/lib/python3.7/site-packages/tf2onnx/shape_inference.py", line 34, in infer_shape
    tf_graph = infer_shape_for_graph(tf_graph)
File "/home/ubuntu/miniconda3/envs/tf_env1/lib/python3.7/site-packages/tf2onnx/shape_inference.py", line 80, in infer_shape_for_graph
for o in tf_graph.get_operations():
AttributeError: get_operations

**Comment by IAMAl** [comment]
Is the error on a custom ops ?

**Comment by jignparm** [comment]
The frozen model you are using is a `graph_def` object, but process_tf_graph() requires a `graph` object instead.

See  this example of importing a `graph_def` object into a `graph`--> https://github.com/onnx/tensorflow-onnx/blob/master/tests/run_pretrained_models.py#L261

Two lines below that, a session is created, using the graph object. Then, in the `self.to_onnx()` function, there is a call to process_tf_graph(). You should be able to trace the code in this file to fix the `get_operations()` error message above!

**Comment by IAMAl** [comment]
Hi, I meet Assertion error after updating code (see my repo), for example;

AssertionError: pose_exp_net/pose/cnv6/BatchNorm/moving_variance/Assign is not in graph

>python tf2pb.py

This changes AssertionError massage every time. What is happened?

my repo;
https://github.com/IAMAl/onnx

model.py is this;
https://github.com/tensorflow/models/tree/master/research/vid2depth

**Comment by jignparm** [comment]
The order of operations looks incorrect, or at least different from the example link pasted above.

The freeze_session() call should happen before creating a session. The object to freeze would be the sub_graph. Can you freeze  sub_graph instead, and remove the freeze_session() call inside the session?

Also, you'll need to update line 104 to : "process_tf_graph(sess.graph,...)".

(Not sure if you'are aware, but the code in your repo won't compile -- it's missing file model.py. Also, the vid2depth link above doesn't point to a model -- it shows training code but not the model file itself. There's probably no way we can debug -- only review the code.)

**Comment by IAMAl** [comment]
Hi, @jignparm 

By updating my script with your advice, now error on freeze_session() is gone (thank you !).
As you noted;
>Also, you'll need to update line 104 to : "process_tf_graph(sess.graph,...)".

I meet error on there

>Failed to convert: inputs/outputs specified do not exist, make sure your passedin format: input/output_node_name:port_id.

I googled "passedin format", but could not find in net. but find this;

>onnx_graph = tf2onnx.tfonnx.process_tf_graph(sess.graph,
                                                 custom_op_handlers={"Print": (print_handler, ["Identity", "mode"])},
                                                 extra_opset=[helper.make_opsetid(_TENSORFLOW_DOMAIN, 1)],
                                                 input_names=["input:0"],
                                                 output_names=["output:0"])

This is at; https://github.com/onnx/tensorflow-onnx#summarize_graph

So the '["input:0"]' and '["output:0"]' formation are issue I think.

>Models with simple input / output names are not supported #872

at https://github.com/onnx/tensorflow-onnx#summarize_graph
Discussed about error I meet;

model.py is in vid2depth;
https://github.com/tensorflow/models/tree/master/research/vid2depth

I uploaded the model.py
in my repository;
https://github.com/IAMAl/onnx

**Comment by jignparm** [comment]
It looks closer to passing :)  Can you hard-code the values of the model in/outputs into the function 'process_tf_graph()'? Maybe the rest of the script will pass.

BTW, I cloned the vid2depth repository, and copied your your tf2pb.py into that directory (to ensure all modules are available). When I run tf2pb.py on Windows 10, TF=1.14, Python=3.7, I get the error message below. 

1. Any idea what's causing  the error message below?
1. Is it possible for you to upload a binary version of the model and provide a link to it? I want to check that the model converts from the command line successfully or not. This will also increase confidence that the conversion script you are writing will work. Additionally, it'll make it easier to inspect the model inputs/outputs and nodes if the physical model is present.



###stack trace
``` 
$ python tf2pb3.py
...< lots  of warnings>
Traceback (most recent call last):
  File "tf2pb3.py", line 139, in <module>
    app.run(main)
  File "D:\anaconda37\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "D:\anaconda37\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "tf2pb3.py", line 135, in main
    _run_pb_gen()
  File "tf2pb3.py", line 39, in _run_pb_gen
    img_width=FLAGS.img_width)
  File "D:\tensorflow\models\research\vid2depth\model.py", line 90, in __init__
    util.count_parameters()
  File "D:\tensorflow\models\research\vid2depth\util.py", line 77, in count_parameters
    format_number(shape.num_elements()))
  File "D:\tensorflow\models\research\vid2depth\util.py", line 113, in format_number
    locale.setlocale(locale.LC_ALL, 'en_US')
  File "D:\anaconda37\lib\locale.py", line 604, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by IAMAl** [comment]
Hi,
Thank you for your suggestion;

My environment is;
OS: ubuntu 18.4LTS
anaconda:  custom, py37_1 (univ's env)
Python: version 3.7.6
tensorflow: version 1.15.3

**Comment by IAMAl** [comment]
>Can you hard-code the values of the model in/outputs into the function 'process_tf_graph()'? Maybe the rest of the script will pass.

I have never done this, and not understand meaning of hard-code of in/outputs. Is it to extract name of in/outputs from precess_tf_graph()'s arguments ?

and locate error can be gone by adding;
'''
import locale
locale.setlocale(locale.LC_ALL, '')
'''

**Comment by IAMAl** [comment]
>Is it possible for you to upload a binary version of the model and provide a link to it?
vid2depth is by google, and they removed binary model (pb file), so this is reason why I challenge to do and meet this error.

**Comment by IAMAl** [comment]
>It looks closer to passing

I do not yet understand about the "pass" procedure what this works.
Is there any document or web site explaining about it ?

**Comment by jignparm** [comment]
>and they removed binary model (pb file), 

I see. Thanks for clarifying that the pre-trained TF model is not available.

I was able to get past the initial error by setting locale to ''. I then saved the frozen model in your code as a graph_def pb file, to inspect it and try to convert the model from the command line. The input and output names can be viewed using Netron easily.

The training code in tf2pb.py is generating a model that doesn't load up in TF due to a bad shape error for BatchNorm (see below). This is probably due to some other error during training -- any idea if the shape values on the command line below are good? I see the shapes in the model inputs, but maybe the model needs to be trained with different values.

#error log
```
python -m tf2onnx.convert --graphdef frozen.pb --inputs depth_prediction/depth_prediction/raw_input:0[4,128,416,3],raw_input:0[4,128,1248,3] --outputs depth_prediction/depth_prediction/truediv:0 --fold_const --output frozen.onnx
...
Traceback (most recent call last):
  File "D:\anaconda37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\anaconda37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\jignparmtf2onnx2\tf2onnx\convert.py", line 171, in <module>
    main()
  File "D:\jignparmtf2onnx2\tf2onnx\convert.py", line 125, in main
    graph_def, inputs, outputs = tf_loader.from_graphdef(args.graphdef, args.inputs, args.outputs)
  File "D:\jignparmtf2onnx2\tf2onnx\tf_loader.py", line 156, in from_graphdef
    frozen_graph = tf_optimize(input_names, output_names, frozen_graph)
  File "D:\jignparmtf2onnx2\tf2onnx\tf_loader.py", line 388, in tf_optimize
    graph_def = TransformGraph(graph_def, input_names, output_names, transforms)
  File "D:\anaconda37\lib\site-packages\tensorflow\tools\graph_transforms\__init__.py", line 51, in TransformGraph
    transforms_string, status)
  File "D:\anaconda37\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 548, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Beta input to batch norm has bad shape: [32]
```


![image](https://user-images.githubusercontent.com/13698702/87237496-a5379880-c3e6-11ea-8da6-b7aa8a7ade12.png)

**Comment by IAMAl** [comment]
I checked slim.2dconv at ''https://github.com/google-research/tf-slim/blob/master/tf_slim/layers/layers.py''
It indeed include batch_norm, and nets.py in vid2depth use it. The nets.py defines default shape for the 2dconv.

**Comment by IAMAl** [comment]
I dumped the graph and picked BatchNorm, do you mean the error is on first batchnorm ?
I0712 04:07:53.055708 140703578396480 util.py:77] depth_prediction/depth_net/cnv1/BatchNorm/beta (32,): 32
I0712 04:07:53.056106 140703578396480 util.py:77] depth_prediction/depth_net/cnv1b/BatchNorm/beta (32,): 32
I0712 04:07:53.056433 140703578396480 util.py:77] depth_prediction/depth_net/cnv2/BatchNorm/beta (64,): 64
I0712 04:07:53.056754 140703578396480 util.py:77] depth_prediction/depth_net/cnv2b/BatchNorm/beta (64,): 64
I0712 04:07:53.057067 140703578396480 util.py:77] depth_prediction/depth_net/cnv3/BatchNorm/beta (128,): 128
I0712 04:07:53.057379 140703578396480 util.py:77] depth_prediction/depth_net/cnv3b/BatchNorm/beta (128,): 128
I0712 04:07:53.057688 140703578396480 util.py:77] depth_prediction/depth_net/cnv4/BatchNorm/beta (256,): 256
I0712 04:07:53.057996 140703578396480 util.py:77] depth_prediction/depth_net/cnv4b/BatchNorm/beta (256,): 256
I0712 04:07:53.058305 140703578396480 util.py:77] depth_prediction/depth_net/cnv5/BatchNorm/beta (512,): 512
I0712 04:07:53.058614 140703578396480 util.py:77] depth_prediction/depth_net/cnv5b/BatchNorm/beta (512,): 512
I0712 04:07:53.058943 140703578396480 util.py:77] depth_prediction/depth_net/cnv6/BatchNorm/beta (512,): 512
I0712 04:07:53.059269 140703578396480 util.py:77] depth_prediction/depth_net/cnv6b/BatchNorm/beta (512,): 512
I0712 04:07:53.059593 140703578396480 util.py:77] depth_prediction/depth_net/cnv7/BatchNorm/beta (512,): 512
I0712 04:07:53.059916 140703578396480 util.py:77] depth_prediction/depth_net/cnv7b/BatchNorm/beta (512,): 512
I0712 04:07:53.060846 140703578396480 util.py:77] depth_prediction/depth_net/icnv1/BatchNorm/beta (16,): 16
I0712 04:07:53.061148 140703578396480 util.py:77] depth_prediction/depth_net/icnv2/BatchNorm/beta (32,): 32
I0712 04:07:53.061453 140703578396480 util.py:77] depth_prediction/depth_net/icnv3/BatchNorm/beta (64,): 64
I0712 04:07:53.061766 140703578396480 util.py:77] depth_prediction/depth_net/icnv4/BatchNorm/beta (128,): 128
I0712 04:07:53.062151 140703578396480 util.py:77] depth_prediction/depth_net/icnv5/BatchNorm/beta (256,): 256
I0712 04:07:53.062459 140703578396480 util.py:77] depth_prediction/depth_net/icnv6/BatchNorm/beta (512,): 512
I0712 04:07:53.062772 140703578396480 util.py:77] depth_prediction/depth_net/icnv7/BatchNorm/beta (512,): 512
I0712 04:07:53.063085 140703578396480 util.py:77] depth_prediction/depth_net/upcnv1/BatchNorm/beta (16,): 16
I0712 04:07:53.063404 140703578396480 util.py:77] depth_prediction/depth_net/upcnv2/BatchNorm/beta (32,): 32
I0712 04:07:53.063716 140703578396480 util.py:77] depth_prediction/depth_net/upcnv3/BatchNorm/beta (64,): 64
I0712 04:07:53.064029 140703578396480 util.py:77] depth_prediction/depth_net/upcnv4/BatchNorm/beta (128,): 128
I0712 04:07:53.064352 140703578396480 util.py:77] depth_prediction/depth_net/upcnv5/BatchNorm/beta (256,): 256
I0712 04:07:53.064671 140703578396480 util.py:77] depth_prediction/depth_net/upcnv6/BatchNorm/beta (512,): 512
I0712 04:07:53.064986 140703578396480 util.py:77] depth_prediction/depth_net/upcnv7/BatchNorm/beta (512,): 512
I0712 04:07:53.066807 140703578396480 util.py:77] pose_exp_net/pose/cnv6/BatchNorm/beta (256,): 256
I0712 04:07:53.067158 140703578396480 util.py:77] pose_exp_net/pose/cnv7/BatchNorm/beta (256,): 256

**Comment by IAMAl** [comment]
Hi,
Training uses these hyper-parameters as default;
'''
flags.DEFINE_integer('batch_size', 4, 'The size of a sample batch')
flags.DEFINE_integer('img_height', 128, 'Input frame height.')
flags.DEFINE_integer('img_width', 416, 'Input frame width.')
flags.DEFINE_integer('seq_length', 3, 'Number of frames in sequence.')
'''
defined in train.py. It seems that error is occurred by other reason...

**Comment by IAMAl** [comment]
When I tried to comment out line 'tf_reset_default_graph()' at line 98th;

```
File "tf2pb.py", line 123, in _run_pb_gen
output_names=outputs)
File "/home/ubuntu/miniconda3/envs/tf_env1/lib/python3.7/site-packages/tf2onnx/tfonnx.py", line 379, in process_tf_graph
onnx_nodes, op_cnt, attr_cnt, output_shapes, dtypes, _ = tensorflow_to_onnx(tf_graph, shape_override)
File "/home/ubuntu/miniconda3/envs/tf_env1/lib/python3.7/site-packages/tf2onnx/tf_utils.py", line 228, in tensorflow_to_onnx
return tflist_to_onnx(graph, shape_override)
File "/home/ubuntu/miniconda3/envs/tf_env1/lib/python3.7/site-packages/tf2onnx/tf_utils.py", line 166, in tflist_to_onnx
dtypes[out.name] = map_tf_dtype(out.dtype)
File "/home/ubuntu/miniconda3/envs/tf_env1/lib/python3.7/site-packages/tf2onnx/tf_utils.py", line 116, in map_tf_dtype
dtype = TF_TO_ONNX_DTYPE[dtype]
KeyError: tf.float32_ref
```

**Comment by IAMAl** [comment]
I have dumped outputs which is generated *before* ```process_tf_graph()```, and found this;
```
'depth_prediction/depth_prediction/depth_net/icnv4/BatchNorm/AssignMovingAvg_1/sub/x:0', 'init:0', 
```
so, I did to fetch only first element of list of ```outputs```, see my updated code of tf2pb.py.
After this process_tf_graph() works, and by commenting out, ```tf2onnx.optimizer.optimize_graph()``` and ``` onnx.checker.check_model(model_proto)```, then *onnx file is generated*, although I meet error in the generated file as ```error on UTF-8 format```.

**Comment by jignparm** [comment]
@IAMAl , use the master branch or latest tf2onnx package -- it'll get rid of the UTF-8 error.

I modified your tf2pb.py script slightly (see attached file). This generates a valid Onnx model that I can load and score in OnnxRuntime.

Update if you have further question, otherwise feel free to close out this issue.



[tf2pb4.py.txt](https://github.com/onnx/tensorflow-onnx/files/4911841/tf2pb4.py.txt)


###Run log of model using OnnxRuntime
```
$ python ort_load_model.py saved_model.onnx
[[[9.99001e-02]
  [1.00000e+02]
  [9.99001e-02]
  ...
  [1.00000e+02]
  [9.99001e-02]
  [1.00000e+02]]
...
```

**Comment by IAMAl** [comment]
@jignparm thank you very much for your many advices, I just can generate the onnx file !

Anyway what is the ```ort_load_model.py``` and what is this purpose ?

**Comment by jignparm** [comment]
It's a simple scoring script, using OnnxRuntime API to score the model. Have a look the OnnxRuntime repository for more details on  how to use the Python API.

**Comment by IAMAl** [comment]
I reinstalled with ```pip install git+https://github.com/onnx/tensorflow-onnx``` but still meet error of 
```
saved_model.onnx is not UTF-8 encoded
Saving disabled.
```

and could not find where is the ```ort_load_model.py``` including Microsoft's site.

**Comment by jignparm** [comment]
You have to `pip install onnxruntime`, and then see this example how to use the load/score a model: https://github.com/onnx/onnx-docker/blob/master/onnx-ecosystem/inference_demos/simple_onnxruntime_inference.ipynb

**Comment by IAMAl** [comment]
Hi,

I do not yet understand how doing the scoring, or what is the scoring ?, is it an inference ?
I referenced your link;
https://github.com/onnx/onnx-docker/blob/master/onnx-ecosystem/inference_demos/simple_onnxruntime_inference.ipynb

I get this error;
```
TypeError: Unable to load from type '<class 'onnx.onnx_ONNX_REL_1_7_ml_pb2.ModelProto'>'
```

**Comment by jignparm** [comment]
Sorry for late reply. Yes, scoring is same as inference (as shown in the link above).

For the error message above, can you try using the latest version of Onnx, OnnxRuntime and Tf2onnx to see if that resolves the issue?

**Comment by IAMAl** [comment]
Hi,

the error is on version of; 
‘’’
onnx: 1.7.0
onnxruntime: 1.4.0
tf2onnx: 1.7.0
‘’’

**Comment by jignparm** [comment]
Adding @TomWildenhain-Microsoft , @guschmue for further help as needed.

**Comment by IAMAl** [comment]
Additional info: onnx file is readable (I think no issue)

**Comment by IAMAl** [comment]
@jignparm ,
I have one-step progress;

At line 84 in inference.py,
```
sess = onnxruntime.InferenceSession(model)
```
modify as
```
sess = onnxruntime.InferenceSession(model, "./")
```
Then error is changed as;
```
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession(arg0: onnxruntime.capi.onnxruntime_pybind11_state.SessionOptions, arg1: str, arg2: bool)
```
Regarding ```pybind11```, some discussion is here;
```std::array in constructor: incompatible constructor arguments #955```
https://github.com/pybind/pybind11/issues/955
Someone says that include ```pybind11/stl.h``` is needed.
What does this mean ?

**Comment by IAMAl** [comment]
I modified the line as follows;
```
  model = onnx.load(model_path)
  sess = onnxruntime.InferenceSession(path_or_bytes="./", sess_options=None, providers=model)
```
Then error is;
```
RuntimeError: /onnxruntime_src/onnxruntime/core/session/inference_session.cc:238 onnxruntime::InferenceSession::InferenceSession(const onnxruntime::SessionOptions&, const onnxruntime::Environment&, const string&) status.IsOK() was false. Given model could not be parsed while creating inference session. Error message: Protobuf parsing failed.
```
This thread discusses the error;
Cannot run bertsquad-10.onnx on Ubuntu #306
```
it was because Git did not download the whole onnx file. A corrupted one was parsed by the Protobuf thus the failure.
```
https://github.com/onnx/models/issues/306

**Comment by guschmue** [comment]
How about
```
sess=onnxruntime.InferenceSession("model.onnx")
```
?

**Comment by guschmue** [comment]
I assume this is fixed.
