### ISSUE TITLE
Does --inputs-as-nchw changes the axis for expand_dims/squeeze etc?

### ISSUE THREAD

**Issue by stratomaster31** [onnx/tensorflow-onnx#992]
When using --inputs-as-nchw option, I wonder if the converter changes the axis of the _expand_dims_ and _squeeze_ functions in the netwrok, I mean:

Example:
* Original Input (NHWC) shape = (-1, 300, 1, 3) -> squeeze(axis=2) yields to (-1, 300, 3)
* If we use --inputs-as-nchw, the squeeze should be performed on axis=3 , to get a shape of (-1, 3, 300) from (-1, 3, 300, 1)

Does the converter take care of that?

**Comment by guschmue** [comment]
We blindly override. --inputs-as-nchw was meant to help for models with unknown rank or unknown dims and because of unknown rank we can not count on the shape that we find.
