### ISSUE TITLE
Error of converting SAPD .pb to onnx

### ISSUE THREAD

**Issue by HelloAlone** [onnx/tensorflow-onnx#994]
**Describe the bug**
I wonder to convert .pb model of SAPD (A little bit different from original [https://github.com/xuannianz/SAPD](url)) which was trained by Keras to .onnx model. 

**Urgency**
None

**System information**
- Docker image: nvcr.io/nvidia/tensorflow:20.03-tf1-py3
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Tensorflow Version: Using tensorflow=1.15.2, onnx=1.7.0, tf2onnx=1.6.2
- Python version: 3.6.9

**To Reproduce**
This is my command:

`python -m tf2onnx.convert --graphdef rjcd_13_0.1421_0.1290.pb --output model.onnx --inputs image_input:0,max_detections:0,iou_threshold:0,score_threshold:0 --outputs output/Squeeze:0 --opset 10 --fold_const`

And got error message like this:

> 2020-07-03 08:04:43,990 - INFO - Using tensorflow=1.15.2, onnx=1.7.0, tf2onnx=1.6.2/8d5253
2020-07-03 08:04:43,990 - INFO - Using opset <onnx, 10>
2020-07-03 08:04:50,739 - ERROR - Failed to convert node preprocessor/PadV2
OP=Pad
Name=preprocessor/PadV2
Inputs:
	preprocessor/resize/ResizeBilinear:0=Transpose, [1, -1, -1, 3], 1
	resize_information_computer/stack_Concat__115:0=Concat, [4, 2], 6
	preprocessor/PadV2/constant_values:0=Const, [], 1
Outpus:
	preprocessor/PadV2:0=[-1, -1, -1, -1], 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 256, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/onnx_opset/nn.py", line 463, in version_1
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/graph.py", line 267, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: resize_information_computer/stack_Concat__115 must be Const
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 169, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/convert.py", line 153, in main
    inputs_as_nchw=args.inputs_as_nchw)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 475, in process_tf_graph
    raise exceptions[0]
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/tfonnx.py", line 256, in tensorflow_onnx_mapping
    func(g, node, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/onnx_opset/nn.py", line 463, in version_1
    paddings = np.array(node.inputs[1].get_tensor_value()).transpose().flatten()
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/graph.py", line 267, in get_tensor_value
    raise ValueError("get tensor value: {} must be Const".format(self.name))
ValueError: get tensor value: resize_information_computer/stack_Concat__115 must be Const

If I use opset==11 instead of 10, I got another error message like this:

> 2020-07-03 08:11:51,821 - INFO - Using tensorflow=1.15.2, onnx=1.7.0, tf2onnx=1.7.0/011cf5
2020-07-03 08:11:51,821 - INFO - Using opset <onnx, 11>
2020-07-03 08:12:03,941 - INFO - Optimizing ONNX model
2020-07-03 08:13:14,791 - WARNING - Failed to apply optimize_transpose
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/__init__.py", line 52, in optimize_graph
    graph = opt.optimize(current) or graph
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/optimizer_base.py", line 41, in optimize
    graph = self._optimize(graph)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 135, in _optimize
    return self._apply_optimization(graph, self._optimize_at_current_graph_level)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/optimizer_base.py", line 62, in _apply_optimization
    graph = optimize_func(graph)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 148, in _optimize_at_current_graph_level
    if self._handle_nhwc_tranpose(n):
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 281, in _handle_nhwc_tranpose
    return op_handler(trans, p)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 688, in _shape_handler
    self._g.remove_node(node.name)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/graph.py", line 601, in remove_node
    utils.make_sure(node_name in self._nodes_by_name, "node %s not in current graph, cannot remove", node_name)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/utils.py", line 193, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: node sapd_p/block2b_drop/cond/Shape not in current graph, cannot remove
2020-07-03 08:13:58,200 - WARNING - Failed to apply optimize_transpose
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/__init__.py", line 52, in optimize_graph
    graph = opt.optimize(current) or graph
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/optimizer_base.py", line 41, in optimize
    graph = self._optimize(graph)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 135, in _optimize
    return self._apply_optimization(graph, self._optimize_at_current_graph_level)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/optimizer_base.py", line 62, in _apply_optimization
    graph = optimize_func(graph)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 148, in _optimize_at_current_graph_level
    if self._handle_nhwc_tranpose(n):
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 281, in _handle_nhwc_tranpose
    return op_handler(trans, p)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 688, in _shape_handler
    self._g.remove_node(node.name)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/graph.py", line 601, in remove_node
    utils.make_sure(node_name in self._nodes_by_name, "node %s not in current graph, cannot remove", node_name)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/utils.py", line 193, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: node sapd_p/block2b_drop/cond/Shape not in current graph, cannot remove
2020-07-03 08:14:13,897 - WARNING - Failed to apply optimize_transpose
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/__init__.py", line 52, in optimize_graph
    graph = opt.optimize(current) or graph
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/optimizer_base.py", line 41, in optimize
    graph = self._optimize(graph)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 135, in _optimize
    return self._apply_optimization(graph, self._optimize_at_current_graph_level)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/optimizer_base.py", line 62, in _apply_optimization
    graph = optimize_func(graph)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 148, in _optimize_at_current_graph_level
    if self._handle_nhwc_tranpose(n):
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 281, in _handle_nhwc_tranpose
    return op_handler(trans, p)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/optimizer/transpose_optimizer.py", line 688, in _shape_handler
    self._g.remove_node(node.name)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/graph.py", line 601, in remove_node
    utils.make_sure(node_name in self._nodes_by_name, "node %s not in current graph, cannot remove", node_name)
  File "/usr/local/lib/python3.6/dist-packages/tf2onnx/utils.py", line 193, in make_sure
    raise ValueError("make_sure failure: " + error_msg % args)
ValueError: make_sure failure: node sapd_p/block2b_drop/cond/Shape not in current graph, cannot remove
2020-07-03 08:14:17,834 - INFO - After optimization: BatchNormalization -46 (80->34), Cast -57 (149->92), Const -582 (998->416), Identity -73 (82->9), Less -1 (13->12), ReduceMean -4 (24->20), Reshape -13 (95->82), Shape -2 (32->30), Slice -1 (42->41), Squeeze -19 (35->16), Transpose -220 (495->275), Unsqueeze -67 (117->50)
2020-07-03 08:14:17,981 - INFO - 
2020-07-03 08:14:17,982 - INFO - Successfully converted TensorFlow model rjcd_13_0.1421_0.1290.pb to ONNX
2020-07-03 08:14:18,008 - INFO - ONNX model is saved at model.onnx

**Expected behavior**
Successfully get the onnx model. (I prefer opset==10 because it seems TensorRT 7 don't fully support opset==11).

**Screenshots**
None

**Additional context**
The .pb model file can be download at [https://yadi.sk/d/PN3tDlm6GzwSpw](url)

**Comment by jignparm** [comment]
>I prefer opset==10 because it seems TensorRT 7 don't fully support opset==11

Unfortunately, opset==10 requires the `pads` values of the `Pad` operator to be a compile time constant. The model uses dynamic `pads` value, so you will have to use opset==11 or later to convert the model.

Good news is that opset==11 is able to convert the model and you end up with a `model.onnx` file (the errors above are optimization errors, not conversion errors).  I'll have a look at the optimization error -- should be able to get a clean run on this model.

**Comment by HelloAlone** [comment]
> > I prefer opset==10 because it seems TensorRT 7 don't fully support opset==11
> 
> Unfortunately, opset==10 requires the `pads` values of the `Pad` operator to be a compile time constant. The model uses dynamic `pads` value, so you will have to use opset==11 or later to convert the model.
> 
> Good news is that opset==11 is able to convert the model and you end up with a `model.onnx` file (the errors above are optimization errors, not conversion errors). I'll have a look at the optimization error -- should be able to get a clean run on this model.

Thank you. I tried to convert model.onnx(opset==11) to TensorRT engine(TRT==7.1), and I got a "unsupported datatype" error. So it's true that TensorRT doesn't support opset=11? May I need to go over to TensorRT team for advice?

> [TensorRT] WARNING: onnx2trt_utils.cpp:220: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[TensorRT] WARNING: onnx2trt_utils.cpp:246: One or more weights outside the range of INT32 was clamped
[TensorRT] ERROR: onnx2trt_utils.cpp:467: Found unsupported datatype (11) when importing initializer: resize_information_computer/truediv/Cast:0
ERROR: Failed to parse the ONNX file.
In node -1 (parseGraph): UNSUPPORTED_NODE: Assertion failed: convertOnnxWeights(initializer, &weights, ctx)

**Comment by jignparm** [comment]
It looks like TRT is complaining about the type of the initializer below (DOUBLE). 

If you edit the model (either the original TF pb or else the Onnx pb) and set the initializer to a type TRT can handle (e.g. FLOAT), that may be sufficient to convert the model in TRT.

See this example of how to edit an Onnx model: https://github.com/microsoft/onnxruntime/issues/2264

```
%resize_information_computer/truediv/Cast:0[DOUBLE, scalar]
```

**Comment by HelloAlone** [comment]
> It looks like TRT is complaining about the type of the initializer below (DOUBLE).
> 
> If you edit the model (either the original TF pb or else the Onnx pb) and set the initializer to a type TRT can handle (e.g. FLOAT), that may be sufficient to convert the model in TRT.
> 
> See this example of how to edit an Onnx model: [microsoft/onnxruntime#2264](https://github.com/microsoft/onnxruntime/issues/2264)
> 
> ```
> %resize_information_computer/truediv/Cast:0[DOUBLE, scalar]
> ```

I edited the original pb to change the node's type (float64->float32), and finally ... the error message has changed. 

> [V] [TRT] ModelImporter.cpp:125: preprocessor/PadV2 [Pad] inputs: [preprocessor/resize/ResizeBilinear:0 -> (-1, -1, -1, -1)], [preprocessor/PadV2__135:0 -> (8)], [preprocessor/PadV2/constant_values:0 -> ()], 
ERROR: builtin_op_importers.cpp:2179 In function importPad:
[8] Assertion failed: inputs.at(1).is_weights()

It seems is TensorRT issue ([https://github.com/NVIDIA/TensorRT/issues/439](url)). But it still could be tensorflow-onnx issue, because padding opset11 support had added here [https://github.com/onnx/onnx-tensorrt/pull/408](url)

**Comment by jignparm** [comment]
The converted Onnx model seems to run successfully using OnnxRuntime (https://github.com/microsoft/onnxruntime). See the run log below using some random inputs.

The message above is probably a TensorRT issue -- it might require  special handling for some operators in this model.

###run log using OnnxRuntime
```
$ python ort_load_model.py rjcd_13_0.1421_0.1290.onnx
[array([[  0.94475746, 120.1998    , 399.        , 391.56778   ],
       [ 55.827072  ,   0.        , 216.91899   ,  28.274895  ],
       [  0.        ,   0.        ,   7.8887687 ,   6.98773   ],
       [391.54025   ,   0.        , 399.        ,   5.949155  ],
       [252.83525   ,   0.78260005, 376.99463   ,  32.60255   ]],
      dtype=float32)]
```

**Comment by HelloAlone** [comment]
> The converted Onnx model seems to run successfully using OnnxRuntime (https://github.com/microsoft/onnxruntime). See the run log below using some random inputs.
> 
> The message above is probably a TensorRT issue -- it might require special handling for some operators in this model.
> 
> ###run log using OnnxRuntime
> 
> ```
> $ python ort_load_model.py rjcd_13_0.1421_0.1290.onnx
> [array([[  0.94475746, 120.1998    , 399.        , 391.56778   ],
>        [ 55.827072  ,   0.        , 216.91899   ,  28.274895  ],
>        [  0.        ,   0.        ,   7.8887687 ,   6.98773   ],
>        [391.54025   ,   0.        , 399.        ,   5.949155  ],
>        [252.83525   ,   0.78260005, 376.99463   ,  32.60255   ]],
>       dtype=float32)]
> ```

Thank you for your patient response, I'll turn to TensorRT team for help. But I hope tensorflow-onnx also fix the "Failed to apply optimize_transpose" warning, LOL. It breaks the topological order, so onnx-simplifier doesn't work in the generated onnx model.

**Comment by jignparm** [comment]
@HelloAlone , PR #1004 will fix the optimizer errors you see in this model, and should generate a slightly faster/smaller model.

**Comment by HelloAlone** [comment]
> @HelloAlone , PR #1004 will fix the optimizer errors you see in this model, and should generate a slightly faster/smaller model.

Hey guy, I'm glad to see it. BUT .. although now the warnings no longer appears, onnx-simplifier still refuse to work. Same "Nodes in a graph must be topologically sorted" error.

> onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'sapd_p/block2b_project_bn/FusedBatchNormV3:0' of node: 
input: "sapd_p/block2b_project_bn/FusedBatchNormV3:0" input: "sapd_p/block2b_drop/cond/dropout/truediv:0" output: "sapd_p/block2b_drop/cond/dropout/mul:0" name: "sapd_p/block2b_drop/cond/dropout/mul" op_type: "Mul" domain: ""
 is not output of any previous nodes.

However, I've changed my mind. You see, the TensorRT team didn't notice my issue. So I rebuilt the pb model and fixed the model input as (1,512,512,3) two days ago. I'd hoped to work this time, but tensorflow-onnx generates several isolated onnx nodes. Sign.

The new pb file can be download at [https://yadi.sk/d/4oNmHjE3JVYp3Q](https://yadi.sk/d/4oNmHjE3JVYp3Q). And the strange isolated onnx nodes is visualized like this [https://imgur.com/a/1ATvaLd](https://imgur.com/a/1ATvaLd)

**Comment by jignparm** [comment]
@HelloAlone, 

Using the command above, the new TF model (converted to Onnx) loads and runs fine using OnnxRuntime. See the run log below, using random input. I'm using Onnx=1.7.0,  TF 2.1, and master branch of this repo, 

The model also  passes  the official Onnx model checker tool, so it **should be a valid model**. I'm not familiar with the Onnx Simplifier tool that you mentioned, but it seems to be saying the model is **not valid** for some reason -- it's a mystery why it disagrees with the official tool!

The isolated nodes you posted are not really isolated. The Netron tool does not render all the connections for sub-graphs (e.g. for the Loop operator in the pic below), so while they appear disconnected in the visualization, that's not really the case when you inspect the model nodes using command line utils.

Can you try skipping the Simplifier tool? Does the model run fine in TRT without the tool?

###run log on new model  using OnnxRuntime
```
$ python ort_load_model.py  rjcd_13_0.1421_0.1290_0707.onnx
2020-07-09 10:23:02.9623995 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer keras_learning_phase:0 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
[array([[[ 4.0000000e+00, -4.6638791e+02,  4.7045175e+02,  1.9203037e+03],
        [-1.4555296e+04, -7.5824774e+02,  9.4229473e+03,  1.6304163e+03],
        [-9.1338711e+03, -1.5759072e+03,  5.0685830e+03,  1.3460347e+03],
        [-3.1475710e+03, -1.0324958e+03,  1.4297511e+03,  9.3705402e+02],
        [-1.8300527e+03, -9.4775317e+02,  6.6875470e+02,  1.2831443e+03],
        [-3.3494382e+02,  2.9118463e+02,  1.4648230e+02,  6.1183331e+02],
        [-4.4111969e+01,  4.2176355e+02,  4.8292825e+02,  5.2527191e+02],
        [-5.1042329e+03, -5.9550293e+02,  3.8963765e+03,  1.0340212e+03],
        [-3.5535068e+02, -6.3189825e+02,  4.1559647e+02,  6.3793530e+02],
        [-7.8779004e+02,  9.3568756e+01,  2.0836755e+02,  8.7513293e+02],
        [-1.1683861e+03, -2.4362518e+02,  6.2773444e+02,  1.1805684e+03],
        [-2.9176605e+02, -1.4737860e+02,  4.6928445e+02,  7.8071558e+02],
        [-6.6461255e+02, -3.6993475e+02,  5.0400000e+02,  8.6114697e+02],
        [-2.4525669e+03,  2.5999234e+02,  6.3349384e+02,  5.0800000e+02],
        [-1.8661357e+02,  3.5187125e+02,  6.7641302e+02,  6.0872290e+02],
        [-1.5244753e+03, -7.4266498e+02,  1.4966861e+02,  7.6160156e+02],
        [-3.0257684e+02, -2.7711127e+02,  4.5912949e+02,  3.5882950e+02],
        [-2.6590027e+02, -1.2800936e+03,  8.8454608e+02,  3.2874414e+03],
        [ 4.0000000e+00, -2.8410104e+02,  2.0337965e+02,  1.4153900e+03]]],
      dtype=float32)]
```

![image](https://user-images.githubusercontent.com/13698702/87028824-b7d78500-c1ce-11ea-8124-c6c8c1f581b7.png)

**Comment by HelloAlone** [comment]
> @HelloAlone,
> 
> Using the command above, the new TF model (converted to Onnx) loads and runs fine using OnnxRuntime. See the run log below, using random input. I'm using Onnx=1.7.0, TF 2.1, and master branch of this repo,
> 
> The model also passes the official Onnx model checker tool, so it **should be a valid model**. I'm not familiar with the Onnx Simplifier tool that you mentioned, but it seems to be saying the model is **not valid** for some reason -- it's a mystery why it disagrees with the official tool!
> 
> The isolated nodes you posted are not really isolated. The Netron tool does not render all the connections for sub-graphs (e.g. for the Loop operator in the pic below), so while they appear disconnected in the visualization, that's not really the case when you inspect the model nodes using command line utils.
> 
> Can you try skipping the Simplifier tool? Does the model run fine in TRT without the tool?
> 
> ###run log on new model using OnnxRuntime
> 
> ```
> $ python ort_load_model.py  rjcd_13_0.1421_0.1290_0707.onnx
> 2020-07-09 10:23:02.9623995 [W:onnxruntime:, graph.cc:814 onnxruntime::Graph::Graph] Initializer keras_learning_phase:0 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.
> [array([[[ 4.0000000e+00, -4.6638791e+02,  4.7045175e+02,  1.9203037e+03],
>         [-1.4555296e+04, -7.5824774e+02,  9.4229473e+03,  1.6304163e+03],
>         [-9.1338711e+03, -1.5759072e+03,  5.0685830e+03,  1.3460347e+03],
>         [-3.1475710e+03, -1.0324958e+03,  1.4297511e+03,  9.3705402e+02],
>         [-1.8300527e+03, -9.4775317e+02,  6.6875470e+02,  1.2831443e+03],
>         [-3.3494382e+02,  2.9118463e+02,  1.4648230e+02,  6.1183331e+02],
>         [-4.4111969e+01,  4.2176355e+02,  4.8292825e+02,  5.2527191e+02],
>         [-5.1042329e+03, -5.9550293e+02,  3.8963765e+03,  1.0340212e+03],
>         [-3.5535068e+02, -6.3189825e+02,  4.1559647e+02,  6.3793530e+02],
>         [-7.8779004e+02,  9.3568756e+01,  2.0836755e+02,  8.7513293e+02],
>         [-1.1683861e+03, -2.4362518e+02,  6.2773444e+02,  1.1805684e+03],
>         [-2.9176605e+02, -1.4737860e+02,  4.6928445e+02,  7.8071558e+02],
>         [-6.6461255e+02, -3.6993475e+02,  5.0400000e+02,  8.6114697e+02],
>         [-2.4525669e+03,  2.5999234e+02,  6.3349384e+02,  5.0800000e+02],
>         [-1.8661357e+02,  3.5187125e+02,  6.7641302e+02,  6.0872290e+02],
>         [-1.5244753e+03, -7.4266498e+02,  1.4966861e+02,  7.6160156e+02],
>         [-3.0257684e+02, -2.7711127e+02,  4.5912949e+02,  3.5882950e+02],
>         [-2.6590027e+02, -1.2800936e+03,  8.8454608e+02,  3.2874414e+03],
>         [ 4.0000000e+00, -2.8410104e+02,  2.0337965e+02,  1.4153900e+03]]],
>       dtype=float32)]
> ```
> 
> ![image](https://user-images.githubusercontent.com/13698702/87028824-b7d78500-c1ce-11ea-8124-c6c8c1f581b7.png)

Okay, I trust what you say. Indeed it may be a simple matter of visualization rather than a model error. [Onnx-simplifier](https://github.com/daquexian/onnx-simplifier) can simplify ONNX models by replaces the redundant operators with their constant outputs. I've heard it's helpful for model conversion, but it's really not a required step. 
As for TRT ... Finally it told me the NonMaxSuppression ONNX op is not supported. I've had enough. :)

**Comment by HelloAlone** [comment]
At least the "Failed to apply optimize_transpose" warning is fixed, LOL @jignparm . This issue can be closed.

**Comment by jignparm** [comment]
> As for TRT ... Finally it told me the NonMaxSuppression ONNX op is not supported. I've had enough. :)

Sorry to hear that :-/ ! I'm bit surprised that NonMaxSuppression is not supported by TRT -- hopefully it's only a matter of time before it's supported.

And thank you for sharing the model -- the "Failed to apply optimize_transpose" error was a good fix in tf2onnx (rare case, but important).
