### ISSUE TITLE
GraphMatcher allow_reorder should be specified explicitly by each subpattern

### ISSUE THREAD

**Issue by TomWildenhain-Microsoft** [onnx/tensorflow-onnx#998]
**Describe the bug**
If a pattern contains a non-commutative op (ex: Sub) within a commutative one (ex: Mul), allow_reorder should be applied to the outer op but not the inner one.  Currently, allow_reorder cannot be applied differently for outer/inner ops in a pattern.  The existing codebase has many instances where allow_reorder is erroneously applied to the entire pattern tree.

**Urgency**
Not urgent.

**Comment by guschmue** [comment]
in practice we have not seen such a issue, mostly because the pattern itself should prevent this
